Глеб Костин
frontend-park-mail-ru/homework_2024_1 pull request #10
Opened 2024-02-11 09:40 UTC by glebkos

2024-02-11 10:28 UTC, mafin1799 reviewed
Привет
Меня зовут Никита

Оставил комментарии по коду.
Как будет готово или будут вопросы пиши в телегу @macmafin_17

2024-02-11 10:28 UTC, mafin1799 commented on source/sorting.js
> +"using strict";
Что такое "using strict"
Для чего его используют?
Где его писать не обязательно?

2024-02-11 10:28 UTC, mafin1799 commented on source/sorting.js
> +let sorting = (array, keys) => {
Почему для объявления функции используется let?
Какие еще есть варианты объявления функции? 
Какие у них отличия?
Почему выбрал именно стрелочные функции?

Вот тут информация по стрелочным функциям
https://learn.javascript.ru/arrow-functions-basics

Тут по переменным
https://doka.guide/js/var-let/

2024-02-11 10:28 UTC, mafin1799 commented on source/sorting.js
> +let sorting = (array, keys) => {
К самой функции нужно добавить JSDoc

2024-02-11 10:28 UTC, mafin1799 commented on source/sorting.js
> +        array.sort((a, b) => (typeof a[item] === 'string') && (typeof b[item] === 'string') ? a[item].localeCompare(b[item]) : a[item] - b[item]);
Так как сортировка является частью твоего задания, этот код нужно будет переписать. Необходима собственная реализация. т.е. sort использовать нельзя

2024-02-11 10:28 UTC, mafin1799 commented on source/sorting.js
> +    return array
Нужно ставить ; 
https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

В файле есть "" и ''
Нужно выбрать что-то одно

2024-02-11 10:28 UTC, mafin1799 commented on source/sorting.js
> +        array.sort((a, b) => (typeof a[item] === 'string') && (typeof b[item] === 'string') ? a[item].localeCompare(b[item]) : a[item] - b[item]);
Тут сложно читать код
Даже если бы sort был разрешен,
то текущий вид можно было бы вынести в операторные скобки {}

2024-02-11 16:29 UTC, glebkos commented on source/sorting.js
> +"using strict";
У JS существует два режима работы "современный" и "устаревший". И когда в начале скрипта явно указывается директива "using strict" это означает, что весь скрипт работает в "современном" режиме. Если ее не поставить, то JS сам решит какой режим использовать. К примеру в моем случае будет всегда использоваться режим strict режим, потому что я объявляю переменные через let, что является ключевым словом strict mod'а.

2024-02-11 17:03 UTC, mafin1799 commented on source/sorting.js
> +function comporator(a, b){
Не забудь проверить случаи, когда к тебе приходит не только строка, а что-нибудь еще:
boolean
object
array
...

Проверь что все работает хорошо
Нове проверки занести в тесты

2024-02-11 18:05 UTC, glebkos commented on source/sorting.js
> +function comporator(a, b){
Здесь я использовал function declaration для того чтобы код было легче читать, ведь если бы я поместил это во внутрь функции sorting, то код был бы более нагроможденным. Плюс к этому само название функции дает больше информацию о том, что функция делает. 

Стрелочная функция отличается от объявления функции: 

- Нет оператора **this**
- Не имеет переменную **arguments**
- Ее нельзя создать с помощью **new**
- И не имеет ключевого слова **super**

2024-02-11 18:05 UTC, glebkos commented on source/sorting.js
> +let sorting = (array, keys) => {
Кроме let существует var и const, начнем с const, он записывает значения и не позволяет их больше изменять. А let и var используются для объявления переменных первое используется в "современном" режиме, а второе в устаревшем. Также если мы работаем в устаревшем режиме, то допускается опустить ключевое слово var. К переменной, объявленой с помощью var, можно обратиться до инициализации и получить **undefined**, также эта переменная доступна за пределами функции, в которой она объявлена. В то время как к let и const можно получить доступ только внутри функции и на всех вложенных уровнях. 

Здесь я выбрал стрелочную функцию, потому что она быстрее пишется и ее легче читать. Об отличиях  ответил в следующем блоке.

2024-02-11 18:07 UTC, mafin1799 commented on source/sorting.js
> +function comporator(a, b){
Еще function declaration можно использовать до объявления.
Так как функция создается до выполнения первой строчки кода.

2024-02-11 18:08 UTC, mafin1799 commented on source/sorting.js
> +    for (let key of keys.reverse()) {
Тут скорее keys.reverse().foreach(key => ...)

2024-02-11 18:17 UTC, glebkos commented on source/sorting.js
> +        for (let [index, item] of array.entries()) {
`Object.entries()` возвращает массив `[key, value]`, таким образом `array.entries()` превратиться в `[[key1, value1], [key2, value2], ..., [keyN, valueN]]`. Конструкция `for..of` будет итерироваться, брать набор значений и приравнивать их. К примеру на первом шаге будет: `[index, item] = [key1, value1]`, такая конструкция эквивалентна записи:
```
index = key1;
item = value1;
```
и так как мы работаем с массивом, то значением ключа будет значение индекса, т.е. `key1 = 0, key2 = 1, ...`

2024-02-11 19:09 UTC, mafin1799 commented on source/sorting.js
> +    for (let key of keys.reverse()) {
Ну в целом окей

2024-02-13 22:21 UTC, DPeshkoff commented on source/sorting.js
> +"using strict";
> потому что я объявляю переменные через let, что является ключевым словом strict mod'а.

Уверен? Как будто бы не в let дело)

2024-02-13 22:25 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 22:25 UTC, DPeshkoff commented on source/sorting.js
> +    if ((typeof a === 'string') && (typeof b === 'string')) {
Я куда-то жмал и все сломалось

<img width="386" alt="Снимок экрана 2024-02-14 в 01 23 22" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/101c6044-5bf4-4211-85cd-8bc4dc3fd514">

Такие строки не пройдут твою проверку, хотя они вполне себе строки)

Давай подумаем, как починить?

2024-02-13 22:25 UTC, DPeshkoff commented on source/sorting.js
> +};
\n

2024-02-13 22:25 UTC, DPeshkoff commented on source/sorting.js
> +            const insertIndex = array.findIndex((elem) => (comporator(elem[key], item[key]) > 0));
> comporator

comparator :D

2024-02-13 22:25 UTC, DPeshkoff commented on tests/sorting.js
> +	});
А если на вход вообще придет какой-то undefined null? Гоу дополним тесты)

2024-02-14 14:26 UTC, glebkos commented on source/sorting.js
> +    if ((typeof a === 'string') && (typeof b === 'string')) {
Здесь нужно добавить проверку:
` a instanceof String && b instanceof String`

2024-02-15 10:51 UTC, glebkos commented on source/sorting.js
> +    if ((typeof a === 'string') && (typeof b === 'string')) {
Добавил эту проверку и написал тесты(№16, 17) по этому случаю.

2024-02-15 10:52 UTC, glebkos commented on tests/sorting.js
> +	});
Добавил больше проверок на типы и придумал тесты к ним

2024-02-15 11:24 UTC, glebkos commented on source/sorting.js
> +"using strict";
Суть в том, что JS может переключаться в "современный" режим, если видит ключевые слова или операторы, используемые в "современном" режиме. И здесь я привел неправильный пример, let среди этих ключевых слов нет.

2024-02-15 22:35 UTC, DPeshkoff commented on source/sorting.js
> +"using strict";
А в чем заключается этот режим?

2024-02-16 07:33 UTC, glebkos commented on source/sorting.js
> +"using strict";
Изменения в строгом режиме:

- Превращает некоторые прощавшиеся ранее ошибки в исключения. 
JavaScript временами придаёт заведомо ошибочным операциям семантику нормального кода. Строгий режим расценивает такие ошибки как ошибки времени выполнения, для того чтобы они могли быть обнаружены и исправлены в обязательном порядке.
- Упрощает сопоставление имени переменной с местом её определения в коде. 
При компиляции JavaScript простое сопоставление имени переменной с местом её определения в коде невозможно, без выполнения того самого кода. Строгий же режим исключает большинство таких случаев, благодаря чему оптимизации компилятора работают эффективнее.
- В строгом режиме снижается количество странностей в поведении `arguments` и `eval`.
Строгий режим вводит ограничения для `arguments` и `eval`, что уменьшает количество "аномалий" в коде
- Упрощает написание "безопасного" JavaScript-кода.
В браузерах, JavaScript может иметь доступ к приватной информации пользователя, поэтому, в целях ограничения доступа к запретной функциональности, такой JavaScript перед выполнением должен быть частично преобразован. Для этого необходимо сделать многочисленные проверки во время исполнения, что приведет к потерям производительности. Но, некоторые особенности строгого режима, плюс обязательное требование того, чтобы JavaScript, загруженный пользователем, имел строгий режим и вызывался определённым способом, существенно снижают потребность проверках. 
- Введены ограничения для упрощения перехода на новые версии.
В будущих версиях ECMAScript с высокой вероятностью появится новый синтаксис, и для упрощения перехода на новые версии, в строгом режиме ECMAScript 5 введено несколько ограничений.

2024-02-17 09:20 UTC, DPeshkoff requested changes

2024-02-17 09:20 UTC, DPeshkoff commented on source/sorting.js
> +function comparator(a, b){
Гоу стрелочной?)

2024-02-17 10:16 UTC, glebkos commented on source/sorting.js
> +function comparator(a, b){
Я решил сделать функцией потому что: 
- На момент написания функции я не знал сколько раз я ее буду использовать.
- Функция своим названием наводит на ее содержание.
- Я хотел попробовать разные пути подхода, предоставляемые языком.

Соответсвенно вопрос: а нужно ли переписывать?

2024-02-17 18:08 UTC, glebkos commented on source/sorting.js
> +function comparator(a, b){
Я переделал

2024-02-18 12:29 UTC, closed without merging