Спасскова Ксения
frontend-park-mail-ru/homework_2024_1 pull request #11
Opened 2024-02-11 11:46 UTC by sp20ks

2024-02-11 12:01 UTC, Glibusss requested changes

2024-02-11 12:01 UTC, Glibusss commented on index.html
> -<script src="tests/max.js"></script>
Как и это

2024-02-11 12:05 UTC, Glibusss commented
Привет! Меня зовут Глеб и я буду ревьюером твоего ДЗ0. Ты очень хорошо справилась с заданием, но я внёс пару мелких правок. По всем вопросам ты можешь ко мне обратиться в:
[VK](https://vk.com/glibu_s)
[TG](https://web.telegram.org/k/#@glibusss)

2024-02-11 12:06 UTC, Glibusss commented on tests/roman.js
> +		assert.strictEqual(roman('&!"№%::?*()'), null);
Попробуй сделать тесты с входным Object или массивом

2024-02-11 12:14 UTC, Glibusss commented on source/roman.js
> +const roman = (input) => {
К слову, не забудь написать JSDoc для функций

2024-02-11 12:26 UTC, sp20ks commented on source/roman.js
> +'use strict'; // строгий режим
директива включает строгий режим интерпретатора. в таком режиме можно поймать некоторые ошибки, которые в грязном режиме были бы проигнорированы.

2024-02-11 12:26 UTC, Glibusss commented on source/roman.js
> +'use strict'; // строгий режим
А какие например?

2024-02-11 14:11 UTC, sp20ks commented on source/roman.js
> +'use strict'; // строгий режим
например, нельзя глобальную переменную создать или модифицировать сущности, которые только для чтения (arguments, как пример)

2024-02-11 14:12 UTC, sp20ks commented on source/roman.js
> +const roman = (input) => {
Декларативное объявление нужно, когда мы не планируем функцию передавать в качестве параметра. Такие функции создаются интерпретатором до выполнения кода (их можно вызвать до объявления).

При помощи функционального выражения функции можно передавать в качестве аргумента, создавать анонимные функции.

Стрелочная функция анонимная, но ее можно присвоить переменной. из особенностей - this у функции не свой, а контекста, из которого происходит вызов

2024-02-11 14:13 UTC, Glibusss commented on source/roman.js
> +const roman = (input) => {
Супер!

2024-02-11 14:13 UTC, sp20ks commented on source/roman.js
> +function preprocessInput(input) {
объявила preprocessInput как раз, чтоб использовать функцию до ее объявления. сделала так для того, чтобы код читался сверху вниз по мере появления функций в контексте

2024-02-11 14:14 UTC, Glibusss commented on source/roman.js
> +const roman = (input) => {
Не забудь про JSDoc

2024-02-11 14:16 UTC, Glibusss commented on source/roman.js
> +}
Оставь пустую строчку в конце файла(в тестах тоже). Так будет более удобно писать что-либо ещё в перспективе

2024-02-11 14:19 UTC, Glibusss commented on source/roman.js
> +function preprocessInput(input) {
Молодец, но правила есть правила, современный стиль есть современный стиль, поэтому лучше перепиши на arrow function

2024-02-11 19:01 UTC, sp20ks commented on source/roman.js
> +function preprocessInput(input) {
поправила

2024-02-11 19:07 UTC, Glibusss commented on index.html
> -<script src="source/max.js"></script>
max.js и тесты для него не нужно было убирать

2024-02-12 08:53 UTC, sp20ks commented on index.html
> -<script src="source/max.js"></script>
и это вернула

2024-02-12 08:58 UTC, Glibusss commented on source/roman.js
> +
Теперь финишная прямая. Тут нужно убрать пустую строчку

2024-02-12 09:01 UTC, Glibusss commented on source/roman.js
> +    if (typeof input !== 'number' && typeof input !== 'string') {
Попробуй написать тест с входным объектом String, в конструктор которой переданы валидные входные данные. Например new String(‘XV’)

2024-02-12 15:41 UTC, sp20ks commented on source/roman.js
> +    if (typeof input !== 'number' && typeof input !== 'string') {
добавила

2024-02-12 15:42 UTC, sp20ks commented on source/roman.js
> +
поправила

2024-02-12 15:44 UTC, Glibusss commented
Молодец! Ставлю апрув

2024-02-12 15:45 UTC, Glibusss approved these changes

2024-02-13 22:44 UTC, DPeshkoff requested changes
Привет! Мне нравится твое решение, но кое-что надо поправить)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 22:44 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Произошли страшные вещи - предлагаю тут поменять местами, чтобы не было diff'а

Лишний diff - не ок, представь, что у тебя не 3 файлика, а 30)

2024-02-13 22:44 UTC, DPeshkoff commented on tests/roman.js
> +		assert.strictEqual(roman(['VI', 'V']), null);
Предлагаю еще всяких гадостей напроверять - вдруг там Function будет на входе...

2024-02-13 22:44 UTC, DPeshkoff commented on source/roman.js
> +    if (!isNaN(numericInput)) {
А чем `isNaN` отличается от `Number.isNaN`?

2024-02-13 22:44 UTC, DPeshkoff commented on source/roman.js
> +        return null;
Предлагаю [throw'ать](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw)

2024-02-15 17:59 UTC, sp20ks commented on source/roman.js
> +    if (!isNaN(numericInput)) {
```IsNaN``` сначала кастит к Number, а после проверяет, является ли NaN. ```Number.IsNaN``` не приводит типы, а просто проверяет значение, т.е. при одной и той же, например, строке, переданной в качестве аргумента, функции вернут разные значения.

2024-02-15 22:45 UTC, DPeshkoff approved these changes

2024-02-15 22:45 UTC, closed without merging