Сапранов Дима - Вар 2
frontend-park-mail-ru/homework_2024_1 pull request #12
Opened 2024-02-11 16:41 UTC by UserNameShouldBeHere

2024-02-11 17:15 UTC, mafin1799 commented
Поправь название ПР "Фамилия Имя студента"

2024-02-11 17:27 UTC, mafin1799 reviewed
Привет.
Меня зовут Никита
Проверяю твое дз0

Если возникнут вопросы пиши в телегу @macmafin_17

2024-02-11 17:27 UTC, mafin1799 commented on source/euclid.js
> +'use strict';
А что такое этот 'use strict'
Для чего он используется?
Когда работает по умолчанию?

2024-02-11 17:27 UTC, mafin1799 commented on source/euclid.js
> +function gcd(num1, num2) {
Почему тут используешь function declaration?
Еще есть arrow function.

Одно из отличий в том, что второе более модное и современное
https://learn.javascript.ru/arrow-functions-basics

Ответь какая между ними разница, можешь также переписать на стрелочные функции

2024-02-11 17:27 UTC, mafin1799 commented on source/euclid.js
> +    if (num2 == 0)
В js можно использовать 2 оператора равенства == и ===
Почему выбрал ==
Какие отличия от ===
Как можно сократить эту проверку и написать вообще без ==

2024-02-11 17:27 UTC, mafin1799 commented on source/euclid.js
> +function euclid(...numbers) {
Что значат эти ...

2024-02-11 17:27 UTC, mafin1799 commented on source/euclid.js
> +    for (let i = 1; i < numbers.length; i++) {
Тут вполне спокойно можно использовать foreach

2024-02-11 17:27 UTC, mafin1799 commented on source/euclid.js
> +function gcd(num1, num2) {
Еще для функций нужно написать JSDoc
Вот пример
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/90977148/f1ce69db-7ccb-4039-84ee-26104b71e56e)

2024-02-11 18:24 UTC, UserNameShouldBeHere commented on source/euclid.js
> +'use strict';
'use strict' говорит о том, что мы используем строгий режим, т.е. обеспечивается обратная совместимость, ловится больше ошибок. При использовании классов или модулей 'use strict' включается автоматически

2024-02-11 18:26 UTC, UserNameShouldBeHere commented on source/euclid.js
> +    if (num2 == 0)
== допускает приведение типов
=== не допускает приведение типов
можно использовать !num, чтобы не писать сравнение с 0

2024-02-11 18:29 UTC, UserNameShouldBeHere commented on source/euclid.js
> +function euclid(...numbers) {
тут это остаточные параметры, т.е. все параметры, переданные в функцию

2024-02-11 18:31 UTC, mafin1799 commented on source/euclid.js
> +'use strict';
окей

2024-02-11 18:31 UTC, mafin1799 commented on source/euclid.js
> +    if (num2 == 0)
если еще не переписал, то стоит сократить условие таким образом

2024-02-11 18:34 UTC, UserNameShouldBeHere commented on source/euclid.js
> +    if (num2 == 0)
уже отправил коммит

2024-02-11 18:34 UTC, mafin1799 commented on source/euclid.js
> +function euclid(...numbers) {
обычно так обозначается rest параметр, который собирает аргументы в массив

2024-02-11 18:35 UTC, mafin1799 commented on source/euclid.js
> +        result = gcd(result, number)
; забыл

2024-02-11 18:35 UTC, mafin1799 commented on source/euclid.js
> +        return undefined
;

2024-02-11 18:36 UTC, mafin1799 commented on source/euclid.js
> +        return undefined
и скорее лучше вернуть null
Расскажи какие отличия undefined и  null

2024-02-11 18:37 UTC, UserNameShouldBeHere commented on source/euclid.js
> +function gcd(num1, num2) {
разница в том, что у стрелочных нет this, они берут его из функции, которая их вызывает, а также стрелочные используются для передачи в качестве параметра в другие функции

2024-02-11 18:38 UTC, mafin1799 commented on source/euclid.js
> +    if (num2 == 0)
ок, не заметил, простити

2024-02-11 18:39 UTC, mafin1799 commented on source/euclid.js
> +        result = gcd(result, number)
проверь везде наличие ; отступов и пробелов
https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda
Вот статейка с рекомендациями по стилю кода

2024-02-11 18:41 UTC, UserNameShouldBeHere commented on source/euclid.js
> +        return undefined
undefined это объявленная, но не инициализированная переменная
null это нулевое значение переменной

2024-02-11 18:42 UTC, UserNameShouldBeHere commented on source/euclid.js
> +        result = gcd(result, number)
насколько важны ; ?
Js не че то ругался на это

2024-02-11 18:50 UTC, mafin1799 commented on source/euclid.js
> +        return undefined
верно

2024-02-11 18:53 UTC, mafin1799 commented on source/euclid.js
> +        result = gcd(result, number)
Да, js не ругается на ;
Но бывают подводные камни))

2024-02-11 18:56 UTC, UserNameShouldBeHere commented on source/euclid.js
> +        result = gcd(result, number)
все, прогнал через линтер

2024-02-11 18:56 UTC, mafin1799 commented on source/euclid.js
> +        result = gcd(result, number)
окей

2024-02-11 19:01 UTC, mafin1799 commented on source/euclid.js
> +        result = gcd(result, number)
после этого коммита пропали стрелочные функции

2024-02-11 19:05 UTC, mafin1799 commented on tests/euclid.js
> +	QUnit.test('Функция должна правильно находить НОД двух натуральных чисел', function (assert) {
Давай добавим проверки на то, что число не натуральное, отрицательное и ноль

И то что передается не число а строка, объект, true/false

2024-02-11 19:05 UTC, mafin1799 commented on source/euclid.js
> +    let result = numbers[0];
Заметил, что этот блок кода красиво бы смотрелся с reduce()
https://doka.guide/js/array-reduce/

2024-02-11 20:03 UTC, mafin1799 commented on tests/euclid.js
> +	QUnit.test('Функция должна правильно находить НОД двух натуральных чисел', function (assert) {
ok

2024-02-12 15:35 UTC, DPeshkoff requested changes
Привет! Прикольное решение, но нужно кое-что поправить)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-12 15:35 UTC, DPeshkoff commented on source/euclid.js
> +"use strict";
А что делает эта строчка?

2024-02-12 15:35 UTC, DPeshkoff commented on source/euclid.js
> +function gcd(num1, num2) {
Гоу стрелочной)

2024-02-12 15:35 UTC, DPeshkoff commented on source/euclid.js
> +        throw new Error("numbers should be natural");
Что думаешь, может, лучше [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RangeError)?

2024-02-12 15:35 UTC, DPeshkoff commented on source/euclid.js
> +}
\n

2024-02-12 15:35 UTC, DPeshkoff commented on tests/euclid.js
> +"use strict";
Предлагаю вернуть, как было

2024-02-12 15:35 UTC, DPeshkoff commented on tests/euclid.js
>  	});
Исходное не меняем)

2024-02-13 09:55 UTC, UserNameShouldBeHere commented on source/euclid.js
> +function gcd(num1, num2) {
Я прогнал через JsLint и там была ошибка, что для стрелочной много параметров и лучше заменить на обычную

2024-02-13 09:55 UTC, UserNameShouldBeHere commented on source/euclid.js
> +"use strict";
'use strict' говорит о том, что мы используем строгий режим, т.е. обеспечивается обратная совместимость, ловится больше ошибок. При использовании классов или модулей 'use strict' включается автоматически

2024-02-13 09:56 UTC, UserNameShouldBeHere commented on tests/euclid.js
> +"use strict";
тут жаловался линтер, поэтому я поставил ""

2024-02-13 10:00 UTC, UserNameShouldBeHere commented on tests/euclid.js
>  	});
и тут тоже линтер жаловался.... Я просто поменял кавычки с ' на "

2024-02-13 10:03 UTC, UserNameShouldBeHere commented on source/euclid.js
> +        throw new Error("numbers should be natural");
ага, поменял

2024-02-13 22:35 UTC, DPeshkoff requested changes

2024-02-13 22:35 UTC, DPeshkoff commented on source/euclid.js
> +function gcd(num1, num2) {
JsLint можно конфигурировать, как и любой линтер. У нас все-таки уже готовый проект (пусть и не полный), а тут имеет смысл придерживаться имеющихся правил кодстайла)

Поэтому гоу стрелочную)

Кстати, чем они отличаются от обычных?

2024-02-13 22:35 UTC, DPeshkoff commented on tests/euclid.js
> +"use strict";
Ну, изменения тут точно не нужны, старый кодстайл не меняем)

2024-02-13 22:37 UTC, DPeshkoff commented on source/euclid.js
> +        result = gcd(result, number)
> насколько важны ; ? Js че то не ругался на это

<img width="570" alt="Снимок экрана 2024-02-14 в 01 37 11" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/a69b8be9-6731-4fce-a02f-544e2ab56093">

Как думаешь, почему так происходит?

2024-02-14 07:19 UTC, UserNameShouldBeHere commented on source/euclid.js
> +        result = gcd(result, number)
js склеил строчки....

2024-02-14 21:21 UTC, DPeshkoff approved these changes

2024-02-14 21:22 UTC, closed without merging