Variant 3
frontend-park-mail-ru/homework_2024_1 pull request #13
Opened 2024-02-11 16:48 UTC by dozerdozerdozer

2024-02-11 17:14 UTC, Glibusss requested changes

2024-02-11 17:14 UTC, Glibusss commented on source/roman.js
> +function containsDigits(input) {
Имхо, здесь это излишне, но в принципе работает. [А узнать, как это сделать проще поможет простой jsный...](https://learn.javascript.ru/number#proverka-isfinite-i-isnan)

2024-02-11 17:14 UTC, Glibusss commented on source/roman.js
> +    let i = 12;
Давай называть переменные информативно

2024-02-11 17:14 UTC, Glibusss commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
Тут та же ситуация с function declaration

2024-02-11 17:14 UTC, Glibusss commented on source/roman.js
> +function romanToArab(input, romanNumbers) {
Как и тут

2024-02-11 17:14 UTC, Glibusss commented on source/roman.js
> +    while (A > 0) {
Подумай, как бы ты смог решить эту задачу с помощью [Перебирающих методов](https://learn.javascript.ru/array-iteration)
P.S. Это реально

2024-02-11 17:17 UTC, Glibusss commented
Привет! Меня зовут Глеб и я буду ревьюировать твоё ДЗ0. Я оставил несколько исправлений к твоему решению и пару вопросов. Также тебе нужно будет дописать тесты. По всем вопросам ты можешь обратиться ко мне в 
[https://vk.com/glibu_s](VK)
TG: @glmakko

2024-02-11 17:23 UTC, dozerdozerdozer commented on index.html
сделал

2024-02-11 17:27 UTC, dozerdozerdozer commented on source/roman.js
> +'use strict';
как я понял, эта строчка позволяет очень старому коду работать (на подобии "var"). Написал ее, потому что в max.js она есть + в учебнике написано, что лучше всегда писать

2024-02-11 17:29 UTC, dozerdozerdozer commented on source/roman.js
> +function containsDigits(input) {
если в строке есть цифры, то arabToRoman, если нет - romanToArab

2024-02-11 17:30 UTC, dozerdozerdozer commented on source/roman.js
> +    let i = 12;
i - просто итератор

2024-02-11 17:33 UTC, Glibusss commented on source/roman.js
> +'use strict';
Советую изучить вопрос [здесь](https://learn.javascript.ru/strict-mode)

2024-02-11 17:34 UTC, dozerdozerdozer commented on source/roman.js
> +    while (A > 0) {
можно попробовать через стэк сделать - добавляем символы, пока не попадется символ с бОльшим числом или не кончится строка.

2024-02-11 17:36 UTC, Glibusss commented on source/roman.js
> +function containsDigits(input) {
А вот этот момент проверить поможет такая интересная штука, как проверка на NaN. Подумай, как можно с ним работать

2024-02-11 17:36 UTC, Glibusss commented on source/roman.js
> +    let i = 12;
Лучше в таком случае index, result

2024-02-11 17:37 UTC, dozerdozerdozer commented on source/roman.js
> +'use strict';
вот я этот учебник и читал, и отложилось только про обратную совместимость

2024-02-11 17:38 UTC, dozerdozerdozer commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
не совсем понял. Имеется ввиду, что передаваемые переменные не информативно названы?

2024-02-11 17:42 UTC, Glibusss commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
Не, имею ввиду, что помимо такого объявления есть другие виды. Подумай в чём их различия и какой лучше всего подходит в контексте задачи

2024-02-11 17:47 UTC, dozerdozerdozer commented on source/roman.js
> +function containsDigits(input) {
if (isNaN(roman)) {
        return romanToArab(roman, romanNumbers);
    } else {
        return arabToRoman(roman, romanNumbers);
    }
    
    используя это свойство "alert( isNaN("str") ); // true"

2024-02-11 17:57 UTC, dozerdozerdozer commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
по хорошему надо сделать вспомогательные функции анонимными с помощью функционального выражения

2024-02-11 18:06 UTC, Glibusss commented on source/roman.js
> +'use strict';
Хорошо, пришло время для [Серьёзных учебников](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Strict_mode)

2024-02-11 18:06 UTC, Glibusss commented on source/roman.js
> +function containsDigits(input) {
Молодец!

2024-02-11 18:07 UTC, Glibusss commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
Ну в таком случае лучше стрелочные функции. Как ты думаешь, почему?

2024-02-11 18:25 UTC, dozerdozerdozer commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
мб синтаксис короче, и так же анонимны

2024-02-11 18:27 UTC, Glibusss commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
А также более современный способ объявления функций

2024-02-11 18:44 UTC, dozerdozerdozer commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
'use strict';

const roman = (roman) => {
    const romanNumbers = [
        {num: 1, ch: "I"}, {num: 4, ch: "IV"}, {num: 5, ch: "V"},
        {num: 9, ch: "IX"}, {num: 10, ch: "X"}, {num: 40, ch: "XL"},
        {num: 50, ch: "L"}, {num: 90, ch: "XC"}, {num: 100, ch: "C"},
        {num: 400, ch: "CD"}, {num: 500, ch: "D"}, {num: 900, ch: "CM"},
        {num: 1000, ch: "M"},
    ];

    if (isNaN(roman)) {
        roman = roman.toUpperCase();
        let idx = 12;
        let pointer = 0;
        let result = 0;
        while (pointer < roman.length) {
            while (roman.substring(pointer, pointer + romanNumbers[idx].ch.length) !== romanNumbers[idx].ch) {
                idx--;
                if (idx === 0) break;
            }
            result += romanNumbers[idx].num;
            pointer += romanNumbers[idx].ch.length;
        }
        return result;
    } else {
        let pointer = 12;
        let result = "";
        let A = roman;
        while (A > 0) {
            while (romanNumbers[pointer].num > A) {
                pointer -= 1;
            }
            result += romanNumbers[pointer].ch;
            A -= romanNumbers[pointer].num;
        }
        return result;
    }
}

2024-02-11 18:47 UTC, Glibusss commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
Коммить

2024-02-11 18:47 UTC, Glibusss commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
Не нужно в комментах писать

2024-02-11 18:47 UTC, Glibusss commented on source/roman.js
> +function containsDigits(input) {
Это тоже закоммить

2024-02-11 19:07 UTC, dozerdozerdozer commented on source/roman.js
> +function arabToRoman(input, romanNumbers) {
закоммитил

2024-02-11 19:10 UTC, Glibusss commented on source/roman.js
> +}
Пустую строчку в конец файла

2024-02-11 19:13 UTC, Glibusss commented on source/roman.js
> -
Нене, добавь

2024-02-11 19:14 UTC, dozerdozerdozer commented on source/roman.js
> -
я пытаюсь, она не появляется

2024-02-11 19:27 UTC, Glibusss commented on source/roman.js
> +const roman = (roman) => {
Финальные штрихи. Нужно написать JSDoc

2024-02-11 19:28 UTC, Glibusss commented on source/roman.js
> +    if (isNaN(roman)) {
Хорошо. Теперь подумай, что можно передать, чтобы поломать. Начни с написания новых тестов, так будет удобнее

2024-02-11 20:17 UTC, dozerdozerdozer commented on source/roman.js
> +    if (isNaN(roman)) {
добавил тестов, под них программу переделал

2024-02-11 20:17 UTC, dozerdozerdozer commented on source/roman.js
> +const roman = (roman) => {
сделал

2024-02-11 20:17 UTC, Glibusss commented on source/roman.js
> +        console.log(roman)
Это нельзя

2024-02-11 20:19 UTC, Glibusss commented on source/roman.js
> +console.log(isNaN("boba"))
console.log() надо убрать

2024-02-11 20:19 UTC, Glibusss commented on tests/roman.js
> +		assert.strictEqual(roman('5000'), 'IƆƆƆ');
Попробуй добавить тесты с невалидными входными данными

2024-02-11 20:19 UTC, Glibusss commented on tests/roman.js
>  });
Строчку в конце файла

2024-02-11 20:20 UTC, dozerdozerdozer commented on source/roman.js
> +    let i = 12;
сделал

2024-02-11 20:20 UTC, dozerdozerdozer commented on source/roman.js
> +        console.log(roman)
убрал

2024-02-11 20:20 UTC, dozerdozerdozer commented on source/roman.js
> +console.log(isNaN("boba"))
убрал

2024-02-11 20:34 UTC, dozerdozerdozer commented on tests/roman.js
> +		assert.strictEqual(roman('5000'), 'IƆƆƆ');
готово

2024-02-11 20:35 UTC, Glibusss commented on source/roman.js
> +            return "Не валидные данные!";
Лучше undefined или null возвращать, либо кидать исключения

2024-02-11 20:36 UTC, Glibusss commented on tests/roman.js
> +		assert.strictEqual(roman('VHBVbBVYBSUYIHBVohivbhjxbhdvVIIIIIAAAAA'), 'Не валидные данные!');
А если объект передать или к примеру массив?

2024-02-11 20:37 UTC, dozerdozerdozer commented on source/roman.js
> +            return "Не валидные данные!";
сделал

2024-02-11 20:44 UTC, dozerdozerdozer commented on tests/roman.js
> +		assert.strictEqual(roman('VHBVbBVYBSUYIHBVohivbhjxbhdvVIIIIIAAAAA'), 'Не валидные данные!');
сделал

2024-02-11 20:47 UTC, Glibusss commented on source/roman.js
> +    if (typeof (roman) !== "number" && typeof (roman) !== "string") {
Не вижу смысла во вложенности здесь.
else не нужен т.к. при выполнении условия в любом случае закончится выполнение и вернётся null

2024-02-11 20:49 UTC, Glibusss commented on tests/roman.js
> +		assert.strictEqual(roman('VHBVbBVYBSUYIHBVohivbhjxbhdvVIIIIIAAAAA'), 'Не валидные данные!');
Накину ещё один интересный кейс. Существует объект String. Что произойдет, если я передам этот объект с валидными данными на вход?

2024-02-11 20:50 UTC, Glibusss commented on tests/roman.js
> +		assert.strictEqual(roman('5000'), 'IƆƆƆ');
А если передать 5000000? Infinity?

2024-02-11 20:51 UTC, dozerdozerdozer commented on source/roman.js
> +    if (typeof (roman) !== "number" && typeof (roman) !== "string") {
исправил

2024-02-11 20:57 UTC, dozerdozerdozer commented on tests/roman.js
> +		assert.strictEqual(roman('VHBVbBVYBSUYIHBVohivbhjxbhdvVIIIIIAAAAA'), 'Не валидные данные!');
null выдаст, исправляю

2024-02-11 21:15 UTC, dozerdozerdozer commented on tests/roman.js
> +		assert.strictEqual(roman('VHBVbBVYBSUYIHBVohivbhjxbhdvVIIIIIAAAAA'), 'Не валидные данные!');
не знаю, как не пропускать массив, но в то же время пропускать new String("V"). сделал typeof (roman) !== "object", стал проходить массив

2024-02-11 21:16 UTC, dozerdozerdozer commented on tests/roman.js
> +		assert.strictEqual(roman('5000'), 'IƆƆƆ');
ограничил 8999

2024-02-11 21:16 UTC, dozerdozerdozer commented on tests/roman.js
>  });
сделал

2024-02-11 21:26 UTC, Glibusss commented on tests/roman.js
> +		assert.strictEqual(roman('VHBVbBVYBSUYIHBVohivbhjxbhdvVIIIIIAAAAA'), 'Не валидные данные!');
Дам небольшую подсказку. Проверь на возможность привести к типу, а заодно проверку по регулярке

2024-02-11 21:37 UTC, dozerdozerdozer commented on tests/roman.js
> +		assert.strictEqual(roman('VHBVbBVYBSUYIHBVohivbhjxbhdvVIIIIIAAAAA'), 'Не валидные данные!');
сделал

2024-02-12 05:01 UTC, Glibusss commented on source/roman.js
> +    if (!/^(string|number)$/.test(typeof roman) && !(roman instanceof String)) {
Дам ещё подсказку. [Почитай про преобразование](https://learn.javascript.ru/number#parseint-i-parsefloat), проверь на возможность преобразовать к числу, в случае невозможности, приведи к строке и проверяй по регулярке

2024-02-12 09:53 UTC, dozerdozerdozer commented on source/roman.js
> +    if (!/^(string|number)$/.test(typeof roman) && !(roman instanceof String)) {
сделал

2024-02-12 09:55 UTC, Glibusss commented on source/roman.js
> +
Оставь одну пустую строчку

2024-02-12 09:56 UTC, Glibusss commented on tests/roman.js
>  });
Одну пустую строчку в конце файла

2024-02-12 10:04 UTC, dozerdozerdozer commented on source/roman.js
> +
сдулал

2024-02-12 10:04 UTC, dozerdozerdozer commented on tests/roman.js
>  });
сделал

2024-02-12 10:04 UTC, Glibusss commented
Больше вопросов нет! Ставлю апрув

2024-02-12 14:33 UTC, Glibusss approved these changes

2024-02-13 22:33 UTC, DPeshkoff requested changes
Привет! Хорошее решение, но нужна парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 22:33 UTC, DPeshkoff commented on index.html
> -
Тут не нужны изменения, предлагаю вернуть

2024-02-14 13:05 UTC, dozerdozerdozer commented on source/roman.js
> +    if (typeof(roman) === "string" || typeof(roman.valueOf()) === "string") {
немного переработал структуру проверки и дополнил регулярное выражение в проверке строки

2024-02-14 13:07 UTC, dozerdozerdozer commented on source/roman.js
> +        roman = roman.replace(" ", "").replace(".", "")
сделал

2024-02-14 13:09 UTC, dozerdozerdozer commented on source/roman.js
> +            }
сделал через startsWith

2024-02-14 13:09 UTC, dozerdozerdozer commented on source/roman.js
> +        let A;
переименовал в subSum

2024-02-14 13:09 UTC, dozerdozerdozer commented on tests/roman.js
> +	QUnit.test('roman правильно обрабатывает большие числа', function (assert) {
добавил обработку Infinity и NaN

2024-02-14 13:11 UTC, dozerdozerdozer commented on source/roman.js
> +        }
вот не совсем понимаю на счет ошибки. Если добавить выкидывание ошибки, то, как я понял, вызов этой функции надо заворачивать в try{} catch{}. Получается эту конструкцию надо в тест закидывать?

2024-02-14 13:43 UTC, dozerdozerdozer commented on source/roman.js
> +'use strict';
use strict - строгий режим, в котором отлавиваются некоторые ошибки на ранних стадиях, запрещается использование глобальных переменных, повышается производительность, учучшается безопасность

2024-02-15 23:06 UTC, DPeshkoff commented on source/roman.js
> +        }
[Не обязательно](https://api.qunitjs.com/assert/throws/)

2024-02-15 23:09 UTC, DPeshkoff requested changes

2024-02-15 23:09 UTC, DPeshkoff commented on source/roman.js
> +        while (pointer < roman.length && idx >= 0) {
Можно еще и по-другому по строке итерироваться)

2024-02-15 23:09 UTC, DPeshkoff commented on source/roman.js
> +            throw new Error('Число превышает максимально допустимое значение');
Кажется, удобнее [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RangeError)

2024-02-15 23:09 UTC, DPeshkoff commented on source/roman.js
> +    if (isNaN(parseInt(roman))) {
А как работает приведение типов в каждом из кейсов?

2024-02-15 23:09 UTC, DPeshkoff commented on source/roman.js
> +        if (typeof (roman) === 'string') {
А тут точно такая строка?)

2024-02-15 23:09 UTC, DPeshkoff commented on tests/roman.js
> +		QUnit.test('roman правильно переводит из римской системы счисления', function (assert) {
Давай вернем как было - тут какой-то странный diff

2024-02-15 23:25 UTC, dozerdozerdozer commented on source/roman.js
> +    if (isNaN(parseInt(roman))) {
isNaN пытается преобразовать строку в число, и если не получится вернет true. Number.isNaN не пытается преобразовать строку в число перед проверкой, он строго проверяет, является ли типом number и равен NaN

2024-02-15 23:26 UTC, dozerdozerdozer commented on tests/roman.js
> +		QUnit.test('roman правильно переводит из римской системы счисления', function (assert) {
не понял про что

2024-02-15 23:28 UTC, dozerdozerdozer commented on source/roman.js
> +        }
сделал

2024-02-15 23:28 UTC, dozerdozerdozer commented on source/roman.js
> +        if (typeof (roman) === 'string') {
поменял

2024-02-15 23:31 UTC, dozerdozerdozer commented on source/roman.js
> +            throw new Error('Число превышает максимально допустимое значение');
сделал

2024-02-17 09:21 UTC, DPeshkoff commented on tests/roman.js
> +		QUnit.test('roman правильно переводит из римской системы счисления', function (assert) {
<img width="837" alt="Снимок экрана 2024-02-17 в 12 21 01" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/7ac3e27a-c05a-4091-8776-f54860767a67">

2024-02-17 09:23 UTC, DPeshkoff requested changes

2024-02-17 09:23 UTC, DPeshkoff commented on source/roman.js
> +        while (pointer < roman.length && idx >= 0) {
Строки можно развернуть)

2024-02-17 09:23 UTC, DPeshkoff commented on source/roman.js
> +        if (typeof (roman) === 'string') {
Не поменял, на 20 строке сам же написал другие виды)

2024-02-17 09:24 UTC, DPeshkoff commented on source/roman.js
> +    if (isNaN(parseInt(roman))) {
И какой нам нужен, если мы уже парсим parseInt?

2024-02-18 09:22 UTC, dozerdozerdozer commented on tests/roman.js
> +		QUnit.test('roman правильно переводит из римской системы счисления', function (assert) {
там табуляция съехала почему-то, исправил

2024-02-18 09:23 UTC, dozerdozerdozer commented on source/roman.js
> +        if (typeof (roman) === 'string') {
исправил

2024-02-18 09:23 UTC, dozerdozerdozer commented on source/roman.js
> +        while (pointer < roman.length && idx >= 0) {
переделал логику перевода из римского вида в численный, без вложенного цикла

2024-02-18 09:24 UTC, dozerdozerdozer commented on source/roman.js
> +    if (isNaN(parseInt(roman))) {
согласен. Number.isNaN() лучше подходит. исправил

2024-02-18 15:45 UTC, DPeshkoff requested changes

2024-02-18 15:45 UTC, DPeshkoff commented on tests/roman.js
> -	});
Не исправил(

![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/fc44a08c-1939-4a60-bc0b-90f5e30e5173)

2024-02-19 12:53 UTC, dozerdozerdozer commented on tests/roman.js
> -	});
поправил

2024-02-19 15:46 UTC, DPeshkoff requested changes

2024-02-19 15:46 UTC, DPeshkoff commented on tests/roman.js
> -	});
И снова нет(

2024-02-19 18:04 UTC, dozerdozerdozer commented
напиши, пожалуйста, сколько пробелов один отступ. Потому что я сделал в точности, как в примере, и всё равно возникают ошибки

2024-02-20 15:05 UTC, dozerdozerdozer commented
исправил

2024-02-21 16:25 UTC, DPeshkoff approved these changes

2024-02-21 16:27 UTC, closed without merging