homework_1
frontend-park-mail-ru/homework_2024_1 pull request #14
Opened 2024-02-11 17:38 UTC by EvilAv

### Вуколов Андрей
Решение первого дз

2024-02-11 18:03 UTC, Glibusss requested changes

2024-02-11 18:03 UTC, Glibusss commented on tests/get.js
> +		assert.strictEqual(get(object, '.'), object);
Подумай, что ещё валидное или нет можно передать в параметры и допиши тесты

2024-02-11 18:07 UTC, EvilAv commented on source/get.js
> +'use strict'
включает строгий режим, который ругается на всякие легаси штуки

2024-02-11 18:08 UTC, Glibusss commented
Привет! Меня зовут Глеб и я буду ревьюировать твоё ДЗ0. Я оставил несколько исправлений к твоему решению и пару вопросов. Также тебе нужно будет дописать тесты. По всем вопросам ты можешь обратиться ко мне в
[https://vk.com/glibu_s](https://github.com/frontend-park-mail-ru/homework_2024_1/pull/VK)
TG: @glmakko

2024-02-11 18:08 UTC, Glibusss commented on source/get.js
> +'use strict'
Так-так. И какие такие штуки?)

2024-02-11 18:19 UTC, EvilAv commented on source/get.js
> +function get(obj, property){
функцию объявленную при помощи function declaration видно до объявление, т.е. если функцию объявляем в конце файла, то в самом начале можно ее спокойно использовать
есть еще function expression, выглядит примерно так `const f = function() {return 'ok'}`, ее можно использовать только после объявления

2024-02-11 18:20 UTC, Glibusss commented on source/get.js
> +function get(obj, property){
Не назвал ещё одну

2024-02-11 18:25 UTC, EvilAv commented on source/get.js
> +'use strict'
например объявление переменной без ключевого слова примерно как в питоне, раньше так можно было, но теперь нельзя

2024-02-11 18:25 UTC, EvilAv commented on source/get.js
> +function get(obj, property){
есть еще стрелочные функции

2024-02-11 18:28 UTC, Glibusss commented on source/get.js
> +'use strict'
А ещё?

2024-02-11 18:29 UTC, Glibusss commented on source/get.js
> +function get(obj, property){
Правильно, стоит переписать на них. Как ты думаешь, почему?

2024-02-11 18:47 UTC, EvilAv commented on source/get.js
> +function get(obj, property){
не знаю, чуть меньше символов писать?

2024-02-11 18:55 UTC, Glibusss commented on source/get.js
> +function get(obj, property){
1) Это более современный способ задания функций. Он предпочтительнее
2) Контекст выполнения тебя не обязывает к определенному объявлению [Подробнее читай здесь](https://learn.javascript.ru/arrow-functions)

2024-02-11 19:04 UTC, Glibusss commented on source/get.js
> +    if (!property) return undefined;
Почти. Ты же ожидаешь только строку. Проверь на неё

2024-02-11 19:08 UTC, EvilAv commented on source/get.js
> +'use strict'
нельзя, чтобы у объекта было несколько свойств с одинаковыми ключами.
если у объекта свойство отмечено как свойство в котором нельзя менять его значения, то при попытке присвоения ему нового значения будет ошибка

2024-02-11 19:31 UTC, Glibusss commented on source/get.js
> +    if (typeof(property) !== 'string') return undefined;
Близко. Но что будет если я передам объект String? Это тоже валидные входные данные

2024-02-11 19:32 UTC, Glibusss commented on source/get.js
> +}
Строчку в конце! Это хороший тон)

2024-02-11 19:49 UTC, EvilAv commented on source/get.js
> +    if (typeof(property) !== 'string') return undefined;
а про это точно было в условиях? По тестам не очень понятно что туда что-то кроме строки передают

2024-02-11 19:50 UTC, Glibusss commented on source/get.js
> +    if (typeof(property) !== 'string') return undefined;
Нужно, поверь. Если интересно, то потом расскажу

2024-02-11 19:54 UTC, Glibusss commented on source/get.js
> +    if (typeof(property) !== 'string') return undefined;
Как js-разработчик ты должен предусматривать если не все, то большинство случаев

2024-02-11 20:09 UTC, Glibusss commented
Осталось совсем немного! Нужно сделать arrow function и добавить строчки в конце файла!

2024-02-11 20:13 UTC, Glibusss commented on source/get.js
> +}
Нужно строчку в конце файла

2024-02-11 20:14 UTC, Glibusss commented on source/get.js
> +}
В тестовом файле не забудь

2024-02-11 20:29 UTC, Glibusss commented
Молодец! Заслуженный апрув!

2024-02-11 20:32 UTC, Glibusss commented on source/get.js
> +const get = (obj, property) => {
Прости пожалуйста, забыли одну важную вещь - нужно написать JSDoc

2024-02-11 20:53 UTC, Glibusss commented
Молодец! Апрув

2024-02-12 14:34 UTC, Glibusss approved these changes

2024-02-13 22:48 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 22:48 UTC, DPeshkoff commented on tests/max.js
> +
А зачем тут diff?

2024-02-13 22:48 UTC, DPeshkoff commented on source/get.js
> +    if (typeof(property) !== 'string' && !(property instanceof String)) return undefined;
Предлагаю сделать перенос и обернуть в {}

2024-02-13 22:48 UTC, DPeshkoff commented on source/get.js
> +        if (copy === undefined) return copy;
[Можно сократить](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

2024-02-13 22:48 UTC, DPeshkoff commented on tests/get.js
> +	QUnit.test('get правильно обрабатывает примитивы, переданный как первый аргумент', function (assert) {
Как думаешь, что еще можно сюда передать?

2024-02-14 09:07 UTC, EvilAv commented on tests/max.js
> +
добавил строчки в конце файлов, на всякий случай во всех файлах

2024-02-14 21:25 UTC, DPeshkoff requested changes

2024-02-14 21:25 UTC, DPeshkoff commented on source/get.js
> +    if (property[0] !== '.') return undefined;
{} и перенос)

2024-02-14 21:25 UTC, DPeshkoff commented on source/get.js
> +        if (!copy) return copy;
И тут

2024-02-14 21:25 UTC, DPeshkoff commented on tests/max.js
> +
Гоу уберем - не надо делать дифф там, где он не нужен)

2024-02-15 22:47 UTC, DPeshkoff approved these changes

2024-02-15 22:47 UTC, closed without merging