Новиков Богдан
frontend-park-mail-ru/homework_2024_1 pull request #15
Opened 2024-02-11 17:49 UTC by novakf

2024-02-11 17:50 UTC, mafin1799 commented
Привет
Меня зовут Никита
Буду проверять твое ДЗ0
Будут вопросы пиши в телегу @macmafin_17

2024-02-11 17:59 UTC, mafin1799 commented on source/sort.js
> +'use strict';
Что это за директива?
Зачем используется?
Когда работает по умолчанию?

2024-02-11 17:59 UTC, mafin1799 commented on source/sort.js
> +const sort = (sentence) => sentence.split(' ').map(wordSort).sort(ruComparator).join(' ');
Круто что используешь стрелочные функции)
Чем они отличаются от function declaration и function expression
Какие между ними отличия?

2024-02-11 17:59 UTC, mafin1799 commented on source/sort.js
> +  const collator = new Intl.Collator('ru-RU');
А что это такое?

2024-02-11 17:59 UTC, mafin1799 commented on source/sort.js
> +  word = word.split('').sort(ruComparator).join('');
Так как в твоем индивидуальном задании требуется написать функцию сортировки, то нужно написать свою реализацию

2024-02-11 18:04 UTC, mafin1799 commented on source/sort.js
> +const sort = (sentence) => sentence.split(' ').map(wordSort).sort(ruComparator).join(' ');
Также нужно написать JSDoc для функции

2024-02-11 18:48 UTC, novakf commented on source/sort.js
> +'use strict';
Директива 'use strict' указывает интерпретатору на то, что код должен выполняться в "строгом режиме", что позволит предотвратить некоторые потенциальные ошибки и сделать код более надежным (например, выдаст ошибку при использовании необъявленной переменой). 
По умолчанию всегда работает в модулях.

2024-02-11 18:49 UTC, mafin1799 commented on source/sort.js
> +'use strict';
И в классах
Отлично

2024-02-11 18:52 UTC, novakf commented on source/sort.js
> +  const collator = new Intl.Collator('ru-RU');
Intl.Collator() - конструктор класса, функция compare которого позволяет сравнивать символы, учитывая особенности языка, в данной функции использовал для правильного сравнения с буквой "ё".
Также можно было бы использовать localeCompare, данный метод сам использует Intl.Collator() под капотом, однако использование экземпляра класса Intl.Collator() производительнее при сортировке большого числа элементов.

2024-02-11 18:54 UTC, mafin1799 commented on source/sort.js
> +  const collator = new Intl.Collator('ru-RU');
окей)

2024-02-11 19:01 UTC, novakf commented on source/sort.js
> +const sort = (sentence) => sentence.split(' ').map(wordSort).sort(ruComparator).join(' ');
Функции, объявленные как function declaration, создаются интерпретатором до выполнения кода. Поэтому их можно вызвать до объявления, в отличие от function expressions.
Стрелочная функция - сокращенная версия function expression. Однако такие функции не имеют this и переменной arguments.

2024-02-11 19:06 UTC, mafin1799 commented on source/sort.js
> +const sort = (sentence) => sentence.split(' ').map(wordSort).sort(ruComparator).join(' ');
все верно

2024-02-11 19:31 UTC, novakf commented on source/sort.js
> +  word = word.split('').sort(ruComparator).join('');
Готово!

2024-02-11 19:37 UTC, mafin1799 commented on source/sort.js
> +  word = word.split('').sort(ruComparator).join('');
окей)
Все вроде норм

2024-02-11 19:39 UTC, mafin1799 commented
Молодец. У меня вопросов нет.

2024-02-13 22:15 UTC, DPeshkoff requested changes
Привет! Классное решение, но нужно кое-что поправить)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 22:15 UTC, DPeshkoff commented on source/sort.js
> +const wordSort = (word) => {
Ко всем функциям нужен JSDOC, гоу допишем)

2024-02-13 22:15 UTC, DPeshkoff commented on source/sort.js
> +  if (arr.length < 2) return arr;
Предлагаю добавить {} и сделать перенос)

2024-02-13 22:15 UTC, DPeshkoff commented on source/sort.js
> +    if (ruComparator(val, pivot) === -1) leftArr.push(val);
Тут тоже

2024-02-13 22:15 UTC, DPeshkoff commented on source/sort.js
> +  let rightArr = [];
А не const? Теоретический вопрос: а чем отличается let от const (и от var)?

2024-02-13 22:15 UTC, DPeshkoff commented on tests/sort.js
> +	});
Предлагаю попробовать закинуть в функцию всякие NaN, undefined, null и прочие радости жизни - интересно же, что получится)

2024-02-14 14:09 UTC, novakf commented on source/sort.js
> +  let rightArr = [];
Точно, здесь const, поскольку я меняю лишь элементы внутри массива, а не присваиваю новое значение переменной.

```const``` в отличие от ```let``` задает переменную, значение которой нельзя поменять, однако свойства объекта или элементы массива, заданного константой от изменений не защищены.

- Переменная, созданная через ```var``` видна внутри всей функции, а ```let``` - только внутри блока {}, в котором объявлена;
- Переменная ```var``` до объявления равна ```undefined```, а обращаясь к ```let``` переменной до объявления получим ошибку;
- Также при использовании ```let``` в цикле ```for (let ...)``` для каждой итерации создается отдельная переменная, а при объявлении через ```var``` переменная - одна на весь цикл.

2024-02-14 14:10 UTC, novakf commented on tests/sort.js
> +	});
Сделал проверку и добавил тесты

2024-02-14 14:10 UTC, novakf commented on source/sort.js
> +    if (ruComparator(val, pivot) === -1) leftArr.push(val);
Исправил

2024-02-14 21:27 UTC, DPeshkoff approved these changes

2024-02-14 21:28 UTC, closed without merging