Валова София
frontend-park-mail-ru/homework_2024_1 pull request #16
Opened 2024-02-11 19:11 UTC by ssofiica

2024-02-11 19:16 UTC, Glibusss commented
Привет! Меня зовут Глеб и я буду ревьюить твоё ДЗ0. Сейчас я проверю код и в случае чего внесу правки. По любым вопросам можешь обращаться в:
[VK](https://vk.com/glibu_s)
TG: @glmakko

2024-02-11 19:24 UTC, Glibusss requested changes

2024-02-11 19:24 UTC, Glibusss commented on source/minmax.js
> +'use strict';
Что делает эта директива?

2024-02-11 19:24 UTC, Glibusss commented on source/minmax.js
> +const minmax = str => {
Тут ты использовала arrow function. Какие ещё способы объявления функций ты знаешь? В чём их особенности? Когда и какие лучше применять?
P.S. Лучше str обернуть в скобки(это минорное замечание)

2024-02-11 19:24 UTC, Glibusss commented on source/minmax.js
> +    if (numbers.length == 0) {
Точно нужна нестрогая проверка? [Почитай тут](https://learn.javascript.ru/comparison)

2024-02-11 19:24 UTC, Glibusss commented on source/minmax.js
> +    let numbers = str.split(' ').map(Number).filter(element => !isNaN(element));
А почему let? Ты же не собираешься переприсваивать

2024-02-11 19:24 UTC, Glibusss commented on source/minmax.js
> +    if (str === '') {
А если я на вход передам Null, Object, undefined

2024-02-11 19:24 UTC, Glibusss commented on tests/minmax.js
>  		assert.deepEqual(minmax('0'), [ 0, 0 ]);
Допиши ещё тесты. Выше написал

2024-02-11 19:24 UTC, Glibusss commented on source/minmax.js
> +const minmax = str => {
Необходимо написать JSDoc

2024-02-12 04:46 UTC, ssofiica commented on source/minmax.js
> +'use strict';
Директива применят правила, которые ограничивают использование конструкций, ведущих к ошибкам, которые в обычном режиме игнорировались бы, пример ошибок: использование объявления переменных без ключевых слов, наличие одинаковых имен у аргументов функции и другие.

2024-02-12 04:48 UTC, Glibusss commented on source/minmax.js
> +'use strict';
Факты

2024-02-12 05:11 UTC, ssofiica commented on source/minmax.js
> +const minmax = str => {
Обычная функция во всех языках - ```function func(a, b) { //код } ``` - называется function declaration, может быть вызвана до момента ее объявления.
Функциональное выражение (function expression) - ``` let a = function () { //код }``` - можно вызвать только после объявления.
Function deckaration лучше создавать, когда нужна функция доступная во всем коде; function expression, когда нужно присвоить функцию переменной или использовать её как значение

2024-02-12 05:13 UTC, ssofiica commented on source/minmax.js
> +    let numbers = str.split(' ').map(Number).filter(element => !isNaN(element));
Забыла поменять на const, так как до этого пыталась другим способом решить, исправлю

2024-02-12 05:17 UTC, Glibusss commented on source/minmax.js
> +const minmax = str => {
А что можешь рассказать про контекст выполнения у разных видов объявления функций?

2024-02-12 05:25 UTC, ssofiica commented on source/minmax.js
> +    if (numbers.length == 0) {
numbers.length вернет число и 0 число, так что ошибки не должно быть. Или вы хотите сказать, что так как == приводит типы, а у меня элементы одного типа, то надо использовать ===?

2024-02-12 05:26 UTC, Glibusss commented on source/minmax.js
> +    if (numbers.length == 0) {
Да, это будет семантически правильно

2024-02-12 05:26 UTC, Glibusss commented on source/minmax.js
> +    if (numbers.length == 0) {
Используй ===

2024-02-12 06:47 UTC, ssofiica commented on source/minmax.js
> +const minmax = str => {
function declaration - глобальна в рамках текущего окружения, имеет доступ к глобальным переменным и функциям этого окружения 
function expression - имеет свой контекст, который включает в себя переменные, параметры и доступ к this
arrow function - нет своего контекста, использует контекст окружения, в котором определена

2024-02-12 06:47 UTC, ssofiica commented on source/minmax.js
> +    if (str === '') {
Исправила

2024-02-12 06:47 UTC, ssofiica commented on tests/minmax.js
>  		assert.deepEqual(minmax('0'), [ 0, 0 ]);
Дописала

2024-02-12 06:47 UTC, ssofiica commented on source/minmax.js
> +const minmax = str => {
Добавила

2024-02-12 06:50 UTC, Glibusss commented on source/minmax.js
> +    if (str === '') {
Вот с этим мы сейчас ещё немного поработаем

2024-02-12 06:56 UTC, Glibusss commented on source/minmax.js
> +    if (typeof(str) === 'string') {
Уже очень хорошо. Осталось немного
1)Чтобы избавиться от лишней вложенности можно инвертировать условие и вернуть undefined
2)Напиши тест, где передается объект String. Это валидные входные данные, но код упадет

2024-02-12 06:57 UTC, Glibusss commented on source/minmax.js
> +
Вот тут не надо отступ

2024-02-12 06:58 UTC, Glibusss commented on tests/minmax.js
> +	});
Пустую строчку в конце файла

2024-02-12 06:59 UTC, Glibusss commented on source/minmax.js
>  }
Пустую строчку в конце файла

2024-02-12 07:57 UTC, Glibusss commented on tests/minmax.js
> +		assert.deepEqual(minmax("string"), [ undefined, undefined]);
Я имел ввиду передай на вход new String().

2024-02-12 07:58 UTC, Glibusss commented on source/minmax.js
> +
Не забудь убрать

2024-02-12 07:59 UTC, Glibusss commented
Осталось совсем немного!

2024-02-12 08:10 UTC, Glibusss commented on tests/minmax.js
> +		var str = new String('asx');
Давай сделаем тест кейс с объектом String, в конструктор которого передается валидная строка. Например ‘1 2 3’

2024-02-12 08:11 UTC, Glibusss commented on tests/minmax.js
> +		var str = new String('asx');
Такой ввод валиден, но код отработает неправильно

2024-02-12 08:12 UTC, ssofiica commented on source/minmax.js
> +
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/91909561/b90566d3-5f28-4b0d-892a-d70cc2d9a2a5)
надо прям так или между * и текстом вставить пробел? или отступ это про пустую 9 строку?

2024-02-12 08:14 UTC, Glibusss commented on source/minmax.js
> +
Про 9 строку

2024-02-12 08:23 UTC, ssofiica commented on tests/minmax.js
> +		var str = new String('asx');
То есть надо исправить код, чтоб он принимал объект String?

2024-02-12 08:28 UTC, Glibusss commented on tests/minmax.js
> +		var str = new String('asx');
Да, нужно предусмотреть этот случай

2024-02-12 08:33 UTC, ssofiica commented
Убрала отступ на 9 строке, сделала проверку на объект String

2024-02-12 08:36 UTC, Glibusss commented
Молодец! Ставлю апрув

2024-02-12 08:36 UTC, ssofiica commented
Спасибо!

2024-02-12 14:34 UTC, Glibusss approved these changes

2024-02-13 22:12 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 22:12 UTC, DPeshkoff commented on source/minmax.js
> +    console.log(typeof(str))
Ой-ой-ой! Не очень хорошо оставлять логи тут)

2024-02-13 22:12 UTC, DPeshkoff commented on source/minmax.js
> +    if (str === '') {
Предлагаю [упростить](https://developer.mozilla.org/ru/docs/Glossary/Falsy)

2024-02-13 22:12 UTC, DPeshkoff commented on source/minmax.js
> +    const numbers = str.split(' ').map(Number).filter(element => !isNaN(element));
Чем `isNaN` отличается от `Number.isNaN`?

2024-02-13 22:12 UTC, DPeshkoff commented on tests/minmax.js
> +		var nullParametr = null;
Ой! А чем var отличаются от let и const? Что тут лучше использовать?

2024-02-13 22:12 UTC, DPeshkoff commented on tests/minmax.js
> +		var NaNParametr = Number('asx'); //NaN
[NaN можно получить и проще](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/NaN#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0_%D0%BD%D0%B0_%D1%80%D0%B0%D0%B2%D0%B5%D0%BD%D1%81%D1%82%D0%B2%D0%BE_nan)

2024-02-14 19:58 UTC, ssofiica commented on source/minmax.js
> +    console.log(typeof(str))
Исправила

2024-02-14 19:58 UTC, ssofiica commented on source/minmax.js
> +    if (str === '') {
Исправила

2024-02-14 19:59 UTC, ssofiica commented on source/minmax.js
> +    const numbers = str.split(' ').map(Number).filter(element => !isNaN(element));
isNaN - преобразует аргумент в число и проверяет, является ли результат NaN, Number.isNaN не преобразовывает, а строго проверяет является ли число NaN или нет. Тогда в моем случае, лучше использовать  Number.isNaN, так как в массиве будут только Number и NaN элементы после преобразования c помощью map и опять делать приведение (которое делает isNaN) нет смысла

2024-02-14 19:59 UTC, ssofiica commented on tests/minmax.js
> +		var nullParametr = null;
К переменным, объявленным с помощью var, можно обращаться до момента объявления, также если они объявлены вне функции, то становятся глобальными объектами. let и const доступны только в блоке кода, где они объявлены. Так как переменные в тесте необходимы только в данной функции теста и дальше по коду не нуждаются переопределении, то лучше использовать const. Так как первый параметр без значения, то для него использовать надо let, так константной переменной должно быть присвоено значение

2024-02-14 19:59 UTC, ssofiica commented on tests/minmax.js
> +		var NaNParametr = Number('asx'); //NaN
Исправила

2024-02-15 22:40 UTC, DPeshkoff requested changes

2024-02-15 22:40 UTC, DPeshkoff commented on tests/minmax.js
> +		const nullParametr = null;
Можно прямо на 43-46 строки вставить

2024-02-16 07:33 UTC, ssofiica commented on tests/minmax.js
> +		const nullParametr = null;
Исправила

2024-02-17 09:27 UTC, DPeshkoff approved these changes

2024-02-17 09:28 UTC, closed without merging