Плёнкин Никита
frontend-park-mail-ru/homework_2024_1 pull request #17
Opened 2024-02-11 19:32 UTC by kond9

2024-02-11 20:30 UTC, VladislavKirpichov reviewed
Привет! Я буду ревьером твоего дз0, если будут вопросы, пиши @vladislavkirpichov в телеграме, помогу)

2024-02-11 20:30 UTC, VladislavKirpichov commented on index.html
> +    <script src="https://code.jquery.com/qunit/qunit-2.4.0.js"></script>
Лишнее изменение отступов

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +'use strict';
Можешь рассказать, зачем нужна эта строчка? На что она влияет?

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +        groupsOfWords[wordAfterSortChars].push(word);
Это все можно записать одной строчкой, подумай как

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +const anagram = function (words) {
Неожиданный синтаксис) Расскажи, что такое function declaration и function expression? В чем отличие? Почему тут решил писать именно так? Что такое hoisting?
Давай поменяем тут на стрелочную функцию

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +    filteredGroups.sort((a, b) => a[0].localeCompare(b[0]));
Отлично что знаешь методы объектов и массивов. Расскажи, какие типы ты знаешь в js? Что такое примитивные типы? Каким примитивным типов является массив?
Что такое прототипное наследование? Что выведет и как работает такая запись: `[1, 2, 3].toString()`

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +}
Добавь пустую строку в конец файла и расскажи, зачем она нужна

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +    });
Здесь ты накапливаешь элементы в один объект. Для такого существует специальный метод у массивов, найди какой и используй его

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +    filteredGroups.sort((a, b) => a[0].localeCompare(b[0]));
Какие аргументы еще принимает localCompare? Почему решил не использовать операторы сравнения?

2024-02-11 20:30 UTC, VladislavKirpichov commented on tests/anagram.js
> +        ];
Какая-то беда с форматированием. Поправь этот дифф, такого не должно быть, и советую настроить ide чтобы за тебя правильно все форматировала

2024-02-11 20:30 UTC, VladislavKirpichov commented on tests/anagram.js
> +});
Нет пустой строки

2024-02-11 20:30 UTC, VladislavKirpichov commented on tests/anagram.js
> +            '        ] anagram []');
Строкам совсем плохо) Убери эти пробелы, воспользуйся форматной строчкой \`\`

2024-02-11 20:30 UTC, VladislavKirpichov commented on tests/anagram.js
> +        const output = [];
Можно не заводить эти константы, а прямо в тесте передавать массивы как аргументы

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +    filteredGroups.forEach(group => group.sort());
Зачем эта строчка? Ничего полезного не делает

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +const anagram = function (words) {
Напиши комментарий в формате JSdoc

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +        const wordAfterSortChars = word.split('').sort().join('');
Почему везде используешь const? Какие еще знаешь способы объявления переменных? Какая между ними разница?

2024-02-11 20:30 UTC, VladislavKirpichov commented on source/anagram.js
> +const anagram = function (words) {
Что будет, если в `words` придет какое-то значение с другим типов(number, object, etc)? Добавь проверки таких кейсов, и не забудь написать тесты

2024-02-11 20:30 UTC, VladislavKirpichov commented on tests/anagram.js
> +    QUnit.test('Функция работает правильно, когда нет анаграмм', function (assert) {
Добавь строчку между }) и QUnit.

2024-02-11 20:30 UTC, VladislavKirpichov commented on tests/anagram.js
> +});
Не хватает тестов, особенно негативных. Что будет если встретятся не валидные данные? Что если в функцию придет null? Для таких кейсов нужны тесты

2024-02-11 21:56 UTC, kond9 commented on source/anagram.js
> +'use strict';
В этой строчке подключается так называемый "строгий режим", при котором явно подключаются современный решения, позволяющие совершать меньше ошибок и работать в безопасном режиме.

2024-02-12 15:08 UTC, VladislavKirpichov commented on source/anagram.js
> +'use strict';
Очень абстрактно написал) Можешь подробнее рассказать, что запрещается делать в строгом режиме? Советую прочитать сначала: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

2024-02-19 17:48 UTC, kond9 commented on source/anagram.js
> +'use strict';
Эту директиву следует размещать в первой строке скрипта или в начале тела функции.

Без "use strict" код также запустится, но некоторые возможности будут работать в «режиме совместимости» со старыми версиями языка JavaScript. Нам же предпочтительнее современное поведение.

Некоторые конструкции языка (например, классы, которые нам ещё предстоит изучить) включают строгий режим по умолчанию.

    Устраняет некоторые молчаливые ошибки JavaScript, заменяя их на выдачу ошибок.
    Исправляет ошибки, которые затрудняют оптимизацию механизмов JavaScript: иногда код строгого режима может работать быстрее, чем идентичный код, не поддерживающий строгий режим.
    Запрещает некоторый синтаксис, который может быть определен в будущих версиях ECMAScript.

2024-02-19 18:05 UTC, kond9 commented on source/anagram.js
> +const anagram = function (words) {
Если функция объявлена в привычном нам стиле function *название*(*аргументы*){}, то это function declaration. Если функция была создана как часть выражения, то это function expression (то есть как у меня в коде). 
Отличие в том, что при function expression функция создаётся только в тот момент, когда поток дойдёт до неё. В случае function declaration мы можем использовать её до создания. Это поведение в JS, которое помогает переменным или же, в нашем случае, функциям "перенестись" в начало кода чтобы она была видна во всём скрипте, по сути и называется hoisting'ом. 
Я написал именно так, потому что решил попробовать новый вид создания функции и потом уже просто не переделывал в function declaration.

2024-02-19 18:38 UTC, kond9 commented on source/anagram.js
> +}
В первую очередь, я подумал о читаемости кода и общепринятого стиля. Почитав в интернете, понял, что некоторые утилиты могут неправильно обрабатывать такие моменты, например, не считая строкой последнюю "строку с кодом"

2024-02-19 18:55 UTC, kond9 commented on source/anagram.js
> +    filteredGroups.sort((a, b) => a[0].localeCompare(b[0]));
Примитивные типы данных (их значениями могут быть только простые значения): number, bigint, string, boolean, null, undefined, symbol. Не примитивный (коллекции данных или сложные структуры): object.  

Массив может содержать любые типы данных, включая другие объекты и функции.  

Прототипное наследование - механизм, с помощью которого реализуется создание объекта на основе другого объекта. Например, объект "кошка" на основе "животное". Мы не копируем все функции и свойства, а наследуем от "животного". Например, функция "дышать", "передвигаться". У "кошки мы можем "передвигаться" сделать "красться", "бегать", "прыгать". Или если у нас есть функция, которую не надо менять в наследнике, то она будет искаться в "прототипе".

[1, 2, 3].toString() должна вывести "1,2,3". Функция применяется к каждому элементу массива, преобразуя в строку, затем соединяет их в одну строку, разделяя запятыми.

2024-02-19 19:37 UTC, kond9 commented on source/anagram.js
> +    filteredGroups.sort((a, b) => a[0].localeCompare(b[0]));
Вообще, решил использовать как раз из документации https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare. Обязательным параметром является строка, с которой исходная сравнивается. Необязательные: языковой тег locales и иные настройки options

2024-02-19 19:42 UTC, kond9 commented on source/anagram.js
> +    filteredGroups.forEach(group => group.sort());
Почему же не даёт? Используя пример, который изначально был в ветке, я понял, что слова внутри должны быть отсортированы ещё и по алфавиту внутри каждой группы. 
Ожидается   "пост", "стоп"
Выводится   "стоп", "пост"

2024-02-19 19:49 UTC, kond9 commented on source/anagram.js
> +        const wordAfterSortChars = word.split('').sort().join('');
Исправил этот момент.. Почему-то казалось, что разницы особой не будет в моём коде. 
let - современный способ объявления переменной, у которой можно изменять значение
const - способ объявления переменной, у которой нельзя изменять значение

var - устаревший способ объявления переменной (из отличий: например, с ним можно объявлять переменную несколько раз)

2024-02-21 10:32 UTC, VladislavKirpichov commented on source/anagram.js
> +        const wordAfterSortChars = word.split('').sort().join('');
Я был не против `const`, их надо наоборот, часто использовать)

2024-02-21 10:35 UTC, VladislavKirpichov commented on source/anagram.js
> +        const wordAfterSortChars = word.split('').sort().join('');
Советую прочитать про области видимости переменных: https://learn.javascript.ru/closure. Как себя ведут var, let, const при объявлении? Как работают внутри блоков:
```
let test = 1;
{
let test = 2;
}
console.log(test);
```?

2024-02-21 10:47 UTC, kond9 commented on source/anagram.js
> +        const wordAfterSortChars = word.split('').sort().join('');
Я читал про разницу как раз в этой статье)  let и const ведут себя одинаково при объявлении, в блоках кода. Если переменная объявлена до блока кода {}, как в примере, то в самом блоке это будет другая переменная(локальная), которая видна в рамках этого блока. Иная ситуация с var: он виден вне этого блока и может использоваться, например, после цикла for, после if, да и просто скобок {}. Также var можно объявлять больше 1 раза и ошибки не будет, будет изменение на последнее значение. С let и const так нельзя.   В примере let test = 2 не будет виден для console.log(), соответственно будет вывод 2

2024-02-21 11:00 UTC, kond9 commented on tests/max.js
Я настроил ide на нужное форматирование и решил сделать код приятнее во всех файлах, в том числе и этот

2024-02-21 11:12 UTC, kond9 commented on source/anagram.js
> +    accumulator[wordSorted] = (accumulator[wordSorted] || []).concat(word);
arr1.push(...arr2); (добавить в конец)
arr1.unshift(...arr2); (добавить в начало)
arr1.splice(start, deleteCount, ...arr2); (универсальный метод, который начиная c start удаляет deleteCount и добавляет ...arr2) 

...arr2 - это "распакование" массива, чтобы достать каждый элемент

2024-02-21 15:21 UTC, VladislavKirpichov commented on source/anagram.js
> +        const wordAfterSortChars = word.split('').sort().join('');
Вот неплохая статья про hoisting, советую прочитать:  https://dmitripavlutin.com/variables-lifecycle-and-why-let-is-not-hoisted/

2024-02-21 15:21 UTC, VladislavKirpichov commented on source/anagram.js
> +    accumulator[wordSorted] = (accumulator[wordSorted] || []).concat(word);
Почти то что я хотел увидеть) Еще можно [...arr2], давай тут переделаем на этот синтаксис

2024-02-22 19:46 UTC, VladislavKirpichov commented on source/anagram.js
> +const anagram = (words) => {
Последняя правка: что будет, если в массив придет не string[], а массив рандомных типов([undefined, 1, "Hello world", ...])? Напиши на это тест и проверь работу программы

2024-02-22 20:35 UTC, DPeshkoff requested changes
Привет! Хорошее решение, но нужна парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-22 20:35 UTC, DPeshkoff commented on index.html
> +    <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.0.css">
Здесь не должно быть разницы

2024-02-22 20:35 UTC, DPeshkoff commented on source/anagram.js
> +    if (typeof word !== 'string') {
<img width="351" alt="307051794-ddec583f-779e-4a3f-a342-e8e83dba96a6" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/1fb174af-8a4f-4f90-a2a6-6b439414e87d">

Такая строка сломает(

2024-02-22 20:35 UTC, DPeshkoff commented on source/anagram.js
> +    throw new Error("Input should be an array!!!")
Не теряй ;, это важно и может привести к сломанному коду.

Еще приняты одиночные кавычки

И вместо такой ошибки лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-22 20:35 UTC, DPeshkoff commented on tests/anagram.js
> +      'кот', 'пила', 'барокко',
Тут тоже

2024-02-22 20:35 UTC, DPeshkoff commented on tests/max.js
> +  });
А тем более тут

2024-02-24 19:22 UTC, DPeshkoff requested changes

2024-02-24 19:22 UTC, DPeshkoff commented on source/anagram.js
> +      console.log(e.stack); // Стек ошибок
Здесь не нужен try catch. Обработать надо в тестах

2024-02-25 14:08 UTC, DPeshkoff requested changes

2024-02-25 14:08 UTC, DPeshkoff commented on index.html
> +    	<script src="https://code.jquery.com/qunit/qunit-2.4.0.js"></script>
![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/407be1d5-0103-4509-9ea2-d7cc6b0654f4)

Все еще не убрал. Возьми изменения из оригинального файла

2024-02-25 14:08 UTC, DPeshkoff commented on tests/anagram.js
> +      'кот', 'пила', 'барокко',
![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/0d04fca7-0766-4139-87e6-303a9bae8a62)

На работе такие изменения у тебя тоже завернут - исходный код не нужно менять, если в этом нет необходимости. Даже отступы)

2024-02-26 10:01 UTC, DPeshkoff approved these changes

2024-02-26 10:01 UTC, closed without merging