Implemented function & Added tests.
frontend-park-mail-ru/homework_2024_1 pull request #18
Opened 2024-02-11 20:06 UTC by roflanpotsan

Долматов Фёдор WEB-21

2024-02-11 21:24 UTC, johnSamilin commented
Привет!
Меня зовут Саша, я проверю ПР в ближайшее время и оставлю комментарии, если это потребуется. Если возникнут вопросы ты всегда можешь написать мне в тг: @WatasheeBaka

2024-02-12 17:48 UTC, johnSamilin commented
Оформи пожалуйста название ПР по правилам: название должно быть "Фамилия Имя студента"

2024-02-12 17:57 UTC, johnSamilin requested changes

2024-02-12 17:57 UTC, johnSamilin commented on source/anagram.js
> +    return Object.values(words.sort().reduce((anagramDictionary, word) => {
расскажи пожалуйста, зачем ты сортируешь массив слов?

2024-02-12 17:57 UTC, johnSamilin commented on source/anagram.js
> +let anagram = words => {
почему эта переменная объявлена как let?

2024-02-12 17:57 UTC, johnSamilin commented on source/anagram.js
> +    return Object.values(words.sort().reduce((anagramDictionary, word) => {
можно ли обойтись без вызова этого метода?

2024-02-12 17:57 UTC, johnSamilin commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно без анаграм', function (assert) {
не хватает тестов на неправильные входные данные, например `anagram(2)`, `anagram([1, 'foo', null])`

2024-02-13 20:30 UTC, roflanpotsan commented on source/anagram.js
> +    return Object.values(words.sort().reduce((anagramDictionary, word) => {
Сортировал я так как по условию "слова в группах, как и сами группы, должны быть отсортированными". Я решил воспользоваться словарем, чтобы добавлять элементы в массивы лежащие по соответствующему ключу. Согласен, что при добавлении можно искать место для вставки в самих массивах, а не сортировать все элементы заранее, но я не придумал как решить проблему с сортировкой самих групп, так как словарь хранит ключи в порядке добавления. Я не нашел встроенную структуру данных, которая бы сама сортировала ключи, может я плохо искал... Если такая структура данных есть, то да, можно без сортировки обойтись. Еще можно просто отсортировать ключи после заполнения словаря, ключей будет < слов, если не учитывать ключи с одним словом внутри. Если это норм идея - реализую и спушу в ближайшее время.

2024-02-13 20:37 UTC, roflanpotsan commented on source/anagram.js
> +let anagram = words => {
Ошибся, раз уж внутри функция, то надо было объявлять как константу, меняться она не будет. Заменил на обычную декларацию через function.

2024-02-13 20:37 UTC, roflanpotsan commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно без анаграм', function (assert) {
Добавил тест.

2024-02-13 21:09 UTC, johnSamilin requested changes

2024-02-13 21:09 UTC, johnSamilin commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно без анаграм', function (assert) {
хорошо, только `let foo = ['мир', 'рим']; foo = undefined; anagram(foo)` все еще вызовет исключение. давай сделаем так, чтобы этого не происходило

2024-02-14 12:58 UTC, roflanpotsan commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно без анаграм', function (assert) {
Такой фикс корректен(оно работает, но вопрос костыль ли это)? words = words ?? []

2024-02-14 19:51 UTC, roflanpotsan commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно без анаграм', function (assert) {
Поменял решение выше на обертку в массив.

2024-02-15 06:54 UTC, johnSamilin requested changes

2024-02-15 06:54 UTC, johnSamilin commented on source/anagram.js
> +        words = [words];
сам подход вполне имеет место быть, но мутировать входные данные - плохо. в этом месте можно сразу сделать `return []`, потому что все последующие обработки не имеют смысла. или завести локальную переменную, сразу сказать, что это копия массива и работать уже с ней

2024-02-15 12:57 UTC, johnSamilin approved these changes

2024-02-15 22:53 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 22:53 UTC, DPeshkoff commented on source/anagram.js
> +'use strict';
А что делает эта строчка?

2024-02-15 22:53 UTC, DPeshkoff commented on source/anagram.js
> +function anagram (words) {
Предлагаю стрелочную все-таки вернуть)

Чем они отличаются от function?

2024-02-15 22:53 UTC, DPeshkoff commented on tests/anagram.js
> +	});
Давай добавим еще больше некорректных данных (массив объектов, например)

2024-02-15 22:53 UTC, DPeshkoff commented on tests/anagram.js
> +		let foo = ['мир', 'рим']; foo = undefined;
86 строчка: происходит непонятное!

2024-02-15 22:53 UTC, DPeshkoff commented on source/anagram.js
> +        if (typeof word !== 'string'){
<img width="360" alt="Снимок экрана 2024-02-16 в 01 53 04" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/9f51e132-3dc5-4264-95e6-67c5078f37b3">


Вроде тоже строка, а тут упадет

2024-02-15 22:53 UTC, DPeshkoff commented on source/anagram.js
> +function anagram (words) {
Еще давай добавим JSDOC

2024-02-17 16:01 UTC, roflanpotsan commented on source/anagram.js
> +'use strict';
Обрубает обратную совместимость со старым кодом взамен на более новые функции и устройство языка.
Например, при 'use strict' не получится присвоить что-либо необъявленной переменной.
`word = 'hehe'` - выдаст ошибку
`let word = 'hehe'` - ok
И там еще куча всего, чего я пока не знаю...

2024-02-17 16:01 UTC, roflanpotsan commented on source/anagram.js
> +function anagram (words) {
У них нет параметра arguments, они не наследуемы, не могут быть использованы в качестве конструктора (с оператором new), у них нет параметра this, он берется у ближайшего родителя.

2024-02-18 15:47 UTC, DPeshkoff requested changes

2024-02-18 15:47 UTC, DPeshkoff commented on source/out/anagram.js.html
Эти файлики не обязательно грузить.

Как и разбирали на первой лекции - всему, что можно сгенерировать автоматически, не место в репозитории)

2024-02-18 15:47 UTC, DPeshkoff commented on source/out/global.html
Поэтому предлагаю выпилить всю папку ./out

2024-02-18 16:21 UTC, roflanpotsan commented on source/out/anagram.js.html
Справедливо 0_0

2024-02-18 16:21 UTC, roflanpotsan commented on source/out/global.html
Сделано!

2024-02-19 11:39 UTC, closed without merging