Чугин Илья
frontend-park-mail-ru/homework_2024_1 pull request #19
Opened 2024-02-11 20:09 UTC by IlyaChgn

2024-02-11 21:22 UTC, johnSamilin commented
Привет!
Меня зовут Саша, я проверю ПР в ближайшее время и оставлю комментарии, если это потребуется. Если возникнут вопросы ты всегда можешь написать мне в тг: @WatasheeBaka

2024-02-12 17:35 UTC, johnSamilin commented
@IlyaChgn почему у тебя в ПР 2 коммита? там есть один лишний, который приносит ненужные изменения. проверь, правильно ли ты отвел ветку

2024-02-12 17:47 UTC, johnSamilin requested changes

2024-02-12 17:47 UTC, johnSamilin commented on source/sort.js
> +const sort = function (sentence) {
почему ты выбрал присваивание функции переменной, а не просто объявление функции?

2024-02-12 17:47 UTC, johnSamilin commented on source/sort.js
> +    sentence = sentence.toLowerCase()
изменять входные параметры неправильно, почти всегда это приводит к нежелательным последствиям. лучше объявить локальную переменную

2024-02-12 17:47 UTC, johnSamilin commented on source/sort.js
> +        splitedString = splitedString.sort((new Intl.Collator('ru')).compare);
давай сделаем так, чтобы сортировка происходила вне зависимости от языка. например, кто-то захочет отправить в эту функцию предложение "Напишите функцию sort, которая будет сортировать буквы"

2024-02-12 17:47 UTC, johnSamilin commented on source/sort.js
> +        splitedString = splitedString.sort((new Intl.Collator('ru')).compare);
но то, что ты знаешь про Intl, круто

2024-02-12 17:47 UTC, johnSamilin commented on source/sort.js
> +        words[i] = splitedString.join('');
методы в js можно вызывать по цепочке: `splittedString.sort(...).join('')`

2024-02-12 17:47 UTC, johnSamilin commented on tests/sort.js
>  		assert.strictEqual(sort('zzzzzz'), 'Zzzzzz', 'Работает с английским алфавитом');
а ты запускал тесты? в текущем виде они не пройдут

2024-02-12 17:47 UTC, johnSamilin commented on tests/sort.js
> +		//Исправил тест, поменяв латинскую букву А в слове Ан на русскую
это неправильно. уже написанные тесты менять не нужно

2024-02-13 11:00 UTC, IlyaChgn commented on source/sort.js
> +const sort = function (sentence) {
Присваивание функции переменной позволяет передать ее в другие функции, что необходимо для теста

2024-02-13 11:00 UTC, IlyaChgn commented on source/sort.js
> +    sentence = sentence.toLowerCase()
Исправил

2024-02-13 11:01 UTC, IlyaChgn commented on source/sort.js
> +        splitedString = splitedString.sort((new Intl.Collator('ru')).compare);
Я добавил тесты, которые показывают, что функция будет работать для предложений, где есть и русские, и английские слова

2024-02-13 11:01 UTC, IlyaChgn commented on source/sort.js
> +        words[i] = splitedString.join('');
Исправил

2024-02-13 11:04 UTC, IlyaChgn commented on tests/sort.js
>  		assert.strictEqual(sort('zzzzzz'), 'Zzzzzz', 'Работает с английским алфавитом');
У меня все тесты работают. Прикрепляю скриншот:
![p120DGY1kQ](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/149610530/28028d1b-2575-40a3-ade6-0fb7eadda3ce)

2024-02-13 11:07 UTC, IlyaChgn commented on tests/sort.js
> +		//Исправил тест, поменяв латинскую букву А в слове Ан на русскую
Написанные изначально тесты не удовлетворяют условию. Там написано: 'Функция делает первую букву слова прописной'.
При этом в качестве примера приводится тест:
`assert.strictEqual(sort('Rrrrrrrr'), 'rrrrrrrr');`.
Это напрямую противоречит тому, что написано выше. Поэтому я поменял тест.

2024-02-13 20:43 UTC, johnSamilin commented on tests/sort.js
> +		//Исправил тест, поменяв латинскую букву А в слове Ан на русскую
да, но во втором случае латинская A была добавлена намеренно

2024-02-13 21:01 UTC, johnSamilin commented on tests/sort.js
> +	});
еще нужно добавить тесты на неправильные входные данные

2024-02-13 21:02 UTC, johnSamilin commented on tests/sort.js
> +	QUnit.test('Дополнительный тест', function (assert) {
и еще, это неинформативное название. что именно тестирует этот тест?

2024-02-14 19:34 UTC, IlyaChgn commented on tests/sort.js
> +	});
Добавил еще 3 теста

2024-02-15 06:48 UTC, johnSamilin requested changes

2024-02-15 06:48 UTC, johnSamilin commented on tests/sort.js
> +	});
я имел в виду не просто добавить тесты, а еще и правильно обработать эти невалидные данные. как именно - решать тебе, бросая исключение, возвращая пустую строку, логом в консоль или что-то еще

2024-02-15 06:48 UTC, johnSamilin commented on source/sort.js
> +    for (let i = 0; i < words.length; ++i) {
а можно тут обойтись без цикла for?

2024-02-15 15:22 UTC, IlyaChgn commented on source/sort.js
> +    for (let i = 0; i < words.length; ++i) {
Добавил проверку на валидность введенных данных

2024-02-15 15:23 UTC, IlyaChgn commented on source/sort.js
> +    for (let i = 0; i < words.length; ++i) {
Без цикла for можно обойтись, если заменить его на forEach

2024-02-18 15:48 UTC, DPeshkoff requested changes

2024-02-18 15:48 UTC, DPeshkoff commented on README.md
> +В этом репозитории содержится условие варианта №8. Чтобы начать с ним работать, тебе необходимо склонировать репозиторий к себе на компьютер и перейти в ветку твоего варианта.
здесь непонятный дифф
давай переделаем так, чтобы этого не было (надо настроить грамотно ветки)

2024-02-19 17:44 UTC, IlyaChgn commented on README.md
> +В этом репозитории содержится условие варианта №8. Чтобы начать с ним работать, тебе необходимо склонировать репозиторий к себе на компьютер и перейти в ветку твоего варианта.
Вроде пофиксил

2024-02-20 19:54 UTC, closed without merging