Solution Naumov I.
frontend-park-mail-ru/homework_2024_1 pull request #2
Opened 2024-02-09 17:01 UTC by IvanNaum

2024-02-10 07:19 UTC, mafin1799 commented on index.html
**Общее замечание**
Некорректное название ПРа. Оно должно быть «Фамилия Имя студента».

2024-02-10 08:00 UTC, mafin1799 reviewed
Привет! Проделана большая работа 👍
Замечания в комментариях
Удачных правок!

2024-02-10 09:58 UTC, IvanNaum commented on source/chess.js
> +const chess = (n) => {
Разница в основном только в синтаксисе, отличия выглядят как костыли) нет arguments, нельзя new

2024-02-10 10:07 UTC, mafin1799 commented on source/chess.js
> +const chess = (n) => {
Тут можно посмотреть теорию по функциям в js
https://learn.javascript.ru/function-basics
Есть еще отличия, которые ты не перечислил)

2024-02-10 15:59 UTC, mafin1799 commented on source/chess.js
> +};
Не заметил. Прошу прощения

2024-02-10 16:15 UTC, mafin1799 commented on source/chess.js
> +  for (let i = 0; i < n; i++) {
или через методы строк
Вот еще ссылка
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

2024-02-10 20:45 UTC, IvanNaum commented on source/chess.js
> +  for (let i = 0; i < n; i++) {
fixed

2024-02-10 20:49 UTC, IvanNaum commented on source/chess.js
> +  if (n <= 1) {
Переписал на 
```
if (boardSize && boardSize <= 1) return null;
```

2024-02-10 21:02 UTC, IvanNaum commented on source/chess.js
> +"use strict";
Строгий режим - переключает в "новый" режим язык. Задает новую семантику, например, ошибки приводят к остановке программы, возникают ошибки некорректного синтаксиса, применяются оптимизации. 
Можно использовать для скрипту или конкретной функции. 
Использование его стоит для предотвращения ошибок и повышения безопасности, но это не является обязательным. Однако стоит помнить, что не все [браузеры](https://caniuse.com/use-strict) поддерживают его.

2024-02-10 21:05 UTC, IvanNaum commented on source/chess.js
> +const chess = (n) => {
```У стрелочных функций нет «this»``` - тоже важное отличие

2024-02-11 06:33 UTC, mafin1799 commented on source/chess.js
> +const chess = (n) => {
Да, у стрелочных функций нет собственного this и они будут ссылаться на верхний уровень.
Еще отличием от function declaration, может быть то, что её можно вызвать до объявления, так как она создается до выполнения первой строки кода

2024-02-11 06:35 UTC, mafin1799 commented on source/chess.js
> +  if (n <= 1) {
Тут можно сделать явную проверку на то, что у тебя могут быть только числа. через typeof, instanceof, тут немного дописать и твой код будет реагировать только на числа.

2024-02-11 06:36 UTC, mafin1799 commented on source/chess.js
> +"use strict";
Да это верно.
Есть еще ситуации когда оно может работать по умолчанию и в явном виде прописывать не нужно

2024-02-11 06:39 UTC, mafin1799 commented on source/chess.js
> +  for (let i = 0; i < n; i++) {
Хорошо. Это уже похоже на javascript.
Бывают ситуации, когда без цикла for в си-стайле не обойтись, но не не всегда))

2024-02-11 06:47 UTC, mafin1799 commented on source/chess.js
> +  if (n <= 1) {
https://learn.javascript.ru/types вот статья по typeof

https://learn.javascript.ru/instanceof#ref-instanceof статья по instanceof. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number а это статья про то, как еще можно создать число и как с ним работать

2024-02-11 06:55 UTC, mafin1799 commented on index.html
>  <script src="tests/chess.js"></script>
Еще нужно дописать свои тест кейсы, нужно проверить на все типы данных и убедиться что функция ведет себя корректно. 
Вот статья по типам https://learn.javascript.ru/types
Тесты можно писать по аналогии с существующими.

2024-02-11 06:59 UTC, mafin1799 commented on source/chess.js
> +  if (n <= 1) {
И обрати внимание на тесты

`
assert.strictEqual(chess(1), null);
assert.strictEqual(chess('1'), null);
`
Со строкой можно работать, если она приводится к числу.

2024-02-11 07:28 UTC, IvanNaum commented on source/chess.js
> +"use strict";
В консоли браузера по умолчанию включен use strict

2024-02-11 07:35 UTC, IvanNaum commented on source/chess.js
> +  if (n <= 1) {
А почему нельзя использовать parseInt()?

2024-02-11 07:49 UTC, mafin1799 commented on source/chess.js
> +"use strict";
Да верно. Еще при работе с классами и модулями es6, когда используются import, export

2024-02-11 08:18 UTC, mafin1799 commented on source/chess.js
> +  if (n <= 1) {
parseInt работает со строкой.
И берет оттуда число, как бы все корректно.
Но как берется число. До тех пор пока не появится ошибка чтения

![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/90977148/9ea53f99-820a-4996-b876-7084ee51835c)

Тесты дополнительные не забудь дописать.
Заодно проверь все ли ок если передаешь в функцию не число
chess(true)
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/90977148/926a9e6b-0da7-4a01-99b6-bf840be29d7d)

chess(object)
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/90977148/71766b3a-61a9-40f3-b23d-f4453164e200)

и тд...

А чтобы не проверять все типы
Можно попробовать привести параметр функции к типу Number
Проверить результат приведения и диапазон и дальше ты гарантированно работаешь с числом

2024-02-11 08:28 UTC, mafin1799 commented on source/chess.js
> +      if (idx % 2 === 0) {
Тут можно сделать лучше

Проверку на равенство нулю можно сократить

Вот примеры как можно сделать
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/90977148/32b621cf-6e04-4866-9fe5-d7ba16860861)

![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/90977148/58d61bb4-7a39-40e1-888c-42f538b851f9)

А вот статья где более подробно говорится об этом
https://learn.javascript.ru/ifelse

Выводы 0 эквивалентен false
Все остальное эквивалентно true

2024-02-11 08:33 UTC, mafin1799 commented on source/chess.js
> +const chess = (boardSize) => {
К самой функции также нужно добавить jsDoc
Пример 
`/**
 * Represents a book.
 * @constructor
 * @param {string} title - The title of the book.
 * @param {string} author - The author of the book.
 */
function Book(title, author) {
}`

2024-02-11 16:20 UTC, IvanNaum commented on source/chess.js
> +const chess = (boardSize) => {
fixed

2024-02-11 16:20 UTC, IvanNaum commented on source/chess.js
> +      if (idx % 2 === 0) {
fixed

2024-02-11 16:20 UTC, IvanNaum commented on index.html
>  <script src="tests/chess.js"></script>
fixed

2024-02-11 16:21 UTC, IvanNaum commented on source/chess.js
> +  if (n <= 1) {
fixed

2024-02-11 16:53 UTC, mafin1799 commented
Проделана большая работа, молодец.
Отправляю тебя в заботливые руки Димы Пешкова)

2024-02-12 15:05 UTC, DPeshkoff requested changes
Привет! Классное решение, еще парочка минорных правок)

Со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-12 15:05 UTC, DPeshkoff commented on source/chess.js
> +"use strict";
Предлагаю одинарные кавычки

2024-02-12 15:05 UTC, DPeshkoff commented on source/chess.js
> +  if (!boardSize) return null;
Гоу добавим {} и перенос для читаемости

2024-02-12 15:11 UTC, IvanNaum commented on source/chess.js
> +  if (!boardSize) return null;
fixed

2024-02-13 21:55 UTC, closed without merging