Батовкин Александр
frontend-park-mail-ru/homework_2024_1 pull request #20
Opened 2024-02-11 20:22 UTC by blackHATred

2024-02-11 20:47 UTC, VladislavKirpichov reviewed
Привет! Я буду ревьером твоего дз0, если будут вопросы, пиши @vladislavkirpichov в телеграме, помогу)

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +'use strict'; // typescript на минималках
Скорее уж JSdoc это ts на минималках) А что вообще делает 'use strict'? Почему надо его использовать?

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> + */
Отлично что написал jsdoc!

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +const letters = (text, flag) => {
Какие еще варианты объявления функций знаешь? Какие между ними отличия?

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +    const map = new Map();
Отлично что знаешь тип `Map`. Какая разница между `Set` и `Map`? Как они работают "под капотом"? Почему решил использовать `Map`, а не объект?

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +            map.set(letter, 1);
Вместо `for` лучше писать `forEach`, а вообще, ты здесь накапливаешь значение, для этого есть специальный метод у массивов, найди и используй его

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +            map.set(letter, map.get(letter)-1);
Аналогично комментарию выше

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +        if (map.get(letter) === 1 || map.get(letter) !== 0 && flag){
В чем разница между `===` и `==`? Как выполняется `||` и `&&` и что возвращает каждая из этих логических операций? Советую еще всегда писать скобки в таких проверках

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +            map.set(letter, 1);
Используй `{}` когда пишешь циклы и условия

2024-02-11 20:47 UTC, VladislavKirpichov commented on tests/letters.js
> +	});
Отлично что подобрал такие тест кейсы. Но не хватает негативных тестов, что будет, если придует `number` или объект в функцию? Напиши тесты на это и сделай проверку типов аргументов в функции, на твое усмотрение, как эту ошибку возвращать

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +    const map = new Map();
Какие еще знаеш способы объявления переменных кроме const? Как они работают и в чем их отличие?

2024-02-11 20:47 UTC, VladislavKirpichov commented on source/letters.js
> +    for (const letter of text)
`for` надо заменить на вызов функции у массива

2024-02-11 20:55 UTC, blackHATred commented on source/letters.js
> +'use strict'; // typescript на минималках
use strict включает строгий режим, т.е. начинают выбрасываться ошибки при использовании небезопасных конструкций. К примеру, с этой конструкцией не удастся использовать ключевые слова как названия переменных по типу let, package, private и т.д., ну и во многих других случаях для избегания неясностей этот режим будет выкидывать ошибки

2024-02-11 20:56 UTC, blackHATred commented on source/letters.js
> +const letters = (text, flag) => {
1) Декларативное, самое типичное, с помощью function ИмяФункции(параметры){ код функции }

2024-02-11 20:59 UTC, blackHATred commented on source/letters.js
> +const letters = (text, flag) => {
1) Декларативное, самое типичное, с помощью function ИмяФункции(параметры){ код функции }. В коде можно вызывать функцию до того, как она будет объявлена, такое явление называется hoisting
2) Функциональное, когда в переменную сохраняется функция: const f = function(){}
3) Стрелочная функция, как у меня в коде. Как и в cpp, с её помощью удобно записывать анонимные функции

2024-02-11 21:05 UTC, blackHATred commented on source/letters.js
> +    const map = new Map();
Set - множество, Map - словарь, оба работают на хэшах, но set хранит только значения, а map хранит пары ключ-значение. Использовал Map, потому что было привычнее его использовать после cpp, хотя object по идее тоже бы подошёл. Удобство map заключается в том, что он итерируется прямо, т.е. с соблюдением порядка вставки значений в него (в этом плане object скорее как unordered map), ну и в качестве ключей можно использовать далеко не только строки, что в рамках этой задачи, конечно, значения не имеет)

2024-02-11 21:09 UTC, blackHATred commented on source/letters.js
> +        if (map.get(letter) === 1 || map.get(letter) !== 0 && flag){
=== выполняет строгое сравнение, а == - нестрогое. К примеру, 0 == false, но 0 !== false. || и && выполняются в том же порядке, что и в других ЯП, согласно правилам информатики, т.е. сначала И, а потом ИЛИ. В следующем коммите добавлю скобочек, чтобы было легче воспринимать порядок выполнения условия

2024-02-11 21:10 UTC, blackHATred commented on tests/letters.js
> +	});
На такой случай я в JSDoc указал тип аргумента в виде string, чтобы снять с себя ответственность, если передадут не тот тип на вход) В следующем коммите добавлю обработку для этого

2024-02-11 21:12 UTC, blackHATred commented on source/letters.js
> +    const map = new Map();
Есть ещё let и var. Let объявляет переменную, которую можно изменять в рамках одного блока кода (т.е. в {} или во всём файле), а var задаёт глобальную переменную, но насколько я знаю, var лучше не юзать, т.к. это рудимент

2024-02-11 21:26 UTC, VladislavKirpichov commented on source/letters.js
> +'use strict'; // typescript на минималках
В общем верно, советую прочитать на mdn полную статью про strict: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

2024-02-11 21:30 UTC, VladislavKirpichov commented on source/letters.js
> +const letters = (text, flag) => {
Тут был скорее вопрос про function declaration vs function expression. В чем между ними разница? И к каким типам относится то, что ты описал в своих пунктах?

2024-02-11 21:30 UTC, blackHATred commented
Добавил .reduce(), изменил for на forEach и расставил дополнительные скобочки

2024-02-11 21:34 UTC, VladislavKirpichov commented on source/letters.js
> +    const map = new Map();
В объектах в качестве ключей можно использовать не только строки(перечили 3 типа которые могут быть ключами в объекте)

2024-02-11 21:37 UTC, VladislavKirpichov commented on source/letters.js
> +        if (map.get(letter) === 1 || map.get(letter) !== 0 && flag){
Тут есть особенность небольшая, проверь, что вернет `true && 'Hello world!'` и `'Hello world!' || false`, а также `1 || 2` и `2 || 1`. Вот тут https://javascript.info/logical-operators можешь прочитать подробнее

2024-02-11 21:38 UTC, blackHATred commented on source/letters.js
> +const letters = (text, flag) => {
function declaration - это объявление функций в основном коде, а function expression - объявление функции в рамках другого выражения. Иными словами, function declaration обрабатываются интерпретатором до запуска кода, а function expression во время работы кода. Поэтому пункт 1 в моём комменте выше это function declaration, остальное - function expression. А ещё function declaration позволяет использовать hoisting)

2024-02-11 21:39 UTC, VladislavKirpichov commented on source/letters.js
> +    const map = new Map();
Советую прочитать про области видимости переменных: https://learn.javascript.ru/closure

Объясни, почему будет разный вывод для этих функций:
```
    const test = () => {
        var i = 0;
        {
            var i = 1;
            {
                var i = 2;
                console.log(i)
            }
            console.log(i)
        }
        console.log(i)
    }

    const test = () => {
        let i = 0;
        {
            let i = 1;
            {
                let i = 2;
                console.log(i)
            }
            console.log(i)
        }
        console.log(i)
    }
```

2024-02-11 21:49 UTC, blackHATred commented on source/letters.js
> +        if (map.get(letter) === 1 || map.get(letter) !== 0 && flag){
В целом это логично, т.к. || и && представляют собой сокращённые варианты ИЛИ и И. Т.е. если в рамках конструкции ИЛИ первое выражение истинно, то нету смысла проверять следующее и аналогично с И - если первое выражение ложно, то точно так же нету смысла смотреть дальше. В некоторых ЯП для этого строго выделяют | и || или & и && по отдельности (в случае с | и & переменные проверяются параллельно-побитово, хотя в JS это работает иначе - только что проверил, 1 | 2 без оператора сравнения возвращает 3, но если добавить сравнение, то 1 | 2 === 1 вернёт true, в то же время 1 | 2 === 3 | 4 вернёт 5, а не true, и это забавно :) )

2024-02-11 21:54 UTC, blackHATred commented on source/letters.js
> +    const map = new Map();
Действительно. Где-то читал, что у объектов ключом могут быть только строки и символы, но оказывается, что числа тоже могут быть ключом. Хотя это логично, т.к. все они спокойно хэшируются)

2024-02-11 21:56 UTC, blackHATred commented on source/letters.js
> +    const map = new Map();
Во втором случае при выходе из блока {} все let удаляются, вот и выходит, что при "разворачивании" блоков получается 2 1 0. В первом случае при выходе за {} значения var не удаляются, поэтому последнее указанное значение i сохраняется и на выходе имеем 2 2 2

2024-02-11 22:36 UTC, blackHATred commented
И ещё добавил парочку тестов для проверки разных типов данных в аргументе функции

2024-02-12 10:51 UTC, VladislavKirpichov commented on source/letters.js
> +    const map = new Map();
Расскажи, что такое тип symbol и как он используется в js?

2024-02-12 10:51 UTC, VladislavKirpichov commented on source/letters.js
> +const letters = (text, flag) => {
Можешь рассказать, как ведет себя this в этих функциях? Посмотри, как отличается поведение стрелочных функций тут: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2024-02-12 10:58 UTC, VladislavKirpichov commented on source/letters.js
> +    return res;
Кажется что тут тоже можно использовать reduce

2024-02-12 10:58 UTC, VladislavKirpichov commented on source/letters.js
> +        throw new Error("Аргумент text обязательно должен быть типа string")
не забывай про `{}`, даже когда это одна строчка

2024-02-12 10:58 UTC, VladislavKirpichov commented on source/letters.js
> +        new Map()
Расскажи, как работает оператор `new` в js? Что знаешь про прототипы объектов, каким требованиям должна удовлетворять функция, с которой вызывается `new`?
Источники:
https://learn.javascript.ru/constructor-new
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/new

2024-02-12 10:58 UTC, VladislavKirpichov commented on tests/letters.js
> +	QUnit.test('Передаём неверные типы и намеренно вызываем ошибку', function (assert) {
Давай поменяем названия тестов. Обычно их пишут в формате "что функция должна сделать", например, should throw some error then accepts wrong type, что-то такое(язык на твое усмотрение)

2024-02-12 10:58 UTC, VladislavKirpichov commented on source/letters.js
> +        if (map.get(letter) === 1 || map.get(letter) !== 0 && flag){
js)

2024-02-12 11:49 UTC, blackHATred commented on source/letters.js
> +const letters = (text, flag) => {
this в отличие от других ЯП не является фиксированным и принимает своё значение во время исполнения. Например, this внутри функции будет ссылаться на объект, внутри которого реализован метод с этой функцией. Если же функция не является методом объекта, то вернётся undefined. В стрелочной функции this будет брать своё значение из внешней функции (если только та не будет снова стрелочной - тогда надо смотреть ещё на уровень выше)

2024-02-12 11:56 UTC, blackHATred commented on source/letters.js
> +    const map = new Map();
Symbol - это такой тип данных, у которого при создании значения будут уникальными, даже если они будут иметь общее описание, т.е. Symbol("id") !== Symbol("id"). Его можно использовать как ключ у объекта, при этом свойство объекта будет скрыто. К примеру, такое свойство нельзя будет получить через for..in

2024-02-12 12:37 UTC, blackHATred commented on source/letters.js
> +        new Map()
New позволяет создавать однотипные объекты с помощью функции-конструктора. Работает это таким образом: js создаёт пустой объект, привязывает его к прототипу конструктора (прототип - это объект, который содержит свойства и методы, доступные экземплярам объектов, созданным с использованием данного конструктора), конструктор запускается с привязкой этого нового объекта к this, затем оператор new возвращает только что созданный объект (или же если конструктор явно делает return объекта, то возвращается именно он). Функция должна удовлетворять следующим требованиям: 1) она имеет прототип; 2) функция должна быть выполнена с контекстом this, который ссылается на новый объект; 3) функция должна быть вызываемой. Ну и необязательное правило, которое является хорошим тоном - функция должна начинаться с заглавной буквы )

2024-02-12 12:38 UTC, blackHATred commented
Поправил описание теста, заменил forEach на reduce

2024-02-12 15:12 UTC, VladislavKirpichov commented on source/letters.js
> +const letters = (text, flag) => {
Да, а когда может так случиться, что this будет == undefined? Как можно это пофиксить? Вот тут можно подробнее прочитать:
https://learn.javascript.ru/bind
https://learn.javascript.ru/call-apply-decorators

2024-02-12 15:16 UTC, VladislavKirpichov commented on source/letters.js
> +            return res;
else if по сути тут "лишний", ты же делаешь early return. early return считается хорошей практикой, часто ограничивают кол-во `else if` так как это понижает читаемость. Давай тут заменим else if на просто if

2024-02-12 15:16 UTC, VladislavKirpichov commented on source/letters.js
> +    return Array.from(text).reduce(
Как еще можно строчку "превратить" в массив?

2024-02-12 15:18 UTC, VladislavKirpichov commented on source/letters.js
> +        new Map()
Давай еще разобьем на пару функций, первая будет проводить частотный анализ, вторая - повторно обходить строку. Не забудь написать JSdoc

2024-02-12 16:22 UTC, blackHATred commented
Разделил код на несколько функций, к каждой добавил JSDoc. Постарался сделать их более универсальными, чтобы они работали с любыми массивами, а не только строками

2024-02-12 16:24 UTC, blackHATred commented on source/letters.js
> +    return Array.from(text).reduce(
Из питона вспоминается способ со сплитом) Т.е. "hello vk education".split("")

2024-02-12 16:33 UTC, blackHATred commented on source/letters.js
> +const letters = (text, flag) => {
Если передать функцию отдельно без контекста, то this может "потеряться" и стать undefined, например в setTimeout. Как вариант - использовать функции-обёртки, например setTimeout(() => {Объект.функция()}, 1000 ). Либо можно использовать bind, которая привязывает функцию к объекту

2024-02-12 16:54 UTC, VladislavKirpichov commented on source/letters.js
> +const letters = (text, flag) => {
Да, еще есть apply и call

2024-02-12 16:55 UTC, VladislavKirpichov commented on source/letters.js
> +    return Array.from(text).reduce(
верно, небольшой момент: в js чаще пишут ' вместо ", обычно линтер за тебя это сам правит, но все же)

2024-02-12 17:09 UTC, VladislavKirpichov commented on source/letters.js
> +    }
В дополнение к new, как работает instanceof? Что такое constructor и prototype? И вот тут ты проверяешь конкретно на массив, но итерироваться например можно не только по массивам. Что такое symbol.iterator и каким свойствам должны удовлетворять итерируемые объекты?
И давай вернем конкретно на массив строк. Меня например смущает кейс, в котором массив состоит из объектов. Объясни, как сравниваются объекты в js, почему, например`{} === {}` вернет false?
Делать функции слишком универсальными часто тоже не есть хорошо

2024-02-12 17:09 UTC, VladislavKirpichov commented on source/letters.js
> +    }
давай вместо instanceof будем по другому проверять) (подсказка: length и `?`)

2024-02-12 17:09 UTC, VladislavKirpichov commented on source/letters.js
> +};
Кажется тут можно обойтись одной строчкой)

2024-02-12 17:09 UTC, VladislavKirpichov commented on source/letters.js
> +}
Подумай как с помощью тернарного оператора можно вынести в "одну строку"

2024-02-12 17:54 UTC, blackHATred commented on source/letters.js
> +    }
instanceof позволяет проверить, принадлежит ли объект определенному классу

constructor - свойство объекта, которое ссылается на его функцию-конструктор, т.е. если function test() {}
let obj = new test(); то тогда obj.constructor === test

prototype - это свойство функции-конструктора, которое ссылается на прототип для новых экземпляров, которые будут создаваться этой функцией-конструктором. Из моего примера ранее можно сказать, что obj.__proto__ === test.prototype. К слову, instanceof как раз работает на основе сравнения прототипов. 

symbol.iterator - специальная штука, которая определяет, может ли объект итерироваться через forEach или for..of. При этом symbol.iterator должен возвращать специальный итератор, который содержит метод next(), который в свою очередь должен возвращать объект с полями value и done. 

{} !== {} потому что это разные объекты, которые будут размещаться в разных участках памяти, хоть и выглядят они схоже.

В следующем коммите уйду от использования Array и заточу функции только под string

2024-02-12 20:55 UTC, blackHATred commented
Захардкодил функции, чтобы они работали только со string, как следствие от instanceof тоже отказался. Добавил тернарники для примера, хотя имхо прошлый вариант был читабельнее. К слову, заметил, что если вместо Array.from использовать split(""), то не проходит тест на utf-8. С чем это может быть связано?

2024-02-12 20:56 UTC, blackHATred commented on source/letters.js
> +    }
Вернулся от Array к string, поэтому думаю, что легче так же проверять через typeof)

2024-02-13 23:04 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 23:04 UTC, DPeshkoff commented on source/letters.js
> +    })() :
<img width="346" alt="Снимок экрана 2024-02-14 в 02 01 19" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/f70138ef-66cf-4466-94fb-a771a9d27f10">

Вроде тоже строка, а не пройдет(

2024-02-13 23:04 UTC, DPeshkoff commented on source/letters.js
> +const strByFreq = (str, freq, flag) => typeof str !== "string" ?
Аналогично + дублирование получаем - может, вынесем во вспомогательную функцию?

2024-02-13 23:04 UTC, DPeshkoff commented on source/letters.js
> +        throw new Error("Функция работает только со строками")
Лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-13 23:04 UTC, DPeshkoff commented on source/letters.js
> +        throw new Error("Функция работает только со строками")
Строки принято оборачивать в одиночные кавычки - предлагаю везде поменять)

2024-02-13 23:04 UTC, DPeshkoff commented on tests/letters.js
> +		assert.throws(function() {
Новые строки тоже лучше добавить)

Кстати, а тут нельзя на стрелочную переписать?)

2024-02-13 23:35 UTC, blackHATred commented on source/letters.js
> +    })() :
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/43523398/309949d9-775e-45ee-a1f0-3e1406172020)

а такой вариант?

2024-02-13 23:37 UTC, blackHATred commented on source/letters.js
> +            if (flag === false) {
В первом условии можно, но flag === false заменить не выйдет, т.к. flag так же может быть undefined. Можно конечно отдельно проверить на undefined, но тогда условие станет ещё более громоздким и легче просто оставить flag === false

2024-02-13 23:48 UTC, blackHATred commented
В тестах все функции сделал стрелочными ;
Проверку аргумента на соответствие примитивной строке или строковому объекту вынес в отдельную функцию ;
Обновил jsdoc, чтобы ide перестал ругаться на то, что в некоторых тестах аргумент flag явно не передаётся) ;
Чуть урезал условие в strByFreq, но от flag === false избавиться не смог, т.к. flag так же может быть undefined и лучше делать точное сравнение ;
Добавил тест, который проверяет новую функцию на работу с new String().

2024-02-15 22:58 UTC, DPeshkoff requested changes

2024-02-15 22:58 UTC, DPeshkoff commented on source/letters.js
> +const checkStr = (str) => Object.prototype.toString.call(str) === '[object String]' ? str : (() => {throw new TypeError("Функция работает только со строками");})();
Можно и так, но [проще](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof)

2024-02-15 23:54 UTC, blackHATred commented on source/letters.js
> +const checkStr = (str) => Object.prototype.toString.call(str) === '[object String]' ? str : (() => {throw new TypeError("Функция работает только со строками");})();
Исправил

2024-02-17 09:30 UTC, DPeshkoff approved these changes

2024-02-17 09:31 UTC, closed without merging