Оглоблин Алексей
frontend-park-mail-ru/homework_2024_1 pull request #21
Opened 2024-02-11 20:28 UTC by AlexeiLDD

Added zip and tests

2024-02-11 21:19 UTC, johnSamilin commented
Привет!
Меня зовут Саша, я проверю ПР в ближайшее время и оставлю комментарии, если это потребуется. Если возникнут вопросы ты всегда можешь написать мне в тг: @WatasheeBaka

2024-02-12 18:02 UTC, johnSamilin requested changes

2024-02-12 18:02 UTC, johnSamilin commented on source/zip.js
> +const zip = (...objects) => Object.assign({}, ...objects.reverse());
это неправильная реализация. перечитай, пожалуйста, постановку задачи

2024-02-13 13:32 UTC, johnSamilin commented on source/zip.js
> +const zip = (...objects) => Object.assign({}, ...objects.reverse());
прошу прощения, мне казалось, что должен был быть второй аргумент со списком полей.
правильная реализация - пробежаться по всем ключам объектов и скопировать их в один новый. в текущей например нет проверки на неправильные входные данные. плюс, нужен jsdoc.
это изящное однострочное решение, но давай попробуем обойтись без деструктуризации

2024-02-13 15:48 UTC, AlexeiLDD commented on source/zip.js
> +const zip = (...objects) => Object.assign({}, ...objects.reverse());
Переделал

2024-02-13 20:41 UTC, johnSamilin commented on tests/zip.js
> +		assert.deepEqual(zip('sfd'), {0:'s', 1:'f', 2:'d'}, 'Распаковывает по индексам как свойства объекта');
а такое требование было? функция должна работать только с объектами

2024-02-13 21:22 UTC, AlexeiLDD commented on tests/zip.js
> +		assert.deepEqual(zip('sfd'), {0:'s', 1:'f', 2:'d'}, 'Распаковывает по индексам как свойства объекта');
В учебнике по js, который нам скидывали было написано следующее: "Массив – это особый подвид объектов". https://learn.javascript.ru/array#vnutrennee-ustroystvo-massiva
Поэтому мне показалось уместным добавить данные тесты. Могу их убрать

2024-02-14 18:48 UTC, johnSamilin commented on tests/zip.js
> +		assert.deepEqual(zip('sfd'), {0:'s', 1:'f', 2:'d'}, 'Распаковывает по индексам как свойства объекта');
с массивами ок, а вот строки как раз должны считаться невалидными данными

2024-02-14 18:56 UTC, AlexeiLDD commented on tests/zip.js
> +		assert.deepEqual(zip('sfd'), {0:'s', 1:'f', 2:'d'}, 'Распаковывает по индексам как свойства объекта');
Тогда как лучше сделать? Добавить проверку в функцию, что бы она не воспринимала строки или просто убрать их из теста?

2024-02-15 06:40 UTC, johnSamilin commented on tests/zip.js
> +		assert.deepEqual(zip('sfd'), {0:'s', 1:'f', 2:'d'}, 'Распаковывает по индексам как свойства объекта');
добавь пожалуйста проверку

2024-02-15 10:26 UTC, AlexeiLDD commented on tests/zip.js
> +		assert.deepEqual(zip('sfd'), {0:'s', 1:'f', 2:'d'}, 'Распаковывает по индексам как свойства объекта');
Поправил

2024-02-16 10:26 UTC, johnSamilin requested changes

2024-02-16 10:26 UTC, johnSamilin commented on source/zip.js
> +        if (typeof object !== 'object') {
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/5821894/7b96b3d3-82f0-4229-9bd1-0f6b13e55522)
знаешь еще какие-нибудь способы проверки типа переменной?

2024-02-16 22:26 UTC, AlexeiLDD commented on source/zip.js
> +        if (typeof object !== 'object') {
Честно говоря, до этого не знал. Но вот, что я понял из всего этого. Есть оператор typeof, который я и использовал. Но на null и любую функцию конструктор он выдаёт object, что является неверным. Также есть оператор instanceof, который определяет, является ли объект экземпляром определённого типа или его подтипа (надеюсь правильно сформулировал). Работает он соответственно только с объектами - в том смысле, что 1 instanceof Number выдаст false - и на переменную или константу созданную через конструктор выдаёт true, так что это тоже не подходит. Вроде как, самое надёжное - использовать Object.prototype.toString. Таким способом уже можно будет корректно отличать все типы данных, вплоть до даты и регулярных выражений. Но если я в данной задаче хочу, чтобы функция работала не только с обычными объектами, но и с массивами и т.д. , то в таком способе придётся добавлять множество проверок  на различные подтипы. Также есть более ситуативные методы вроде isNaN или isArray.

2024-02-16 22:31 UTC, AlexeiLDD commented on source/zip.js
> +        if (typeof object !== 'object') {
Ещё не знаю, насколько это подходит под проверку на типы, но операторы === и !== как раз их учитывают. Поэтому можно использовать какой-нибудь === null, как проверку на null например

2024-02-18 16:07 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-18 16:07 UTC, DPeshkoff commented on source/zip.js
> +'use strict';
А что делает эта строчка? Распиши, пожалуйста

2024-02-18 16:07 UTC, DPeshkoff commented on source/zip.js
> +const zip = (...objects) => {
Распиши, что такое ...

2024-02-18 16:07 UTC, DPeshkoff commented on source/zip.js
> +    let resultObj = {};
Кажется, здесь можно const. В чем его отличие от let? Чем отличается от var?

2024-02-18 16:07 UTC, DPeshkoff commented on tests/zip.js
> +	QUnit.test('Функция работает с массивами и строками', function (assert) {
Давай добавим тесты на некорректный ввод

2024-02-18 16:47 UTC, AlexeiLDD commented on source/zip.js
> +'use strict';
Данная строчка включает строгий режим. Появился он с выходом ECMAScript 5, и по сути в нем применяются более строгие требования к семантике языка. Например, в строгом режиме нельзя объявить переменную без ключевого слова, присвоить значение глобальным сущностям вроде NaN или undefined, удалить свойство объекта, для которого запрещено удаление, и т. д. На все подобные действия в строгом режиме будут выкинуты исключения, что делает это режим более безопасным.

2024-02-18 17:04 UTC, AlexeiLDD commented on source/zip.js
> +const zip = (...objects) => {
Это оператор расширения. Он распаковывает сущность и представляет её содержимое в виде отдельных сущностей. То есть объект он распакует по свойствам, массив по элементам и т.д. Тем же самым занимается * перед списком в python, например. В данном случае объявление ...objects в параметрах функции позволяет передать ей любое количество аргументов.

2024-02-18 17:30 UTC, AlexeiLDD commented on source/zip.js
> +    let resultObj = {};
сonst - объявление константы (константной ссылки). let - объявление переменной. В общем их поведение идентично за исключением того, что значение константы нельзя переназначать. var - устаревший вариант объявления переменной. Отличается от let тем, что не имеет блочной области видимости и обрабатывается в самом начале запуска скрипта или функции.

2024-02-18 17:57 UTC, AlexeiLDD commented on tests/zip.js
> +	QUnit.test('Функция работает с массивами и строками', function (assert) {
Тесты добавил. Надеюсь, я правильно понял, что требуется

2024-02-19 13:06 UTC, DPeshkoff approved these changes

2024-02-19 13:06 UTC, closed without merging