Купцов Гавриил
frontend-park-mail-ru/homework_2024_1 pull request #22
Opened 2024-02-11 21:32 UTC by Naruto-sys

Вариант 17.

2024-02-12 15:19 UTC, rissenberg commented
Привет! Меня зовут Костя, я буду твоим проверяющим ментором по ДЗ0. Если возникнут вопросы, смело пиши в тг - @PassPort_Guardian, или в вк - @rissenberg

2024-02-12 16:09 UTC, rissenberg requested changes
В целом, код написан хорошо, но вынесенные замечания нужно исправить. Как только закончишь - пиши мне в соцсети, чтобы я быстрее перепроверил твои исправления)

2024-02-12 16:09 UTC, rissenberg commented on source/plainify.js
> +}
Забыл пустую строчку в конце файла - например, если к файлу будут добавляться новые строки, то, без новой строки в конце, гит пометит прежнюю последнюю строку как измененную, хотя по факту она не менялась. Хорошей привычкой будет всегда ставить пустые строки в конец кода

2024-02-12 16:09 UTC, rissenberg commented on tests/plainify.js
> +		assert.deepEqual(plainify(nested3), plain3);
К тестам так же нужно добавить кейсы с некорректным вводом данных - когда передается не объект. В целом тестом очень мало, подумай, есть ли другие краевые случаи, и добавь тесты на них

2024-02-12 17:10 UTC, Naruto-sys commented on source/plainify.js
> +'use strict';
Если есть 'use strict', то интерпретатор js будет применять к коду строгий режим, а именно: запрещает изменение const переменных, запрещает дубликаты параметров функций, запрещает использование необъявленных переменных и т.д.

2024-02-12 17:16 UTC, Naruto-sys commented on source/plainify.js
> +const plainify = function (object) {
Про отличия (в коде заменил)
Стрелочные функции не имеют собственного "this", в стрелочных функция с 1 инструкцией в теле можно опустить {} и значение будет возвращено без "return"-a. Массив arguments внутри обыкновенной функции содержит список аргументов функции, а стрелочная функция, не имеет массива arguments.

2024-02-12 19:06 UTC, rissenberg requested changes

2024-02-12 19:06 UTC, rissenberg commented on source/plainify.js
> +	parent_string += parent_string !== '' ? '.' : '';
здесь в принципе тоже можно убрать явное сравнение с пустой строкой и просто оставить parent_string

2024-02-12 19:06 UTC, rissenberg commented on source/plainify.js
> +			if (typeof object[key] !== 'object' || object[key] === null) {
Аналогично убери явное сравнение с null

2024-02-13 23:18 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 23:18 UTC, DPeshkoff commented on source/plainify.js
> +		throw new Error('InvalidArgumentException');
Кажется, лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-13 23:18 UTC, DPeshkoff commented on source/plainify.js
> +	if (typeof object !== 'object' || !object) {
Кажется, проверка неполная - такие строки, вроде бы, за'plainify'ить нельзя

<img width="458" alt="Снимок экрана 2024-02-14 в 02 16 42" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/b4720221-629f-48bd-9a01-da651c7827d9">


Давай подумаем, как это можно починить)

2024-02-13 23:18 UTC, DPeshkoff commented on source/plainify.js
> +const plain_obj = (object, parent_string='') => {
Сюда тоже хочу JSDOC

2024-02-13 23:18 UTC, DPeshkoff commented on source/plainify.js
> +		if (Object.prototype.hasOwnProperty.call(object, key)) {
Кажется, можем [упростить](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

2024-02-13 23:18 UTC, DPeshkoff commented on tests/plainify.js
> +
Давай вынесем это в отдельный module и добавим больше тестов на некорректный ввод

2024-02-15 23:48 UTC, DPeshkoff approved these changes

2024-02-15 23:48 UTC, closed without merging