сделал дз0 (WEB-22 Саяпин Егор)
frontend-park-mail-ru/homework_2024_1 pull request #23
Opened 2024-02-11 21:53 UTC by exg0rd

Сделал дз, добавил тестов. vk.com/exg0rd для связи

2024-02-11 22:36 UTC, Kand1 commented
Привет!
Меня зовут Влад, скоро проверю PR, оставлю комменты. Если возникнут вопросы - пиши в тг: @Kand111

2024-02-11 23:40 UTC, Kand1 commented
@exg0rd Пробегись по комментам, которые помечены outdated, я писал для другой версии кода, но многие остались актуальны, отписал в каждом из них. Решил тегнуть, прост сам хз как это работает в гитхабе, может они у тебя останутся скрытые, сам в гитлабе в основном.

2024-02-12 00:05 UTC, Kand1 commented on source/letters.js
> +            if (charCount.get(char) <= 1) { // берем только уникальные символы
Лучше использовать строгое сравнение, тогда будет явно видно, что  2 - magic number и его следует как минимум вынести в константу

2024-02-12 00:05 UTC, Kand1 commented on source/letters.js
> +        }
2 цикла for здесь лучше заменить использованием методов массива

2024-02-12 00:08 UTC, Kand1 commented
Не уверен, критично ли, но поемняй плз название PR-a на Фамилия Имя, вроде все так делают.

2024-02-12 00:21 UTC, Kand1 commented on source/letters.js
> +const letters = ((letters, param) => {
Типизация не строгая в js, поэтому хорошо бы проверить, тот ли тип данных тебе пришел в аргументах функции. Если какое то несоответствие, то возвращай null. И напиши на этот кейс тесты.

2024-02-12 07:25 UTC, exg0rd commented on source/package.json
> +}
просто уберу пока

2024-02-12 07:25 UTC, exg0rd commented on tests/letters.js
> +	});
Попробовал добавить тестов основываясь на эквивалентности

2024-02-12 07:25 UTC, exg0rd commented on source/letters.js
> +    }
Сделал через свитч

2024-02-12 07:25 UTC, exg0rd commented on source/letters.js
> +    }
Вынес в функции код

2024-02-12 07:25 UTC, exg0rd commented on source/letters.js
> +    }
Остался только в одном месте теперь

2024-02-12 07:34 UTC, exg0rd commented on source/letters.js
> +"use strict"
Строгий режим для нашего кода: нельзя использовать необъявленные переменные, выбрасывает ошибку если значение поля нельзя изменить или удалить, не даёт повторять имена параметров функций, не даёт называть переменнные некоторыми keywordами JS и не даёт использовать устаревшие небезопасные штуки вроде eval
Вроде в моем коде ничего не должно меняться так как us strict объявлен глобально и всё уже работает под ним

2024-02-12 07:34 UTC, exg0rd commented on source/letters.js
> +    } else { // надо повернуть строку
Сделал

2024-02-12 07:37 UTC, exg0rd commented on source/letters.js
> +const letters = ((letters, param) => {
Исправил

2024-02-12 07:37 UTC, exg0rd commented on source/letters.js
> +            if (charCount.get(char) <= 1) { // берем только уникальные символы
Поправил

2024-02-12 07:38 UTC, exg0rd commented on source/letters.js
> +            charCount.set(char, (charCount.get(char) || 0) + 1);
Поправил

2024-02-12 07:38 UTC, exg0rd commented on source/letters.js
> +        console.log(charCount);
Ой..

2024-02-12 07:39 UTC, exg0rd commented on source/letters.js
> +        const charCount = new Map();
Поправил

2024-02-12 07:41 UTC, exg0rd commented on source/letters.js
> +        const charCount = new Map();
const не переопределяется, не объявляется повторно в рамках одного scope (блока), её надо инициализировать при объявлении
let переопределяется, но не может быть повторно объявлена в рамках блока
var может быть переопределена и повторно объявлена

2024-02-12 08:38 UTC, Kand1 commented on source/letters.js
> +        const charCount = new Map();
Тут не полностью, какая разница в области видимости каждого из объявлений?

2024-02-12 08:52 UTC, Kand1 commented on source/letters.js
> +"use strict"
Не очень понял, что значит 'все уже работает под ним'. В твоем случае и правда ничего не поменяется, если его убрать, но не поэтому. А почему?

2024-02-12 08:55 UTC, Kand1 commented on source/letters.js
> +            if (charCount.get(char) <= 1) { // берем только уникальные символы
Поправил, но не полностью. Мб ты не понял про magic number, вот глянь https://ru.hexlet.io/blog/posts/magic-numbers. Нужно 2 вынести в константу с именем, по которому будет понятно, что это за число и что делает.

2024-02-12 08:56 UTC, Kand1 commented on source/letters.js
> +const letters = ((letters, param) => {
Мне не очень нравится, что ты делаешь проверку, как одно из условий свитча. Обычно проверки на типы делаются в самом верху функции в if, который сразу прерывает функцию, если проверка не прошла. Давай так сделаем лучше, а в свитче оставь проверку уже значения переменной на true/false/undefined

2024-02-12 08:57 UTC, Kand1 commented on source/letters.js
> +const letters = ((letters, param) => {
И в данной реализации ты проверяешь тип только у второго параметра, нужна проверка и для первого. И тесты для неправильного типа первого аргумента тоже нужны.

2024-02-12 08:59 UTC, Kand1 commented on source/letters.js
> + */
Коммент должен быть сразу над функцией, к которой ты этот коммент пишешь

2024-02-12 09:10 UTC, Kand1 commented on source/letters.js
> +)
Вот эта скобочка при объявлении стрелочной функции лишняя

2024-02-12 09:12 UTC, Kand1 commented on source/letters.js
> +function uniqueLetterString(letters) {
Какие бывают способы объявления функций в js, почему тут используется такой подход? Обычно если тебе не нужна явно функциональность, которая становится доступной при таком подходе, все объявляют через стрелочные функции - так лаконичней, более современный подход. Так что поменяй плз везде на стрелочные.

2024-02-12 09:15 UTC, Kand1 commented on source/letters.js
> +    }, new Map());
Вот тут хорошее название для массива, отражает сразу что это за переменная, но плохое для мапы. Если ты объявляешь мапу то и отрази в названии переменной, что это мапа. Как я уже писал, я бы сделал в идеале что то типа charToCharCountMap - немного длинноватое, но символы бесплатные и полностью отражает суть того, что именно в этой мапе хранится ключем/значением

2024-02-12 09:17 UTC, Kand1 commented on source/letters.js
> +    letters = [...letters];
Вот эта строка ломает принцип чистой функции, ты меняешь данные, которые приходят в качестве аргумента.

2024-02-12 09:17 UTC, Kand1 commented on source/letters.js
> +    const set = new Set();
Давай сделаем более говорящее название для сет-а

2024-02-12 09:18 UTC, Kand1 commented on source/letters.js
> +    if (!param) letters.reverse();
Я бы рекомендовал в конструкциях if всегда писать { }, даже если там одна строка. Так код становится более читаемым

2024-02-12 09:20 UTC, Kand1 commented on source/letters.js
> +    return param ? Array.from(set).join('') : Array.from(set).reverse().join('');
Уже писал коммент про reverse, не самая лучшая идея 2 раза в функции разворачивать массив - операция дорогая и можно обойтись без нее, давай перепишем без reverse

2024-02-12 09:21 UTC, Kand1 commented on source/letters.js
> +}
В этой функции можно добавить немного отступов, как ты сделал во второй, код станет немного читаемее

2024-02-12 09:29 UTC, Kand1 commented
Убери скобочку в названии PR-a плз

2024-02-12 09:43 UTC, Kand1 commented on source/letters.js
> +            return stringFromStringSet(letters, param);
Мне кажется можно какие то более говорящие названия придумать, что бы сразу понятно было, что функция вернет. Первое название еще +- ок, но я б тоже поменял, в целом понятно, что что то про уникальность. А вторая функция вообще без контекста, непонятно, что именно она возвращает и про какой set идет речь

2024-02-12 10:14 UTC, exg0rd commented on source/letters.js
> +)
vs code пишет что нужна...
![Screenshot from 2024-02-12 13-09-46](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/92265706/0eb4580e-63ef-44af-b020-179051241114)

2024-02-12 10:31 UTC, exg0rd commented on source/letters.js
> +            if (charCount.get(char) <= 1) { // берем только уникальные символы
Добавил константу

2024-02-12 10:32 UTC, exg0rd commented on source/letters.js
> +const letters = ((letters, param) => {
Добавил тесты, поменял проверку

2024-02-12 10:34 UTC, exg0rd commented on source/letters.js
> + */
Сделал

2024-02-12 10:34 UTC, exg0rd commented on source/letters.js
> +    }, new Map());
Поменял название

2024-02-12 10:34 UTC, exg0rd commented on source/letters.js
> +    letters = [...letters];
Добавил временную переменную

2024-02-12 10:35 UTC, exg0rd commented on source/letters.js
> +    const set = new Set();
Сделал

2024-02-12 10:35 UTC, exg0rd commented on source/letters.js
> +    if (!param) letters.reverse();
Сделал

2024-02-12 10:36 UTC, exg0rd commented on source/letters.js
> +        const charCount = new Map();
У var внутри функции, если вне то глобальная
У let внутри блока (условие, цикл)
У const внутри блока с обязательной инициализацией

Var - плохо)

2024-02-12 10:38 UTC, exg0rd commented on source/letters.js
> +"use strict"
"use strict" применяется ко всему файлу сразу

2024-02-12 10:39 UTC, Kand1 commented on source/letters.js
> +"use strict"
Да, но мой вопрос был в другом. Что будет если его убрать? Как уже писал, думал это ты мне ответил - ничего не изменится. Вопрос - почему?

2024-02-12 10:42 UTC, Kand1 commented on source/letters.js
> +const charAmountInString = 2;
Вот [тут ](https://melikhova-summary.gitbook.io/veb-tekhnologii/javascript/znakomstvo-s-javascript/funkcii/imenovanie-peremennykh-i-funkcii) можно прочитать про принятые в js стили именования функций/переменных/глобальных констант. У тебя тут используется для константы camelCase - это неправильно

2024-02-12 10:46 UTC, Kand1 commented on source/letters.js
>      switch (typeof(param)) {
Нет смысла здесь проверять тип, раз ты уже уверен, что до сюда дойдут только правильные значения. Лучше тут по значению самой переменной case-ы писать

2024-02-12 10:49 UTC, Kand1 commented on source/letters.js
> +    }
1) Строгое сравнение
2) Можно кодстайл улучшить выносом 2х проверок в переменные сверху (писал в одном из тредов про это), в таком виде if тяжеловато читается из за большого кол-ва переносов скобочек и логических операторов

2024-02-12 10:59 UTC, Kand1 commented on source/letters.js
> +            return stringWithSingleChars(letters, param);
Давай тут еще в название в начало добавим слово get, ты ж все таки получаешь новые строки. Не бойся больших названий, сильно лучше если ты читаешь 10 слов в названии функции, чем потом не понимая что она делает читаешь в ней 10 строк кода. Первое название ок как по мне с get будет, а второе опять надо поменять. Давай все таки напишу тебе как я это вижу, ты вроде не прям понимаешь о чем речь и насколько в целом ок делать длинные названия, когда из за этого заметно повышается читаемость. `getStringWithSingleOccuranceOfRepeatedChars`

2024-02-12 11:02 UTC, Kand1 commented on source/letters.js
> +)
Ну если ты из парных скобочек будешь удалять только 1ну, то кншн нужна)

2024-02-12 11:16 UTC, exg0rd commented on source/letters.js
> +"use strict"
Я использую функционал es6 (let, стрелочные функции и тд)
В es6 уже использована директива use strict, поэтому без этой директивы в начале ничего не поменяется

2024-02-12 11:16 UTC, exg0rd commented on source/letters.js
> +)
🤦‍♂️🤦‍♂️🤦‍♂️

2024-02-12 11:20 UTC, Kand1 commented on source/letters.js
> +    const set = new Set();
Как ты уже мог заметить, я прям сильно придираюсь к названиям, но это реально важно научиться их правильно писать. Невероятно сильно упрощает чтение кода, когда ты по названию понимаешь, что лежит в переменной/что делает функция, не смотря на реализацию. Все еще по названию set-а я не понимаю, что он делает. Посмотри как ты называл мапу и сделай по аналогии, что б название звучало так, как будто ты мне просто речью кратко объяснил, что делает эта переменная.

2024-02-12 11:46 UTC, Kand1 commented on source/letters.js
> +const charAmountInString = 2;
Еще не заметил сразу, константы принято объявлять в самом верху файла

2024-02-12 13:15 UTC, exg0rd commented on source/letters.js
> +    const set = new Set();
Поменял название

2024-02-12 13:16 UTC, exg0rd commented on source/letters.js
> +    return param ? Array.from(set).join('') : Array.from(set).reverse().join('');
Использовал for, reverse только в конце

2024-02-12 13:17 UTC, exg0rd commented on source/letters.js
> +}
Поправил форматирование

2024-02-12 13:20 UTC, exg0rd commented on source/letters.js
> +const charAmountInString = 2;
Поправил

2024-02-12 13:22 UTC, exg0rd commented on source/letters.js
>      switch (typeof(param)) {
Сделал, но будет 2 кейса свича: true и false же?

2024-02-12 13:25 UTC, exg0rd commented on source/letters.js
> +    }
Поправил

2024-02-12 13:36 UTC, exg0rd commented on source/letters.js
> +function uniqueLetterString(letters) {
2 способа объявления: function a(b) {...} или const f = function(a) для обычной
И стрелочные функции const multiply(a, b) => return a * b;

У стрелочных функций нет собственного контекста this, они используют контекст родительской области видимости. Внутри стрелочной функции this будет ссылаться на this, который был установлен во время объявления функции.
 У обычных функций имеют собственный контекст this, который зависит от того, как они были вызваны.

2024-02-12 13:38 UTC, Kand1 commented on source/letters.js
> +function uniqueLetterString(letters) {
Еще 1 отличие есть, погугли

2024-02-12 13:39 UTC, Kand1 commented on source/letters.js
> +function uniqueLetterString(letters) {
Ну и обычно это называют вроде 3мя типами, хотя ты перечислил правильно. Function declaration, function expression и стрелочная.

2024-02-12 13:41 UTC, Kand1 commented on source/letters.js
> +            return getStringWithSingleOccuranceOfRepeatedChars(letters, false);
для этих 2х кейсов можно написать 1 return, подумай как

2024-02-12 13:44 UTC, Kand1 commented on source/letters.js
> +    }
В правильном направлении, но не так. В if-е должны остаться только твои переменные которые ты создаешь выше и логические операторы. Еще тут с неймингом проблема, которую ты этим решишь, приставка is у переменной подразумевает, что в ней лежит boolean значение.

2024-02-12 13:46 UTC, Kand1 commented on source/letters.js
> +            return stringWithSingleChars(letters, param);
Забыл про uniqueLetterString. Ты не можешь называть функцию без глагола в названии, это какое то действие.

2024-02-12 13:49 UTC, Kand1 commented on source/letters.js
> +        }
Вот в этом форе ошибка

2024-02-12 13:50 UTC, Kand1 commented on source/letters.js
> +    if (param === false) {
Такое сравнение избыточное, когда ты знаешь что у тебя в params всегда лежит boolean. Сделай здесь if который не использует ===

2024-02-12 13:50 UTC, exg0rd commented on source/letters.js
> +    }
Сделал

2024-02-12 13:51 UTC, exg0rd commented on source/letters.js
> +            return getStringWithSingleOccuranceOfRepeatedChars(letters, false);
Сделал

2024-02-12 13:54 UTC, exg0rd commented on source/letters.js
> +            return stringWithSingleChars(letters, param);
Переименовал

2024-02-12 13:55 UTC, exg0rd commented on source/letters.js
> +        }
Да, length - 1

2024-02-12 13:55 UTC, exg0rd commented on source/letters.js
> +    if (param === false) {
Сделал !param

2024-02-12 13:58 UTC, exg0rd commented on source/letters.js
> +function uniqueLetterString(letters) {
> Еще 1 отличие есть, погугли

Нельзя получить доступ к arguments (входным параметрам) у стрелочных

2024-02-12 13:59 UTC, Kand1 commented on source/letters.js
> +    }
Обращай внимание, как объявляешь переменную let/const

2024-02-12 14:01 UTC, exg0rd commented on source/letters.js
> +    }
по логике надо const

2024-02-12 14:06 UTC, Kand1 commented on source/letters.js
> +const letters = (letters, param) => {
Я почему то думал, чт оназвания аргументов даны в названии и внимания на них не обращал - но нет. Нужно поменять. letters у тебя дублирует название функции - так не хорошо, лучше что то тип 'начальная строка', params тоже не очень - у тебя это флаг, по которому совершается какое то действие и лучше его назвать is{ТоЗаЧтоОнОтвечает}

2024-02-12 14:09 UTC, Kand1 commented on source/letters.js
> +const letters = (letters, param) => {
такие штуки кстати автозаменой делаются, я сам в вебшторме сижу, ты можешь погуглить как это делается в vs code, что б не бегать по всему файлу и не менять руками

2024-02-12 14:12 UTC, exg0rd commented on source/letters.js
> +const letters = (letters, param) => {
да в VSC тоже можно, поправил

2024-02-13 23:00 UTC, DPeshkoff requested changes
Привет! Классное решение, но нужно кое-что поправить)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 23:00 UTC, DPeshkoff commented on source/letters.js
> +    }
Как ты думаешь, можем ли мы порефакторить это на [методы строк](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String)?

2024-02-13 23:00 UTC, DPeshkoff commented on source/letters.js
> +const getStringWithSingleOccuranceOfRepeatedChars = (initialString, shouldLeaveFirstChar) => {
Предлагаю добавить JSDOC тут и ко всем остальным функциям

2024-02-13 23:00 UTC, DPeshkoff commented on source/letters.js
> +    const isNotString = (typeof(initialString) !== 'string');
Произошло что-то страшное

<img width="370" alt="Снимок экрана 2024-02-14 в 01 56 42" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/bf696b3c-ed13-4b3e-841f-74a8dfdee4a4">

Вроде бы объект, а вроде бы полноценная строка. Как прокомментируешь, что фиксить будем (и будем ли?)

2024-02-13 23:00 UTC, DPeshkoff commented on source/letters.js
> +        return null;
Предлагаю [throw'ать](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw)

2024-02-13 23:00 UTC, DPeshkoff commented on tests/letters.js
> +	}
Гоу добавим `new String('aaa')` и подумаем, что можно еще добавить

2024-02-14 22:35 UTC, exg0rd commented on source/letters.js
> +    }
Предположил, что речь о String.at()

2024-02-14 22:35 UTC, exg0rd commented on source/letters.js
> +const getStringWithSingleOccuranceOfRepeatedChars = (initialString, shouldLeaveFirstChar) => {
Добавил

2024-02-14 22:35 UTC, exg0rd commented on source/letters.js
> +    const isNotString = (typeof(initialString) !== 'string');
Поменял проверку, дописал тесты

2024-02-14 22:35 UTC, exg0rd commented on source/letters.js
> +        return null;
Кидаю ошибки + другой метод в тестах

2024-02-14 22:36 UTC, exg0rd commented on tests/letters.js
> +	}
Аналогично с new Boolean(null) и тд

2024-02-15 22:39 UTC, DPeshkoff requested changes

2024-02-15 22:39 UTC, DPeshkoff commented on source/letters.js
> +        for (let i = initialString.length - 1; i >= 0; i--) {
А какие еще циклы есть?)

2024-02-16 06:18 UTC, exg0rd commented on source/letters.js
> +        for (let i = initialString.length - 1; i >= 0; i--) {
Есть еще for..in и for..of 
Второй допусти́м в else, он позволяет итерировать по строке в прямом порядке, позволяя сразу получать на каждом шаге цикла элемент объекта. Но с его помощью нельзя пройтись по строке в обратном порядке без преобразования самой строки (например, reverseом), а это не очень шустрая операция будет. 

Можно сделать while (let i = initialString.length() - 1 >= 0) и декрементить, но на мой взгляд использовать for чище.

Честно говоря не понимаю что с моим решением не так)

2024-02-17 09:36 UTC, DPeshkoff commented on source/letters.js
> +        for (let i = initialString.length - 1; i >= 0; i--) {
Оно работает, но в JS можно лучше - есть перебирающие методы, например)

2024-02-17 13:04 UTC, exg0rd commented on source/letters.js
> +        for (let i = initialString.length - 1; i >= 0; i--) {
> Есть еще for..in и for..of 
> Второй допусти́м в else, он позволяет итерировать по строке в прямом порядке, позволяя сразу получать на каждом шаге цикла элемент объекта. Но с его помощью нельзя пройтись по строке в обратном порядке без преобразования самой строки (например, reverseом), а это не очень шустрая операция будет. 
> 
> Можно сделать while (let i = initialString.length() - 1 >= 0) и декрементить, но на мой взгляд использовать for чище.
> 
> Честно говоря не понимаю что с моим решением не так)

2024-02-17 15:01 UTC, exg0rd commented on source/letters.js
> +        for (let i = initialString.length - 1; i >= 0; i--) {
@DPeshkoff поменял реализацию. Вероятно в первом случае можно просто использовать reverse, а затем  forEach, но ментор призывал не использовать реверс.

2024-02-18 12:33 UTC, DPeshkoff approved these changes

2024-02-18 12:33 UTC, closed without merging