Буйдина Кристина
frontend-park-mail-ru/homework_2024_1 pull request #24
Opened 2024-02-11 22:04 UTC by KristinaBu

11 вариант

2024-02-12 07:36 UTC, johnSamilin commented
Привет!
Меня зовут Саша, я проверю ПР в ближайшее время и оставлю комментарии, если это потребуется. Если возникнут вопросы ты всегда можешь написать мне в тг: @WatasheeBaka

2024-02-12 18:21 UTC, johnSamilin requested changes

2024-02-12 18:21 UTC, johnSamilin commented on source/max.js
> +/**
а почему файл называется max, а код, который в нем, делает совсем не max?

2024-02-12 18:21 UTC, johnSamilin commented on source/max.js
> +        return "введите строку";
использовать return в случае ошибки неправильно. нужно либо бросать исключение, либо функция должна возвращать что-то еще, что сигнализировало бы, а были ли ошибки

2024-02-12 18:21 UTC, johnSamilin commented on source/max.js
> +    if(input === ""){
а зачем эта проверка?

2024-02-12 18:21 UTC, johnSamilin commented on source/max.js
> +    let resultArray = [];
а почему resultArray объявлена как let?

2024-02-12 18:21 UTC, johnSamilin commented on source/max.js
> +    for (let i = 0; i < input.length; i++){
можешь переписать этот цикл с использованием встроенных методов (map, reduce)?

2024-02-13 07:28 UTC, KristinaBu commented on source/max.js
> +/**
Спасибо за замечание, я это исправлю

2024-02-13 07:32 UTC, KristinaBu commented on source/max.js
> +    if(input === ""){
Да, она не очень логичная, ведь у меня дальше в цикле есть такая же проверка на длину. Я уберу ее

2024-02-13 20:33 UTC, johnSamilin commented on tests/rle.js
> +        assert.strictEqual(rle('A'), 'A', "rle('A') === 'A1'");
а ты запускала тесты? они прошли?

2024-02-14 05:39 UTC, KristinaBu commented on tests/rle.js
> +        assert.strictEqual(rle('A'), 'A', "rle('A') === 'A1'");
Да, запускала, все тесты пройдены. Вот скрин с ними:
![Тесты_ДЗ_0](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/114954578/e97a1910-9936-4aa6-b8a3-f771e884b106)

2024-02-14 18:41 UTC, johnSamilin commented on tests/rle.js
> +        assert.strictEqual(rle('A'), 'A', "rle('A') === 'A1'");
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/5821894/323a4620-51d2-461d-98aa-ead0c606960a)
уверена?

2024-02-14 18:47 UTC, johnSamilin commented on source/rle.js
> +            accumulator.push(prev + (counter > 1 ? counter : ''));
еще комментарий (это не руководство к действию, просто на будущее) - третий параметр reduce - индекс текущего элемента, так что здесь можно обойтись без slice(1), а еще accumulator можно инициализировать строкой и не делать .join('') в конце

2024-02-14 21:41 UTC, KristinaBu commented on source/rle.js
> +            accumulator.push(prev + (counter > 1 ? counter : ''));
Я в комментарии оставила вариант. С индексами у меня были небольшие затруднения, поэтому я решила reduce заменить на map, чтобы сначала изменить массив input и превратить его в resultArray, а потом собрать его в одну строку с помощью reduce (вместо join)

2024-02-15 06:39 UTC, johnSamilin approved these changes

2024-02-15 23:52 UTC, DPeshkoff requested changes
Привет! Классное решение, но нужны исправления)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:52 UTC, DPeshkoff commented on source/rle.js
> +function rle(input){
Гоу стрелочную)

А чем стрелочные функции отличаются от обычных?

2024-02-15 23:52 UTC, DPeshkoff commented on source/rle.js
> +    if(prev !== undefined){
Предлагаю [так](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)

2024-02-15 23:52 UTC, DPeshkoff commented on source/rle.js
> + */
А это кто такой и что он тут делает

2024-02-15 23:52 UTC, DPeshkoff commented on tests/rle.js
> +        assert.throws( function() {
А можем тут стрелочную функцию использовать?

2024-02-16 04:29 UTC, KristinaBu commented on source/rle.js
> +'use strict';
Модули автоматически в строгом режиме, там не нужно писать 'use strict'

2024-02-16 04:31 UTC, KristinaBu commented on source/rle.js
> +function rle(input){
В стрелочных не пишется слово function и иногда return (если он нужен, но в функции всего 1 инструкция). И у стрелочных функций нет своих this и массива аргументов, они берут их от внешней функции

2024-02-16 04:33 UTC, KristinaBu commented on source/rle.js
> + */
Мой проверяющий дал рекомендацию, необязательную к написанию. Я сделала по ней второй вариант решения и вынесла в комментарий

2024-02-17 09:39 UTC, DPeshkoff requested changes

2024-02-17 09:39 UTC, DPeshkoff commented on source/max.js
> +const max = numbers => Math.max(...numbers);
Не поменялось(

2024-02-17 09:39 UTC, DPeshkoff commented on index.html
> -
И тут

2024-02-17 09:39 UTC, DPeshkoff commented on source/rle.js
> +let rle = (input) => {
А почему let? Можно const? в чем отличие?

2024-02-17 09:39 UTC, DPeshkoff commented on source/rle.js
> +    if (objToStr.call(input) !== "[object String]") {
Можно [так](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof)

2024-02-17 09:39 UTC, DPeshkoff commented on source/rle.js
> + */
?

2024-02-17 09:39 UTC, DPeshkoff commented on tests/max.js
> +});
\n

2024-02-18 13:40 UTC, KristinaBu commented on source/rle.js
> +let rle = (input) => {
Let объявляет переменную, которую можно изменить в пределах одного блока кода. Переменную с  const нельзя переназначить, в остальном она похожа на let. Если есть объект, то сам объект, если он const, изменить нельзя, но можно изменить его свойства (с массивами так же). Еще есть var, она для глобальных переменных. 
Здесь можно использовать const, это ничему не противоречит. Просто let мне было привычнее

2024-02-18 14:12 UTC, KristinaBu commented on source/max.js
> +const max = numbers => Math.max(...numbers);
Я копировала код с исходного файла и вручную переписывала. Не знаю, почему это строка различается, там не должно быть \n

2024-02-18 17:28 UTC, KristinaBu commented on index.html
> +</html>
Хорошо. Я исправила, теперь есть только добавленные строки, измененных и удаленных нет

2024-02-19 11:42 UTC, DPeshkoff approved these changes

2024-02-19 11:42 UTC, closed without merging