Сделано нулевое дз, все тесты проходятся успешно, Дорожкин Павел
frontend-park-mail-ru/homework_2024_1 pull request #25
Opened 2024-02-11 22:23 UTC by Skotyty

Дорожкин Павел

2024-02-12 06:30 UTC, Zela2520 commented
Привет ) 
Меня зовут Даня, буду проверять твоё дз и оставлю комменты, если они понадобятся )

Поздравляю с зачислением на курс и первым выполненным ДЗ !
Уверен, что тебе понравится обучение 😏

2024-02-12 09:35 UTC, Zela2520 commented
Мне нравится твоё решение, но попробуй отпимизировать своё решение и посмотреть в сторону структур данных. 
Как думаешь какая структура данных подойдёт ? 

Ты уверен, что нам необходимо использовать два раза метод replace или можно обойтись одним разом ?

2024-02-12 11:28 UTC, Skotyty commented
Воспользовался структурой данных Set с сложностью O(1), вместо O(n) в прошлой реализации. Уменьшил кол-во вызовов replace для повышения производительности.

2024-02-12 11:42 UTC, Skotyty commented
Воспользовался структурой данных Set с сложностью O(1), вместо O(n) в прошлой реализации. Уменьшил кол-во вызовов replace для повышения производительности.

2024-02-13 04:52 UTC, Zela2520 commented
Ты был не очень внимательным ) Надеюсь исправишься :) 
Не вижу, чтобы мои замечания были исправлены. Большая часть осталась проигнорина - возвращаю в работу

2024-02-13 12:57 UTC, Skotyty commented
Использую структуру данных словарь для оптимизации решения. Метод replace теперь используется один раз. Перенёс решение из папки tests в папку source

2024-02-13 13:04 UTC, Skotyty commented
> Ты был не очень внимательным ) Надеюсь исправишься :) Не вижу, чтобы мои замечания были исправлены. Большая часть осталась проигнорина - возвращаю в работу
> 
> На вопросы не ответил ) Оставил в папке tests решение

На вопросы ответил. Решение перенёс в папку source

2024-02-13 17:49 UTC, Zela2520 commented on tests/filter.js
>  'use strict';
Понимаешь ли ты зачем используется эта строчка и в чём её смысл ? Что было бы без её использования ?

2024-02-14 13:21 UTC, Skotyty commented on tests/filter.js
Исправил

2024-02-14 13:30 UTC, Skotyty commented on tests/filter.js
> +function escapeHtml(unsafe) {
Исправил в коде. Arrow function имеет более короткий и читаемый синтаксис, не имеет собственного контекста this. Значение this внутри определяется контекстом, в котором эта функция была создана, а function declaration наоборот имеет собственный контекст this, который зависит от способа вызова функции.  Ещё arrow function не имеет собственного объекта 'arguments"  и не может быть использована в качестве конструктора. Arrow functions обычно предпочтительнее из-за лаконичности кода и особенностей "this"

2024-02-14 13:30 UTC, Skotyty commented on tests/filter.js
> +function escapeHtml(unsafe) {
Исправил нейминг

2024-02-14 13:34 UTC, Skotyty commented on tests/filter.js
> +    let allowedTagsDict = {};
let используется для объявления переменных, значение которых может изменяться, а const для объявления переменных, значение которых не предполагается изменять. Попытка переназначить переменную, объявленную с const, приведет к ошибке. Const запрещает переназначение самой переменной, но не ее содержимого. Поэтому если переменная содержит объект, то можно изменить содержимое этого объекта.
Это можно сделать потому что примитивные типы сравниваются по значению, а объекты сравниваются по ссылке

2024-02-14 13:35 UTC, Skotyty commented on tests/filter.js
> +        } else {
убрал

2024-02-14 13:35 UTC, Skotyty commented on tests/filter.js
> +        switch (match) {
Изменил код

2024-02-14 13:37 UTC, Skotyty commented on tests/filter.js
>  'use strict';
Эта строчка активирует строгий режим выполнения кода: вводятся более строгие правила(строка, которая могла не вызвать исключение в "обычном" коде, вызовет его при наличии 'use strict'), предотвращается использование некоторых устаревших функций

2024-02-14 13:43 UTC, Skotyty commented on tests/filter.js
> +function escapeHtml(unsafe) {
Изменил нейминг, добавил jsDoc

2024-02-15 07:03 UTC, Zela2520 commented on tests/filter.js
> +function escapeHtml(unsafe) {
Почитай про хостинг. Как при хостинге себя ведут arrow function и function declaration ?

2024-02-15 07:12 UTC, Zela2520 reviewed
Поправь замечания и на проверку к главному ментору )

2024-02-15 07:12 UTC, Zela2520 commented on source/filter.js
> +        } else {
else не нужен

2024-02-15 07:12 UTC, Zela2520 commented on source/filter.js
> +    allowedTags.forEach(tag => allowedTagsDict[tag.toLowerCase()] = true);
можно использовать метод reduce.

2024-02-15 11:26 UTC, Skotyty commented on source/filter.js
> +    allowedTags.forEach(tag => allowedTagsDict[tag.toLowerCase()] = true);
Исправил

2024-02-15 11:26 UTC, Skotyty commented
Прикрепляю скрин с успешно пройденными тестами
![Снимок экрана от 2024-02-15 14-24-41](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/92323843/939eb0f2-34d4-4098-b677-39b507bc155b)

2024-02-15 15:58 UTC, Zela2520 commented on source/filter.js
> +        return makeHtmlSafe(fragment);
пустую строку перед return-ом

2024-02-15 15:58 UTC, Zela2520 commented on source/filter.js
> +    }, {});
пустую строку

2024-02-15 23:13 UTC, DPeshkoff requested changes
Привет! Хорошее решение, но есть пара вопросов)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:13 UTC, DPeshkoff commented on source/filter.js
> +/**
Вижу, в другом ответе расписал про строгий режим. А почему тут выбрал нестрогий?

Могут ли быть кейсы, когда код в строгом режиме без явного указания с помощью директивы?

2024-02-15 23:13 UTC, DPeshkoff commented on source/filter.js
> +function filter(html, allowedTags) {
Хочу JSDOC и сюда)

2024-02-15 23:13 UTC, DPeshkoff commented on tests/filter.js
> +        const expected = '<strong>Hello, <em>World!</em></strong> 1 + 2 &lt; 4!';
Предлагаю вернуть, как было - чтобы не было лишнего diff'а

2024-02-15 23:13 UTC, DPeshkoff commented on tests/filter.js
> +});
Пустую строчку в конце)

2024-02-15 23:13 UTC, DPeshkoff commented on source/filter.js
> +function filter(html, allowedTags) {
Чем стрелочные функции отличаются от обычных? Почему тут такая?

2024-02-15 23:13 UTC, DPeshkoff commented on source/filter.js
> +    const allowedTagsDict = allowedTags.reduce((dict, tag) => {
А если allowedTags не массив? Предлагаю проверять + добавить тесты

2024-02-15 23:14 UTC, DPeshkoff commented on tests/filter.js
> +function escapeHtml(unsafe) {
Хочу сюда ответ тоже)

2024-02-16 16:22 UTC, Skotyty commented on source/filter.js
> +/**
1) Забыл добавить. В новом коммите исправил
2)Такие кейсы есть: код, написанный в модулях и внутри классов ECMAScript исполняется в строгом режиме без написания 'use strict'

2024-02-16 16:22 UTC, Skotyty commented on source/filter.js
> +function filter(html, allowedTags) {
Добавил

2024-02-16 16:23 UTC, Skotyty commented on tests/filter.js
> +        const expected = '<strong>Hello, <em>World!</em></strong> 1 + 2 &lt; 4!';
Исправил. Всё слетело из-за  ctrl+alt+l в pycharm'e

2024-02-16 16:24 UTC, Skotyty commented on tests/filter.js
> +});
добавил

2024-02-16 16:25 UTC, Skotyty commented on source/filter.js
> +function filter(html, allowedTags) {
1) Контекст this - не используется в этой функции.
2) Функция относительно сложная, поэтому решил, что удобнее сделать её такой

2024-02-16 16:26 UTC, Skotyty commented on source/filter.js
> +    const allowedTagsDict = allowedTags.reduce((dict, tag) => {
А что делать в случае неудачной проверки? И что должны проверять новые тесты?

2024-02-16 16:38 UTC, Skotyty commented on tests/filter.js
> +function escapeHtml(unsafe) {
Функции, объявленные с помощью Function declaration подвержены хостингу(поднимаются в начало области видимости), т.е. их можно вызвать до их объявления в коде. Вызов стрелочной функции, объявленной с помощью const/let до её объявления вызовет ошибку. Если стрелочную функцию объявить с помощью var, то переменная будет известна, но попытка вызова функции до её определения приведет к ошибке(видна сама переменная, а не её значение)

2024-02-17 09:47 UTC, DPeshkoff commented on tests/filter.js
> +function escapeHtml(unsafe) {
Предлагаю стрелочную функцию - нам не нужны специфические вещи вроде this)

2024-02-17 09:48 UTC, DPeshkoff commented on source/filter.js
> +function filter(html, allowedTags) {
Как по мне, тут лучше стрелочная)

2024-02-17 09:48 UTC, DPeshkoff commented on source/filter.js
> +    const allowedTagsDict = allowedTags.reduce((dict, tag) => {
Ну, [не знаю](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw) : )

2024-02-17 09:49 UTC, DPeshkoff requested changes

2024-02-17 09:49 UTC, DPeshkoff commented on tests/filter.js
> +        QUnit.test('filter не экранирует валидные html-тэги', function (assert) {
Не поменялось

2024-02-18 17:23 UTC, Skotyty commented on tests/filter.js
> +        QUnit.test('filter не экранирует валидные html-тэги', function (assert) {
Исправил

2024-02-18 17:24 UTC, Skotyty commented on source/filter.js
> +    const allowedTagsDict = allowedTags.reduce((dict, tag) => {
Добавил проверку и тесты

2024-02-18 17:24 UTC, Skotyty commented on tests/filter.js
> +function escapeHtml(unsafe) {
Исправил на стрелочную

2024-02-18 20:55 UTC, Skotyty commented on source/filter.js
> +function filter(html, allowedTags) {
Исправил

2024-02-19 15:47 UTC, DPeshkoff approved these changes

2024-02-19 15:47 UTC, closed without merging