Горбунов Алексей
frontend-park-mail-ru/homework_2024_1 pull request #26
Opened 2024-02-11 22:24 UTC by Famelbyby

Вариант 5

2024-02-12 14:04 UTC, AnnSkay commented on tests/chess.js
> +	QUnit.test('Шахматная доска по умолчанию', function (assert) {
Этот тест не соответствует постановке задачи)

2024-02-12 14:04 UTC, AnnSkay commented on tests/chess.js
> +	QUnit.test('Шахматной доски asd на asd не бывает', function (assert) {
тест на валидные данные - круть) Но давай расширим их и включим сюда все типы данных, которые могут прилететь в функцию)

2024-02-12 14:04 UTC, AnnSkay commented on tests/chess.js
> +	QUnit.test('Шахматной доски -1 на -1 не бывает', function (assert) {
Название теста должно отражать то, что ты проверяешь - а проверяешь ты отрицательные числа) Лучше название в данном случае не привязывать к -1. Почему?) Допустим, потом функция расширится и надо будет добавить кейсы на другие отрицательные числа - придется либо переименовывать тест, либо добавлять новый - что не очень удобно.

2024-02-12 15:24 UTC, AnnSkay commented on source/chess.js
> +const chess = (dimension = 2) => {
давай еще добавим JSDос)

2024-02-13 23:02 UTC, Famelbyby commented on source/chess.js
> +const chess = (dimension = 2) => {
Исправлено)

2024-02-13 23:02 UTC, Famelbyby commented on tests/chess.js
> +	QUnit.test('Шахматной доски -1 на -1 не бывает', function (assert) {
Исправлено)

2024-02-13 23:02 UTC, Famelbyby commented on tests/chess.js
> +	QUnit.test('Шахматной доски asd на asd не бывает', function (assert) {
Исправлено)

2024-02-13 23:03 UTC, Famelbyby commented on tests/chess.js
> +	QUnit.test('Шахматная доска по умолчанию', function (assert) {
Тест убран)

2024-02-13 23:03 UTC, Famelbyby commented on source/chess.js
> +    while (i < dimension ** 2){
Исправлено)

2024-02-13 23:04 UTC, Famelbyby commented on source/chess.js
> +};
Некоторые текстовые редакторы "игнорируют" незаконченную строку, то есть ту, которая не заканчивается "\n", поэтому }; может не сохранится в файле

2024-02-13 23:06 UTC, Famelbyby commented on source/chess.js
> +const chess = (dimension = 2) => {
Исправлено)

2024-02-13 23:13 UTC, Famelbyby commented on source/chess.js
Рассмотрим следующий пример:
`
let a = chess(2)`
`
[0]
`
`
console.log(a);` 
В данном случае `a = '*'`, но это неверно. Однако если сделать так:
`
let a = chess(2);`
`
[0]
`
`
console.log(a);` 
То `a = '* \n *'`. Всё потому, что в данном случае компилятор представляет выражение 
`let a = chess(2)`
`[0]` 
как единую строку `let a = chess(2)[0]`, поэтому необходим разделитель `;`.

2024-02-13 23:17 UTC, Famelbyby commented on source/chess.js
Строгий режим позволяет ограничить некоторые возможности, способные вызвать ошибки, которые в не строгом режиме могут допускаться. Так, например, strict режим не позволит создать объект `{name: 'Alex', name: 'Alex'}`, или приравнять необъявленную переменную `x = 10`. В таких случаях будут вызваны ошибки.

2024-02-13 23:19 UTC, Famelbyby commented on source/chess.js
Исправлено)

2024-02-13 23:19 UTC, Famelbyby commented on source/chess.js
Исправлено)

2024-02-13 23:26 UTC, Famelbyby commented on source/chess.js
> +    if (!Number.isInteger(dimension = +dimension) || dimension <= 1){//если длина доски не является допустимым значением
Чистые функции - те, которые при одних и тех же входных параметрах выдают одинаковый ответ и не меняют внешние параметры. Так, например, если передать в функцию объект или массив, то они передадутся по ссылке и буду изменены в этой функции, что делает эту функцию нечистой.

2024-02-13 23:26 UTC, Famelbyby commented on source/chess.js
> +    if (!Number.isInteger(dimension = +dimension) || dimension <= 1){//если длина доски не является допустимым значением
Исправлено)

2024-02-13 23:29 UTC, Famelbyby commented on source/chess.js
> +        board += (((i++ + invert) % 2) == 0 ? '*' : ' ')//чередование символов
Потому что строгое сравнение не выполняет приведение типов. Так, например, `'' == 0` выдаст `true`, как и `[] == 0`. Так как "логически" пустая строка, пустой массив и 0 - это всё `false`. А вот `'' === 0` и `[] === 0` выдадут `false`, так как это всё разные типы.

2024-02-13 23:29 UTC, Famelbyby commented on source/chess.js
> +        board += (((i++ + invert) % 2) == 0 ? '*' : ' ')//чередование символов
Исправлено)

2024-02-13 23:29 UTC, Famelbyby commented on source/chess.js
> +};
Исправлено)

2024-02-14 06:59 UTC, AnnSkay commented on source/chess.js
крутатенюшка) чуть-чуть с отступами перестарался) 10 и 8 разделять нет необходимости - это первая строка в функции))

2024-02-14 07:13 UTC, AnnSkay commented on source/chess.js
> +    if (!Number.isInteger(dimension = +dimension) || dimension <= 1){//если длина доски не является допустимым значением
так, теперь неплохо)) но до этого у тебя было предусмотрена работа с дробными числами - сейчас уже нет)) тебе нужно решить, как с ними поступить: либо не пропускать - это isInteger, либо обрезать до целого -  это parseInt. + добавим на это тест))

2024-02-14 07:18 UTC, AnnSkay commented on source/chess.js
> +    let board = '', invert = 0, i = 0//здесь invert - смещение для новой строки
ай ай ай)) не надо за ревьюера резолвить обсуждение)) я же должна проверить, исправил ли ты это))

вот тут ты на 15-16 строчках опять сделал цепочку объявлений))

2024-02-14 07:33 UTC, AnnSkay commented on source/chess.js
> +        isOdd = Number(dimension % 2 === 1);
смотри, сейчас isOdd объявлена через let. Какое другое объявление в данном случае лучше использовать и почему))

2024-02-14 07:33 UTC, AnnSkay commented on source/chess.js
> +    board = (board + '*'.repeat(isOdd) + '\n' + board.split('').reverse().join('') +
Теперь мы обошлись без циклов - это круто)) Но давай сделаем с этой длинной страшной операцией кое-что:
1. Вынесем в константы вне фукнции символы звездочки, конца строки и пробела) Сразу скажу - хорошая практика называть константы - upper case + snake case. Почему?) Если нам, например, понадобится заменить звездочку на другой символ, нам надо будет ходить по всему файлу и искать все места. А с константами нам нужно будет изменить только в одном месте))
2.  Разделим строчку на блоки и повыносим смысловые составляющие в отдельные переменные - сейчас очень сложно прочитать эту длинную строчку и понять, что тут происходит)) Просто сейчас кажется, что ты немного переборщил с количеством преобразований)

2024-02-14 07:33 UTC, AnnSkay commented on tests/chess.js
> +	QUnit.test('Шахматной доски [1, 2, 3] на [1, 2, 3] не бывает', function (assert) {
У тебя тут и ниже проверяется одинаковый тип данных - объекты) давай либо уберем одну из проверок, либо объединим их в одном тесте, назвав тест более конкретно))

2024-02-14 07:33 UTC, AnnSkay commented on tests/chess.js
> +	QUnit.test('Шахматной доски {name: "Alex"} на {name: "Alex"} не бывает', function (assert) {
И давай не будет в случаях проверки на невалидные данные подписывать в названии теста эти данные)) а если мы захотим добавить в этот тест еще одну проверку с объектом, то что нам надо будет тогда делать с названием) Это касается всех тестов, где ты так сделал) В случае проверок с числом - это уместно, а тут нет)

2024-02-14 07:36 UTC, AnnSkay commented on source/chess.js
> +        isOdd = Number(dimension % 2 === 1);
также. А зачем ты проверку приводишь к числовому типу?)). isOdd - это булеан, судя по названию) если тебе нужно число, значит и назвать нужно переменную соответствующе)

2024-02-14 16:31 UTC, Famelbyby commented on source/chess.js
Исправлено)

2024-02-14 16:33 UTC, Famelbyby commented on source/chess.js
> +    let board = '', invert = 0, i = 0//здесь invert - смещение для новой строки
Прошу прощения, мисклик)) Исправлено)

2024-02-14 16:35 UTC, Famelbyby commented on source/chess.js
> +    if (!Number.isInteger(dimension = +dimension) || dimension <= 1){//если длина доски не является допустимым значением
Исправлено)

2024-02-14 16:40 UTC, Famelbyby commented on source/chess.js
> +    board = (board + '*'.repeat(isOdd) + '\n' + board.split('').reverse().join('') +
Исправлено)

2024-02-14 16:41 UTC, Famelbyby commented on tests/chess.js
> +	QUnit.test('Шахматной доски {name: "Alex"} на {name: "Alex"} не бывает', function (assert) {
Исправлено)

2024-02-14 16:45 UTC, Famelbyby commented on source/chess.js
> +        isOdd = Number(dimension % 2 === 1);
Нужно использовать `const`, а не `let`. Лучше объявить константу, чтобы в будущем случайно не изменить её.

2024-02-14 16:46 UTC, Famelbyby commented on source/chess.js
> +        isOdd = Number(dimension % 2 === 1);
Исправлено)

2024-02-14 17:09 UTC, AnnSkay commented on source/chess.js
> +    let lines = "* ".repeat(dimension / 2);
"* " бы тоже вынести в константу)) и в идеале константы сделать таким образом, чтобы отсеживался смысл - поменял только в одном месте и все заработало))
```
const EOL = '\n';
const ASTRA = '*';
const SPACE = ' ';
const ASTRA_EOL = `${ASTRA}${EOL}`;
const SPACE_EOL = `${SPACE}${EOL}`;
const ASTRA_SPACE = `${ASTRA}${SPACE}`;
```

2024-02-14 17:12 UTC, AnnSkay commented on source/chess.js
> +    const isOdd = dimension % 2 === 1;
давай упростим)) % 2 возвращает либо 1 либо 0)) 1 - это всегда  true, 0 - false)

2024-02-14 18:14 UTC, Famelbyby commented on source/chess.js
> +    const isOdd = dimension % 2 === 1;
Исправлено)

2024-02-14 18:14 UTC, Famelbyby commented on source/chess.js
> +    let lines = "* ".repeat(dimension / 2);
Исправлено)

2024-02-14 18:14 UTC, Famelbyby commented on source/chess.js
> +    let reverse_line = lines.split('').reverse().join('');
Исправлено)

2024-02-15 06:34 UTC, AnnSkay commented on source/chess.js
> +    const isOdd = dimension % 2 === 1;
теперь осталось только последнее) мы опять вернулись к тому, что в переменной, по названию ожидающий булеан, хранится число)
Надо определиться:
1.   const isOdd = !!(dimension % 2);
2.   const remainder = dimension % 2;

Но первый способ выглядит поприятнее))

2024-02-15 08:50 UTC, Famelbyby commented on source/chess.js
> +    const isOdd = dimension % 2 === 1;
Исправлено)

2024-02-15 08:58 UTC, AnnSkay commented on source/chess.js
> +    let reversedLine = lines.split('').reverse().join('');
и последнее)) тут бы тоже поменять let - ты же не переприсваиваешь эту переменную))

2024-02-15 10:28 UTC, Famelbyby commented on source/chess.js
> +    let reversedLine = lines.split('').reverse().join('');
Исправлено)

2024-02-15 10:35 UTC, AnnSkay commented
Поздравляю, у тебя получилось классная реализация!)) Надеюсь, тебе помогли мои замечания, и ты все это будешь применять и дальше)

2024-02-15 23:18 UTC, DPeshkoff requested changes
Привет! Крутое решение, буквально одна минорная стилистическая правка)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:18 UTC, DPeshkoff commented on source/chess.js
> +'use strict'
Точку с запятой бы)

2024-02-16 08:52 UTC, Famelbyby commented on source/chess.js
> +'use strict'
Исправлено)

2024-02-17 09:49 UTC, DPeshkoff approved these changes

2024-02-17 09:49 UTC, closed without merging