Маленко Владимир
frontend-park-mail-ru/homework_2024_1 pull request #29
Opened 2024-02-11 22:40 UTC by vovangy

2024-02-12 09:21 UTC, AnnSkay commented
Вова, привет!)) Я Оля, сегодня-завтра я отпишусь по ревью :))
Если вдруг будут какие-то вопросы - пиши, не стесняйся в телегу https://t.me/annskay

2024-02-12 17:20 UTC, AnnSkay commented on source/roman.js
> +    while (number > 0) {
аж 3 уровня вложенности циклов) Я думаю, тут внешний цикл тебе не нужен, давай без него)

2024-02-12 17:20 UTC, AnnSkay commented on source/roman.js
> +        for (let convert of listWithConvertRomToDec) {
тут также давай через reduce попробуем)

2024-02-12 17:20 UTC, AnnSkay commented on source/roman.js
> +                number -= convert[0];
Тут то же замечание про "чистую функцию", что и в функции convertFromRomToDec)

2024-02-12 17:20 UTC, AnnSkay commented on source/roman.js
> +    if (typeof (number) !== "number" && typeof (number) !== "string") {
Это условие можно переписать с помощью одного встроенного метода)) Скажи, какого?)

2024-02-12 17:20 UTC, AnnSkay commented on source/roman.js
> +    if (isNaN(number)) {
а в чем различие между **isNaN** и **Number.isNaN** и почему ты использовал именно этот?)

2024-02-12 17:20 UTC, AnnSkay commented on source/roman.js
> +    return convertFromDecToRom(Number(number));
 в твоей реализации функции convertFromDecToRom нет необходимости делать преобразование в число) Но даже если оно бы тебе понадобилось, то лучше его делать внутри функции convertFromDecToRom, так как если мы допустим захотим эту функцию переиспользовать, то отдельно от фукнции roman она также должна уметь работать с числом в виде строки)

2024-02-12 17:20 UTC, AnnSkay commented on source/roman.js
> +    if (number > 3999 || number <= 0) {
Объясни, а почему ты решил выставить верхнее ограничение 3999, ведь в задании никаких ограничений нет?)

2024-02-12 17:20 UTC, AnnSkay commented on tests/roman.js
> +    QUnit.test('roman проверяет на корректный тип объекты', function (assert) {
а почему ты решил проверить только на объекты?) Ведь в js существуют и другие типы данных)

2024-02-12 17:20 UTC, AnnSkay commented on tests/roman.js
А ты проверял, что будет, если передать не целое число?)

2024-02-14 10:21 UTC, vovangy commented on tests/roman.js
Добавил проверку на целые числа в функцию convertFromDecimalToRoman

2024-02-14 10:22 UTC, vovangy commented on tests/roman.js
> +    QUnit.test('roman проверяет на корректный тип объекты', function (assert) {
Добавил тесты на undefined, boolean

2024-02-14 10:26 UTC, vovangy commented on source/roman.js
> +    return convertFromDecToRom(Number(number));
Теперь делаю преобразование в функции

2024-02-14 10:36 UTC, vovangy commented on source/roman.js
> +    if (isNaN(number)) {
Потому что, Number.isNan будет пытаться автоматически приводить к числу различные типы данных, например на строчку "m" он вернет false, как и на строчку "2", а просто isNaN не будет приводить

2024-02-14 10:38 UTC, vovangy commented on source/roman.js
> +    if (typeof (number) !== "number" && typeof (number) !== "string") {
Переписал на ['number', 'string'].includes(typeof number), который проверит нахождение названия типа в массиве

2024-02-14 10:38 UTC, vovangy commented on source/roman.js
> +                number -= convert[0];
Переделал

2024-02-14 10:38 UTC, vovangy commented on source/roman.js
> +        for (let convert of listWithConvertRomToDec) {
Переделал

2024-02-14 10:39 UTC, vovangy commented on source/roman.js
> +    while (number > 0) {
Цикла больше😔

2024-02-14 10:41 UTC, vovangy commented on source/roman.js
> +        while (number.toLowerCase().startsWith(convert[1].toLowerCase())) {
Переписал, используя match, правда как-то вяло выглядит, но надеюсь, я правильно понял

2024-02-14 10:42 UTC, vovangy commented on source/roman.js
> +    for (let convert of listWithConvertRomToDec) {
Переписал на reduce

2024-02-14 10:45 UTC, vovangy commented on source/roman.js
> +    if (!regex.test(number.toUpperCase())) {
Добавил выбрасывание исключений вместо null, теперь кейс с пустой строчкой учитывается💪

2024-02-14 10:46 UTC, vovangy commented on source/roman.js
> +    let regex = new RegExp(/^M{0,4}(CM|CD|D?C{0,4})(XC|XL|L?X{0,4})(IX|IV|V?I{0,4})$/);
Вынес объявление Регулярного выражения и также его переименовал
Объяснение регулярки:
/^ и $/ Начинать поиск с Начала и конца строки
M{0,4} - Может стоять от 0 до 4 символов M
(CM|CD|D?C{0,4}) - Может стоять либо "CM", либо "CD", либо (“D”, за которой следует от нуля до четырех символов “C”).
(XC|XL|L?X{0,4}) - Может стоять либо “XC“, либо “XL“, либо (“L”, за которой следует от нуля до четырех символов “X”).
(IX|IV|V?I{0,4}) - Может стоять либо “IX“, либо “IV“, либо (“V”, за которой следует от нуля до четырех символов “I”).

2024-02-14 10:47 UTC, vovangy commented on source/roman.js
> +const convertFromRomToDec = number => {
Все аргументы обернуты 👀

2024-02-14 10:48 UTC, vovangy commented on source/roman.js
> +const listWithConvertRomToDec = [[1000, "M"], [900, "CM"], [500, "D"], [400, "CD"], [100, "C"], [90, "XC"], [50, "L"], [40, "XL"], [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"]]
Теперь храню в массиве объекты с ключами romanValue и decimalValue

2024-02-14 10:55 UTC, vovangy commented on source/roman.js
> +            number = number.slice(convert[1].length);
Чистая функция - это функция, которая при одном и том же аргументе возвращает один и тот же результат, а также не имеет побочных эффектов, то есть не изменяет входные данные. Моя convertFromRomToDec изменяла, но больше не будет🥺 Переписал на чистую

2024-02-14 11:44 UTC, vovangy commented on source/roman.js
> +'use strict';
Честно говоря, даже не знаю зачем я ее вставил, наверное потому что делал на основе max.js. Непосредственно в интернете узнал, что она активирует строгий режим😳
1) Строгий режим превращает некоторые прощавшиеся ранее ошибки в исключения.
```javascript
'use strict';
a = 2; // Выбросит исключение, так как нет типа переменной
``` 
```javascript
a = 2; // а без 'use strict' об этой ошибке мы узнаем уже при использовании переменной
``` 
2) Любое присваивание, которое в обычном режиме завершается неудачей, в строгом режиме выбросит исключение
```javascript
'use strict'
var a = {};
Object.defineProperty(a, "x", { value: 1, writable: false });
a.x = 5; // TypeError 
// Без использования 'use strict' никаких исключений не вылетит 
``` 
3) В строгом режиме попытки удалить неудаляемые свойства будут вызывать исключения
4) Строгий режим требует, чтобы все свойства, перечисленные в сериализованном объекте, встречались только один раз
5) Cтрогий режим требует, чтобы имена аргументов в объявлении функций встречались только один раз
6) Cтрогий режим запрещает синтаксис восьмеричной системы счисления
7) Cтрогий режим запрещает использование with
8) Eval в строгом режиме не добавляет новых переменных в окружающий контекст
9) Cтрогий режим запрещает удаление простых имён
10) Ключевые слова eval и arguments не могут быть переопределены или изменены
11) и еще много чего другого

Если резюмировать то, он нужен для
1) Предотвращение ошибок
2) Улучшение безопасности
3) Улучшение производительности
4) Более четкий и понятный код
5) Подготовка к будущим версиям языка

2024-02-14 11:45 UTC, vovangy commented
Переписал код с учетом ваших комментариев

2024-02-14 11:47 UTC, AnnSkay commented on source/roman.js
> +const listWithConvertRomToDec = [[1000, "M"], [900, "CM"], [500, "D"], [400, "CD"], [100, "C"], [90, "XC"], [50, "L"], [40, "XL"], [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"]]
круть)) только давай эту константу тоже назовем по правилами, как ты назвал константу ниже)

2024-02-14 11:56 UTC, vovangy commented on source/roman.js
> +const listWithConvertRomToDec = [[1000, "M"], [900, "CM"], [500, "D"], [400, "CD"], [100, "C"], [90, "XC"], [50, "L"], [40, "XL"], [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"]]
Сделано

2024-02-14 11:57 UTC, AnnSkay commented on source/roman.js
> +    if (isNaN(number)) {
а может наоборот?)
Number.isNaN не приводит типы и проверяет только является ли это числом и одновременно  NaN, а вот isNaN заодно приводит к числу) Поэтому твой выбор в данном случае верен

2024-02-14 11:58 UTC, AnnSkay commented on source/roman.js
> +'use strict';
круто, молодец)

2024-02-14 12:00 UTC, AnnSkay commented on source/roman.js
> +    if (!regex.test(number.toUpperCase())) {
супер, теперь единственное - давай сократим запись `upperRomanNumber.length == 0`)

2024-02-14 12:00 UTC, AnnSkay commented on source/roman.js
> +    if (!regex.test(number.toUpperCase())) {
и заодно расскажи, чем строгое сравнение отличается от нестрого и почему лучше никогда не использовать нестрогое)

2024-02-14 12:02 UTC, AnnSkay commented on source/roman.js
1. далеко не везде исправлено)

2024-02-14 12:05 UTC, AnnSkay commented on source/roman.js
> +            number = number.slice(convert[1].length);
молодец))

2024-02-14 12:06 UTC, vovangy commented on source/roman.js
> +    if (!regex.test(number.toUpperCase())) {
Переделал на !upperRomanNumber.length

2024-02-14 12:07 UTC, AnnSkay commented on source/roman.js
> +        while (number.toLowerCase().startsWith(convert[1].toLowerCase())) {
ты все правильно понял и у тебя круто вышло))

2024-02-14 12:08 UTC, vovangy commented on source/roman.js
> +    if (!regex.test(number.toUpperCase())) {
Строгое сравнение еще сравнивает типы, а нестрогое будет пытаться привести к одному типу, следовательно возможна путаница, а со строгим непредвиденных ситуация быть не должно(точне меньше)

2024-02-14 12:20 UTC, AnnSkay commented on source/roman.js
> +    if (number > 3999 || number <= 0) {
хм, действительно)) видно римлянам хватало 3999. Конечно, можно пойти выше, но давай тогда остановимся на 3999, принцип то такой же))) но число 3999 - это же MMM.....
Почему тогда регулярка у тебя 4 цифры  M подряд разрешает?)

2024-02-14 12:21 UTC, AnnSkay commented on source/roman.js
> +    if (number > 3999 || number <= 0) {
смотри, iiii - мне кажется, баговый тест. Такого числа нет - это число iv. Давай испрвим этот тест и напишем правильную регулярку))

2024-02-14 12:21 UTC, vovangy commented on source/roman.js
Вроде сейчас исправил

2024-02-14 12:25 UTC, AnnSkay commented on source/roman.js
только давай еще на 38 строчке пробел перед  let  поставим) мне кажется, там его не достает)

2024-02-14 12:25 UTC, vovangy commented on source/roman.js
> +    if (number > 3999 || number <= 0) {
Разрешает, потому что так и не понял как правильно(В предоставленных тестах есть кейс с 'iiii'), поэтому оставил совместимость с четырьмя, но для конвертации из целых чисел у меня строго до 4000

2024-02-14 12:27 UTC, vovangy commented on source/roman.js
Добавил

2024-02-14 12:28 UTC, vovangy commented on source/roman.js
> +    if (number > 3999 || number <= 0) {
Сообщение про баговый тест пришло с задержкой, сейчас исправлю

2024-02-14 12:30 UTC, vovangy commented on source/roman.js
> +    if (number > 3999 || number <= 0) {
Исправлено

2024-02-14 12:31 UTC, AnnSkay commented on source/roman.js
> +    let regex = new RegExp(/^M{0,4}(CM|CD|D?C{0,4})(XC|XL|L?X{0,4})(IX|IV|V?I{0,4})$/);
просто замечательно - респект)

2024-02-14 12:40 UTC, vovangy commented on source/roman.js
> +    if (isNaN(number)) {
Понял

2024-02-14 12:43 UTC, AnnSkay commented on tests/roman.js
> +		assert.throws(() => {roman(0)}, RangeError);
а раз уж мы так круто везде обработали ошибки, давай в тестах проверять текст ошибки, а не просто, что выбросится ошибка))

P.S. отдельный респект за то, что выбрал такой тип ошибок, а не просто new Error)

2024-02-14 12:43 UTC, AnnSkay commented on source/roman.js
> +  const romanNumber = LIST_WITH_CONVERTION_ROMAN_AND_DECIMAL.reduce(
давай еще тут и в функции convertFromRomanToDecimal сразу будем возвращать результат reduce) зачем нам создавать лишнюю переменную, которую мы потом ниже сразу возвращаем)

2024-02-14 12:43 UTC, AnnSkay commented on source/roman.js
> +      let checkOnStartRegex = new RegExp(
поменяем на другое объявление?) на 52, 53 тоже))

2024-02-14 13:01 UTC, vovangy commented on source/roman.js
> +  const romanNumber = LIST_WITH_CONVERTION_ROMAN_AND_DECIMAL.reduce(
Сделал

2024-02-14 13:02 UTC, vovangy commented on tests/roman.js
> +		assert.throws(() => {roman(0)}, RangeError);
Теперь сравниваю с ошибкой,  у которой переопределил message

2024-02-14 13:02 UTC, AnnSkay commented on source/roman.js
> +      let checkOnStartRegex = new RegExp(
не, с названиями было все норм)) в объявлении дело - какие вообще есть виды объявлений переменных?)

2024-02-14 13:03 UTC, AnnSkay commented on tests/roman.js
> +		assert.throws(() => {roman(0)}, RangeError);
прям супер код получается)) ток давай тут тоже объявление переменных ошибок поменяем))

2024-02-14 13:05 UTC, vovangy commented on source/roman.js
> +      let checkOnStartRegex = new RegExp(
var, let, const
var - глобальная область видимости
let - блочная область видимости
const - блочная область видимости, значение не изменяется

2024-02-14 13:08 UTC, vovangy commented on tests/roman.js
> +		assert.throws(() => {roman(0)}, RangeError);
Сделано

2024-02-14 13:08 UTC, vovangy commented on source/roman.js
> +      let checkOnStartRegex = new RegExp(
Исправлено

2024-02-14 13:14 UTC, AnnSkay commented
Ну что ж, поздравляю! У тебя получилось решение, достойное большого лайка от меня)) Надеюсь, тебе помогли мои замечания, и ты все это будешь применять и дальше)

2024-02-15 23:40 UTC, DPeshkoff requested changes
Привет! Крутое решение, но есть вопрос по IIII)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:40 UTC, DPeshkoff commented on tests/roman.js
> +		assert.strictEqual(roman('iii'), 3);
Погоди, а почему тут так? 

Это не ошибка, это валидная запись:

![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/25efac2d-fc54-4cb5-a18a-ecee6ae83c96)

2024-02-16 04:55 UTC, vovangy commented on tests/roman.js
> +		assert.strictEqual(roman('iii'), 3);
Списывался с ментором по этому вопросу(можно посмотреть в resolve), что есть ограничение на 4 подряд символа в Римской записи, поэтому решили поправить тесты и регулярку(Изначально она у меня проверяла на 4 символа). Могу вернуть обратно(Для этого мне нужно просто в регулярке 3 на 4 поменять)

2024-02-16 04:58 UTC, vovangy commented on tests/roman.js
> +		assert.strictEqual(roman('iii'), 3);
Короче вернул поддержку четырех символов и тест вернул

2024-02-16 06:41 UTC, AnnSkay commented on tests/roman.js
> +		assert.strictEqual(roman('iii'), 3);
а разве число 4 пишется не как  IV?) IIII - это же исключение только на часах, но именно в переводе -эт о IV)

2024-02-17 09:51 UTC, DPeshkoff commented on tests/roman.js
> +		assert.strictEqual(roman('iii'), 3);
Ну вообще оно должно поддерживать и IV, и IIII)

2024-02-17 09:52 UTC, DPeshkoff approved these changes

2024-02-17 09:52 UTC, closed without merging