Михалёв Ярослав
frontend-park-mail-ru/homework_2024_1 pull request #3
Opened 2024-02-09 21:29 UTC by YarikMix

2024-02-10 10:22 UTC, AnnSkay commented
Привет! Я Оля, в этом задании буду твоим ревьюером :))

2024-02-10 11:16 UTC, AnnSkay commented on source/inverse.js
> +    let arr2 = numbers.slice(pos, numbers.length)
Названия переменных, как и любые другие названия лучше также не сокращать и называть более понятно. Почему? Представь, твой код будет использовать другой член команды, ему придется более глубоко вникать в строчки кода, чтобы понять, что тут происходит, так как название arr2 не отражает того, что лежит в этом переменной

2024-02-10 11:16 UTC, AnnSkay commented on source/inverse.js
> +    return pos >= 0 ? [...arr1, ...arr2.reverse()] : [...arr1.reverse(), ...arr2]
Также у меня к тебе предложение, раз ты так быстро справился с заданием) Твою реализацию можно сделать лучше - а именно избавиться от двойного склеивания массивов, а обойтись в конце всего одним. Плюс при значении позиции 0, можно избавиться от необходимости копирования частей массива и их склеивания, что улучшит производительность, использование памяти и добавит тебе мой респект и уважуху))

2024-02-10 11:16 UTC, AnnSkay commented on tests/inverse.js
> +	QUnit.test('Дополнительные тесты', function (assert) {
При написании тестов, лучше их называть более конкретно (см тесты выше уже написанные).  Так тебе и, возможно, другим членам команды потом будет легче в них ориентироваться и расширять)

2024-02-10 11:16 UTC, AnnSkay commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 1, 1, 1, 1 ], 1), [ 1, 1, 1, 1, 1 ]);
этот тест не несет в себе ничего нового - этот кейс уже обработан выше)

2024-02-10 11:16 UTC, AnnSkay commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 'a', 5, null, false, 10 ], -2), [ null, 5, 'a', false, 10 ]);
тут также - нет необходимости в этом тесте)

2024-02-10 11:16 UTC, AnnSkay commented on tests/inverse.js
> +	QUnit.test('Дополнительные тесты', function (assert) {
Советую тебе еще раз посмотреть на тесты выше и найти такие кейсы, которые не покрываются уже предоставленными тестами) Как я писала выше про обработку невалидных данных - вот пример необработанного момента тестами))

2024-02-10 11:18 UTC, AnnSkay commented on source/inverse.js
> +'use strict';
Ты решил добавить эту строчку - расскажи, пожалуйста, почему и зачем она нужна)

2024-02-10 11:48 UTC, AnnSkay commented on source/inverse.js
> +
Также давай поправим код стайл, чтобы у нас был красивый код)) 
1. В конце строки должна стоять ';'
2. Отсутствует пустая строка в конце файла (зачем она можешь почитать тут - https://qna.habr.com/q/1094540)
3. Смысловые блоки надо разделять отступами, например, между 5 и 6 строчкой.

Вот держи ссылочку на хорошую практику написания кода - https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2024-02-10 12:02 UTC, YarikMix commented on source/inverse.js
> +const inverse = (numbers, pos=0) => {
Плохая практика, сокращать переменные - потому что не отражает смысла переменной и потом можно запутаться

2024-02-10 12:03 UTC, YarikMix commented on source/inverse.js
> +    let arr1 = numbers.slice(0, pos)
let можно заменить на const, потому что в дальнейшем эта переменная не изменяется

2024-02-10 12:05 UTC, YarikMix commented on source/inverse.js
> +    return pos >= 0 ? [...arr1, ...arr2.reverse()] : [...arr1.reverse(), ...arr2]
Спред заменил на Array.concat

2024-02-10 12:06 UTC, YarikMix commented on source/inverse.js
> +    return pos >= 0 ? [...arr1, ...arr2.reverse()] : [...arr1.reverse(), ...arr2]
Concat и spread отличаются, когда аргумент не является массивом.
Concat добавляет его целиком в то время как ... пытается преобразовать его к массиву
`
a = [1, 2, 3]
x = 'hello';

console.log(a.concat(x));  // [ 1, 2, 3, 'hello' ]
console.log([...a, ...x]); // [ 1, 2, 3, 'h', 'e', 'l', 'l', 'o' ]
`

2024-02-10 12:10 UTC, AnnSkay commented on source/inverse.js
> +    let arr1 = numbers.slice(0, pos)
а если бы мы добавляли или удаляли что-то из массива, как бы ты объявил переменную?)

2024-02-10 12:14 UTC, AnnSkay commented on source/inverse.js
> +    return pos >= 0 ? [...arr1, ...arr2.reverse()] : [...arr1.reverse(), ...arr2]
молодец! Круто, что у тебя присутствует навык поиска нужной информации в интернете) Ведь одно и ключевых навыков разработчика, как ни странно, умение гуглить, ибо какой бы крутой разраб ни был, он не может знать всего)

2024-02-10 12:14 UTC, YarikMix commented on source/inverse.js
> +'use strict';
"use strict" - это установка, которая заставляет код обрабатываться в строгом режиме

Строгий режим нужен, чтобы:
- некоторые ошибки можно найти быстрее,
- более опасные и не полезные черты JavaScript либо запрещены, либо приводят к ошибке

[Отличия строго режима от обычного](https://ru.stackoverflow.com/questions/435546/%D0%A7%D1%82%D0%BE-%D0%B7%D0%BD%D0%B0%D1%87%D0%B8%D1%82-use-strict)

2024-02-10 12:16 UTC, AnnSkay commented on source/inverse.js
> +'use strict';
А можешь попробовать своими словами привести пример строчки кода, поведение которой будет отличаться в зависимости от установки стрикт режима?)

2024-02-10 12:31 UTC, YarikMix commented on source/inverse.js
> +    let arr1 = numbers.slice(0, pos)
Тоже можно const прописать. Я вспомнил, let позволяет переприсвоить значение переменной, а const - нет

2024-02-10 12:39 UTC, YarikMix commented on source/inverse.js
> +'use strict';
Например, в строгом режиме нельзя присваивать значение в неопределённую переменную.
В неограниченном режиме создается глобальная переменная.
![Screenshot_1](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/43493788/d02f2645-b0ef-4618-b3eb-3aca02ad55aa)
![Screenshot_2](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/43493788/ec40007e-9126-48d3-be3e-638693e0bad0)

2024-02-10 12:40 UTC, YarikMix commented on tests/inverse.js
> +	QUnit.test('Дополнительные тесты', function (assert) {
Поправил тесты

2024-02-10 12:55 UTC, AnnSkay commented on source/inverse.js
> +    let arr1 = numbers.slice(0, pos)
правильно) Но когда мы делаем например array.push('1'). Мы же не переприсваиваем значение переменной. Почему тогда мы и в этом случае оставляем const?)

2024-02-10 12:57 UTC, AnnSkay commented on source/inverse.js
> +'use strict';
отлично, даже со скринами - ставлю лайк)

2024-02-10 13:10 UTC, AnnSkay commented on source/inverse.js
> +        return false;
false - не совсем хороший тригер. Лучше ошибку или в крайнем случае null

2024-02-10 13:23 UTC, AnnSkay commented on source/inverse.js
> +    position >= 0 ? array2.reverse() : array1.reverse();
у тебя выше уже проверяется position на 0.  Значит на этой строчке можно не включать 0 в условие, а просто писать ">"

2024-02-10 13:36 UTC, AnnSkay commented on tests/inverse.js
> +	QUnit.test('В функцию передан не массив', function (assert) {
хороший тест) но можно добавить еще - у нас же аргументов у функции 2) Да, slice не упадет при невалидном position. Но разве нас устраивает, что например, с агрументом position = [] мы получим тот же результат, что и при 0)

2024-02-10 14:08 UTC, YarikMix commented on source/inverse.js
> +    let arr2 = numbers.slice(pos, numbers.length)
Если так называть переменные, то когда проект разрастется, можно выстелить себе в ногу :)

2024-02-10 14:09 UTC, YarikMix commented on source/inverse.js
> +
1. Исправил
3. Исправил

2024-02-10 14:10 UTC, YarikMix commented on source/inverse.js
> +        return false;
Заменил на null

2024-02-10 14:10 UTC, YarikMix commented on source/inverse.js
> +    position >= 0 ? array2.reverse() : array1.reverse();
Исправил

2024-02-10 14:11 UTC, YarikMix commented on tests/inverse.js
> +	QUnit.test('В функцию передан не массив', function (assert) {
Добавил тесты на проверку типа второго аргумента и проверку вызова функции без аргументов

2024-02-10 14:11 UTC, YarikMix commented on .idea/.gitignore
> +# Default ignored files
Удалил

2024-02-10 14:19 UTC, YarikMix commented on source/inverse.js
> +    let arr1 = numbers.slice(0, pos)
Может быть потому что использовать const - хороший тон?)

2024-02-10 14:33 UTC, AnnSkay commented on source/inverse.js
> +    let arr1 = numbers.slice(0, pos)
ахахах, не, с объявлением переменных хороший тон не работает)) суть в различиях между примитивными и ссылочными типами данных) и что изменения в ссылочных не приводят к изменению значения переменной, так как она хранит не само значение, а ссылку на нее)

2024-02-10 14:35 UTC, AnnSkay commented on source/inverse.js
> +    let arr2 = numbers.slice(pos, numbers.length)
не совсем тебя поняла)) как "так" - непонятно или понятно?)

2024-02-10 14:37 UTC, YarikMix commented on source/inverse.js
> +    let arr2 = numbers.slice(pos, numbers.length)
Я имею в виду, коротко, по типу arr1 и arr2

2024-02-10 14:43 UTC, AnnSkay commented on source/inverse.js
> +    let arr2 = numbers.slice(pos, numbers.length)
array1 и array2 - тоже не очень понятно)) нужно называть по тому смыслу, что там хранится)

2024-02-10 14:44 UTC, AnnSkay commented on source/inverse.js
> +
2 не исправлено((

2024-02-10 14:58 UTC, YarikMix commented on source/inverse.js
> +    let arr2 = numbers.slice(pos, numbers.length)
Изменил на partBeforePosition и partAfterPosition

2024-02-10 14:58 UTC, YarikMix commented on source/inverse.js
> +
Пустая строка в конце файла такая должна быть?
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/43493788/d8157d08-0b56-4b8c-9e32-a90c9f93d91f)

2024-02-10 15:19 UTC, AnnSkay commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], "a"), null);
Добавь проверки для всех типов данных, чтобы тебе было легче понимать, что ты все предусмотрел)

2024-02-10 15:27 UTC, YarikMix commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], "a"), null);
Добавил проверку второго аргумента на NaN и еще пару тестов

2024-02-10 15:35 UTC, AnnSkay commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], "a"), null);
ты немного перепутал типа данных и написал дубли тестов)) см https://developer.mozilla.org/ru/docs/Web/JavaScript/Data_structures

2024-02-10 15:35 UTC, AnnSkay commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], "a"), null);
[] и {}  - это одно и то же по типу)

2024-02-10 15:43 UTC, YarikMix commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], "a"), null);
Убрал лишний тест

2024-02-12 15:08 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-12 15:08 UTC, DPeshkoff commented on source/inverse.js
> +const inverse = (array, position = 0) => {
Давай добавим JSDOC

2024-02-12 15:08 UTC, DPeshkoff commented on source/inverse.js
> +    if (Number.isNaN(position) || typeof(position) !== 'number') {
А чем isNaN отличается от Number.isNaN?

2024-02-13 12:51 UTC, YarikMix commented on source/inverse.js
> +    if (Number.isNaN(position) || typeof(position) !== 'number') {
В отличие от глобальной функции isNaN(), Number.isNaN() не имеет проблемы принудительного преобразования параметра в число. Это значит, что в него безопасно передавать значения, которые обычно превращаются в NaN, но на самом деле NaN не являются. Также это значит, что метод возвращает true только для числовых значений, имеющих значение NaN.

Примеры
```
Number.isNaN(NaN); // true
Number.isNaN(Number.NaN); // true
Number.isNaN(0 / 0); // true

// При использовании глобальной функции isNaN() это всё будет true
Number.isNaN("NaN"); // false
Number.isNaN(undefined); // false
Number.isNaN({}); // false
Number.isNaN("blabla"); // false
```

2024-02-13 13:03 UTC, YarikMix commented on source/inverse.js
> +const inverse = (array, position = 0) => {
Добавил

2024-02-13 21:56 UTC, closed without merging