Могилевский Артём
frontend-park-mail-ru/homework_2024_1 pull request #30
Opened 2024-02-11 22:43 UTC by mvp-mogila

Могилевский Артём, вариант 19

2024-02-12 07:40 UTC, johnSamilin commented
Привет!
Меня зовут Саша, я проверю ПР в ближайшее время и оставлю комментарии, если это потребуется. Если возникнут вопросы ты всегда можешь написать мне в тг: @WatasheeBaka

2024-02-13 07:04 UTC, johnSamilin requested changes

2024-02-13 07:04 UTC, johnSamilin commented on source/sorting.js
> +    while (i < left.length && j < right.length) {
кажется, что тут два избыточных цикла. сделай, пожалуйста, так, чтобы их не было

2024-02-13 07:04 UTC, johnSamilin commented on source/sorting.js
> +function merge(left, right, prop) {
нужно написать jsdoc на функции

2024-02-13 07:04 UTC, johnSamilin commented on source/sorting.js
> +    let result = [];
а почему result объявлена как let?

2024-02-13 07:04 UTC, johnSamilin commented on source/sorting.js
> +    if (properties.length && array.length) {
а что если `array` окажется не массивом, а объектом или чем-то еще?

2024-02-13 07:04 UTC, johnSamilin commented on tests/sorting.js
> +	QUnit.test('sorting не сортирует по несуществующим полям', function (assert) {
нужно добавить тесты на неправильные входные данные

2024-02-13 14:45 UTC, mvp-mogila commented on source/sorting.js
> +        for (let prop of properties.reverse()) {
костыль под тест, потому что сортировка с конца параметров происходит

2024-02-13 19:21 UTC, mvp-mogila commented on tests/sorting.js
> +	QUnit.test('sorting не сортирует по несуществующим полям', function (assert) {
добавил

2024-02-13 19:21 UTC, mvp-mogila commented on source/sorting.js
> +    if (properties.length && array.length) {
добавил проверку на это, иначе условие просто не выполнится и вернется исходный аргумент

2024-02-13 19:21 UTC, mvp-mogila commented on source/sorting.js
> +function merge(left, right, prop) {
добавил описание

2024-02-13 19:22 UTC, mvp-mogila commented on source/sorting.js
> +    while (i < left.length && j < right.length) {
избавился от циклов, заменил на slice

2024-02-13 19:22 UTC, mvp-mogila commented on source/sorting.js
> +            array = mergeSort(array, prop);
поправил

2024-02-13 19:44 UTC, mvp-mogila commented on source/sorting.js
> +        for (let prop of properties.reverse()) {
переписал с помощью reduce, но оставил reverse

2024-02-13 20:22 UTC, johnSamilin requested changes

2024-02-13 20:22 UTC, johnSamilin commented on source/sorting.js
> +    let result = [];
а где происходит ее переприсваивание?

2024-02-13 20:22 UTC, johnSamilin commented on source/sorting.js
> +        result = properties.reverse().reduce((result, prop) => mergeSort(result, prop), array);
лучше не использовать конфликтующих имен переменных. у тебя уже есть result, содержащий финальный результат. первый аргумент reduce - это промежуточный

2024-02-13 20:22 UTC, johnSamilin commented on tests/sorting.js
> +		assert.deepEqual(actual, expected);
а как sorting отсортирует такой массив: `[
{ prop1: 'foo' },
{ prop1: 'bar', prop2: 1 },
null,
{ prop1: [] },
]`?

2024-02-14 16:57 UTC, mvp-mogila commented on source/sorting.js
> +        result = properties.reverse().reduce((result, prop) => mergeSort(result, prop), array);
поправил

2024-02-15 23:23 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:23 UTC, DPeshkoff commented on source/sorting.js
> +function sorting(array, properties) {
Чем обычные функции отличаются от стрелочных? Почему тут так?

2024-02-15 23:23 UTC, DPeshkoff commented on source/sorting.js
> +        let rightPart = mergeSort(array.slice(halfLen), prop);
Точно let? Разве где-то меняем?

2024-02-15 23:23 UTC, DPeshkoff commented on source/sorting.js
> +    }
Происходят страшные вещи, хочу пояснений, почему так и можно ли оптимизировать)

2024-02-15 23:23 UTC, DPeshkoff commented on source/sorting.js
> +'use strict';
Что делает эта строчка?

2024-02-15 23:23 UTC, DPeshkoff commented on source/sorting.js
> +}
\n

2024-02-15 23:23 UTC, DPeshkoff commented on tests/sorting.js
> +		let expected = [{'key': 'value'}];
А тут меняется?)

2024-02-16 14:43 UTC, mvp-mogila commented on tests/sorting.js
> +		let expected = [{'key': 'value'}];
меняется, здесь несколько тесткейсов в один тест помещены, чтобы разные входные данные проверить

2024-02-16 14:43 UTC, mvp-mogila commented on source/sorting.js
> +}
добавил

2024-02-16 14:43 UTC, mvp-mogila commented on source/sorting.js
> +        let rightPart = mergeSort(array.slice(halfLen), prop);
поправил

2024-02-16 14:49 UTC, mvp-mogila commented on source/sorting.js
> +function sorting(array, properties) {
Отличия стрелочной функции от обычной в том, что в стрелочной нельзя использовать this, обращаться к arguments, создавать ее через new. В моей программе реализовано обычным способом, потому что так привычней

2024-02-16 14:52 UTC, mvp-mogila commented on source/sorting.js
> +    }
Сначала проверяется, что объекты в принципе существуют, затем, если это объект, проверяется наличие в нем заданного свойства, по которому происходит сортировка. Если условие не выполняется, то возвращается null, который потом трактуется как ошибка и исходный массив не меняется. С 18 строки происходит слияние двух массивов в соответствии с алгоритмом мортировки слиянием.

2024-02-17 09:59 UTC, DPeshkoff commented on source/sorting.js
> +function sorting(array, properties) {
Давай стрелочную)

2024-02-17 09:59 UTC, DPeshkoff commented on source/sorting.js
> +    }
А если [так](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty)?

2024-02-17 10:00 UTC, DPeshkoff commented on source/sorting.js
> +'use strict';
Какие ограничения?

2024-02-17 10:01 UTC, DPeshkoff requested changes

2024-02-17 10:01 UTC, DPeshkoff commented on tests/sorting.js
> +		let expected = [{'key': 'value'}];
Кажется, что тесткейсам лучше быть независимыми -  давай разнесем (или будем создавать новые переменные)

2024-02-18 12:43 UTC, mvp-mogila commented on tests/sorting.js
> +		let expected = [{'key': 'value'}];
разделил

2024-02-18 12:53 UTC, mvp-mogila commented on source/sorting.js
> +    }
изменил, но мне кажется, первый способ нагляднее

2024-02-18 12:53 UTC, mvp-mogila commented on source/sorting.js
> +function sorting(array, properties) {
переделал

2024-02-18 16:08 UTC, DPeshkoff approved these changes

2024-02-18 16:08 UTC, closed without merging