Черников Артём
frontend-park-mail-ru/homework_2024_1 pull request #32
Opened 2024-02-11 22:53 UTC by FunnyRockfish

2024-02-12 09:04 UTC, Zela2520 commented
Тёма, привет )
Меня зовут Даня, буду проверять твоё дз. В течение дня выполню проверку.

2024-02-12 09:10 UTC, FunnyRockfish commented
> Тёма, привет ) Меня зовут Даня, буду проверять твоё дз. В течение дня выполню проверку.

Спасибо, буду ждать)

2024-02-12 10:28 UTC, Zela2520 commented on source/filter.js
> +function filter(input, allowedTags) {
Давай будем использовать arrow function. Почитай и расскажи в чём разница между arrow function и function declaration :)

2024-02-12 10:30 UTC, Zela2520 commented on source/filter.js
> +        if (allowedTags.includes(tag.toLowerCase())) {
посмотри в сторону структур данных, подумай какую структуру ты можешь использовать здесь.

2024-02-12 10:30 UTC, Zela2520 commented on source/filter.js
> +        return text.replace(/[&<>"']/g, function (m) {
arrow function

2024-02-12 10:37 UTC, Zela2520 commented on source/filter.js
> +    function escapeHtml(text) {
Ты вот уже второй кто так функцию называет, может я не прав конечно, но как по мне назвать функцию makeHtmlSave || deleteHtmlUnsafeCharacters конкретнее. Аргумент точно стоит переименовать.

Вы сейчас пишите утилиты. Они глобально будет переиспользоваться вашими сокомандниками в проектах. Открыв функцию для меня было бы неочевидно: что она делает ? что она принимает ? 

Поскольку это не ts, который даёт нам с помощью типов добавлять описание и ясность того что функция принимает, что функция возвращает, для чего вообще нужна - добавь jsdoc. 

На первых этапах проекта, пока не начнёте на typescript-е писать будет использовать jsdoc для того чтобы легче понимать для чего нужна та или иная утилита.

2024-02-12 10:38 UTC, Zela2520 commented on source/filter.js
> +        const map = {
Map это хорошо, молодец )

2024-02-12 10:40 UTC, Zela2520 commented on source/filter.js
> +    //Регулярное выражение для поиска тегов (придумал не сам, ещё не проходили регулярки)
комменты надо убрать будет

2024-02-12 10:43 UTC, Zela2520 commented on source/filter.js
> +    let marker = '___HTML_TAG_MARKER___';
почему использовал let, а не const расскажи в чём разница между ними ? Какие ещё способы объявления переменной бывают в js ? Как интерпретатор js обрабатывает переменные объявленные с помощью (let, const, var) ?

2024-02-12 10:44 UTC, Zela2520 commented on source/filter.js
> +    let tagMap = {};
Почему использовал let ? Каким образом в js происходит сравнение примитивных типов и объектов ?

2024-02-12 10:44 UTC, Zela2520 commented on source/filter.js
> +        } else {
else не надо

2024-02-12 10:48 UTC, Zela2520 commented on source/filter.js
> +    for (let key in tagMap) {
Какие ещё виды циклов есть в js ? Какие есть методы для работы с объектами, какие ты мог бы использовать  ?

2024-02-12 10:54 UTC, Zela2520 commented on source/filter.js
> +    function escapeHtml(text) {
escapeHtml - не зависит от функции filter. Отдельная утилита - не должно быть инкапсуляции. Ты вполне можешь её потенциально использовать где-то ещё - вынести.

2024-02-12 10:56 UTC, Zela2520 commented on source/filter.js
> +    const tagRegExp = /<\/?([a-zA-Z0-9]+)[^>]*>/g;
"ещё не проходили регулярки" - у тебя классная задача. Почитай и расскажи мне:
- что значит флаг g ?
- что значит символ /? 
- что значит конструкция [^>]* ?

2024-02-13 19:29 UTC, FunnyRockfish commented on source/filter.js
> +function filter(input, allowedTags) {
Исправил вообще весь код, совсем сделал всё по-другому. Та предыдущая версия ломалась на некоторых тестах и была вообще какая та мутная. Сделал так же и function declaration. Различаются они синтаксисом, arrow - стрелочная функция. Ещё прочитал, что отличается тем, что не имеет своего this и использует this контекста. Но я этим не пользовался, и пока не понял от этого плюсов.

2024-02-13 19:30 UTC, FunnyRockfish commented on source/filter.js
> +    function escapeHtml(text) {
Переименовал. Согласен, логичнее будет! Но пока jsdoc не сделал - до завтра будет

2024-02-13 19:32 UTC, FunnyRockfish commented on source/filter.js
> +        const map = {
Решил использовать map из за более высокой читабельности и понятности кода, хотя раньше map редко очень использовал)

2024-02-13 19:32 UTC, FunnyRockfish commented on source/filter.js
> +    //Регулярное выражение для поиска тегов (придумал не сам, ещё не проходили регулярки)
Убрал

2024-02-13 19:44 UTC, FunnyRockfish commented on source/filter.js
> +    let marker = '___HTML_TAG_MARKER___';
let - задаёт саму переменную, которую можно будет менять. А const - это константа, неизменяемая. Тут, на самом деле, можно было и const-ом объявить, но поставил let. 
Можно объявить с помощью let, const, var(устаревшее).  Как обрабатывает:
**var** - повторное объявление переменной с помощью var в той же области видимости не вызывает ошибку. Они видны во всей функции, в которой они были объявлены, и кроме того, они поднимаются наверх блока, т.е. можно обращаться к переменным до их объявления в коде (объявили снизу, использовали сверху). 
**let** - вилимы в одном блоке, повторно объявить с помощью let нельзя и наверх не поднимаються.
const - главная особенность - нельзя переприсвоить значение после объявления

2024-02-13 19:53 UTC, FunnyRockfish commented on source/filter.js
> +    for (let key in tagMap) {
Есть ещё while, do ... while, for ... of (для перебора эл-тов массив). Там по работе с объектами есть всякие разные действия - копирование, вренуть массив значений объекта, проверка на содержимое и ещё несколько. Я бы мог использовать проверку на содержимое, копирование возможно пригодилось бы тоже

2024-02-13 19:53 UTC, FunnyRockfish commented on source/filter.js
> +    function escapeHtml(text) {
Сделал

2024-02-13 19:59 UTC, FunnyRockfish commented on source/filter.js
> +    const tagRegExp = /<\/?([a-zA-Z0-9]+)[^>]*>/g;
Разобрался с регулярками.
g - global, то есть везде искать
/?  - "строки, в которых **возможно** будет /"
 [^>]* - отрицание содержания символа > (любой символ, кроме >) может повторяться 0 и более раз.

2024-02-14 07:25 UTC, Zela2520 commented on source/filter.js
> +    let tagMap = {};
В данном случае подойдет const. Скажи почему ? Каким образом в js происходит сравнение объектов ?

2024-02-14 07:56 UTC, Zela2520 commented on source/filter.js
>      return saveText(input, allowedTags, tagsMas);
Уверен, что тут не будет ошибки ? Если её нет, то странно. Чем ещё отличаются arrow function от function declaration ? 
Подсказка: посмотри в сторону хостинга

2024-02-14 07:59 UTC, Zela2520 commented on source/filter.js
>      const regex = new RegExp(`[&<>"'\\s]`, 'g');
Убрать переменную, ты её один раз используешь на 25 строке (запихни туда и всё, если больше нигде не нужна)

2024-02-14 07:59 UTC, Zela2520 commented on source/filter.js
>          } else {
else не надо

2024-02-14 08:00 UTC, Zela2520 commented on source/filter.js
>      for (let i = 0; i < openingTags.length; i++) {
Используй современные методы для работа с массивами. Если просто перебрать хочешь forEach, если хочешь изменить map.

2024-02-14 08:02 UTC, Zela2520 commented
Наверное, как-то неверно тебя направил первый раз ... 
Код очень сильно разросся - это плохо. Используешь cи стайл - есть встроенные методы массивов js, надо использовать их. Почитай про хостинг и чем опасно использование стрелочных функций до их объявления
Надо код сильно сократить и убрать лишнее)

2024-02-14 08:29 UTC, FunnyRockfish commented on source/filter.js
> +    let tagMap = {};
А, точно. Const был бы правильнее - так как они используются для хранения состояния и потом не изменяются. 
Сравнение объектов - сравнение если точное (===), то будут сравниваться ссылки (даже если содержимое одинаковое, а ссылки разные, то false). Если нужно сравнивать содержимое, то самому пройти по их содержимому и сравнить (посимвольно, например)

2024-02-14 08:31 UTC, FunnyRockfish commented on source/filter.js
>      return saveText(input, allowedTags, tagsMas);
Да, точно: стрелочные функции нельзя использовать в коде выше их инициализации. А я вызывал её в начале, а объявлял в конце. Действительно странно, что не было ошибки. Но в исправленном коде этот недостаток устранён

2024-02-14 08:31 UTC, FunnyRockfish commented on source/filter.js
>      const regex = new RegExp(`[&<>"'\\s]`, 'g');
Убрал

2024-02-14 08:33 UTC, FunnyRockfish commented on source/filter.js
>      for (let i = 0; i < openingTags.length; i++) {
Исправил, спасибо за замечание

2024-02-14 08:34 UTC, FunnyRockfish commented
> Наверное, как-то неверно тебя направил первый раз ... Код очень сильно разросся - это плохо. Используешь cи стайл - есть встроенные методы массивов js, надо использовать их. Почитай про хостинг и чем опасно использование стрелочных функций до их объявления Надо код сильно сократить и убрать лишнее)

Вроде бы учёл все твои пожелания, код удалось сократить почти на 20 строк! Постарался использовать стиль уже более JS-ный

2024-02-16 06:52 UTC, Zela2520 commented
Тём, смотри. 
Ты сильно поменял решение у меня заняло достаточное кол-во времени, чтобы в нём разобраться ) Это уже не есть хорошо. Много сишного стиля какого-то ) Давай попробуем всё-таки улучшить исходное решение.

2024-02-16 07:20 UTC, FunnyRockfish commented
> Тём, смотри. Ты сильно поменял решение у меня заняло достаточное кол-во времени, чтобы в нём разобраться ) Это уже не есть хорошо. Много сишного стиля какого-то ) Давай попробуем всё-таки улучшить исходное решение.

Залил новый код)

2024-02-16 07:51 UTC, Zela2520 commented on source/filter.js
> +const saveText = (text, allowedTags, tagIndexes) => {
Добавить jsdoc везде.

2024-02-16 07:51 UTC, Zela2520 commented on source/filter.js
> +    return text.replaceAll(/[&<>"'\s]/g, (match, index) =>
Давай используем replace. Возьмём все не безопасные символы и с помощью словаря, который содержит соответствия небезопасных символов и их безопасных эквивалентов выполним замену. Можно оставить checkIndex, конечно. Но будет выглядеть компактнее ) 

Подсказка: В callback-е у тебя есть match, достань поэтому ключу значение из словаря и будет выполнена замена как раз на безопасный символ :)

2024-02-16 07:51 UTC, Zela2520 commented on source/filter.js
> +        let flag = false;
Выглядит как костыль )
И не информативное название. Если флаг, то назови чтобы было понятно что за флаг )

2024-02-16 07:51 UTC, Zela2520 commented on source/filter.js
> +const filter = (input, allowedTags) => {
Давай попробуем упростить твоё решение )
1) предлагаю создать мапку из разрешённых тегов и пометить их как разрешённые )
2) предлагаю пройтись по html тескту по массиву и изменить соответствующие метки в соотвествии с определённой регулярной )
3) проверить является ли элемент тегом и является ли он разрешённым тегом -> вернуть если ок, если нет то сделать элемент текста безопасным

2024-02-17 10:23 UTC, Zela2520 reviewed
Хорошая работа !

Сложная реализация, но студент поработал с методами массивов, хорошо поработал с регулярными выражениями !)

Моё пожелания оптимизировать алгоритм + если возможно упростить решение, посмотрев в сторону другой структуры данных )

2024-02-17 10:23 UTC, Zela2520 commented on source/filter.js
> +        closingTags.push(match.index + tagName.length + 3); // Добавляем длину '</tagName>'.
3 - magic number, в константу

2024-02-17 10:28 UTC, Zela2520 commented on source/filter.js
> +    while ((match = openingTagRegex.exec(text)) !== null) {
посмотри в сторону использования Array.from

2024-02-17 10:50 UTC, FunnyRockfish commented on source/filter.js
> +    const tagsMas = [];
Вроде бы теперь исправил это, и также изменил на Array.from

2024-02-17 10:58 UTC, FunnyRockfish commented on source/filter.js
> +const findClosingTag = (text, tagName) => {
Я изменил на использование стека, код стал выглядеть понятнее и немного проще, спасибо) А саму структуру знаю, постарался реализовать в коде LIFO

2024-02-17 10:58 UTC, FunnyRockfish commented on source/filter.js
> +        closingTags.push(match.index + tagName.length + 3); // Добавляем длину '</tagName>'.
Сделано

2024-02-17 10:58 UTC, FunnyRockfish commented on source/filter.js
> +    while ((match = openingTagRegex.exec(text)) !== null) {
Сделано

2024-02-17 11:04 UTC, Zela2520 reviewed
Слушай, ну красота )
Я доволен, ты большой молодец )

Хорошо поработали !

2024-02-17 11:04 UTC, Zela2520 commented on source/filter.js
> +    return saveText(input, allowedTags, tagsMas);
перед return-ом пустую строку везде

2024-02-17 11:04 UTC, Zela2520 commented on source/filter.js
> +        return checkIndex(index, tagIndexes) ? match : replacement || match;
пустую строку перед return-ом

2024-02-17 12:31 UTC, FunnyRockfish commented on source/filter.js
> +    return saveText(input, allowedTags, tagsMas);
Сделано

2024-02-17 12:33 UTC, FunnyRockfish commented
> Слушай, ну красота ) Я доволен, ты большой молодец )
> 
> Хорошо поработали !

Спасибо большое! Благодарен тебе за комментарии и правки)

2024-02-18 17:07 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-18 17:07 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Здесь не нужно удалять старое, давай вернем, как было

2024-02-18 17:07 UTC, DPeshkoff commented on source/filter.js
> +function findClosingTag(text, tagName, allowedTags) {
Давай тут тоже стрелочную)

2024-02-18 17:07 UTC, DPeshkoff commented on source/max.js
Предлагаю вернуть)

2024-02-18 17:07 UTC, DPeshkoff commented on source/filter.js
> +/**
А в каком режиме работает код? Какие есть?

2024-02-18 17:44 UTC, FunnyRockfish commented on index.html
> -<script src="tests/max.js"></script>
Окей! Исправил

2024-02-18 17:44 UTC, FunnyRockfish commented on source/filter.js
> +function findClosingTag(text, tagName, allowedTags) {
Сделано

2024-02-18 17:44 UTC, FunnyRockfish commented on source/max.js
Вернул

2024-02-18 17:50 UTC, FunnyRockfish commented on source/filter.js
> +/**
Ой, забыл "use strict" - строгий режим, чтобы применить изменения (ES5) в старом коде. Когда включаем use strict, код работает в современном режиме. Ещё слушал про режим безопасного кода и режим модуля (для разработки больших приложений удобно)

2024-02-19 13:03 UTC, DPeshkoff requested changes

2024-02-19 13:03 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Не исправил(

![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/7d058a92-41d5-490a-b040-3809603d340b)

2024-02-19 13:03 UTC, DPeshkoff commented on source/filter.js
> +/**
А что еще делает use strict? Приведи примеры современного режима)

2024-02-19 13:03 UTC, DPeshkoff commented on source/max.js
> -
Тут изменения не нужны

2024-02-19 17:16 UTC, FunnyRockfish commented
Вроде бы исправил...У меня так отображалось
Вот про use strict:
Из основных:

Запрет использования необъявленных переменных
Запрет изменения аргументов и свойств функции arguments
Запрет удаления переменных, функций и функций-конструкторов
Запрет использования ключевых слов в качестве идентификаторов
Вроде бы всё

Немного примеров: 
```suggestion
/**"use strict";
let x = 10;
const y = 20;
```

```suggestion
/**"use strict";
var obj = {};
delete obj.property; // Ошибка: нельзя удалить свойство объекта в строгом режиме
```

```suggestion
/**"use strict";
eval("var x = 10;");
console.log(x); // Ошибка: x не определен
```

2024-02-19 17:17 UTC, DPeshkoff approved these changes

2024-02-19 17:17 UTC, FunnyRockfish commented
Все остальные правки внёс

2024-02-19 17:17 UTC, closed without merging