Nikitin Alexandr variant-6
frontend-park-mail-ru/homework_2024_1 pull request #34
Opened 2024-02-12 09:44 UTC by Olegsandrik

First homework. Ниже скриншот с тестами
![Снимок экрана от 2024-02-12 12-42-12](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/138722305/1b885ec8-766a-40aa-8d44-67c465137881)

2024-02-12 09:48 UTC, Zela2520 commented
Саша, привет )
Меня зовут Даня, буду проверять твоё дз. В течение дня выполню проверку.

При необходимости связаться со мной, пиши в тг: [Даня](https://t.me/Zela28)

2024-02-12 14:46 UTC, Zela2520 commented on source/tree.js
> +'use strict';
Для чего нужна эта строчка ?

2024-02-12 14:47 UTC, Zela2520 commented on source/tree.js
> +    if (number<3){
что будет если кто-то решит передать строку или объект ?

2024-02-12 14:49 UTC, Zela2520 commented on source/tree.js
> +    for (let i = 0; i < number-1; i++) {
Си стайл. Какие методы массивов ты знаешь ? Попробуй посмотреть [learn.js](https://learn.javascript.ru)
Выбери подходящий и напиши почему именно его ты выбрал.

2024-02-12 14:50 UTC, Zela2520 commented on source/tree.js
> +    answer+=' '.repeat(star/2-1) + '|' + ' '.repeat(star/2-1) + '\n'
Добавь пустую строку перед return-ом.

2024-02-12 14:54 UTC, Zela2520 commented on source/tree.js
> +    if (number<3){
этот if и if ниже можно объединить в одно условие

2024-02-12 15:02 UTC, Zela2520 commented on source/tree.js
> +        answer+=' '.repeat(number-2-i) +  '*'.repeat(star) + ' '.repeat(number-2-i) + '\n'
Здорово, используешь метод repeat )

2024-02-12 15:19 UTC, Zela2520 commented
Хорошее решение ) Ты молодец )

Жду исправлений !

2024-02-12 15:21 UTC, Zela2520 commented on tests/tree.js
> +	});
Добавь тесты на входные данные, тебе может прилететь не только число )

2024-02-14 08:52 UTC, Olegsandrik commented on source/tree.js
> +'use strict';
Директива строгого режима, которая позволяет находить ошибки кода

2024-02-14 08:52 UTC, Olegsandrik commented on source/tree.js
> +    if (number<3){
плохо, добавлю обработку, в случае, если не число

2024-02-14 08:59 UTC, Olegsandrik commented on source/tree.js
> +    for (let i = 0; i < number-1; i++) {
concat для объединения элементов, а не сложения строчек, как у меня

2024-02-14 08:59 UTC, Olegsandrik commented on source/tree.js
> +    answer+=' '.repeat(star/2-1) + '|' + ' '.repeat(star/2-1) + '\n'
Принял

2024-02-14 09:00 UTC, Olegsandrik commented on source/tree.js
> +    if (number<3){
Да, объединю три условия (проверка на число)

2024-02-14 09:00 UTC, Olegsandrik commented on tests/tree.js
> +	});
Да, хорошо

2024-02-15 20:56 UTC, Zela2520 reviewed
Good job ) Поправь и к главному ментору на суд :)

2024-02-15 20:56 UTC, Zela2520 commented on source/tree.js
>      for (let i = 0; i < number-1; i++) {
На самом деле, можно создать массив с помощью Array.from на месте с помощью отображающей функции. 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from

Потом можно было бы заспредить массив, который представляет строку дерева, сформировать валидную ёлку и потом заджоинить )

Почитай, поправь :) Это сократит код

2024-02-16 00:02 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-16 00:02 UTC, DPeshkoff commented on source/tree.js
> +'use strict';
А в чем именно он заключается?

2024-02-16 00:02 UTC, DPeshkoff commented on source/tree.js
> +    let star = 1
Не забывай про ;

2024-02-16 00:02 UTC, DPeshkoff commented on source/tree.js
> +    if (number<3 || number!=Math. trunc(number) || isNaN(number)){
Чем isNaN отличается от Number.isNaN?

2024-02-16 00:02 UTC, DPeshkoff commented on source/tree.js
> +const tree = function(number){
Почему function? Какие еще способы есть?

2024-02-16 00:02 UTC, DPeshkoff commented on tests/tree.js
> +QUnit.module('Тестируем функцию tree', function () {
Неправильно настроены ветки - поправь, пожалуйста. Это оригинальные тесты, а не добавленные - переключи на https://github.com/frontend-park-mail-ru/homework_2024_1/blob/variant-6

2024-02-16 11:08 UTC, Olegsandrik commented on source/tree.js
> +'use strict';
Строгий режим ошибки, которые могли быть не замечены, заменяет исключениями. А ещё позволяет использовать только ограниченный синтаксис, для того, чтобы упростить разработку

2024-02-16 11:13 UTC, Olegsandrik commented on source/tree.js
> +    if (number<3 || number!=Math. trunc(number) || isNaN(number)){
Одно является функцией, а второе является методом. Оба очень похожи, так как возвращают булевские значения.

2024-02-16 11:19 UTC, Olegsandrik commented on source/tree.js
> +const tree = function(number){
Мне кажется самой читабельной на ранних порах освоения JS. Есть ещё варианты: 1) const имяФункции = (параметры) => {  // тело функции}; 2)function имяФункции(параметры ) {//Телофункции};

2024-02-16 11:25 UTC, Zela2520 commented on source/tree.js
> +const tree = function(number){
Расскажи разницу между arrow function и function declaration ? Почитай как они себя ведут в процессе хостинга. Что такое процесс хостинг в js ?

2024-02-16 11:51 UTC, Olegsandrik commented on source/tree.js
>      for (let i = 0; i < number-1; i++) {
Можно, но не думаю, что это уже будет моё решение. Возьму на заметку этот метод, спасибо

2024-02-16 12:11 UTC, Olegsandrik commented on tests/tree.js
> +QUnit.module('Тестируем функцию tree', function () {
Изменил базу на 6 варик

2024-02-17 10:01 UTC, DPeshkoff commented on source/tree.js
> +    if (number<3 || number!=Math. trunc(number) || isNaN(number)){
Есть еще разница. Почитай, пожалуйста, и распиши)

2024-02-17 10:02 UTC, DPeshkoff commented on source/tree.js
> +const tree = function(number){
Давай запилим стрелочную функцию

2024-02-17 10:04 UTC, DPeshkoff commented on tests/tree.js
> +QUnit.module('Тестируем функцию tree', function () {
Давай перенесем твой код в ветку 6 варианта у тебя и заново запушим - можешь сам посмотреть на diff)

2024-02-18 07:54 UTC, Olegsandrik commented on source/tree.js
> +    if (number<3 || number!=Math. trunc(number) || isNaN(number)){
Number.isNaN() не имеет проблемы принудительного преобразования параметра в число, в то время как isNaN() может доставить проблем при преобразовании. Лучше юзать 1 вариант, щас переделаю

2024-02-18 07:54 UTC, Olegsandrik commented on source/tree.js
> +const tree = function(number){
Окей

2024-02-18 10:29 UTC, Olegsandrik commented on tests/tree.js
> +QUnit.module('Тестируем функцию tree', function () {
На локалке все сделал, теперь красивый дифф. Но потребовалось делать новый пул реквест, посмотри, пожалуйста) Делал все через консоль, но в итоге разобрался
Все корректировки твои я внес и запушил в новый. Этот не дал изменить мастер

2024-02-18 16:17 UTC, DPeshkoff commented
Уезжаем в #55

2024-02-18 16:17 UTC, closed without merging