Хоченков Алексей
frontend-park-mail-ru/homework_2024_1 pull request #35
Opened 2024-02-12 10:40 UTC by AlexKhochenkov

WEB-22.
Добавил функцию set и два теста к ней.

2024-02-12 14:28 UTC, rissenberg commented
Привет! Меня зовут Костя, я буду твоим проверяющим ментором по ДЗ0. Если возникнут вопросы, смело пиши в тг - @PassPort_Guardian, или в вк - @rissenberg

2024-02-12 15:15 UTC, rissenberg requested changes
Добавлю общее замечание по коду - лучше вокруго операторов ставить пробелы - например, писать так: let x = (y + 1) / 2; таким образом твой код не будет сливаться в одну неразборчивую строку и твоим ревьюверам и сокомандникам будет проще его читать

2024-02-12 15:15 UTC, rissenberg commented on source/set.js
> +    let attributes = path.slice(1).split('.');
Для массивов лучше используй не let, а const, небольшая статья на эту тему, если хочешь узнать как правильно объявлять переменные
https://t.me/makingweb/148
Для константных массивов будут доступны методы добавления, урезания длины и другие, так что функционал эта замена не уменьшит

2024-02-12 15:15 UTC, rissenberg commented on source/set.js
> +    for (let i=0; i < attributes.length; i++){
При итерации по массивам используй встроенные методы JS - например, .forEach(), подробнее о котором можешь почитать здесь
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2024-02-12 15:15 UTC, rissenberg commented on source/set.js
> +    for (let i=currentPath.length-1; i>=0; i--){
Аналогично предыдущему замечанию - но здесь нужно еще и реверснуть массив

2024-02-12 15:15 UTC, rissenberg commented on source/set.js
> +}
Пустая строчка в конце файла, не забывай)

2024-02-12 15:29 UTC, rissenberg requested changes

2024-02-12 15:29 UTC, rissenberg commented on source/set.js
> +
В задании так же просится написать JSDoc для твоей функции - это небольшая документация, которая определяет, как работает твоя функция, что принимает на вход и что возвращает. Более подробно можно прочитать здесь:
https://jsdoc.app/

2024-02-12 20:35 UTC, AlexKhochenkov commented on source/set.js
> +function set(objName={}, path, value){
Особенность стрелочной функции в том, что у неё нет this и arguments, что позволяет нам брать их из внешнего окружения. Например, это удобно в декораторах, когда нужно пробросить вызов с текущими this и arguments.

2024-02-12 20:40 UTC, AlexKhochenkov commented on source/set.js
> +'use strict';
'use strict' - это строгий режим. Он показывает, что скрипт работает в современном режиме. Раньше в языке некоторые возможности работали по другому. Потом в язык добавили новые возможности и переработали существующие. Чтобы старый код работал, по умолчанию включен старый режим. Для того, чтобы пользоваться современными возможностями, необходим 'use strict'.

2024-02-12 21:06 UTC, rissenberg requested changes
По коду почти все норм, в тестах, я думаю, не хватает кейсов с невалидными входными данными. Допиши их, и, если не будут обрабатываться корректно, добавь к основной функции проверку

2024-02-15 21:39 UTC, rissenberg requested changes
Нужно еще подправить

2024-02-15 21:39 UTC, rissenberg commented on source/set.js
> +    if (typeof objName !== 'object' || objName == null) {
C null лучше не сравнивать, пиши !objName

2024-02-15 21:39 UTC, rissenberg commented on source/set.js
> +        return 'ERROR: objName must be an object';
С одной стороны, при завершении работы функции с ошибкой можно возвращать какой-то особый флаг, но такие случаи иногда трудно обрабатывать - в твоем случае, для разных ошибок он вернет разные значения, и их дополнительно нужно будет обрабатывать там, где была вызвана функция. Лучше выброс ошибок сделать с помощью throw type error:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

2024-02-15 21:39 UTC, rissenberg commented on source/set.js
> +        return 'ERROR: objName must be an object';
Тогда тесты тоже нужно будет переписать, чтобы они не сравнивали возвращаемое значение, а выброшенную ошибку

2024-02-15 21:39 UTC, rissenberg commented on source/set.js
> +    if (typeof path !== 'string' || path[0] != '.') {
А здесь забыл строгое сравнение

2024-02-15 21:39 UTC, rissenberg commented on source/set.js
> + * @function
Можно еще @name добавить, так красивее

2024-02-15 21:44 UTC, rissenberg commented on source/set.js
> + * @function
И @description, 4 строчку в него переписать

2024-02-16 10:50 UTC, rissenberg approved these changes
Код теперь выглядит очень хорошо, осталось исправить совсем немного. Я предварительно поставлю допуск на проверку преподу, но перед ней замечания нужно исправить

2024-02-16 10:50 UTC, rissenberg commented on source/set.js
> +        throw new Error('ERROR: objName must be an object');
Лучше использовать тип TypeError - так информативнее

2024-02-16 10:50 UTC, rissenberg commented on source/set.js
> +}
Ну и здесь пустую строчку в конец файла. Для чего она нужна - читай здесь:
https://qna.habr.com/q/1094540

2024-02-18 16:11 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-18 16:11 UTC, DPeshkoff commented on source/set.js
> +const set = (objName = {}, path, value) => {
Теоретический вопрос - а в чем отличие стрелочной функции от обычной?

2024-02-18 17:08 UTC, AlexKhochenkov commented on source/set.js
> +const set = (objName = {}, path, value) => {
Отличие стрелочной функции от обычной в том, что у стрелочной функции нет this и arguments, что позволяет нам брать их из внешнего окружения. Например, это удобно в декораторах, когда нужно пробросить вызов с текущими this и arguments.

2024-02-19 11:47 UTC, DPeshkoff approved these changes

2024-02-19 11:48 UTC, closed without merging