Камалов Марат
frontend-park-mail-ru/homework_2024_1 pull request #36
Opened 2024-02-12 11:17 UTC by MaratKamalovPD

2024-02-12 18:42 UTC, F4lkr4m commented
Добро пожаловать на курс фронтенд-разработки! Я буду проверять твое ДЗ №0. Свои вопросы, комментарии и предложения оставлю в PullRequest'е, если будут какие-то вопросы, всегда можешь обратиться ко мне в личку https://t.me/Falkr4m

2024-02-12 19:21 UTC, F4lkr4m requested changes

2024-02-12 19:21 UTC, F4lkr4m commented on source/set.js
> +  for (i; i < properties.length - 1; i++) {
Цикл for это конечно круто, но встроенные функции перебора гораздо круче - используй их. В твоем случае отлично подойдет reduce, тк ты идешь внутрь объекта и сохраняешь ссылку на свойство https://learn.javascript.ru/array-iteration#reduce-reduceright

2024-02-12 19:21 UTC, F4lkr4m commented on source/set.js
> +  if (object === null) {
Можно просто if (!object)

2024-02-12 19:21 UTC, F4lkr4m commented on source/set.js
> +  current_object[properties[properties.length - 1]] = value;
Можно вместе `properties[properties.length - 1]` использовать `properties.at(-1)`

2024-02-12 19:21 UTC, F4lkr4m commented on source/set.js
> +  let i = Array.isArray(path) ? 0 : 1;
Ты правильно использовал инциализацию переменных, но тем не менее мог бы ты сверх этого еще рассказать чем отличаются let/const/var?

2024-02-12 19:21 UTC, F4lkr4m commented on source/set.js
> +const set = function(object, path, value) {
Не забываем описать JSDoc для твоей функции

2024-02-12 19:21 UTC, F4lkr4m commented on source/set.js
> +const set = function(object, path, value) {
Также было бы неплохо обработать краевые случаи, когда path придет в виде числа, объекта или какой-то еще не обрабатываемой мешуры)

2024-02-12 19:21 UTC, F4lkr4m commented on tests/set.js
> +
Лишние строчки нам тут не нужны

2024-02-12 19:21 UTC, F4lkr4m commented on source/set.js
> +const set = function(object, path, value) {
Ну и если мы передадим путь без точки, напр. 'bar', то тоже скорее всего все сломается, можно было бы проверить на наличие точки в начале строки

2024-02-12 19:21 UTC, F4lkr4m commented on tests/set.js
> +	// дополнительные тесты
Молодец, что добавил дополнительные тесты!

2024-02-12 19:22 UTC, F4lkr4m commented
В целом все круто, немного замечаний поправить. Как поправишь - пингани меня в тг

2024-02-13 10:27 UTC, MaratKamalovPD commented on source/set.js
> +'use strict';
Эта директива нужна, чтобы включить строгий режим, который заставляет интерпретатор использовать более строгие правила для выполнения кода. При включённом строгом режиме происходит более строгая обработка ошибок, вводится запрет на использование устаревших и небезопасных синтаксических конструкций, а также упрощается работа с переменными.

2024-02-13 10:57 UTC, MaratKamalovPD commented on source/set.js
> +const set = function(object, path, value) {
Основное отличие стрелочной функции от объявления функции через ключевое слово function заключается в том, что стрелочная функция не содержит собственного контекста, а используют внешний

2024-02-13 20:25 UTC, MaratKamalovPD commented on source/set.js
> +  let i = Array.isArray(path) ? 0 : 1;
const: объявленные переменные имеют блочную область видимости, и их значение не может быть изменено (блочная видимость означает, что переменные видны только внутри блока кода, в котором они были объявлены)
let: объявленные переменные имеют блочную область видимости, и их значение может быть изменено после инициализации 
var: объявленные переменные имеют глобальную область видимости, и их значение может быть изменено после инициализации 
использование let и const рекомендуется в современном JavaScript, так как они предоставляют более предсказуемое поведение связанное с областью видимости

2024-02-14 06:22 UTC, F4lkr4m requested changes

2024-02-14 06:22 UTC, F4lkr4m commented on .idea/.gitignore
папочки .idea не должно быть

2024-02-14 06:22 UTC, F4lkr4m commented on README.md
В этом файле не должно быть диффаков

2024-02-14 06:22 UTC, F4lkr4m commented on index.html
> +<h1></h1>
Тут это не нужно) Как и пробел под этой строчкой

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> +  const setObject = (object, property) => {
Выделять тело колбека для reduce в отдельную фукнцию - нет необходимости) Давай засунем это в виде колбека в reduce

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> +    return;
При обработке ошибок как вариант можно возвращать undefined, но также есть вариант выкидывать определенный тип ошибки. Давай будем тут выбрасывать ошибку. Подбери подходящую из этих: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> +    return;
Также не забудь добавить описание для нее в JSDoc

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> +  let properties
Тут поехал пробел, также не забываем точку с запятой

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> +
Лишний пробел

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> +      if (path.substring(0, 1) != '.'){
Предлагаю вместо того, чтобы выбрасывать undefined или ошибку в этом случае, считать что входной параметр для path может быть как '.foo.bar', но и без точки в начале 'foo.bar'

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> +  if (typeof path === 'number' || path === null) {
Предлагаю обработку параметров входных вынести в самое начало

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> +  if (typeof path === 'number' || path === null) {
А что если path = {}? Или функцией? Тут скорее всего нужна другая обработка

2024-02-14 06:22 UTC, F4lkr4m commented on source/set.js
> + * @param {*} value - Значение, которое нужно установить
any

2024-02-14 06:32 UTC, F4lkr4m requested changes

2024-02-14 06:32 UTC, F4lkr4m commented on source/set.js
> +   if (Array.isArray(path)) {
Возможно стоит вынести обработку path в отдельную функцию

2024-02-14 10:01 UTC, MaratKamalovPD commented on source/set.js
> + * @param {*} value - Значение, которое нужно установить
К сожалению, не понимаю замечания. У меня, конечно, есть предположение, что имелось в виду, что типы параметров могут быть любые, но разве это имеет смысл, учитывая, что не при любых типах входных параметров функция возвращает результат, соответствующий её функциональному назначению?

2024-02-14 10:39 UTC, MaratKamalovPD commented on README.md
Если честно, я не вижу дифы. Более того я не понимаю, откуда они могли бы теоретически взяться. Я зашёл в соответствующую ветку репозитория в соответствующий файл, через ctrl + A выделил его содержание, скопировал и вставил в свой файл.

2024-02-14 10:43 UTC, MaratKamalovPD commented on README.md
описанную выше операцию я провернул ещё раз, закоммитил, и подсистема контроля изменений не нашла никаких различий, которые можно было бы запихнуть в коммит 
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/55689955/c3a38480-f4d6-4ccc-82a4-428adeef913a)

2024-02-14 17:43 UTC, F4lkr4m requested changes
В основном нужно сделать визуальные улучшайзинги и обработку ошибок поправить

2024-02-14 17:43 UTC, F4lkr4m commented on README.md
Пробел на последней строке просто был

2024-02-14 17:43 UTC, F4lkr4m commented on source/set.js
> +  const parsePath = (path) => {
Функции, которые не задействуют внешний контекст - надо вынести за пределы внешней функции

2024-02-14 17:43 UTC, F4lkr4m commented on source/set.js
> +    if (typeof path === 'number' || !path || typeof path === 'function' || (path instanceof Object && !Array.isArray(path))) {
Обработку ошибок лучше оставить в set на мой взгляд, так будет более понятно, что ты обработал ошибку, а потом дальше по коду пошел использовать разные вспомогательные функции, которые выполняют какую-то конкретную логику

2024-02-14 17:43 UTC, F4lkr4m commented on source/set.js
> +    if (typeof path === 'number' || !path || typeof path === 'function' || (path instanceof Object && !Array.isArray(path))) {
У тебя path по твоему JSDoc может быть только `string | Array<string>` - так может надо от этого и отталкиваться?

2024-02-14 17:43 UTC, F4lkr4m commented on source/set.js
> +    if (typeof path === 'number' || !path || typeof path === 'function' || (path instanceof Object && !Array.isArray(path))) {
Если path не строка и не массив строк, тогда выкидывать ошибку?

2024-02-14 17:43 UTC, F4lkr4m commented on source/set.js
> +    } else {
У тебя сверху return path; После return код дальше не будет исполняться, если он попал в верхний блок. Получается else нам тут не нужен вовсе

2024-02-14 17:43 UTC, F4lkr4m commented on source/set.js
> +      path = path.substring(1);
Потерялся отступ внутри if

2024-02-14 17:43 UTC, F4lkr4m commented on source/set.js
> +  const finalObject = properties.reduce((object, property) => {
finalObject у тебя не функция а у уже конкретный результат - тут JSDoc не нужен

2024-02-14 17:43 UTC, F4lkr4m commented on source/set.js
> +
В конце файла оставь лишь одну пустую строчку

2024-02-14 17:43 UTC, F4lkr4m commented on tests/set.js
> +
Лишние пробелы

2024-02-14 17:43 UTC, F4lkr4m commented on tests/set.js
> +		assert.throws(function() {set({ foo: 'bar' }, null, 'baz')}, TypeError, 'Invalid path type');
Почему не стрелочная запись?

2024-02-15 18:14 UTC, F4lkr4m requested changes
чуть чуть поправить

2024-02-15 18:14 UTC, F4lkr4m commented on source/set.js
> +
лишняя строка

2024-02-15 18:14 UTC, F4lkr4m commented on source/set.js
> +    path = path.substring(1);
Не перезаписываем входные параметры, соблюдаем чистоту функций

2024-02-15 23:51 UTC, DPeshkoff requested changes
Привет! Годное решение, но кое-что надо поправить)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:51 UTC, DPeshkoff commented on source/set.js
> +  if (typeof path != 'string' && !Array.isArray(path)) {
<img width="339" alt="Снимок экрана 2024-02-16 в 02 49 24" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/7ade7541-c982-4f07-b5bf-710cd904b0f5">

Предлагаю починить)

2024-02-18 12:36 UTC, DPeshkoff approved these changes

2024-02-18 12:36 UTC, closed without merging