Ковалев Илья
frontend-park-mail-ru/homework_2024_1 pull request #38
Opened 2024-02-12 12:03 UTC by b0pof

Написал функцию, потестил руками, все работает.
Попробовал запустить тесты, увидел сообщения такого рода в каждом тесте на мою функцию:

Died on test #1     at Object.<anonymous> (file:.../homework_2024_1/tests/format.js:4:8): format is not defined
Expected: | null
Message: Diff suppressed as the expected and actual results have an equivalent serialization
Source: ReferenceError: format is not defined     at Object.<anonymous> (file:.../homework_2024_1/tests/format.js:16:10)

На 16-й строке в районе 10 символа (format.js:16:10) находится данная строка:
    assert.strictEqual(format(input, 1), expected);

Установил qunit через npm, но не помогло.
Подскажите, пожалуйста, что следует установить или исправить)

2024-02-12 19:25 UTC, F4lkr4m commented
Привет, ты забыл добавить в index.html строчку с подключением твоего скрипта - это легко сделать, добавив эту строчку `<script src="source/format.js"></script>`

2024-02-12 19:38 UTC, F4lkr4m requested changes
В целом все круто, пингани меня в телегу, как поправишь

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +'use strict'
Можешь рассказать для чего используется эта директива?

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +const column = function (numbers, columns, nCol) {
Тут ты используешь запись функции через function, давай переделаем на стрелочную запись, а заодно расскажи, пожалуйста, чем эти две записи отличаются?

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +const column = function (numbers, columns, nCol) {
Также тут не хватает JSDoc'а для твоей функции, было бы здорово его добавить

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +    let numbersInColumn = []
Тут ты используешь инициализацию переменной через let, можешь рассказать, чем отличается инициализация через let/const/var?

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +    for (let i = 0; i < numbers.length; i++) {
Си подобные циклы это конечно круто, но куда круче использовать встроенные функции работы с коллекциями, например reduce, который в этом случае тебе подойдет больше)
https://learn.javascript.ru/array-iteration#reduce-reduceright

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +const format = function (numbers, col) {
Тут все тоже самое, что и к функции выше: стрелочная запись, JSDoc

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +        const maxLength = Math.max(...column(numbers, col, i % col).map(num => String(num)).map(str => str.length));
Тут настоящий ниндзя-код, очень круто, но читается сложно, не стесняйся использовать вспомогательные переменные

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +    for (let i = 0; i < numbers.length; i++) {
Давай также переделаем на forEach/reduce подобные функции

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +        if ((i + 1) % col === 0 && i != numbers.length - 1) {
Можешь тут тоже наименовать  `isLastRow = i != numbers.length - 1`, так будет более ясен смысл

2024-02-12 19:38 UTC, F4lkr4m commented on source/format.js
> +    return result
Не забываем в конце каждой строки ;

2024-02-12 19:40 UTC, F4lkr4m requested changes

2024-02-12 19:40 UTC, F4lkr4m commented on source/format.js
> +const format = function (numbers, col) {
Еще было бы круто добавить проверку входных параметров, что они соответствуют формату обрабатываемых тобой данных. А то если вместо массива тебе подсунут объект - то будет ошибка(

2024-02-12 19:40 UTC, F4lkr4m commented on source/format.js
> +const format = function (numbers, col) {
А также еще было бы здорово добавить своих тестов)

2024-02-12 22:08 UTC, b0pof commented on source/format.js
> +    let numbersInColumn = []
В сравнении с let:
- const используется для переменных, значение которых не будет изменяться;
- var расширяет область видимости переменной до всей функции, а не только в блоке, в котором была создана.

2024-02-13 04:26 UTC, F4lkr4m requested changes

2024-02-13 04:26 UTC, F4lkr4m commented on source/format.js
> +    if (!Array.isArray(numbers) || col <= 0) {
А если элемент массива будет не числом? 
Также js уже имеет какие то дефолтные ошибки, которые можно выбрасывать из кода. Можешь заиспользовать одну из них: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error

2024-02-13 04:26 UTC, F4lkr4m commented on source/format.js
> +        let isLastRow;
Нет, я имел ввиду полностью конструкцию присвоить `isLastRow = i != numbers.length - 1` и потом ее использовать. Иначе идет переусложнение кода

2024-02-13 04:26 UTC, F4lkr4m commented on source/format.js
> +    }, []);
А разве начальным значением не должна быть строка, а не массив? Вроде в ответ строку возвращать должны

2024-02-13 04:26 UTC, F4lkr4m commented on source/format.js
> +const column = (numbers, columns, nCol) => {
Тут можно обойтись без фигурных скобок и вернуть конструкцию с reduce

2024-02-13 04:29 UTC, F4lkr4m commented on source/format.js
> +    let numbersInColumn = []
А let для чего нужно?
Помимо этого в const можно класть объекты, которые потом будут изменяться. То есть по факту у нас будет меняться сам объект, а ссылка не будет меняться. Поэтому на этой строчке, что надо было использовать?

2024-02-13 12:11 UTC, F4lkr4m requested changes

2024-02-13 12:11 UTC, F4lkr4m commented on source/format.js
> +    try {
Не, ошибку внутри ловить не надо. Надо при обработке входных параметров просто выкинуть необходимую ошибку)

2024-02-13 18:06 UTC, b0pof commented on source/format.js
> +    let numbersInColumn = []
let имеет следующие особенности:
- переменная создается только в текущем блоке (в if-else или в итерации цикла);
- до строки с созданием переменной (let a = 5) к ней нельзя обращаться. (c var: a = undefined).

И в той строке нужно было использовать
const numbersInColumn = [ ]
, так как объект (массив) остается тем же, ссылка на него не изменяется.

2024-02-13 18:48 UTC, F4lkr4m requested changes

2024-02-13 19:00 UTC, F4lkr4m commented
Lgtm

2024-02-13 22:54 UTC, DPeshkoff requested changes
Привет! Хорошее решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 22:54 UTC, DPeshkoff commented on index.html
> +	<script src="./source/format.js"></script>
Гоу на 16-ю строчку, под max.js

2024-02-13 22:54 UTC, DPeshkoff commented on tests/format.js
> +
Какой-то непонятный diff, давай поправим)

2024-02-13 22:54 UTC, DPeshkoff commented on tests/format.js
>  			'     1\n' +
Исходные тесты лучше не менять - можно просто оставить так

2024-02-13 22:54 UTC, DPeshkoff commented on tests/format.js
> +	QUnit.test('format обрабатывает некорректные входные параметры', function (assert) {
А если на входе будет функция? Null? Infinity?)

2024-02-13 22:54 UTC, DPeshkoff commented on source/format.js
> +        const additionalSpaces = isFirstColumn ? 0 : 1;
Можно немного порефачить (к примеру, 31 строка и 36 могут быть немного подсокращены)

2024-02-15 23:33 UTC, DPeshkoff approved these changes

2024-02-15 23:33 UTC, closed without merging