Волохов Александр
frontend-park-mail-ru/homework_2024_1 pull request #39
Opened 2024-02-12 12:06 UTC by oFem1m

Вариант 4

2024-02-12 12:15 UTC, Zela2520 commented
Саша, привет )
Меня зовут Даня, буду проверять твоё дз. В течение дня выполню проверку.

При необходимости связаться со мной, пиши в тг: [Даня](https://t.me/Zela28)

2024-02-12 20:21 UTC, Zela2520 commented on tests/inverse.js
> +function inverse(arr, num) {
Эта функция должна быть в source

2024-02-12 20:22 UTC, Zela2520 commented on tests/inverse.js
> +        throw new Error('Переданный аргумент не является массивом');
Если бросаешь исключения, то их надо обрабатывать. Что будет если ты не обработаешь исключение ?

2024-02-12 20:23 UTC, Zela2520 commented on tests/inverse.js
> +    if (!Array.isArray(arr)) {
Проверка хорошая :)
Можно тестовый кейс написать

2024-02-12 20:27 UTC, Zela2520 commented on tests/inverse.js
> +    const length = arr.length;
Знаешь свойство length массива, это хорошо ) Зачем оно вынесено у тебя в константу, нельзя обойтись без этой переменной ? Ты используешь её один раз на 14-ой строке, если не ошибаюсь.

2024-02-12 20:28 UTC, Zela2520 commented on tests/inverse.js
> +    } else if (typeof num === 'number') {
else не нужен

2024-02-12 20:29 UTC, Zela2520 commented on tests/inverse.js
> +        } else {
else лишние

2024-02-12 20:29 UTC, Zela2520 commented on tests/inverse.js
> +    if (num === undefined) {
или !num

2024-02-12 20:56 UTC, Zela2520 commented on tests/inverse.js
> +        throw new Error('Второй аргумент должен быть числом или отсутствовать');
лишние, аналогичное замечание было

2024-02-12 21:01 UTC, Zela2520 commented on tests/inverse.js
> +    } else if (typeof num === 'number') {
Проверь сначала негативные кейсы и верни null, это уменьшает количество ветвлений. Логически корректнее не выполнять код дальше, если данные невалидны. Правда же ?)

2024-02-13 04:23 UTC, Zela2520 commented on tests/inverse.js
> +    if (!Array.isArray(arr)) {
Это единственный негативный кейс после которого null можем вернуть ?

2024-02-13 04:33 UTC, Zela2520 commented on tests/inverse.js
> +            return restPart.concat(reversedPart);
Как ещё можно объединить два массива ? Почему выбрал именно этот способ ?

2024-02-13 04:34 UTC, Zela2520 commented on tests/inverse.js
> +            const restPart = arr.slice(0, num);
перед return-ом лучше добавлять пустую строку - это скорее к код стайлу

2024-02-13 04:35 UTC, Zela2520 commented on tests/inverse.js
> +            const reversedPart = arr.slice(num, length).reverse();
Годно используешь slice :) Расскажи мне отличие slice от splice ?

2024-02-13 04:36 UTC, Zela2520 commented on tests/inverse.js
> +            const restPart = arr.slice(0, num);
Расскажи мне какие способы объявление переменной существуют в js и чем они отличаются ?

2024-02-13 15:36 UTC, oFem1m commented on tests/inverse.js
> +function inverse(arr, num) {
Сейчас поправлю

2024-02-13 15:36 UTC, oFem1m commented on tests/inverse.js
> +        throw new Error('Переданный аргумент не является массивом');
программа может зависнуть

2024-02-13 15:54 UTC, oFem1m commented on tests/inverse.js
> +    const length = arr.length;
Я саму функцию переписывал, а эту строчку не поменял) Исправляю

2024-02-13 16:02 UTC, oFem1m commented on tests/inverse.js
> +    } else if (typeof num === 'number') {
Понял, исправляю

2024-02-13 16:06 UTC, oFem1m commented on tests/inverse.js
> +            return restPart.concat(reversedPart);
Еще можно написать: return [...restPart, ...reversedPart];
Вроде как работает аналогично, но как по мне - concat более читаемый)

2024-02-13 16:19 UTC, oFem1m commented on tests/inverse.js
> +            const reversedPart = arr.slice(num, length).reverse();
slice создает новый массив, копируя часть предыдущего
splice изменяет массив, удаляя или заменяя элементы. А возвращает удаленные элементы

2024-02-13 16:52 UTC, oFem1m commented on tests/inverse.js
> +            const restPart = arr.slice(0, num);
var - функциональная область видимости, может быть переобъявлена и переопределена
let - блочная область видимости, нельзя переобъявить в той же области видимости
const - блочная область видимости, нельзя переобъявить

2024-02-13 17:54 UTC, Zela2520 commented on source/inverse.js
> +    if (num < 0) {
лишний if. Если предыдущий if не отработает, то выполнение функции так и так придёт сюда

2024-02-13 18:00 UTC, oFem1m commented on source/inverse.js
> +    if (num < 0) {
да, вы правы, исправляю

2024-02-13 18:03 UTC, Zela2520 commented on source/inverse.js
> +        const reversedPart = arr.slice(0, num).reverse();
Смотри ты создаёшь лишние переменные,  а работаешь по факту с одним условием.
Давай попробуем сделать код компактнее уберём лишние переменные и добавим тернарник.

(https://learn.javascript.ru/ifelse#uslovnyy-operator)

2024-02-13 18:11 UTC, Zela2520 commented on source/inverse.js
> +        if (!num) return arr.slice().reverse();
Проверка избыточна её можно удалить. 
В возвращаемом значение у тебя нигде эта переменная не фигурирует просто возвращается обратный массив arr

2024-02-13 18:18 UTC, Zela2520 commented
Всё гуд :) 
Давай на ты, пожалуйста )

Давай if-ки попробуем везде убрать и используем тернарку (в тернарке условие: (num >= 0)) -> получишь reversedPart и restPart

2024-02-13 20:19 UTC, oFem1m commented
само по себе выражение num >== 0 вызывает ошибку
но я понял вопрос)

== это нестрогое равенство, сравнивает значения после того, как приводятся типы (если они разных типов)

=== это строгое равенство, без приведения типов

2024-02-15 23:31 UTC, DPeshkoff requested changes
Привет! Классное решение, но кое-что надо поправить)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:31 UTC, DPeshkoff commented on source/inverse.js
> +    if (!Array.isArray(arr) || (num !== undefined && typeof num !== 'number')) return null;
Давай везде добавим {} и переносы

Вместо проверки на undefined можно [так](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)

2024-02-15 23:31 UTC, DPeshkoff commented on tests/inverse.js
> +    QUnit.test('Функция выбрасывает ошибку при передаче не массива', function (assert) {
ошибку больше не выбрасывает, а имя не поменял

2024-02-15 23:31 UTC, DPeshkoff commented on tests/inverse.js
> -		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], -15), [ 1, 2, 3, 4, 5 ]);
Давай уберем diff

2024-02-15 23:31 UTC, DPeshkoff commented on source/inverse.js
> +function inverse(arr, num) {
А какие еще способы задать функцию знаешь? Чем они отличаются?

2024-02-15 23:31 UTC, DPeshkoff commented on source/inverse.js
> +'use strict';
А что значит эта строчка?

2024-02-15 23:31 UTC, DPeshkoff commented on source/inverse.js
> +    return (num >= 0) ? restPart.concat(reversedPart) : reversedPart.concat(restPart);
Дублируем аж 3 раза num >= 0, можем оптимизировать?

2024-02-18 16:37 UTC, oFem1m commented on source/inverse.js
> +function inverse(arr, num) {
является частью области видимости выполнения (в том случае, который использовал я)

const Name1 = function(par) {
  // код 
};
не является частью области видимости выполнения

const Name2 = (par) => {
  // код 
};
это сокращенный синтаксис для объявления функций
:)

2024-02-18 19:25 UTC, oFem1m commented on source/inverse.js
> +'use strict';
это включение строгого режима, нужен для безопасности. Возвращаются ошибки при всяких небезопасных действиях, например, при дублировании параметров в функции или в случае присваивания значения необъявленной переменной

2024-02-18 19:27 UTC, oFem1m commented on source/inverse.js
> +    return (num >= 0) ? restPart.concat(reversedPart) : reversedPart.concat(restPart);
Можно вынести условие в отдельную переменную

2024-02-18 19:31 UTC, oFem1m reviewed
поправил

2024-02-19 11:56 UTC, DPeshkoff commented on source/inverse.js
> +function inverse(arr, num) {
А в чем отличие стрелочной от обычной? Только область видимости?

2024-02-19 11:56 UTC, DPeshkoff requested changes

2024-02-19 11:56 UTC, DPeshkoff commented on tests/inverse.js
> +        assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], 1), [ 1, 5, 4, 3, 2 ]);
Не поменялось(

2024-02-19 17:07 UTC, DPeshkoff requested changes

2024-02-19 17:07 UTC, DPeshkoff commented on source/inverse.js
> +function inverse(arr, num) {
Гоу тут стрелочную

2024-02-19 17:13 UTC, DPeshkoff approved these changes

2024-02-19 17:13 UTC, closed without merging