Угрюмов Михаил
frontend-park-mail-ru/homework_2024_1 pull request #4
Opened 2024-02-10 08:01 UTC by 1mizhgun1

2024-02-10 12:09 UTC, AnnSkay commented
Миша, привет! Я Оля :) Звезды так сошлись, что я буду твоим ревьюером на этом задании)
Если возникнут какие-то вопросы, ты все исправишь или просто хочется что-то обсудить - пиши мне в телегу [https://t.me/annskay](https://github.com/frontend-park-mail-ru/homework_2024_1/pull/url)

2024-02-10 12:52 UTC, AnnSkay commented on source/tree.js
> +'use strict';
Расскажи, пожалуйста, зачем ты добавил эту строчку и что это вообще такое?)

2024-02-10 12:52 UTC, AnnSkay commented on source/tree.js
> +}
Расскажи, зачем нужна пустая строка в конце файла)

2024-02-10 12:52 UTC, AnnSkay commented on source/tree.js
> +
Давай пройдемся по код стайлу, чтобы сделать свой код красивым и понятным:
1. Смысловые блоки лучше разделять отступами, например, цикл, return из функции. 
2. Не изменяемые данные нужно выносить в константу. Например, пробел или символ конца строки. Зачем, расскажи мне, пожалуйста)

Посмотреть подробнее хорошие практики написания кода можешь тут - https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

P.S. хочу похвалить тебя за хороший нэйминг переменных, продолжай в том же духе)

2024-02-10 12:52 UTC, AnnSkay commented on source/tree.js
> +const tree = (size) => {
Так как этот код написан без типизации, то есть вероятность совершить ошибку - передать в функцию других тип данных, например массив. Давай обезопасим наш код от невалидных данных и напишем на это тест)

2024-02-10 12:52 UTC, AnnSkay commented on source/tree.js
> +    const width = 2 * size - 3;
Очень круто, что ты вынес переиспользуемый код в отдельную функцию и использовал различные встроенные методы! 
Но перед тем, как мы разберем твою функцию полностью, давай попробуем упростить твой код) Решение этой задачи не требует такого количество вычислений и преобразований, все на самом деле намного проще) Подсказка - тебе будет достаточно лишь цикла и метода repeat)

2024-02-10 12:52 UTC, AnnSkay commented on tests/tree.js
> +	QUnit.test('Ёлочка высотой 6', function (assert) {
Ты добавил 2 юнит теста и даже сохранил порядок - круто)) Но не забудь расширить тесты, когда будешь добавлять обработку ошибок)

2024-02-10 13:02 UTC, 1mizhgun1 commented on source/tree.js
> +'use strict';
Это директива, которая дает интерпретатору сигнал о том, что он должен уделять больше внимания к потенциальным ошибкам (строгий режим). Например, строгий режим не позволит использовать необъявленные переменные, либо изменять помеченные словом const

2024-02-10 13:05 UTC, 1mizhgun1 commented on source/tree.js
> +}
Во-первых, пустая строка в конце гарантирует то, что утилита для подсчета строк в файле правильно посчитает их количество. Во-вторых, при дозаписи в файл, либо при склеивании файлов с помощью утилит, отсутствие пустой строки приведет к слиянию текста

2024-02-10 14:00 UTC, 1mizhgun1 commented on source/tree.js
> +
Код стайл поправил

2024-02-10 14:01 UTC, 1mizhgun1 commented on source/tree.js
> +const tree = (size) => {
Проверку на тип данных сделал, тесты дописал

2024-02-10 14:02 UTC, 1mizhgun1 commented on source/tree.js
> +    const width = 2 * size - 3;
Код упростил, теперь использую только цикл и repeat, но всё равно приходится писать отдельную функцию для избежания дублирующегося кода)

2024-02-10 14:03 UTC, 1mizhgun1 commented on tests/tree.js
> +	QUnit.test('Ёлочка высотой 6', function (assert) {
Тесты расширил

2024-02-10 14:16 UTC, AnnSkay commented on source/tree.js
> +    const endlineSymbol = '\n';
константы лучше называть аперкейсом и снэйком (напр, SOME_NAME). Так в коде сразу они отличаются от других нэймингов) И ставить их лучше в начало файла вне функции, чтобы не пришлось листать то вниз, то вверх)

2024-02-10 14:16 UTC, AnnSkay commented on source/tree.js
> +        result += buildLayer(width, treeLayerWidth, treeSymbol, spaceSymbol, endlineSymbol);
если ты вынесешь константы, как я написала выше, то необходимость прокидывать их в функцию buildLayer отпадет)

2024-02-10 14:16 UTC, AnnSkay commented on source/tree.js
> +    if (typeof size != "number" && !(typeof size == "string" && parseInt(size)) || size < 3) {
Всегда нужно использовать строгое сравнение. Расскажи, почему так?)

2024-02-10 14:16 UTC, AnnSkay commented on source/tree.js
> +    if (typeof size != "number" && !(typeof size == "string" && parseInt(size)) || size < 3) {
слишком сложная проверка получилась) чтобы проверить, что аргумент не соответствует 2м типам данных, его можно написать проще)

2024-02-10 14:22 UTC, AnnSkay commented on source/tree.js
> +        const treeLayerWidth = 2 * layer + 1;
если бы ты выше начал цикл с 1, то можно было бы избавиться от добавления единицы тут и вычитания единицы выше)

2024-02-10 14:22 UTC, AnnSkay commented on source/tree.js
> +    const trunkWidth = 1;
если значение передается в функцию и не вычисляется, то нет необходимости выносить ее в отдельную переменную)

2024-02-10 14:25 UTC, 1mizhgun1 commented on source/tree.js
> +    if (typeof size != "number" && !(typeof size == "string" && parseInt(size)) || size < 3) {
Строгое сравнение нужно использовать для сравнения без приведения типов, чтобы не было никакой "магии", и результат был прозрачен

2024-02-10 14:26 UTC, AnnSkay commented on source/tree.js
> +    return emptySpace + layerSymbol.repeat(layerWidth) + emptySpace + endlineSymbol;
слишком сложная конструкция - сложно читать) в таких случаях лучше доп расчеты выносить в отдельную переменную) в твоем случае это повторение звездочки)

2024-02-10 14:28 UTC, AnnSkay commented on tests/tree.js
> +		assert.strictEqual(tree([101, 4, 123]), null);
проверить нужно на все типы данных)) иначе ты не можешь быть уверен, что все предусмотрел)

2024-02-10 14:41 UTC, 1mizhgun1 commented on tests/tree.js
> +		assert.strictEqual(tree([101, 4, 123]), null);
тесты дописал

2024-02-10 14:41 UTC, 1mizhgun1 commented on source/tree.js
> +    return emptySpace + layerSymbol.repeat(layerWidth) + emptySpace + endlineSymbol;
готово)

2024-02-10 14:41 UTC, 1mizhgun1 commented on source/tree.js
> +    const trunkWidth = 1;
убрал)

2024-02-10 14:42 UTC, 1mizhgun1 commented on source/tree.js
> +        const treeLayerWidth = 2 * layer + 1;
это изменил, теперь только -1 в теле цикла

2024-02-10 14:42 UTC, 1mizhgun1 commented on source/tree.js
> +    if (typeof size != "number" && !(typeof size == "string" && parseInt(size)) || size < 3) {
проверку сделал с помощью метода includes

2024-02-10 14:42 UTC, 1mizhgun1 commented on source/tree.js
> +    if (typeof size != "number" && !(typeof size == "string" && parseInt(size)) || size < 3) {
в коде поправил

2024-02-10 14:43 UTC, 1mizhgun1 commented on source/tree.js
> +        result += buildLayer(width, treeLayerWidth, treeSymbol, spaceSymbol, endlineSymbol);
готово)

2024-02-10 14:43 UTC, 1mizhgun1 commented on source/tree.js
> +    const endlineSymbol = '\n';
поправил

2024-02-10 14:59 UTC, AnnSkay commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || !parseInt(size) || size < 3) {
1. у функции parseInt всегда нужно указывать сс, не смотря на то, что он необязателен) Расскажи, почему?)
2. просто проверка на falsy значение у  parseInt не совсем верное, так как 0 даст false, а следующая проверка может со временем уйти. Посмотри, что возвращает parseInt  в случае невозможности конвертации строки

2024-02-10 15:00 UTC, AnnSkay commented on source/tree.js
> +
1 не до конца. Посмотри на цикл)

2024-02-10 15:02 UTC, AnnSkay commented on source/tree.js
> +        const treeLayerWidth = 2 * layer + 1;
а как так получилось, что ты итератор увеличил на 1, а тут оставил -1?)

2024-02-10 15:04 UTC, AnnSkay commented on source/tree.js
> +    const nonEmptySpace = layerSymbol.repeat(layerWidth);
название переменной немного не понятное)) не пустое пространство - что это значит)) эта же переменная хранит символы слоя)

2024-02-10 15:05 UTC, 1mizhgun1 commented on source/tree.js
> +        const treeLayerWidth = 2 * layer + 1;
Так получилось потому, что при вычислении treeLayerWidth итератор умножается на два (зависимость ширина слоя от глубины в любом случае будет с коэффициентом 2)

2024-02-10 15:14 UTC, 1mizhgun1 commented on source/tree.js
> +
да, точно, пропустил в прошлый раз

2024-02-10 15:15 UTC, 1mizhgun1 commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || !parseInt(size) || size < 3) {
исправил)

2024-02-10 15:15 UTC, 1mizhgun1 commented on source/tree.js
> +    const nonEmptySpace = layerSymbol.repeat(layerWidth);
layerSpace вроде получше)

2024-02-10 15:25 UTC, AnnSkay commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || isNaN(parseInt(size, 10)) || size < 3) {
и последнее - при таком написании первая проверка тебе не нужна)) так как parseInt  уже отсечет все ненужное)

2024-02-10 15:28 UTC, 1mizhgun1 commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || isNaN(parseInt(size, 10)) || size < 3) {
видимо нет, так как при передаче массива чисел parseInt возвращает первый элемент массива) тогда нужно либо менять тест (допускать передачу в функцию массива), либо отставить как есть

2024-02-10 15:29 UTC, AnnSkay commented on tests/tree.js
> +		assert.strictEqual(tree('A'), null);
и еще одно последнее - у тебя уже есть тест на проверку строки 'abc', зачем тебе еще один тест тоже на строку?)

2024-02-10 15:36 UTC, 1mizhgun1 commented on tests/tree.js
> +		assert.strictEqual(tree('A'), null);
действительно лишнее, убрал)

2024-02-10 15:37 UTC, AnnSkay commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || isNaN(parseInt(size, 10)) || size < 3) {
да, все верно. Оставляй как есть

2024-02-10 15:38 UTC, 1mizhgun1 commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || isNaN(parseInt(size, 10)) || size < 3) {
![Screenshot 2024-02-10 183747](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/78853397/2b87c62f-f73e-410b-935a-7e58aaf21aeb)

2024-02-12 15:11 UTC, DPeshkoff requested changes
Привет! Крутое решение, есть парочка минорных правок)

Если будут вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-12 15:11 UTC, DPeshkoff commented on source/tree.js
> +const buildLayer = (width, layerWidth, layerSymbol) => {
Гоу добавим JSDOC здесь и на 15 строчке

2024-02-12 15:11 UTC, DPeshkoff commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || isNaN(parseInt(size, 10)) || size < 3) {
А чем isNaN отличается от Number.isNaN? Какой лучше использовать здесь?

2024-02-13 08:38 UTC, 1mizhgun1 commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || isNaN(parseInt(size, 10)) || size < 3) {
isNaN преобразует аргумент в число, а затем проверяет его. Number.isNaN не делает преобразование, проверяет сразу. Number.isNaN возвращает true только для числовых значений, имеющих значение NaN, поэтому в данном случае лучше использовать именно Number.isNaN, так как parseInt возвращает как раз числовое значение, либо NaN

2024-02-13 11:13 UTC, 1mizhgun1 commented on source/tree.js
> +const buildLayer = (width, layerWidth, layerSymbol) => {
JSDOC добавил

2024-02-13 11:13 UTC, 1mizhgun1 commented on source/tree.js
> +    if (!["number", "string"].includes(typeof size) || isNaN(parseInt(size, 10)) || size < 3) {
исправил

2024-02-13 22:19 UTC, DPeshkoff approved these changes

2024-02-13 22:19 UTC, closed without merging