Журмилов Вадим
frontend-park-mail-ru/homework_2024_1 pull request #40
Opened 2024-02-12 12:13 UTC by veglem

2024-02-12 19:38 UTC, F4lkr4m commented
Добро пожаловать на курс фронтенд-разработки! Я буду проверять твое ДЗ №0. Свои вопросы, комментарии и предложения оставлю в PullRequest'е, если будут какие-то вопросы, всегда можешь обратиться ко мне в личку https://t.me/Falkr4m

2024-02-12 19:56 UTC, F4lkr4m requested changes
Все хорошо, лишь немного поправить решение, пингани меня в тг, как поправишь

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +'use strict';
Можешь рассказать для чего используется эта директива?

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +const format = (array, columns) => {
Молодец, используешь стрелочную запись, а чем она отличается от обычной записи через function?

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +const format = (array, columns) => {
Не хватает JSDoc для твоей функции

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +            array.some(item => !Number.isInteger(item)) ||
Круто, что добавил проверки входных данных)

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +    if (    !Array.isArray(array) ||
Тут что то не понятное с пробелами(

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +        return undefined
Не забываем ; в конце каждой строки

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +    for (let i = 0, col = 0; i < array.length; ++i, ++col) {
Си подобные циклы это круто, но куда круче использовать встроенные в язык функции перебора, по типу forEach)

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +    for (let i = 0, col = 0; i < array.length; ++i, ++col) {
Тут ты используешь внутри две одинаковые переменные i, col - надо ли оно нам? Если ты хочешь использовать наименование col как алиас - то можно это сделать внутри цикла `const col = i`, нежели чем какие-либо операции совершать с внешней переменной.

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +                formatLenArray[col] < array[i].toString().length) {
`array[i].toString().length` - повторение кода, давай перед if'аком сохраним в переменную и не будем повторяться

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +        if (    formatLenArray[col] === undefined ||
можно просто `!formatLenArray[col]`

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +    for (let i = 0, col = 0; i < array.length; ++i, ++col) {
После for лучше пробел не ставить

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +    let strResult = ""
Ты правильно используешь инициализацию переменной через let, а можешь поподробнее рассказать про инциализацию переменных через let/const/var?

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +    for (let i = 0, col = 0; i < array.length; ++i, ++col) {
Тоже давай переделаем Си подобный цикл

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +        if(col === columns - 1 && i !== array.length - 1){
Можно не стесняться использовать вспомогательные переменные, которые внесут ясность в твой код, например 
`const isLastRow = i !== array.length - 1`

2024-02-12 19:56 UTC, F4lkr4m commented on tests/format.js
> +	QUnit.test('format возвращает undefined при неправильно переданнных данных', function (assert) {
Круто, что добавил свои тесты)

2024-02-12 19:56 UTC, F4lkr4m commented on tests/format.js
> +	QUnit.test('format работает правильно при недостатке элементов в массиае', function (assert) {
массиве*

2024-02-12 19:56 UTC, F4lkr4m commented on source/format.js
> +const format = (array, columns) => {
название переменной array - не вносит ясности в  код, что это же за массив?)

2024-02-13 07:59 UTC, veglem commented on source/format.js
> +'use strict';
На сколько мне известно,  `use strict` используется для повышения безопасности при использовании новых стандартов js, как пример, нельзя использовать не объявленные переменны, дублировать параметры функции или создавать глобальные переменные

2024-02-13 08:04 UTC, veglem commented on source/format.js
> +const format = (array, columns) => {
Стрелочная запись дает нам функционал лямбда функций и их ключевая фишка в том, что они наследуют контекст выполнения от родителя

2024-02-13 08:13 UTC, veglem commented on source/format.js
> +    let strResult = ""
const - создает неизменяемую переменную, те переприсвоить (хотя если речь идет о массивах допустим, то изменять их можно, но только элементы по отдельности, а не весь массив целиком)
var - устаревшая запись и остается для обратной совместимости. Минус ее в том, что она по молчанию равна undefind, и сама переменная создается еще при запуске скрипта (до ее фактического появления в коде), так же такие переменные, при обьявлении в ифе или форе будут доступны за его пределами и эти переменные можно переобьявлять.
let - крутая современная запись, лишенная недостатков выше

2024-02-13 12:22 UTC, F4lkr4m requested changes

2024-02-13 12:22 UTC, F4lkr4m commented on source/format.js
> +        return undefined;
забыл сказать, что тут следует выкинуть ошибку, лучше всего выбрать наиболее подходящую из списка: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error

2024-02-13 12:22 UTC, F4lkr4m commented on source/format.js
> +    intArray.forEach((value, index) => {
Тут можно использовать reduce и возвращать в нем строчку, таким образом как бы будет накопление результата https://learn.javascript.ru/array-iteration#reduce-reduceright

2024-02-13 20:42 UTC, F4lkr4m requested changes

2024-02-13 20:42 UTC, F4lkr4m commented on source/format.js
> + * @returns {undefined|string} - formatted string or undefined if wrong arguments
Не хватает в JSDoc throws

2024-02-13 20:42 UTC, F4lkr4m commented on source/format.js
> +        if(currColumn === columns - 1 && !isLastRow){
потерял пробел после закрывающей скобки

2024-02-13 20:42 UTC, F4lkr4m commented on source/format.js
> + * @returns {undefined|string} - formatted string or undefined if wrong arguments
И уже тогда undefined не возвращает

2024-02-14 06:45 UTC, F4lkr4m approved these changes
lgtm

2024-02-14 06:45 UTC, F4lkr4m commented on source/format.js
> +        const currColumn = index % columns
;

2024-02-15 23:36 UTC, DPeshkoff requested changes
Привет! Классное решение, минорная правка)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:36 UTC, DPeshkoff commented on source/format.js
> +        throw new TypeError();
Давай напишем в сообщении, что же пошло не так)

2024-02-18 12:36 UTC, DPeshkoff approved these changes

2024-02-18 12:37 UTC, closed without merging