MinMax func implementation
frontend-park-mail-ru/homework_2024_1 pull request #41
Opened 2024-02-12 12:14 UTC by frelikhmax

2024-02-12 13:22 UTC, rissenberg commented
Привет! Меня зовут Костя, я буду твоим проверяющим ментором по ДЗ0. Если возникнут вопросы, смело пиши в тг - @PassPort_Guardian, или в вк - @rissenberg

2024-02-12 13:24 UTC, rissenberg commented
Начнем с простого - ПР нужно назвать своим именем и фамилией, группу и вариант писать необязательно

2024-02-12 13:31 UTC, rissenberg commented on source/minmax.js
> +'use strict';
Напиши кратко, что меняет данная запись?

2024-02-12 13:44 UTC, rissenberg commented on source/minmax.js
> +    let minMaxNumbers = [undefined, undefined];
Объявлять переменные с изначальным значением "", undefined или null не надо, они и так принимают пустое значение undefined по умолчанию

2024-02-12 15:16 UTC, rissenberg requested changes
Дерзай!

2024-02-12 15:27 UTC, rissenberg commented
В задании так же просится написать JSDoc для твоей функции - это небольшая документация, которая определяет, как работает твоя функция, что принимает на вход и что возвращает. Более подробно можно прочитать здесь:
https://jsdoc.app/

2024-02-12 15:28 UTC, rissenberg commented on source/minmax.js
> +
В задании так же просится написать JSDoc для твоей функции - это небольшая документация, которая определяет, как работает твоя функция, что принимает на вход и что возвращает. Более подробно можно прочитать здесь:
https://jsdoc.app/

2024-02-13 07:43 UTC, frelikhmax commented on source/minmax.js
> +'use strict';
Активирует "современный" js. Становятся доступными новые возможности, а давно не используемые старые выключаются

2024-02-14 07:34 UTC, frelikhmax commented on source/minmax.js
> +function updateMinMax(min, max, current) {
Объявленные функции: function name(parameter1, parameter2, ... parameterN) {
 // body
} - может быть вызвана в той же области видимости до объявления
Выражения функций: let name = function(parameter1, parameter2, ... parameterN) {
 // body
} - не может быть вызвана до объявления
Стрелочные функции: let func = (arg1, arg2, ..., argN) => expression; ИЛИ let func = function(arg1, arg2, ..., argN) {
  return expression;
}; - чаще используется вместо выражений функций.

2024-02-14 15:58 UTC, rissenberg requested changes
Общие замечания - в репозитории появились ненужные файлы - каталог .idea, его нужно удалить и исправить остальные замечания

2024-02-14 15:58 UTC, rissenberg commented on source/minmax.js
> +    const numbersStrArr = numbersStr.replace(/[,!?]/g, '').split(' ');
Проверка на .replace(/[,!?]/g, '') выглядит костыльно, проверяет ли она все случаи?

2024-02-14 15:58 UTC, rissenberg commented on source/minmax.js
> + * [undefined, undefined].
Я бы последнее предложение не разрывал на две строки

2024-02-14 15:58 UTC, rissenberg commented on source/minmax.js
> +    return numbersArr.length === 0 ? [undefined, undefined] : [Math.min(...numbersArr), Math.max(...numbersArr)];
Код выглядит очень слипшимся. Раздели его пустыми строчками и разбивай длинные строчки на несколько, так повысится читаемость и структура будет лучше

2024-02-15 22:01 UTC, rissenberg requested changes
Других замечаний не нашел. Код хороший, тянет на сеньора, но его нужно дополнить

2024-02-16 21:26 UTC, rissenberg approved these changes
По мелочи осталось исправить, поэтому поставлю предварительно допуск, но подредактируй до проверки преподом. И пустую строчку в конце так и не поставил :/

2024-02-16 21:26 UTC, rissenberg commented on source/minmax.js
> +    if (!(typeof numbersStr === 'string')) {
Можно сразу при сравнении написать !==, и еще нужно добавит проверку на null - существует ли строка

2024-02-18 16:30 UTC, DPeshkoff requested changes
Привет! Хорошее решение, но нужна пара правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-18 16:30 UTC, DPeshkoff commented on source/minmax.js
> +'use strict';
Хочу подробнее - что именно блокируется?

2024-02-18 16:30 UTC, DPeshkoff commented on source/minmax.js
> +    if (typeof numbersStr !== 'string') {
<img width="351" alt="305255761-804205f3-3cc6-4f3d-b26d-6435d9eb0e70" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/29f84e5f-609e-4fac-ae74-c114424c4f46">

Такие строки все ломают(

Как починить?

2024-02-18 16:30 UTC, DPeshkoff commented on source/minmax.js
> +        throw new TypeError("Входные данные должны быть строкой");
В JS приняты одиночные кавычки, давай везде поменяем)

2024-02-18 16:30 UTC, DPeshkoff commented on tests/minmax.js
> +    QUnit.test('minmax работает правильно на строках без чисел', function (assert) {
Давай вернем, как было - тут уже устоявшийся кодстайл

![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/8eaea422-1003-4470-ad08-b3b78d56934d)

2024-02-18 16:30 UTC, DPeshkoff commented on tests/minmax.js
> +
Давай добавим тесты на новые, ломающие нас строки)

2024-02-18 19:06 UTC, frelikhmax commented on source/minmax.js
> +    if (typeof numbersStr !== 'string') {
1. ECMAScript 5 (ES5) добавил новые возможности в язык и изменил некоторые из существующих. Чтобы устаревший код работал, как и раньше, по умолчанию подобные изменения не применяются. Поэтому нам нужно явно их активировать с помощью специальной директивы: "use strict". Когда находится в начале скрипта, весь сценарий работает в «современном» режиме.
2. Создаётся обёртка объекта, т.к. string - примитивный тип. Добавил соответствующую проверку.

2024-02-19 15:44 UTC, DPeshkoff commented on source/minmax.js
> +'use strict';
up

2024-02-19 15:45 UTC, DPeshkoff requested changes

2024-02-19 15:45 UTC, DPeshkoff commented on source/minmax.js
> +    if (typeof numbersStr !== 'string' && !(typeof numbersStr === 'object' && numbersStr instanceof String)) {
Можно не проверять на object

2024-02-19 15:45 UTC, DPeshkoff commented on tests/minmax.js
> +        });
Табы/пробелы?

![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/7d192582-7074-4240-853b-3184afd404d6)

2024-02-19 16:23 UTC, frelikhmax commented on tests/minmax.js
> +        });
табы

2024-02-19 17:11 UTC, frelikhmax commented
JS долгое время продвигался с обратной совместимостью, что привело к сохранению многих ошибок в языке. Однако с появлением ES5 были внесены изменения, включая добавление директивы "use strict", которая активирует строгий режим. В этом режиме:

Нельзя присваивать значения неопределенным переменным.

Ошибка возникает при попытке удалить неизменяемое свойство объекта с помощью оператора delete.

Использование инструкции with запрещено.

Нельзя определить повторные свойства в литерале объекта.

Нельзя определить повторные формальные параметры функции.

Изменения объекта arguments не влияют на аргументы.

Функция eval не может создавать переменные и функции в своем контексте вызова.

Значение this не преобразуется в объект, а если оно равно undefined или null, то не преобразуется в глобальный объект.

Использование eval и arguments в качестве имени переменной запрещено.

Зарезервировано больше слов для будущего использования.

Нельзя использовать литералы восьмеричной системы счисления.

2024-02-19 17:13 UTC, frelikhmax commented
JS долгое время продвигался с обратной совместимостью, что привело к сохранению многих ошибок в языке. Однако с появлением ES5 были внесены изменения, включая добавление директивы "use strict", которая активирует строгий режим. В этом режиме:

Нельзя присваивать значения неопределенным переменным.
Ошибка возникает при попытке удалить неизменяемое свойство объекта с помощью оператора delete.
Использование инструкции with запрещено.
Нельзя определить повторные свойства в литерале объекта.
Нельзя определить повторные формальные параметры функции.
Изменения объекта arguments не влияют на аргументы.
Функция eval не может создавать переменные и функции в своем контексте вызова.
Значение this не преобразуется в объект, а если оно равно undefined или null, то не преобразуется в глобальный объект.
Использование eval и arguments в качестве имени переменной запрещено.
Зарезервировано больше слов для будущего использования.
Нельзя использовать литералы восьмеричной системы счисления.

2024-02-19 17:13 UTC, frelikhmax commented on tests/minmax.js
> +        });
JS долгое время продвигался с обратной совместимостью, что привело к сохранению многих ошибок в языке. Однако с появлением ES5 были внесены изменения, включая добавление директивы "use strict", которая активирует строгий режим. В этом режиме:

Нельзя присваивать значения неопределенным переменным.
Ошибка возникает при попытке удалить неизменяемое свойство объекта с помощью оператора delete.
Использование инструкции with запрещено.
Нельзя определить повторные свойства в литерале объекта.
Нельзя определить повторные формальные параметры функции.
Изменения объекта arguments не влияют на аргументы.
Функция eval не может создавать переменные и функции в своем контексте вызова.
Значение this не преобразуется в объект, а если оно равно undefined или null, то не преобразуется в глобальный объект.
Использование eval и arguments в качестве имени переменной запрещено.
Зарезервировано больше слов для будущего использования.
Нельзя использовать литералы восьмеричной системы счисления.

2024-02-19 17:41 UTC, DPeshkoff approved these changes

2024-02-19 17:41 UTC, closed without merging