Жук Артём, вариант 13
frontend-park-mail-ru/homework_2024_1 pull request #42
Opened 2024-02-12 13:54 UTC by artmzhuk

2024-02-12 15:27 UTC, AlexandraSmirnova commented
Привет, Артем!
Я твой ментор по дз0 и скоро его проверю, если будут вопросы пиши в [телегу](https://t.me/alexandrius23)

2024-02-12 17:07 UTC, artmzhuk commented on source/get.js
> +    for (var i = 0; i < property.length && property[i] != "" && current !== undefined; i++){
> В чем отличие `!=` и `!==` ?

Отличие в том, что `!=` использует приведение типов при сравнении, а `!==` сначала сравнивает типы (если типы не совпадают, то сразу false), а потом проверяет неравенство.

2024-02-12 17:19 UTC, artmzhuk commented on source/get.js
> +function get(object, property){
Есть ещё Function Expression:
`let get = function(object, property) {};`
В отличие от Function Declaration, где функция может быть вызвана раньше, чем она объявлена, Function Expression создаётся, когда до него доходит выполнение.
Также есть отличия по видимости: в строгом режиме Function Declaration доступна только внутри блока кода, но не снаружи. Это можно пофиксить использованием Function Expression

2024-02-12 17:27 UTC, artmzhuk commented on source/get.js
> +    var current = object;
В данном случае стоило бы выбрать let, т.к var это устаревшая конструкция. Я выбрал var по незнанию)
Отличие var от let в том, что var не имеет блочной области видимости, и ограничены, как минимум, телом функции. Также отличие в том, что объявление var происходит в начале функции, вне зависимости от того, в каком реально месте они объявлены.
const -- делает переменную неизменяемой

2024-02-12 17:29 UTC, artmzhuk commented on source/get.js
> +    for (var i = 0; i < property.length && property[i] != "" && current !== undefined; i++){
Мне необходимо выходить из цикла при условии current !== undefined, если я правильно понимаю, выход из forEach можно реализовать только пробросом исключения. Стоит ли здесь так делать?

2024-02-12 17:38 UTC, artmzhuk commented on tests/get.js
> +		assert.strictEqual(get(object, '.baz.3'), object.baz[ 3 ])
поправил

2024-02-12 17:48 UTC, artmzhuk commented on source/get.js
> +function get(object, property){
добавил

2024-02-13 06:20 UTC, artmzhuk commented on source/get.js
> +}
Она необходима для системы контроля версий, чтобы при добавлении чего-либо в конец файла, в git добавлялась новая строка, а не менялась последняя

2024-02-13 09:35 UTC, AlexandraSmirnova commented on source/get.js
> +}
Все так, для контроля версий она нужна, однако не только. При добавлении в конец файла при помощи разных утилит без пустой строки произойдет склеивание текста.

2024-02-13 09:41 UTC, AlexandraSmirnova commented on source/get.js
> +    for (var i = 0; i < property.length && property[i] != "" && current !== undefined; i++){
Верно, !== и === еще называют строгим сравнением, лучше использовать именно строгое сравнение без приведения типов https://learn.javascript.ru/comparison#strogoe-sravnenie

2024-02-13 16:21 UTC, artmzhuk commented on source/get.js
> +function get(object, property){
Переписал на стрелочную функцию

2024-02-14 09:18 UTC, AlexandraSmirnova commented on source/get.js
> +    for (let i = 0; i < propertyArray.length; i++) {
Давай все же заиспользуем forEach, выбросим исключение, когда свойство не найдено, и добавим нужные тесты на отсутствие свойства.

2024-02-14 09:20 UTC, AlexandraSmirnova commented on source/get.js
> +    for (var i = 0; i < property.length && property[i] != "" && current !== undefined; i++){
Да, давай пробрасывать исключение, когда не нашли свойство

2024-02-15 11:29 UTC, AlexandraSmirnova commented on tests/get.js
> +			function(){ get(object, '.0.1.2')},
Очень объемно получилось) давай в таких тестах function заменим на стрелочную функцию, а в параметре с ошибкой написать вместо функции ReferenceError('... <some message>');

2024-02-15 11:52 UTC, AlexandraSmirnova commented on source/get.js
> + * @return {Object|undefined} - Возвращает значение или undefined.
тут еще можно поправить, поскольку теперь у нас прокидывается ошибка и не возвращается явно undefined. Теперь  значение может быть любого типа, в зависимости от свойства объекта.

2024-02-15 12:16 UTC, AlexandraSmirnova commented on source/get.js
> +            current = undefined;
тут можно не присваивать undefined, так как пробрасываем ошибку

2024-02-16 00:07 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-16 00:07 UTC, DPeshkoff commented on source/get.js
> +'use strict';
А что означает эта строчка?

2024-02-16 00:07 UTC, DPeshkoff commented on source/get.js
> +    let propertyArray = property.split('.').slice(1).filter(item => item.length > 0);
А меняется ли propertyArray?

2024-02-16 00:07 UTC, DPeshkoff commented on source/get.js
> +const get = (object, property) => {
Вызываем split у property, но даже не убеждаемся, а точно ли оно строка - предлагаю поправить

2024-02-16 00:07 UTC, DPeshkoff commented on tests/get.js
> +			baz: [ 1, 2, 3, 'undefined' ],
Давай не будем менять исходные тесты

2024-02-16 00:07 UTC, DPeshkoff commented on tests/get.js
> +		assert.throws(() => get(object, '.foobar.length'), ReferenceError('foobar property is undefined'),);
Кажется, тут поменялось поведение - уверен, что так ок?

2024-02-16 05:14 UTC, artmzhuk commented on source/get.js
> +'use strict';
Включение строгого режима. По сути включение "современного" режима, который отключает небезопасные конструкции языка

2024-02-16 09:39 UTC, artmzhuk commented on source/get.js
> +const get = (object, property) => {
Добавил проверку

2024-02-16 09:40 UTC, artmzhuk commented on source/get.js
> +    let propertyArray = property.split('.').slice(1).filter(item => item.length > 0);
Не меняется, исправил на const

2024-02-16 09:44 UTC, artmzhuk commented on source/get.js
> +const get = (object, property) => {
Исправил на исходные

2024-02-16 10:27 UTC, artmzhuk commented on tests/get.js
> +			baz: [ 1, 2, 3, 'undefined' ],
Исправил на исходные

2024-02-18 12:38 UTC, DPeshkoff commented on source/get.js
> +'use strict';
Например, какие?)

2024-02-18 12:38 UTC, DPeshkoff requested changes

2024-02-18 12:38 UTC, DPeshkoff commented on tests/get.js
> +		assert.throws(() => get(object, '.length'), ReferenceError('length property is undefined'),);
Все еще:

![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/35727a52-ca68-4e90-95f8-9c749b72767f)

2024-02-18 13:27 UTC, artmzhuk commented on tests/get.js
> +		assert.throws(() => get(object, '.length'), ReferenceError('length property is undefined'),);
То что поменялось поведение теста "get работает правильно c объектами без свойств" с проверки на undefined, на проверку проброса ReferenceError, то так мы договорились с ментором. Или имеется ввиду другое поведение?

2024-02-18 13:37 UTC, artmzhuk commented on source/get.js
> +'use strict';
1) Принудительно переводит некоторые mistakes в error (как понимаю, это конструкции, которые не выдают error, хотя бы должны)
2) Запрещает присваивание необъявленным переменным
3) Запрещает присваивание тому, чему нельзя присваивать (NaN, Infinity, undefined)
4) Запрещает присваивание getter-only объектам
5) Выбрасывает исключение при попытке удаления св-ва у объекта, которые нельзя удалять (например length)
6) Запрещает одинаковые имена параметров у функции

2024-02-18 16:31 UTC, DPeshkoff commented on tests/get.js
> +		assert.throws(() => get(object, '.length'), ReferenceError('length property is undefined'),);
Хм. И правда договорились)

Тогда ладно, вопрос снимаю

2024-02-18 16:31 UTC, DPeshkoff approved these changes

2024-02-18 16:32 UTC, closed without merging