Лилиана Амирова
frontend-park-mail-ru/homework_2024_1 pull request #43
Opened 2024-02-12 13:57 UTC by endloc

2024-02-12 15:28 UTC, AlexandraSmirnova commented
Привет, Лилиана!
Я твой ментор по дз0 и в течение дня его проверю, если будут вопросы пиши в [телегу](https://t.me/alexandrius23)

2024-02-13 13:51 UTC, AlexandraSmirnova commented on source/zip.js
> +const zip = (...objects) => Object.assign({}, ...objects.reverse());
Давай добавим к твоей функции jsdoc

2024-02-13 13:51 UTC, AlexandraSmirnova commented on source/zip.js
> +const zip = (...objects) => Object.assign({}, ...objects.reverse());
Что будет если передать твоей функции не объект (допустим массив)? Предусмотри, пожалуйста, передачу невалидных аргументов

2024-02-13 13:51 UTC, AlexandraSmirnova commented on tests/zip.js
> +			`zip( {name: "Margo", weight: 49}, {name: "Anna", weight: 49} ) === ${JSON.stringify(obj2)}`);
Этот аргумент для сообщения в случае ошибки, давай здесь и в других похожих тестах для удобства поместим человекочитаемый текст :)

2024-02-13 13:51 UTC, AlexandraSmirnova commented on tests/zip.js
> +});
Добавь пустую строку в конце файла и расскажи для чего нужны пустые строки в конце?

2024-02-14 00:07 UTC, endloc commented on source/zip.js
> +const zip = (...objects) => Object.assign({}, ...objects.reverse());
Добавила обработку невалидных аргументов (массивы отнесла к ним) и тесты с ними. Массивы обозначила отдельно (в jsdoc и в самой функции), так как они также являются объектами, просто особого типа. Из телеги сообщение удалила, так как вроде сама разобралась :)

2024-02-14 00:40 UTC, endloc commented on tests/zip.js
> +});
1) Для гита. Допустим, в конец файла добавлен новый код. Если при предыдущем коммите пустой строки в конце не было, то в diff, помимо нового кода, войдет еще и строка, в которой изменилось лишь одно - добавился символ переноса строки. 
Это ухудшит читаемость и внесет лишний шум.

2) Утилиты Linux, работающие с файлами, воспринимают в качестве самостоятельных строк только те, что заканчиваются символом переноса. Если в конце файла нет пустой строки, то, например, неправильно сработает утилита wc -l (подсчет кол-ва строк).

2024-02-14 09:09 UTC, AlexandraSmirnova commented on .gitignore
> +.idea/
Один файлик остался, он конечно полезный, но для задания не обязательный. хорошо, что используешь .gitignore, и все же не забывай про пустую строку в конце файла :)

2024-02-14 09:11 UTC, AlexandraSmirnova commented on source/zip.js
> +const zip = (...objects) => Object.assign({}, ...objects.reverse());
Отлично, что добавила и сама разобралась 👍

2024-02-14 11:44 UTC, endloc commented on .gitignore
> +.idea/
Так, ты говоришь о README.md или о скриншоте? или вообще о чем-то другом?

2024-02-14 11:47 UTC, endloc commented on source/zip.js
> +    for (let obj of objects) {
переписала, используя reduce

2024-02-14 13:26 UTC, endloc commented on source/zip.js
> +function zip(...objects) {
Основное отличие function declaration (fd) от function expression (fe) в том, что fd создается до исполнения первой строчки кода. Это говорит о том, что мы можем вызывать ее в коде до самого объявления. С fe такое не сработает.

Также особенность fd в том, что если она объявлена внутри блока (допустим, условной конструкции), то использовать мы ее сможем только там же (так как при use strict fd видны только внутри блока, в котором объявлены). Насчет fe - она видна и после блока (в случае условной конструкции: будет использована функция, удовлетворяющая нужному условию).

По поводу arrow function (af) (стрелочная функция): основная ее особенность в том, что она не имеет своего собственного "this". Речь о том, что не создается переменная this, указывающая на объекты, вызывающие функцию (в отличие от fd и fe). this в af указывает на объекты, взятые из внешнего контекста (то, какое значение было у this до объявления af).

Также af - анонимные функции. Допустим, в примере:
    const func = () =>  expression;
func является не именем функции, а переменной, которой присваивается значение, вычисленное с помощью expression.

ps: use strict - строгий режим. 
Когда он включен, интерпретатор js более требователен к коду. Это позволяет предотвратить многие ошибки. Пример: если не включить строгий режим, то не будет сообщения об ошибке при присвоении значения необъявленной переменной. 
Строгий режим контролирует использование устаревших возможностей языка (запрещает их). 
Производительность при включенном строгом режиме возрастает.

2024-02-15 12:03 UTC, AlexandraSmirnova commented on source/zip.js
> +        // reverse() в чистом виде теперь нет, так как подаем sources в assign() в таком порядке,
Хорошо, что оставляешь подробный комментарий! но есть момент: человек который следующим будет читать этот код не поймет о каком reverse  и sources речь, более того это может ввести в заблуждение)

2024-02-15 12:12 UTC, AlexandraSmirnova commented on .gitignore
> +.idea/
Говорила про .gitignore, там не было пустой строки в конце. Скриншот только теперь увидела. Не этот файл как и readme был в задании, можно было не удалять.

2024-02-15 18:14 UTC, endloc commented on tests/zip.js
> +
все исправила;) только хочу спросить: не много ли слов в сообщении к моему последнему коммиту? может как-то оптимизировать стоит в будущем (допустим, писать только самое главное - function comment corrected тут)?

2024-02-16 07:56 UTC, AlexandraSmirnova commented on tests/zip.js
> +
Получилось в сообщении и правда много слов) 
Лучше разбивать на отдельные коммиты в таком случае, но совсем мелко дробить может быть неудобно. Тогда лучше формулировать сообщение так, чтобы было ясно, что объединяет изменения в коммите. Например: "refactor zip.js" или "remove idea files", или еще "fix tests for zip.js". В таких сообщениях нет слишком детальных подробностей, но в целом ясно что за изменения. 
Есть разные статьи на эту тему, рекомендую почитать. Например, статья: https://habr.com/ru/articles/183646/

2024-02-18 16:38 UTC, DPeshkoff requested changes
Привет! Крутое решение, но есть парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-18 16:38 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Не надо было удалять исходное - давай вернем)

2024-02-18 16:38 UTC, DPeshkoff commented on source/zip.js
> +'use strict';
Распиши, пожалуйста, что делает эта строчка

2024-02-18 16:38 UTC, DPeshkoff commented on source/zip.js
> +const zip = (...objects) => {
А что делает ...? Распиши, пожалуйста)

2024-02-18 16:38 UTC, DPeshkoff commented on source/zip.js
> +            throw new Error('The function only accepts objects');
```suggestion
            throw new Error('The function only accepts array of objects');
```

Кажется, так нагляднее. А еще можно throw'ать [это](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-18 16:38 UTC, DPeshkoff commented on tests/zip.js
> +
[Очень годный способ описывать коммиты](https://www.conventionalcommits.org/ru/v1.0.0-beta.4/)

2024-02-18 23:59 UTC, endloc commented on source/zip.js
> +const zip = (...objects) => {
... разделяет объекты там, где их ожидается несколько (при этом может быть и 0, и 1, и, соответственно, больше объектов). В данном случае массив этих объектов называется objects.

2024-02-19 00:09 UTC, endloc commented on source/zip.js
> +'use strict';
Такс, уже было в прошлых комментариях, так что продублирую то, что написала там :)
use strict - строгий режим.
Когда он включен, интерпретатор js более требователен к коду. Это позволяет предотвратить многие ошибки. Пример: если не включить строгий режим, то не будет сообщения об ошибке при присвоении значения необъявленной переменной.
Строгий режим контролирует использование устаревших возможностей языка (запрещает их).
Производительность при включенном строгом режиме возрастает.

2024-02-19 11:58 UTC, DPeshkoff commented on source/zip.js
> +'use strict';
Упс, пропустил, засчитываю)

2024-02-19 11:58 UTC, DPeshkoff approved these changes

2024-02-19 11:58 UTC, closed without merging