Федасов Сергей
frontend-park-mail-ru/homework_2024_1 pull request #44
Opened 2024-02-12 17:28 UTC by Fedasov

2024-02-12 17:35 UTC, Gev0rg commented
Привет!
Меня зовут Геворк, я буду проверять твой ПР в ближайшие дни.
По всем вопросам пиши мне в тг: [Геворк](https://t.me/yurkakurka)

Первый коммент сразу: у тебя многовато непонятных xml файлов, думаю, они лишние

2024-02-13 07:51 UTC, Fedasov commented
Здравствуйте, лишние xml файлы удалил

2024-02-13 20:09 UTC, Gev0rg commented
> Здравствуйте, лишние xml файлы удалил

Давай сразу на ты :)

2024-02-13 20:23 UTC, Fedasov commented
Давай

2024-02-13 21:01 UTC, Fedasov commented
Мне нужно что-то исправить?

2024-02-13 21:05 UTC, Fedasov commented
Слушай, а это не ты в том семестре технопарк закончил? Просто я был на защите проектов и там был парень очень похожий на тебя)

2024-02-13 21:24 UTC, Gev0rg commented
> Мне нужно что-то исправить?

Да, отписал выше

2024-02-13 21:27 UTC, Gev0rg commented
> Слушай, а это не ты в том семестре технопарк закончил? Просто я был на защите проектов и там был парень очень похожий на тебя)

Ага, все так) давай только здесь будем чисто по пр обсуждать, в любой момент можешь в тг написать ;)

2024-02-15 16:22 UTC, Fedasov commented on source/plain.js
> +const plain = (arr) => {
Проверить является ли аргумент массивом?

2024-02-15 16:32 UTC, Fedasov commented on source/plain.js
"use strict" позволяет использовать более строгий и безопасный вариант JavaScript.
При активации он применяет строгие правила и ограничения, помогая выявлять распространенные ошибки.

2024-02-15 16:33 UTC, Fedasov commented on source/plain.js
> +    for (const item of arr) {
Добавил

2024-02-15 16:33 UTC, Fedasov commented on source/plain.js
> +            }
Переписал

2024-02-15 16:36 UTC, Fedasov commented on tests/plain.js
> +	QUnit.test('Написанные тесты для работы с несколькими массивами', function (assert) {
Добавил 3 теста:
1. Работает с вложенными пустыми массивами.
2. Работает с разными типами данных, а также с вложенными массивами. (я не нашёл условие, которое запрещает нам обрабатывать массив из символов)
3. Работает с входными данными не являющимися массивами.

2024-02-15 16:38 UTC, Fedasov commented on source/plain.js
> +const plain = (arr) => {
Добавил

2024-02-15 16:39 UTC, Fedasov commented on source/plain.js
> +const plain = (arr) => {
Добавил проверку на то, что входной аргумент является массивом

2024-02-15 18:10 UTC, Gev0rg commented on source/plain.js
> +const plain = (arr) => {
Это не jsdoc, посмотреть, как правильно можешь [тут](https://jsdoc.app/tags-example) и [тут](https://habr.com/ru/articles/572968/)

2024-02-15 18:10 UTC, Gev0rg commented on source/plain.js
> +    }
Ты перемешал всё в этой проверке, arr.length === 0 - это правильный кейс, тут и правда надо возвращать [], а вот  предыдущих нелбходимо выбрасывать ошибку и соответственно на такие кейсы тесты

2024-02-15 18:10 UTC, Gev0rg commented on source/plain.js
> +        if (Array.isArray(item) === true) {
не нужно проверять на равенство true, т.к. это и так уже boolean, хватит его самого в if

2024-02-15 18:10 UTC, Gev0rg commented on source/plain.js
> +            result = result.concat(item)
Здесь лучше было оставить push, это ведь один элемент

2024-02-15 18:10 UTC, Gev0rg commented on source/plain.js
> +    var result = []
var сильно устарел, есть еще const и let, замени на то, который тебе подходит, и расскажи, в чем разница между ними тремя

2024-02-17 12:13 UTC, Gev0rg commented on source/plain.js
> +const plain = (arr) => {
Всё еще не то, прочитай [эту](https://habr.com/ru/articles/572968/) статью

2024-02-17 12:13 UTC, Gev0rg commented on source/plain.js
> +"use strict";
используй одинарные кавычки, так принято

2024-02-17 12:41 UTC, Gev0rg commented on source/plain.js
> +    if (arr.length == 0) {
В js есть два способа проверки на равенство: == и ===. Расскажи, чем они отлчаются и выбери тот, который здесь тебе больше подходит

2024-02-18 11:29 UTC, Gev0rg commented on source/plain.js
> +const plain = (arr) => {
Это не так, они различаются по нескольким пунктам. И в определенных ситуациях может быть важно выбрать именно одну, а не другую. Почитай [тут](https://habr.com/ru/articles/738146/) и попробуй еще раз объяснить, в чем различия

2024-02-18 11:30 UTC, Gev0rg commented on source/plain.js
> +    var result = []
А чем отличаются var, let, const?

2024-02-18 11:46 UTC, Fedasov commented on source/plain.js
> +    var result = []
Переменные, объявленные при помощи var, имеют глобальную или локальную (в рамках функции) область видимости. Если вы объявляете переменные с использованием let или const, их область видимости будет блочной.
Переменные, объявленные при помощи var, могут обновляться и объявляться заново. Использование let позволяет обновлять переменную, но не объявлять заново, а использование const не предполагает ни того, ни другого.
Переменные всех видов поднимаются в верх своей области видимости. Но переменные, объявленные при помощи var, инициализируются как undefined, а объявленные с использованием let или const — не инициализируются.
При помощи var или let можно объявлять переменные без их инициализации, но если вы объявляете переменную при помощи const, она должна инициализироваться при объявлении.

2024-02-18 11:52 UTC, Fedasov commented on source/plain.js
> +const plain = (arr) => {
Различия:

В синтаксисе (самое очевидное)
Нельзя использовать this
Нельзя получить доступ к аргументам функции
Не позволяет дублировать параметры с одинаковыми именами
Стрелочные функции нельзя использовать с оператором new, в то время как обычные функции можно

2024-02-18 11:54 UTC, Fedasov reviewed
Пояснение

2024-02-18 16:46 UTC, DPeshkoff requested changes
Привет! Хорошее решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-18 16:46 UTC, DPeshkoff commented on source/plain.js
Например, какие?

2024-02-18 16:46 UTC, DPeshkoff commented on source/plain.js
> +        return new Error("The passed argument is not an array!");
Лучше [так](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-18 16:46 UTC, DPeshkoff commented on source/plain.js
> +        return []
Не забывай про ;

<details><summary>Почему это важно?</summary>
<p>

![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/75530df7-18f1-4ff2-bc2d-6da5f342f70b)


</p>
</details>

2024-02-19 14:19 UTC, Fedasov commented on source/plain.js
> +        return new Error("The passed argument is not an array!");
Согласен, поменял на TypeError

2024-02-19 14:24 UTC, Fedasov commented on source/plain.js
> +        return []
; проставил

2024-02-19 14:32 UTC, Fedasov commented on source/plain.js
При активации «use strict»  вводятся следующие ограничения в поведении языка:

1) Невозможно использовать переменные, которые не были объявлены.
2) Невозможно удалить переменные, функции или аргументы функций.
3) Невозможно дублировать параметры функции.
4) Ограничивается использование «this» в функциях, не являющихся методами.

2024-02-19 15:50 UTC, DPeshkoff approved these changes

2024-02-19 15:50 UTC, closed without merging