Жданов Олег
frontend-park-mail-ru/homework_2024_1 pull request #46
Opened 2024-02-13 11:30 UTC by telephonist95

2024-02-13 12:32 UTC, mzingwrld commented
Олег, привет! Меня зовут Ваня. Я буду ревьювером твоего задания

Если вдруг по ходу возникнут вопросы, которые захочешь обсудить лично, ты сможешь написать мне в личку в [телеге](https://t.me/mzingwrld)

2024-02-13 14:12 UTC, mzingwrld commented on source/rle.js
> +    for (let i = 1; i <= input.length; i++) {
Напиши, пожалуйста, какие еще есть способы перебрать символы строки?
Какие плюсы/минусы у каждого по сравнению с этим?

2024-02-13 14:12 UTC, mzingwrld commented on source/rle.js
> +    let prev = input[0];
От этой переменной можно избавиться, используя ниже в цикле обращение относительно индекса

2024-02-13 19:42 UTC, telephonist95 commented on source/rle.js
> +    for (let i = 1; i <= input.length; i++) {
1. **for ... of**
```
for (let l of s) { }
```
_Переберёт все символы строки._

3. **forEach**
```
s.split('').forEach(l => { });
```
_Применит функцию ко всем символам строки._

4. **for ... in**
```
for (let i in s) { }
```
_Переберёт все индексы символов строки._

5. **map**
```
s.split('').map(l => { });
```
_Применит функцию ко всем символам строки._

Мой вариант позволяет получить предыдущий символ в каждой итерации цикла, что не позволяет любой из вариантов итерации посимвольно. Итерацию же я начинаю с индекса 1, что не позволяет вариант номер 4.

2024-02-14 08:00 UTC, mzingwrld commented on source/rle.js
> +    for (let i = 1; i <= input.length; i++) {
Класс, спасибо что расписал.

Тут, наверное, действительно оптимальнее будет оставить твой цикл, тк он не делает дополнительных операций со строкой и будет быстрее, чем `.split('')` и потом еще какой-либо метод перебора

2024-02-14 08:09 UTC, mzingwrld commented on source/rle.js
> +    if (!(typeof input === 'string' || input instanceof String)) {
Расскажи, пожалуйста, для чего тебе нужна вторая проверка? `input instanceof String`

2024-02-14 08:09 UTC, mzingwrld commented on source/rle.js
> +	if (input[i] === input[i-1]) {
Минорная история по форматированию (и ниже тоже поправь, пожалуйста): 

```suggestion
	if (input[i] === input[i - 1]) {
```

Так более читаемо

2024-02-14 08:09 UTC, mzingwrld commented on source/rle.js
> +    }
Проверку на строку можно вынести в функцию-хелпер, например `isString` - код от этого тоже станет более читаемым)

2024-02-14 08:09 UTC, mzingwrld commented on source/rle.js
> +    return result;
Есть такая практика - "clean code". На досуге можешь посмотреть)

Так вот, там, да и не только там, рекомендуют перед return-ом делать перенос строки, чтобы не слипалось с остальным кодом)

2024-02-14 08:09 UTC, mzingwrld commented on source/rle.js
> +}
Задам пару вопросов:
1) для чего нужна строка 'use strict'  в .js файлах?
2) чем отличается стрелочная функция от обычной?

2024-02-14 18:47 UTC, telephonist95 commented on source/rle.js
> +    if (!(typeof input === 'string' || input instanceof String)) {
Для работы со строками, которые были созданы с помощью оператора **new**:
```
var foo = new String('simple');
console.log(typeof foo);            // object
console.log(foo instanceof String); // true
```

2024-02-14 19:08 UTC, telephonist95 commented on source/rle.js
> +}
1. Данная конструкция включает так называемый "строгий режим", который меняет семантику языка, вызывая исключения для потенциальных ошибок в коде, которые игнорируются в обычном режиме, что позволяет разрабатывать более безопасный и быстрый код.
2. Отличия стрелочной функции от обычной:
2.1. Стрелочные функции не имеют ссылки **arguments**.
2.2. Стрелочные функции не имеют ссылки **this**.
2.3. Стрелочные функции невозможно вызвать с помощью оператора **new**.
2.4. Параметры стрелочных функций не могут иметь одинаковые имена (даже в обычном режиме).

2024-02-15 04:04 UTC, mzingwrld commented on source/rle.js
> +    if (!(typeof input === 'string' || input instanceof String)) {
Такой кейс тоже стоит добавить в unit тесты для прозрачности

1) если кто-то решит это условие удалить, то у него упадет проверка и он увидит что это для чего-то там нужно)
2) по юнит тестам некоторые люди смотрят как работает функция - это тоже элемент описания)

2024-02-15 06:23 UTC, mzingwrld commented on source/rle.js
> +}
По второму пункту: почему ты выбрал именно их для использования?

2024-02-15 06:24 UTC, mzingwrld commented
Отписал пару мелких моментов, поправь их, пожалуйста)

Также задал вопрос про стрелочные функции в тред.

2024-02-18 08:26 UTC, telephonist95 commented on source/rle.js
> +}
0. Потому что они были в примере).
1. Синтаксис более компактный.

2024-02-19 17:02 UTC, DPeshkoff commented on source/rle.js
> +const isString = (obj) => {
Давай в строгом режиме

2024-02-19 17:02 UTC, DPeshkoff commented on source/rle.js
> +const rle = (input) => {
Нужно добавить JSDoc к этой и всем остальным функциям

2024-02-19 17:02 UTC, DPeshkoff commented on source/rle.js
> +	throw new Error('Parameter is not a string or missing!');
Лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-19 17:04 UTC, DPeshkoff commented on tests/rle.js
> -	});
Здесь не нужен diff

2024-02-19 17:31 UTC, telephonist95 commented on tests/rle.js
> -	});
У меня другие отступы в редакторе

2024-02-21 16:20 UTC, DPeshkoff requested changes

2024-02-21 16:20 UTC, DPeshkoff commented on source/rle.js
> +const rle = (input) => {
нужно больше информации и оформить [правильно](https://jsdoc.app/about-getting-started)

2024-02-21 16:20 UTC, DPeshkoff commented on tests/rle.js
> -	});
Надо настроить редактор так, чтобы он не менял)

2024-02-21 16:20 UTC, DPeshkoff commented on source/rle.js
> +"use strict";
Одиночные кавычки

2024-02-22 10:39 UTC, DPeshkoff requested changes

2024-02-22 10:39 UTC, DPeshkoff commented on source/rle.js
> + * Throw TypeError if argument is not a string or missing.
`@throws`

2024-02-22 13:35 UTC, DPeshkoff approved these changes

2024-02-22 13:36 UTC, closed without merging