Алцыбеева Маргарита
frontend-park-mail-ru/homework_2024_1 pull request #47
Opened 2024-02-13 14:10 UTC by marrgancovka

2024-02-13 15:26 UTC, Gev0rg commented
Привет, Маргарита!
Меня зовут  Геворк, я буду проверять твой ПР в ближайшие дни.
По всем вопросам пиши мне в тг: [Геворк](https://t.me/yurkakurka)

2024-02-14 14:14 UTC, marrgancovka commented on source/anagram.js
> +'use strict';
Директива 'use strict' включает строгий режим интерпретатора. Он запрещает использование небезопасных конструкций, приводящим к ошибкам, которые проигнорировались бы в обычном режиме, например, использование необъявленной переменной и наличие одинаковых имен у аргументов функции

2024-02-14 14:26 UTC, marrgancovka commented on source/anagram.js
> +const anagram = (words) => {
Обычные функции интерпретатор создает до выполнения кода, поэтому их можно вызвать до объявления.
Стрелочные функции нельзя вызвать до объявления, они не имеют this и собственного объекта arguments

2024-02-15 06:04 UTC, Gev0rg commented on source/anagram.js
> +const anagram = (words) => {
Да, всё верно, ещё стрелочные функции нельзя вызывать с оператором new, и они не допускают одинаковые имена аргументов в любом режиме

2024-02-15 23:45 UTC, DPeshkoff commented on source/anagram.js
> +    if (!words.every(word => typeof word === 'string')) {
<img width="340" alt="Снимок экрана 2024-02-16 в 02 45 46" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/46c9c84a-4f08-4a34-a9c3-a5837ce652b7">

Предлагаю поправить)

2024-02-15 23:46 UTC, DPeshkoff commented on source/anagram.js
> +        throw new Error("All elements in the input array must be strings");
Тоже по типу + в JS приняты одиночные кавычки - давай поменяем везде

2024-02-15 23:46 UTC, DPeshkoff commented on source/anagram.js
> +        let sorted = word.toLowerCase().split("").sort().join("");
Где-то изменяется?)

2024-02-18 15:55 UTC, DPeshkoff requested changes

2024-02-18 15:55 UTC, DPeshkoff commented on source/anagram.js
> +    let groups = new Map();
Где-то разве меняем?)

А в чем вообще заключается константность const? Можешь расписать, пожалуйста?

2024-02-18 21:50 UTC, marrgancovka commented on source/anagram.js
> +    let groups = new Map();
Исправила.
const задаёт константу, то есть переменную, которую нельзя менять, то есть идентификатор не может быть изменен.  Если в константу присвоен объект, то от изменения защищена сама константа, но не свойства внутри неё.

2024-02-19 11:53 UTC, DPeshkoff approved these changes

2024-02-19 11:53 UTC, closed without merging