Карпов Иван
frontend-park-mail-ru/homework_2024_1 pull request #49
Opened 2024-02-13 20:01 UTC by Karpov-Ivan

2024-02-14 16:32 UTC, Karpov-Ivan commented on source/filter.js
> +function filter(input, allowedTags) {
Переделал
Различия:
1. В синтаксисе (самое очевидное)
2. Нельзя использовать this
3. Нельзя получить доступ к аргументам функции
4. Не позволяет дублировать параметры с одинаковыми именами

2024-02-14 16:32 UTC, Karpov-Ivan commented on source/filter.js
> +function filter(input, allowedTags) {
Сделал. Добавил тесты и в файл с тестами, и в файл со скриптом

2024-02-14 16:32 UTC, Karpov-Ivan commented on source/filter.js
> +function filter(input, allowedTags) {
Добавил

2024-02-14 16:32 UTC, Karpov-Ivan commented on tests/filter.js
> +    const expected = "";
Исправил

2024-02-14 16:32 UTC, Karpov-Ivan commented on source/filter.js
> +    const openingTagPattern = new RegExp(`&lt;${tag}&gt;`, "g");
RegExp это объект для работы с регулярными выражениями. Браузер при компиляции воспринимает < как начало тэга, что может привести к ошибке. Поэтому отдельные (не закрывающие <) и  интерпритируются в &lt, чтобы отличать. До создания этого объекта я заменил все знаки и даже тэги теперь выглядят как &lt;${tag}&gt; , мне нужно найти такие выражения и заменить их обратно на нормальные тэги. Поэтому я задаю такое выражение и передаю туда тэги, которые я получил из вне в функцию. Флаг g указывает, что ищутся все совпадения. И в итоге, ищутся точные совпадения данного выражения в строке. 
Я думаю, что их лучше избегать из-за нечитаемости при возрастании сложности логики. Также в интеренете пишут, что медленнее выполняться могут.

2024-02-14 16:32 UTC, Karpov-Ivan commented on source/filter.js
> +    escapedText = escapedText
Исправил, надеюсь правильно смысл понял

2024-02-14 16:32 UTC, Karpov-Ivan commented on source/filter.js
> +"use strict";
В начале я её добавил, потому что в образце такая строчка тоже была. Переводится как "использовать строгий". Я думаю, что она указывает компилятору, что нужно более строго относиться к написанному коду. Например, если мы объявили переменную и не используем, то будет показываться ошибка. Ну и в целом, смотрит на уязвимости в коде

2024-02-14 16:36 UTC, Karpov-Ivan commented on source/filter.js
> +    const openingTagPattern = new RegExp(`&lt;${tag}&gt;`, "g");
Мне знаки &lt; и &gt;  github сам заменяет на нормальный тэг <${tag}>
Вот пример фильтра html-кода хех)

2024-02-15 05:22 UTC, Gev0rg commented on source/filter.js
> +"use strict";
На самом деле ответ вышел довольно неточным, попробуй поискать в интернете и ответить снова, любые вопросы можно и нужно гуглить, это процентов 70 твоей работы в будущем ;)

2024-02-15 05:29 UTC, Gev0rg commented on source/filter.js
> +function filter(input, allowedTags) {
Да, всё так, ещё стрелочные функции нельзя использовать с оператором new, в то время как обычные функции можно

2024-02-15 14:24 UTC, Karpov-Ivan commented on source/filter.js
> +"use strict";
В общем, долгое время JS развивался с обратной совместимостью и поэтому многие ошибки оставались в языке. С появлением ES5 внесли изменение и добавили директиву "use strict", которая означает использование строгого режима. 
В строгом режиме:
 - нельзя присваивать значение в неопределённую переменную
 - delete приводит к ошибке, если аргумент - не изменяемое свойство объекта
 - нельзя использовать инструкцию with
 - нельзя определить повторные свойства в литерале объекта
 - нельзя определить повторные формальные параметры функции
 - изменения объекта arguments не изменяют аргументы
 - eval не может инстанциировать переменные и функции в контексте вызова
 - this не преобразуется в объект, а если значение this - undefined или null, то не преобразуется в глобальный объект
 - eval и arguments - нельзя изменить или использовать в качестве имени
 - больше слов, зарезервированных для использования в будущем
 - нельзя использовать литералы восьмиричной CC

2024-02-16 09:05 UTC, Karpov-Ivan commented on source/filter.js
> +    escapedText = escapedText
Вернул

2024-02-16 09:06 UTC, Karpov-Ivan commented on tests/filter.js
> +      assert.strictEqual(output, expected);
Сделал

2024-02-18 16:54 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-18 16:54 UTC, DPeshkoff commented on source/filter.js
> +    throw new Error("Invalid input. 'allowedTags' must be an array.");
Лучше [так](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-18 16:54 UTC, DPeshkoff commented on source/filter.js
> +  if (typeof input !== "string") {
А такие строки не пройдут:

<img width="340" alt="Снимок экрана 2024-02-16 в 02 45 46" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/46c9c84a-4f08-4a34-a9c3-a5837ce652b7">

Предлагаю поправить)

2024-02-18 16:54 UTC, DPeshkoff commented on source/filter.js
> +    throw new Error("Invalid input. 'input' must be a string.");
В JS принято писать строки с одиночными кавычками - давай поправим)

2024-02-18 16:54 UTC, DPeshkoff commented on source/filter.js
> +    escapedText = escapedText
Не забывай про ;

<details><summary>Почему это важно?</summary>
<p>

![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/75530df7-18f1-4ff2-bc2d-6da5f342f70b)


</p>
</details>

2024-02-18 16:54 UTC, DPeshkoff commented on source/filter.js
> +}
А зачем это тут? Это надо в тестах)

2024-02-18 16:54 UTC, DPeshkoff commented on tests/filter.js
Давай не будем изменять исходный код и вернем так, как было

2024-02-18 20:01 UTC, Karpov-Ivan commented on source/filter.js
> +    throw new Error("Invalid input. 'allowedTags' must be an array.");
Поправил

2024-02-18 20:06 UTC, Karpov-Ivan commented on source/filter.js
> +  if (typeof input !== "string") {
Исправил

2024-02-18 20:35 UTC, Karpov-Ivan commented on source/filter.js
> +    throw new Error("Invalid input. 'input' must be a string.");
Везде поправил

2024-02-18 20:36 UTC, Karpov-Ivan commented on source/filter.js
> +}
Ментор написал "написать тесты ниже", возможно не так трактовал я

2024-02-18 20:52 UTC, Karpov-Ivan commented on source/filter.js
> +    throw new Error("Invalid input. 'input' must be a string.");
В общем, авто-исправление при сохранении меняли все ' на " ...

2024-02-18 20:53 UTC, Karpov-Ivan commented on source/filter.js
> +    escapedText = escapedText
Так там же есть ;
Просто там дальше идёт replace, после которого стоит ;

2024-02-18 20:53 UTC, Karpov-Ivan commented on source/filter.js
> +}
В тестах это тоже есть если что

2024-02-18 20:54 UTC, Karpov-Ivan commented on tests/filter.js
Вот тут также как с ' и "
Авто-исправление решило сделать по-своему
Я всё вернул и отключил эту штуковину)

2024-02-19 12:19 UTC, DPeshkoff commented on source/filter.js
> +    escapedText = escapedText
Проглядел, сорре)

2024-02-19 13:19 UTC, Karpov-Ivan commented on source/filter.js
> +function escapeHTML(text) {
Сделал

2024-02-19 15:43 UTC, closed without merging