Finish
frontend-park-mail-ru/homework_2024_1 pull request #5
Opened 2024-02-10 11:40 UTC by DeadBread-001

Выполнил задание 2 варианта + тесты

2024-02-10 16:34 UTC, mzingwrld commented
Никита, привет! Я Ваня. Я буду ревьювером твоего задания

Если вдруг по ходу возникнут вопросы, ты сможешь написать мне в личку в [телеге](https://t.me/mzingwrld)

2024-02-10 18:28 UTC, mzingwrld requested changes

2024-02-10 18:49 UTC, DeadBread-001 commented on source/euclid.js
> +'use strict';
Для запрета использования устаревших и небезопасных конструкций и избежания ошибок, которые могли бы быть проигнорированы, если бы мы не написали use strict

2024-02-10 19:01 UTC, DeadBread-001 commented on source/euclid.js
> +const euclid = (...numbers) => nod(...numbers);
Во время работы с Git при добавлении новой строки кода в конец будет добавлен символ новой строки. Git будет помечать её как изменённую, что может запутать при просмотре реальных изменений

2024-02-10 19:10 UTC, DeadBread-001 commented on source/euclid.js
> +    const nod2 = (a, b) => (b === 0 ? a : nod2(b, a % b));
Функция `nod2` производит поиск наибольшего общего делителя для двух чисел алгоритмом Евклида через рекурсию

2024-02-10 19:17 UTC, DeadBread-001 commented on source/euclid.js
> +const euclid = (...numbers) => nod(...numbers);
Изначально планировал сделать проверку входных значений в `euclid` и рекурсивное решение в `nod`, но пришел к другому решению и забыл исправить

2024-02-11 04:22 UTC, mzingwrld commented on index.html
> +
Минорное: можно убрать лишнюю новую строку)

2024-02-11 04:22 UTC, mzingwrld commented on source/euclid.js
> +const greatestCommonDivisor = (a, b) => (b === 0 ? a : greatestCommonDivisor(b, a % b));
Давай поговорим еще про рекурсии: какие у них есть плюсы, а какие минусы?

2024-02-11 04:22 UTC, mzingwrld commented on source/euclid.js
> +    return result;
Вопрос со звездочкой: а сможем ли мы перейти здесь на использование numbers.reduce ? https://learn.javascript.ru/array-iteration#reduce-reduceright

2024-02-11 09:15 UTC, DeadBread-001 commented on source/euclid.js
> +const greatestCommonDivisor = (a, b) => (b === 0 ? a : greatestCommonDivisor(b, a % b));
Рекурсия достаточно быстрая и простая в написании и поддержке, а также уменьшает дублирование кода. Но нам приходится жертвовать памятью, т.к. при углублении в рекурсию каждый раз создается новый экземпляр функции и если не учесть это, то может произойти переполнение стека

2024-02-11 09:25 UTC, DeadBread-001 commented on source/euclid.js
> +    if (numbers.some(isNaN)) {
isNaN (is not a number) преобразует значение в число и в зависимости от результата будет выдавать true/false. Гарантией того, что там будет именно не натуральное число, т.к. при вводе отрицательных значений результатом будет false, поэтому после этого идет проверка конкретно на натуральные числа

2024-02-11 09:48 UTC, DeadBread-001 commented on source/euclid.js
> +const euclid = (...numbers) => {
Результатом будет undefind. Может быть введено вещественное число

2024-02-11 09:50 UTC, DeadBread-001 commented on source/euclid.js
> +    if (numbers.length < 2) {
Да, в данной ситуации больше подходит строгое сравнение

2024-02-11 09:54 UTC, DeadBread-001 commented on source/euclid.js
> +        return 'Все числа должны быть натуральными.';
Да, как раз это будет покрывать вещественные числа и строки + не натуральные значения. Эту проверку можно вынести, т.к. она может потребоваться не только в этой задаче

2024-02-11 10:04 UTC, DeadBread-001 commented on source/euclid.js
> +    return result;
Думаю, да, т.к. у нас здесь используются промежуточные результаты вычислений, что используется в методе reduce

2024-02-11 15:53 UTC, mzingwrld commented on source/euclid.js
> +const euclid = (...numbers) => {
Мне все нравится, но нет обработки случая, когда `numbers` будет `undefined`

Давай ее добавим?

2024-02-12 15:33 UTC, mzingwrld commented on source/euclid.js
> +    return numbers.every(number => Number.isInteger(number) && number > 0) && !(numbers.length === 0);
@DeadBread-001, еще стоит добавить тест на это и вместо `!(numbers.length === 0)` есть более простая запись:

```suggestion
    return numbers.every(number => Number.isInteger(number) && number > 0) && numbers.length !== 0;
```

Тем не менее, эта не проверка на `undefined` :)

2024-02-12 18:19 UTC, DeadBread-001 commented on source/euclid.js
> +    return numbers.every(number => Number.isInteger(number) && number > 0) && !(numbers.length === 0);
Запись упрощу, но есть вопрос. Всё-таки если подать в функцию undefined либо вообще ничего не вводить, то это попадает под условия в проверке на валидность. Или лучше стоит добавить `numbers !== undefined`?

2024-02-13 22:06 UTC, DPeshkoff requested changes
Привет!

Классное решение, мне почти ок)

Если будут вопросы, можешь написать в [Telegram](t.me/DmPesh)

2024-02-13 22:06 UTC, DPeshkoff commented on source/euclid.js
> +        throw new Error("Все числа должны быть натуральными.");
Кажется, можно кое-что [получше](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-13 22:06 UTC, DPeshkoff commented on source/euclid.js
> +    if (numbers.length === 1) {
Можно [сократить](https://developer.mozilla.org/ru/docs/Glossary/Truthy) (выше тоже!)

2024-02-13 22:06 UTC, DPeshkoff commented on source/euclid.js
> +const euclid = (...numbers) => {
Давай добавим JSDOC сюда и во все функции)

2024-02-14 21:17 UTC, DPeshkoff approved these changes

2024-02-14 21:17 UTC, closed without merging