Атрошко Никита
frontend-park-mail-ru/homework_2024_1 pull request #51
Opened 2024-02-13 23:33 UTC by broadcast80

Вариант 2

2024-02-14 06:24 UTC, F4lkr4m commented
Привет еще раз!) Я буду проверять твое ДЗ №0. Свои вопросы, комментарии и предложения оставлю в PullRequest'е, если будут какие-то вопросы, всегда можешь обратиться ко мне в личку https://t.me/Falkr4m

2024-02-14 06:39 UTC, F4lkr4m requested changes
Получилось хорошее решение, как поправишь - пингани меня в телеге

2024-02-14 06:39 UTC, F4lkr4m commented on index.html
> -<script src="source/max.js"></script>
Давай max не будем трогать, вернем как было. Это не влияет ни на что, просто чтобы было как у общей массы

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +'use strict';
Можешь рассказать для чего используется эта директива?

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +const euclid = (...args) => {
Молодец, что использовал стрелочную функцию. Можешь рассказать в чем отличие стрелочной функции от записи через слово 'function'

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +const euclid = (...args) => {
Также было бы круто написать JSDoc для функции, также в нем не забудь указать тип ошибки, который выбрасывает функция

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +            throw new Error('Недопустимый аргумент: все аргументы должны быть натуральными конечными числами');
Круто что выкидываешь ошибки при обработке параметров, но помимо обычного new Error можно воспользоваться уже готовыми другими типами ошибок: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error
Посмотри, может тут что то подойдет тебе больше в твоем случае)

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +        else return euclid(args[1], args[0] % args[1]);
Здесь else не нужен

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +        if (args[1] === 0) return args[0];
Давай все конструкции if делать с фигурными скобочками - так более читабильно, также тело фигурной скобки с новой строки

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +    }   else if (args.length > 2) {
Здесь else тоже не нужен

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +    if (args.length === 2) {
Я бы также внутри этого if сохранил бы args[0] и args[1] в переменные

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +    if (args.length === 1) {
Как вариант - можно сделать switch (args.length) { // тут обработать все кейсы для длины }

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +        return args.reduce((result, current) => euclid(result, current));
Круто, что ты используешь reduce

2024-02-14 06:39 UTC, F4lkr4m commented on tests/euclid.js
> -	QUnit.test('Функция должна правильно находить НОД трёх натуральных чисел', function (assert) {
Давай вернем тесты, которые были и просто к ним добавим наши

2024-02-14 06:39 UTC, F4lkr4m commented on source/euclid.js
> +    if (args.length === 2) {
2 - уже будет магическим числом, надо в константу

2024-02-14 16:31 UTC, broadcast80 commented on source/euclid.js
> +const euclid = (...args) => {
Стрелочные функции не имеют ключевого слова this, ссылки на обьект arguments а также не позволяют использовать дублирующиеся имена элементов.

2024-02-14 18:41 UTC, F4lkr4m requested changes
Тесты поправить, а так все супер

2024-02-14 18:41 UTC, F4lkr4m commented on tests/euclid.js
> -	QUnit.test('Функция должна правильно находить НОД трёх натуральных чисел', function (assert) {
Все еще актуально

2024-02-14 18:41 UTC, F4lkr4m commented on source/euclid.js
> +            throw new Error('Недопустимый аргумент: все аргументы должны быть неотрицательными числами');
Мне кажется сюда подойдет ошибка RangeError

2024-02-14 18:41 UTC, F4lkr4m commented on source/euclid.js
> + * @throws {TypeError|Error}
TypeError | Error - пробел между объединением

2024-02-14 19:20 UTC, F4lkr4m approved these changes
lgtm

2024-02-16 00:05 UTC, DPeshkoff requested changes
Привет! Классное решение, близок к аппруву)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-16 00:05 UTC, DPeshkoff commented on source/euclid.js
> +        if (typeof arg != 'number' || !isFinite(arg)) {
Строгие проверки лучше нестрогих)

2024-02-16 00:05 UTC, DPeshkoff commented on source/euclid.js
> +const euclid = (...args) => {
А что означают ...?

2024-02-16 17:59 UTC, broadcast80 commented on source/euclid.js
> +const euclid = (...args) => {
Это остаточный параметр. Если последний именованный аргумент функции имеет префикс ..., он автоматически становится массивом с элементами от 0 до args.length - 1

2024-02-18 15:56 UTC, DPeshkoff approved these changes

2024-02-18 15:56 UTC, closed without merging