Completed the task and added some tests
frontend-park-mail-ru/homework_2024_1 pull request #52
Opened 2024-02-14 14:32 UTC by MrDzhofik

Джафаров Эмиль

2024-02-14 18:46 UTC, F4lkr4m commented
Привет! Я буду проверять твое ДЗ №0. Свои вопросы, комментарии и предложения оставлю в PullRequest'е, если будут какие-то вопросы, всегда можешь обратиться ко мне в личку https://t.me/Falkr4m

2024-02-14 19:08 UTC, F4lkr4m requested changes
Хорошее решение получилось, оставил комментарии, как поправишь - пингани меня в телеге

2024-02-14 19:08 UTC, F4lkr4m commented on source/sort.js
> +    sentence = sentence.trim().split(' ').filter(word => word !== ''); // удаляем лишние пробелы
в filter аргумент функции word давай обернем в скобочки - так читабильнее

2024-02-14 19:08 UTC, F4lkr4m commented on source/sort.js
> +    sentence = sentence.trim().split(' ').filter(word => word !== ''); // удаляем лишние пробелы
не перезаписываем sentence

2024-02-14 19:08 UTC, F4lkr4m commented on source/sort.js
> +    return sentence.map(sortLetters).sort((word, slovo) => word.localeCompare(slovo)).join(' ');
Ну тут все то же самое, я думаю ты уже понял)))0)

2024-02-14 19:08 UTC, F4lkr4m commented on tests/sort.js
> +		// assert.strictEqual(sort('Rrrrrrrr'), 'rrrrrrrr'); // Я думаю тут ошибка тестов, ведь нам надо делать первую букву прописной, а остальные строчными
Да, согласен

2024-02-14 19:08 UTC, F4lkr4m commented on tests/sort.js
> +		// assert.strictEqual(sort('космический корабль летит на марс'), 'Абклорь Амрс Aн Еиийккмоссч Еилтт'); // тут в заданном предложении все русские буквы, а в результате присутствует одна латинская A
Тоже согласен

2024-02-14 19:08 UTC, F4lkr4m commented on tests/sort.js
> +	QUnit.test('Функция работает правильно с разными регистрами', function (assert) {
Молодец, что добавил свои тесты

2024-02-14 19:08 UTC, F4lkr4m commented on source/sort.js
> +function sort(sentence) {
Надо добавить обработку входных данных на ошибочные значения

2024-02-14 19:09 UTC, F4lkr4m commented
Также поправь название PR'та на Фамилия Имя

2024-02-14 21:23 UTC, MrDzhofik commented on source/sort.js
> +'use strict'
Директива используется для включения строгого режима. Он указывается, чтобы предотвратить выполнение устаревшего кода

2024-02-14 21:28 UTC, MrDzhofik commented on source/sort.js
> +function sortLetters(word) {
В стрелочной функции нельзя изменить this, он вычисляется в момент создания функции и не изменяется на протяжении работы программы. Еще нет доступа до переменной arguments. Вместе со стрелочной функцией нельзя использовать ключевые слова new и yield

2024-02-15 06:15 UTC, F4lkr4m commented on source/sort.js
> +function sortLetters(word) {
Также стоит отметить, что стрелочная функция ссылается на внешний контекст и не имеет свой вовсе

2024-02-15 06:21 UTC, F4lkr4m requested changes

2024-02-15 06:21 UTC, F4lkr4m commented on source/sort.js
> +        .sort((letter, char) => letter.localeCompare(char))
Тут у тебя не разные сущности сравниваются, а две одинаковые поэтому можно назвать letterA, letterB

2024-02-15 06:21 UTC, F4lkr4m commented on source/sort.js
> +/* Сортировка букв в слове */
Нужно написать документацию в формате https://jsdoc.app)

2024-02-15 06:21 UTC, F4lkr4m commented on source/sort.js
> +    if (typeof (sentence) !== "string") {
Скобочки не нужны для sentence

2024-02-15 06:21 UTC, F4lkr4m commented on source/sort.js
> +        return "Необходимо ввести строку"
Возвращаешь строку?) Мне кажется это плохой вариант возвращаемого значения) Лучше возвращать undefined или null. А еще лучше выбрасывать ошибку: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error - тут ты можешь выбрать наиболее подходящий тебе тип ошибки

2024-02-15 06:21 UTC, F4lkr4m commented on source/sort.js
> +    const newWord = word
Правильно что используешь const. А можешь рассказать чем отличается инициализация переменной через let/const/var?

2024-02-15 12:01 UTC, MrDzhofik commented on source/sort.js
> +    const newWord = word
У let и var есть одно небольшое различие - область видимости. Var-переменные видны вне блока, они ограничиваются только функцией. Объявление переменной через const делает ее неизменяемой

2024-02-15 18:02 UTC, F4lkr4m requested changes
Чуть-чуть поправить

2024-02-15 18:02 UTC, F4lkr4m commented on source/sort.js
> + * @returns {{sentence | TypeError}} - отсортированное предложение или null,
Типа sentence нет. Есть только string. Тем более функция не может вернуть ошибку, только выкинуть ее

2024-02-15 18:02 UTC, F4lkr4m commented on source/sort.js
> +    if (typeof (sentence) !== "string") {
typeof sentence !== "string"

2024-02-15 18:17 UTC, F4lkr4m reviewed
lgtm

2024-02-15 23:43 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-15 23:43 UTC, DPeshkoff commented on index.html
> +</html>
Здесь не нужен diff, давай вернем, как было

2024-02-15 23:43 UTC, DPeshkoff commented on source/sort.js
> +'use strict'
А что именно подразумевает собой строгий режим?

2024-02-15 23:43 UTC, DPeshkoff commented on source/sort.js
> +    if (typeof sentence !== "string") {
Валидная строка, а не пройдет

<img width="351" alt="Снимок экрана 2024-02-16 в 02 41 50" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/804205f3-3cc6-4f3d-b26d-6435d9eb0e70">

2024-02-15 23:43 UTC, DPeshkoff commented on tests/sort.js
> +	QUnit.test('Функция работает правильно с пустой строкой', function (assert) {
А если на входе будет не строка? Давай добавим тесты на некорректный ввод

2024-02-15 23:43 UTC, DPeshkoff commented on source/sort.js
> +}
\n

2024-02-15 23:43 UTC, DPeshkoff commented on source/sort.js
> +        return new TypeError("Необходимо ввести строку");
В JS приняты одиночные кавычки, давай везде поменяем

2024-02-15 23:43 UTC, DPeshkoff commented on source/sort.js
> +const sortLetters = (word) => {
А чем отличаются стрелочные функции от обычных?

2024-02-16 12:27 UTC, MrDzhofik commented on source/sort.js
> +'use strict'
Строгий режим изменяет поведение интерпретатора, не позволяя ему запускать небезопасные или устаревшие функции. Строгий режим не даёт системе игнорировать ошибки, выдавая соответствующие исключения. Это приводит к остановке выполнения программ. Он помогает JS-движкам оптимизировать код.

2024-02-18 15:58 UTC, DPeshkoff requested changes

2024-02-18 15:58 UTC, DPeshkoff commented on source/sort.js
> +}
Не изменилось, давай поправим настройки IDE, чтобы она не убирала автоматом)

[Почему важно](https://semakin.dev/2020/05/no_newline_at_end_of_file/)

2024-02-18 15:58 UTC, DPeshkoff commented on index.html
> +	<title>Домашнее задание: пример</title>
Какой-то пример (а вроде не пример, а вариант 8)

2024-02-18 16:01 UTC, MrDzhofik commented on source/sort.js
> +}
Я в первый раз не понял,что имелось в виду под \n, поэтому и не менял)

2024-02-18 17:11 UTC, DPeshkoff approved these changes

2024-02-18 17:12 UTC, closed without merging