Титов Егор
frontend-park-mail-ru/homework_2024_1 pull request #53
Opened 2024-02-14 15:22 UTC by EGRoBBeRTiT

2024-02-15 07:54 UTC, Gev0rg commented
Привет, Егор!
Меня зовут Геворк, я буду проверять твой ПР в ближайшие дни.
По всем вопросам пиши мне в тг: [Геворк](https://t.me/yurkakurka)

2024-02-15 08:30 UTC, Gev0rg commented on source/inverse.js
> +// ? Решение 1. Красивое и короткое, но не лучшее,
Молодец, что сделал несколько решений, но давай уберем весь закомментированный код из мр

2024-02-15 09:08 UTC, EGRoBBeRTiT commented on source/inverse.js
> +    if (typeof num !== "number") {
Точно, не заметил. Тесты проходили, сейчас не проходят, что логично)

2024-02-15 09:13 UTC, EGRoBBeRTiT commented on source/inverse.js
> +        : [...arr.slice(0, num).reverse(), ...arr.slice(num, arr.length)];
Честно говоря, специально не вынес, чтобы лишней памяти не создавать. Тут не пересчитывается на самом деле, потому что, `arr.slice(0, num)` и `arr.slice(num, arr.length)` посчитается один раз, они же в тернарнике, поэтому в зависимости от условия будет же один вариант только

2024-02-15 09:20 UTC, EGRoBBeRTiT commented on source/inverse.js
> +const inverse = (arr, num) => {
*

2024-02-15 09:38 UTC, EGRoBBeRTiT commented on source/inverse.js
> +"use strict";
На самом деле, тут в этом надобности не было, просто это уже стандарт использования. Эта строчка включает "use strict" директиву, которая выбрасывает ошибки там, где они не выбрасывались без "use strict". Например, присваивание значения глобальным константам выдаст ошибку: `NaN = 5;`.
Весь код, располагающийся  ниже "use strict", будет работать в "строгом режиме" в одной области видимости. То есть если в нестрелочной функции написать "use strict", то только код кнутри этой функции будет в строгом режиме.

2024-02-15 18:12 UTC, Gev0rg commented
Не закрывай только комментарии, тебе нужно только отвечать на них, закрываю их я, если поправил)

2024-02-15 18:15 UTC, Gev0rg commented on source/inverse.js
> +        : [...arr.slice(0, num).reverse(), ...arr.slice(num, arr.length)];
Да, ты прав, но читать стало проще

2024-02-15 18:17 UTC, Gev0rg commented on source/inverse.js
> +// ? Решение 5. 👍
давай и эту строку удалим с комментом

2024-02-15 18:17 UTC, Gev0rg commented on source/inverse.js
> +    }
на вот эти выбросы ошибок тоже нужны тесты

2024-02-15 18:17 UTC, Gev0rg commented
Ещё переимену правильно ПР, он должен включать только фамилию и имя

2024-02-16 07:46 UTC, Gev0rg commented on source/inverse.js
> +    }
Если этот блок поднять повыше, то из верхнего условия пропадет одна проверка ;)

2024-02-16 07:46 UTC, Gev0rg commented on source/inverse.js
> +    }
Хотя нет, всё правильно, только теперь этот блок мы може вообще убрать, или же очевидно проверять на 0

2024-02-16 07:46 UTC, Gev0rg commented on source/inverse.js
> +"use strict";
Давай везде в js файлах использовать одинарные ковычки, так принято

2024-02-16 07:51 UTC, EGRoBBeRTiT commented on source/inverse.js
> +    }
Тут жу еще undefined может быть, поэтому лучше так и оставить

2024-02-16 07:56 UTC, EGRoBBeRTiT commented on source/inverse.js
> +"use strict";
Согласен, просто тут форматтеров не было и у меня вскод автоматически заменил на двойные

2024-02-18 16:57 UTC, DPeshkoff requested changes
Привет! Хорошее решение, но кое-что надо поправить)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-18 16:57 UTC, DPeshkoff commented on index.html
> +    <body>
Здесь не нужны изменения - давай вернем так, как было

2024-02-18 16:57 UTC, DPeshkoff commented on source/inverse.js
> + * @example
Давай еще добавим `@throws`

2024-02-18 16:57 UTC, DPeshkoff commented on source/inverse.js
> +const inverse = (arr, num) => {
А чем стрелочные функции отличаются от обычных?

2024-02-18 16:57 UTC, DPeshkoff commented on source/inverse.js
> +    if (num !== undefined && !isNumber(num)) {
Первую часть можно [сократить](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)

2024-02-18 16:57 UTC, DPeshkoff commented on tests/inverse.js
> +        assert.deepEqual(inverse([1]), [1]);
Тут тоже давай дифф приведем в норму

2024-02-18 17:02 UTC, EGRoBBeRTiT commented on source/inverse.js
> +    if (num !== undefined && !isNumber(num)) {
Я специально здесь именно на undefined проверяю, чтобы при пустой строке тоже ошибка была

2024-02-18 17:08 UTC, EGRoBBeRTiT commented on source/inverse.js
> +const inverse = (arr, num) => {
Забыл еще один пункт следствие из 1.
4. Нельзя использовать как конструктор с new

2024-02-18 17:10 UTC, EGRoBBeRTiT commented on tests/inverse.js
> +        assert.deepEqual(inverse([1]), [1]);
Может добавить какой нибудь editorconfig или prettier? А то у многих лишние изменения в форматировании

2024-02-19 11:43 UTC, DPeshkoff commented on tests/inverse.js
> +        assert.deepEqual(inverse([1]), [1]);
В своем проекте - да)

К сожалению, не во всей кодовой базе такое бывает — надо уметь работать и с тем, что есть

2024-02-19 11:45 UTC, DPeshkoff approved these changes

2024-02-19 11:45 UTC, closed without merging