Nikitin Alex variant-6 (New)
frontend-park-mail-ru/homework_2024_1 pull request #55
Opened 2024-02-18 10:28 UTC by Olegsandrik

Теперь в diff все красивенько вышло, но в другом пулл реквесте. Заняло много времени, но результат настройки того стоил!
New correct branch! Изменил на стрелочную, поменял на .isNaN и изменил ветки на корректные :)

2024-02-18 16:16 UTC, DPeshkoff requested changes
Лайк за починенный дифф! Осталось чуть-чуть)

2024-02-18 16:16 UTC, DPeshkoff commented on source/tree.js
> +    if (number<3 || number!=Math. trunc(number) || number.isNaN){
Сейчас эта строчка не работает так, как надо(

Например, я сломал решение вот так

![изображение](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/bab378cb-07bb-4874-87ed-388ebef79535)

Давай поправим)

Бонус по последней проверке - ты сейчас проверяешь метод у number (у самого числа, даже не вызываешь)

Распиши, какая разница между тем, что написано, и [этим](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN)

2024-02-18 17:31 UTC, Olegsandrik commented on source/tree.js
> +    if (number<3 || number!=Math. trunc(number) || number.isNaN){
Метод не приводит к принудительному преобразованию параметра в число. Пример: print(Number.isNaN("blabla")); - false, а хотелось бы тру стори 
print(isNaN("blabla")); - true
Таким образом целесообразно использовать все-таки isNaN, чтобы проверка работала.
Наткнулся рядом на функицию isFinite:
print(!isFinite(Infinity)); //true
print(!isFinite(-Infinity)); //true
print(!isFinite("0")); // false
print(!isFinite("blaba")); //true
print(!isFinite(0)); // false
print(!Number.isFinite(Infinity)); //true
print(!Number.isFinite(-Infinity)); //true
print(!Number.isFinite("0")); //true -- поэтому не используем метод
print(!Number.isFinite("blabla")); //true
print(!Number.isFinite(0)); // false
Проверят на бесконечности и на то, является ли числом. Идеально в этом случае, думаю этого ты и ждал от моего решения

2024-02-19 07:28 UTC, Zela2520 reviewed
Название пр-а некорректное, должно быть Фамилия Имя :) 
В целом, все хорошо ) Ты красаучик :)

2024-02-19 07:28 UTC, Zela2520 commented on source/tree.js
> +const tree = (number) => {
а jsdoc где ?)

2024-02-19 07:28 UTC, Zela2520 commented on source/tree.js
> +    for (let i = 0; i < number-1; i++) {
Про возможность использовать Array.from говорил )
Если всё-таки так решил оставить, то расскажи про то что позволяет делать данный метод. Отпиши, что принимает Array.from аргументом.

2024-02-19 07:28 UTC, Zela2520 commented on source/tree.js
> +    answer+=' '.repeat(star/2-1) + '|' + ' '.repeat(star/2-1) + '\n';
Можем нейминг сделать более прозрачным ?)  
Представь, что твоя утилита часть shared библиотеки, её кто-то будет использовать и функция tree возвращать answer ??? Например, answer -> treePattern :)

2024-02-19 10:17 UTC, Olegsandrik commented on source/tree.js
> +const tree = (number) => {
момент

2024-02-19 10:17 UTC, Olegsandrik commented on source/tree.js
> +    answer+=' '.repeat(star/2-1) + '|' + ' '.repeat(star/2-1) + '\n';
treepicture буит, ща запилю

2024-02-19 10:23 UTC, Olegsandrik commented on source/tree.js
> +    answer+=' '.repeat(star/2-1) + '|' + ' '.repeat(star/2-1) + '\n';
сделал

2024-02-19 10:27 UTC, Olegsandrik commented on source/tree.js
> +const tree = (number) => {
название изменил

2024-02-19 10:36 UTC, Olegsandrik commented on source/tree.js
> +    for (let i = 0; i < number-1; i++) {
Параметры: 1) Обязательный массивоподобный или итерируемый объект, преобразуемый в массив, 2) и 3) Необязательные это функция, вызываемая для каждого элемента массива, и это значение, используемое в качестве this при выполнении функции. Возвращает же нам массив. Этот метод позволяет нам создавать массивы из массивоподобных объектов (объектов со свойством length и элементами по индексным ключам) или
из итерируемых объектов таких как set или map. Примеры:
1)Array.from([1, 2, 3], (x) => x + x);  // [2, 4, 6]
2)function f() {return Array.from(arguments);}
f(1, 2, 3);  // [1, 2, 3]
3) var m = new Map([ [1, 2], [2, 4], [4, 8], ]);
Array.from(m); // [[1, 2], [2, 4], [4, 8]]

2024-02-19 12:49 UTC, DPeshkoff requested changes

2024-02-19 12:49 UTC, DPeshkoff commented on tests/tree.js
> +	QUnit.test('Елочка не может принимать не число', function (assert) {
Гоу тесты на бесконечности всякие

2024-02-19 14:49 UTC, Olegsandrik commented on tests/tree.js
> +	QUnit.test('Елочка не может принимать не число', function (assert) {
Добавил два теста на +-Infinity к тестам

2024-02-19 14:59 UTC, Olegsandrik commented on tests/tree.js
> +	QUnit.test('Елочка не может принимать не число', function (assert) {
Всякие сделал, какие можно вообще

2024-02-19 16:28 UTC, DPeshkoff approved these changes

2024-02-19 16:28 UTC, closed without merging