Горевой Александр
frontend-park-mail-ru/homework_2024_1 pull request #56
Opened 2024-02-19 12:13 UTC by AlGrItm

2024-02-19 12:38 UTC, CheerfulMushroom commented
Приветствую на курсе по фронтенду)
Сейчас посмотрю код, накидаю исправлений

2024-02-19 13:04 UTC, CheerfulMushroom requested changes
В целом всё круто, по логике работы проблем не вижу. Исправляй, если будут вопросы - пиши сюда или в [ТГ](https://t.me/CheerfulMushroom). Успехов)

2024-02-19 13:04 UTC, CheerfulMushroom commented on source/tree.js
> +  const result = [];
Ну и ещё немножко по визуалу: обычно для упрощения читаемости кода в него добавляют пустые строки, которые визуально разбивают код на логические блоки. В случае твоей функции, например, я вижу 3 логических блока: проверка входных данных, расчёт результата, возврат результата. Возможно, если их разграничить пустой строкой, то код будет восприниматься проще

2024-02-19 13:59 UTC, AlGrItm commented on source/tree.js
> +const tree = function (height) {
Сложно так ответить.. выглядит лаконичнее)

2024-02-19 16:39 UTC, CheerfulMushroom requested changes

2024-02-19 16:39 UTC, CheerfulMushroom commented on source/tree.js
> + * @param {number} height высота ёлочки
Судя по тестам у тебя на вход может прийти не только число

2024-02-19 16:39 UTC, CheerfulMushroom commented on source/tree.js
> + * @return {string, null} построенная ёлочка, если height <= 2, возарвщает null
Невалидный синтаксис. "Один из типов" не через запятую обозначается 🙃

2024-02-19 16:39 UTC, CheerfulMushroom commented on source/tree.js
> +const tree = function (height) {
Ну оно, конечно, да, но это не единственное различие) Какие ещё есть?

2024-02-19 16:39 UTC, CheerfulMushroom commented on tests/tree.js
> +});
Стоит следить за тем, чтобы файлы заканчивались пустой строкой)
Можно почитать, зачем это нужно, но если кратко, то это может местами привести к неожиданному поведению. Тут, например, я 3 раза вывожу содержимое файла без переноса строки в конце и с переносом

<img width="465" alt="Снимок экрана 2024-02-19 в 19 36 53" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/43929910/03606f6b-e525-431f-9e70-9bb05a7ef90c">

2024-02-19 17:38 UTC, AlGrItm commented on source/tree.js
> +const tree = function (height) {
Стрелочная функция в отличие от обычной не имеет this, поэтому, например, не может быть конструктором

2024-02-21 16:24 UTC, DPeshkoff requested changes
Привет! Хорошее решение, но нужна парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-21 16:24 UTC, DPeshkoff commented on tests/tree.js
> +	});
Давай добавим тесты на некорректный ввод

2024-02-21 16:24 UTC, DPeshkoff commented on source/tree.js
> +  if (height <= 2) {
+Infinity сломает)

2024-02-21 16:24 UTC, DPeshkoff commented on source/tree.js
> +'use strict';
А что это за режим? Что он делает?

2024-02-21 17:24 UTC, AlGrItm commented on source/tree.js
> +'use strict';
Это включение строгого режима, он нам помогает предотвратить некоторые ошибки, предупреждает о неиспользуемых переменных и вроде как некоторые функции доступны только в строгом режиме

2024-02-22 10:39 UTC, DPeshkoff commented on source/tree.js
> +'use strict';
Какие, например?

2024-02-22 11:13 UTC, AlGrItm commented on source/tree.js
> +'use strict';
Ну не совсем правильно сказать, что есть функции, доступные только в строгом режиме, точнее поведение будет отличаться. Если в обычном режиме некоторые ошибки прощались, то в строгом режиме будет выскакивать исключение, например при попытке присвоить Infinity = 5 выскочит исключение. Или, например, при попытке создания внутри объекта двух свойств с одинаковым названием также сработает исключение

2024-02-22 20:25 UTC, DPeshkoff requested changes

2024-02-22 20:25 UTC, DPeshkoff commented on source/tree.js
> +  if (height <= 2 || height === Infinity || isNaN(height)) {
А чем isNaN отличается от Number.isNaN?

На бесконечность лучше [проверять так](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite)

2024-02-22 20:37 UTC, AlGrItm commented on source/tree.js
> +  if (height <= 2 || height === Infinity || isNaN(height)) {
Number.isNan вернет true только если значение является Nan. isNan возвращает true, если переменная не является числом или не может быть преобразована в число

2024-02-24 16:42 UTC, DPeshkoff approved these changes

2024-02-24 16:43 UTC, closed without merging