Илья Чугин
frontend-park-mail-ru/homework_2024_1 pull request #57
Opened 2024-02-20 20:04 UTC by IlyaChgn

Исправление проблем с ветками

2024-02-21 16:23 UTC, DPeshkoff requested changes

2024-02-21 16:23 UTC, DPeshkoff commented on source/sort.js
> +    }
Кажется, старые изменения. Нужно добавить JSDoc, сделать обработку новых строк, выбрасывать ошибки, сделать функцию стрелочной

2024-02-21 19:37 UTC, IlyaChgn commented on source/sort.js
> +    }
Добавлено

2024-02-22 15:34 UTC, DPeshkoff commented on source/sort.js
> +    if (typeof(sentence) != 'string') {
1) Строгие проверки
2) 
<img width="351" alt="305255761-804205f3-3cc6-4f3d-b26d-6435d9eb0e70" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/ddec583f-779e-4a3f-a342-e8e83dba96a6">

2024-02-22 15:34 UTC, DPeshkoff commented on source/sort.js
> +'use strict';
А что эта строчка делает?

2024-02-22 15:34 UTC, DPeshkoff commented on source/sort.js
> +        return null;
Надо [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/throw)

2024-02-22 15:34 UTC, DPeshkoff commented on source/sort.js
> +    for (let i = 0; i < words.length; ++i) {
Давай заюзаем перебирающие методы массивов

2024-02-22 15:34 UTC, DPeshkoff commented on source/sort.js
> +    let words = sentence.toLowerCase().split(' ');
А чем let от const отличаются? Можно тут const?

2024-02-22 15:34 UTC, DPeshkoff commented on source/sort.js
> +}
\n

2024-02-22 16:28 UTC, IlyaChgn commented on source/sort.js
> +'use strict';
Директива 'use strict' используется для включения строгого режима, который позволяет исправить ошибки старых версий JS. Например, нельзя присваивать значение переменной без объявления, нельзя определять повторные формальные параметры функции и т.п.

2024-02-22 16:28 UTC, IlyaChgn commented on source/sort.js
> +    let words = sentence.toLowerCase().split(' ');
let позволяет объявить переменную, которую можно менять в процессе выполнения программы.
Объявление при помощи const не позволяет изменить значение переменной.
Так как в данном случае я объявляю массив, то это означает объявление ссылки на объект. Таким образом, я не могу изменить саму ссылку, но могу менять элементы массива. Поэтому здесь let и const взаимозаменяемы.

2024-02-22 16:30 UTC, IlyaChgn commented on source/sort.js
> +        return null;
Изменил

2024-02-22 16:30 UTC, IlyaChgn commented on source/sort.js
> +    for (let i = 0; i < words.length; ++i) {
Добавил

2024-02-22 16:30 UTC, IlyaChgn commented on source/sort.js
> +}
Добавил

2024-02-22 20:25 UTC, DPeshkoff approved these changes

2024-02-22 20:27 UTC, closed without merging