Шагаев Максим
frontend-park-mail-ru/homework_2024_1 pull request #59
Opened 2024-02-24 15:27 UTC by Maxorella

сделал функцию format и написал тесты для неё

2024-02-25 10:40 UTC, CheerfulMushroom commented
Приветствую на курсе по фронтенду)
Сейчас накидаю правок

2024-02-25 11:22 UTC, CheerfulMushroom requested changes
Ну, в целом всё выглядит неплохо, к алгоритму работы вопросов особых нет. Очень круто, что знаешь и используешь всякие встроенные методы объектов в языке (String,padStart, String.trimEnd, Array,fill). Исправляй правки, по вопросам пиши сюда или мне в [ТГ](https://t.me/CheerfulMushroom). Успехов)

2024-02-25 11:22 UTC, CheerfulMushroom commented on tests/format.js
> +		if (numberWidth > maxWidths[columnIndex]) {
Давай заюзаем здесь `Math.max`, чтобы весь этот if с его содержанием уменьшить с 3 строк до одной. Кода будет меньше, что происходит всё ещё понятно => читаемость кода вырастет

2024-02-25 11:22 UTC, CheerfulMushroom commented on tests/format.js
> +	let result = [];
Почему let?

2024-02-25 11:22 UTC, CheerfulMushroom commented on tests/format.js
> +		let line = [];
Аналогичный вопрос: почему let?

2024-02-25 11:22 UTC, CheerfulMushroom commented on tests/format.js
> +function format(numbers, columns) {
JSDoc очень хочется)

2024-02-25 11:22 UTC, CheerfulMushroom commented on tests/format.js
> +		result.push(line.join(' ').trimEnd());
А в каких случаях здесь отрабатывает trimEnd? Я просто пока плохо понимаю, зачем он тут. Вроде не может быть такого, что пробел появится в конце ряда

2024-02-25 11:22 UTC, CheerfulMushroom commented on tests/format.js
> +function format(numbers, columns) {
Ну и раз функция принимает определённые типы, то давай накинем проверку входных данных. Пусть, если что-то не так, будем возвращать null или кидать ошибку (выбирай любой способ)

2024-02-25 11:22 UTC, CheerfulMushroom commented on tests/format.js
> +function format(numbers, columns) {
Само собой, придётся добавить тесты на проверку валидных параметров

2024-02-27 19:47 UTC, Maxorella commented on tests/format.js
> +function format(numbers, columns) {
1. стрелочная функция пишется быстрее(меньше букв)
2. стрелочная функция не имеет своего this, смотрит на this ближайшей родительской функции
3. тоже самое с arguments

2024-02-27 20:04 UTC, CheerfulMushroom commented on tests/format.js
> +		let line = [];
Вопрос всё ещё актуален

2024-02-27 20:10 UTC, CheerfulMushroom commented on source/format.js
> +let format = (numbers, columns) => {
Нужна проверка на адекватность columns и тесты на эту проверку

2024-02-27 20:18 UTC, CheerfulMushroom commented on source/format.js
> +}
Убедись, что во всех файлах в конце есть перенос строки

2024-02-27 20:21 UTC, CheerfulMushroom commented on tests/format.js
> +		const expected2 = null
Кажется, что лишнюю переменную не нужно тут выделять под null, а то кода многовато становится. И почему она называется expected2?

2024-02-27 20:21 UTC, CheerfulMushroom commented on tests/format.js
> +		const expected2 = null
Тоже лишняя инициализация. Сразу в assert этот null убирай

2024-02-27 20:53 UTC, CheerfulMushroom commented on source/format.js
> + * @param {Number} columns - количество стобцов, на которое надо разделить массив
Ну а ты сюда объекты обёртки передавать будешь или примитивы?)

2024-02-27 20:53 UTC, CheerfulMushroom commented on tests/format.js
> +		let line = [];
Зачем ты их вырезал? 😭

2024-02-27 21:05 UTC, CheerfulMushroom requested changes

2024-02-27 21:05 UTC, CheerfulMushroom commented on tests/format.js
> -
Верни строчечку на место пожалуйста, а то лишнее изменение выходит

2024-02-27 21:05 UTC, CheerfulMushroom commented on source/format.js
> +        if (typeof numbers[j] !== 'number' || typeof columns !== 'number' || columns <= 0) {
Проверка неплохая, но привнести сюда неожиданное поведение всё ещё можно. Например, я могу передать сюда Infinity, NaN, 1.7. Нужно больше проверок на адекватность columns

2024-02-27 21:41 UTC, CheerfulMushroom commented on source/format.js
> +let format = (numbers, columns) => {
Актуально

2024-02-27 21:44 UTC, CheerfulMushroom requested changes
Финишная прямая

2024-02-27 21:44 UTC, CheerfulMushroom commented on source/format.js
> +    if (typeof columns !== 'number' || columns <= 0 ||  !Number.isFinite(columns) ||  !Number.isInteger(columns)) {
Нужно в идеале добавить протестировать каждую из этих проектов, чтобы убедиться, что всё работает как надо

2024-02-27 21:44 UTC, CheerfulMushroom commented on source/format.js
> +    if (typeof columns !== 'number' || columns <= 0 ||  !Number.isFinite(columns) ||  !Number.isInteger(columns)) {
Я _почти_ уверен, что я вижу по два пробела тут местами между ||. Соблюдай кодстайл)

2024-02-29 17:05 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-29 17:05 UTC, DPeshkoff commented on source/format.js
> +        return null;
предлагаю выбрасывать ошибку

2024-02-29 17:05 UTC, DPeshkoff commented on source/format.js
> +        if (typeof numbers[j] !== 'number') {
у массива есть перебирающие методы)

2024-02-29 17:05 UTC, DPeshkoff commented on source/format.js
> +    for (let i = 0; i < numbers.length; i++) {
и тут

2024-02-29 17:05 UTC, DPeshkoff commented on source/format.js
> +                const num = numbers[index].toString();
И тут гоу порефачим

2024-03-01 21:49 UTC, DPeshkoff requested changes

2024-03-01 21:49 UTC, DPeshkoff commented on source/format.js
> +        throw "format params error"
Нужно создавать экземпляр [ошибки ](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2024-03-01 21:49 UTC, DPeshkoff commented on source/format.js
> +        numbers.forEach(function(item,j, numbers) {
А [это ](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/every)не лучше?

2024-03-01 21:49 UTC, DPeshkoff commented on source/format.js
> +    const rowGenerator = generateRows(numbers, columns, maxWidths);
Давай попробуем заюзать [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

2024-03-01 22:50 UTC, Maxorella commented on source/format.js
> +    const rowGenerator = generateRows(numbers, columns, maxWidths);
сделал)

2024-03-03 08:28 UTC, DPeshkoff requested changes

2024-03-03 08:28 UTC, DPeshkoff commented on source/format.js
> + * @returns {string|null} - строка содержащая столбцы чисел, возвращает null, если
throws в jsdoc

2024-03-03 08:28 UTC, DPeshkoff commented on source/format.js
> +        throw Error("format params error")
В JS приняты одиночные кавычки - давай поменяем здесь и везде

Ну и есть различные [типы ошибок](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError))

2024-03-03 19:37 UTC, DPeshkoff requested changes

2024-03-03 19:37 UTC, DPeshkoff commented on source/format.js
> +/**
Давай вернем строгий режим и можно будет окать)

2024-03-03 20:22 UTC, DPeshkoff approved these changes

2024-03-03 20:22 UTC, closed without merging