Митин Пётр
frontend-park-mail-ru/homework_2024_1 pull request #6
Opened 2024-02-10 14:42 UTC by Petr09Mitin

2024-02-10 16:40 UTC, VladislavKirpichov reviewed
Привет! Я буду твоим ревьером дз0, если будут вопросы, пиши @vladislavkirpichov в телеге, помогу)

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +            stack.push(eval(operand1 + token + operand2));
eval лучше никогда не использовать, напиши, почему, и исправь в данном месте). Еще советую почитать про csp(https://developer.mozilla.org/ru/docs/Web/HTTP/CSP), и xss(https://owasp.org/www-community/attacks/xss/)

2024-02-10 16:40 UTC, VladislavKirpichov commented on tests/solve.js
> +	});
Тестов маловато) Напиши поломанные выражения(например: `(a * 1`, другие буквы вместо операндов, вместо `x` пусть будет `x123`, пустая строка в аргументе и подобное), скорее всего твоя реализация сломается и надо будет что-то переписать.
JS слабо типизирован, поэтому не забудь тесты для разных типов входных аргументов еще.

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +}
Объясни, зачем нужна пустая строка в конце файла?

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +    const operators = ['+', '-', '*'];
`operators` будут инициализироваться при каждом вызове функции. Давай вынесем это в отдельную константу(не забудь назвать ее в UPPER_SNAKE_CASE).
И еще насчет операторов, нам сейчас приходится ниже проверять приоритет оператора с помощью `indexOf`(то есть итерация по массиву). Давай сделаем JS объект и будем с его помощью проверять приоритет оператора.

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +    for (let i = 0; i < tokens.length; ++i) {
В js можно использовать функциональный подход при итерации по массиву, давай переделаем на `forEach`

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +    }
В данном цикле ты по сути собираешь нужные тебе элементы в массив. В JS есть функция у массивов, которая как раз нужно для таких кейсов, перепиши данный цикл на нее. Если не найдешь функцию, пиши, подскажу)

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +            case ')':
Давай эти символы тоже вынесем в объект-константу выше по коду

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +    let number = '';
Напиши пожалуйста, в чем отличие const и let(и var)? Когда лучше использовать какой из вариантов? Знаешь что-нибудь про области видимости переменных?

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +const solve = (expression, x) => {
А что будет если в данную функцию придет значение с типом, который мы не ожидаем? Надо написать обработку таких кейсов и добавить тесты

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +const parseOperandsFromExpression = (expression, x) => {
Почему используется function expression а не function declaration? В чем вообще разница?

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +                operators.indexOf(stack[stack.length - 1]) >= operators.indexOf(token) //  Приоритет оператора из конца стека больше или равен приоритету текущего оператора
Если рядом с кодом есть комментарий с пояснением, что этот код делает, скорее всего в коде проблема, код должен быть читаемым) Давай вынесем данную проверку в отдельную функцию

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +            }
Цикл тут лишний, можно обойтись функциями над массивами js, если не придумаешь как, пиши в телегу. И вообще, давай эту логику в отдельную функцию вынесем

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +            return [];
Это на самом деле это не валидный кейс который должен приводить к ошибке. Внешний код, который вызывает данную функцию, должен узнать что данные были не валидны, придумай что можно поменять в данном случае

2024-02-10 16:40 UTC, VladislavKirpichov commented on source/solve.js
> +    const filledExpression = expression.replaceAll('x', x.toString());
Какие еще методы кроме toString знаешь? Можешь что-то рассказать про прототипы объектов в js? Что такое прототипное наследование в js? Что можешь рассказать про типы в js, какие есть, что такое примитивные типы в js?(только если ты знаешь мурыча, не надо душнить спекой))

Вот немного полезных ссылок:
https://learn.javascript.ru/object-basics
https://learn.javascript.ru/prototype-inheritance
https://developer.mozilla.org/ru/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
https://github.com/azat-io/you-dont-know-js-ru/blob/master/this%20%26%20object%20prototypes/README.md#you-dont-know-js-this--object-prototypes

2024-02-10 19:58 UTC, Petr09Mitin commented on source/solve.js
> +'use strict';
Оно включает строгий режим интерпретатора. С ним он выбрасывает ошибки на моменты, которые могут быть небезопасными, например, когда используются необъявленные переменные или когда параметры функции имеют одинаковые имена. Лучше все же с ним, так как этот вариант более безопасен.

2024-02-10 20:23 UTC, Petr09Mitin commented on source/solve.js
> +}
Строка по определению - "последовательность из нуля или более символов, не являющихся символом новой строки, и терминирующего символа новой строки". Если в конце файла не будет перевода строки, то последняя строка может быть проигнорирована, например, системой контроля версий, так как она не подходит под формальное определение строки.

2024-02-10 21:01 UTC, Petr09Mitin commented on source/solve.js
> +const parseOperandsFromExpression = (expression, x) => {
Когда используется function declaration, функцию можно вызывать и до ее объявления, в отличие от function expression. Кроме того, насколько я знаю, в стрелочных функциях нельзя пользоваться this, то есть у объявленных таким образом функций нет своего контекста. Здесь я использую стрелочную функцию, так как контекст в ней мне не нужен, концептуально она является вспомогательной, плюс чтобы продемонстрировать знание синтаксиса ES6+.

2024-02-10 21:27 UTC, Petr09Mitin commented on source/solve.js
> +    const filledExpression = expression.replaceAll('x', x.toString());
Есть много разных методов - toPrecision, valueOf и т. д. Прототипы - некоторые объекты, на которые есть ссылка в "дочерних" объектах, то есть дочерние объекты как бы наследуют методы от прототипа. Типы в js - number, char, boolean, string, undefined (примитивы) и null, object - не примитивы, объекты.

2024-02-11 09:18 UTC, Petr09Mitin commented on source/solve.js
> +    const filledExpression = expression.replaceAll('x', x.toString());
Fixed

2024-02-11 09:19 UTC, Petr09Mitin commented on source/solve.js
> +    }
Fixed

2024-02-11 09:20 UTC, Petr09Mitin commented on source/solve.js
> +            stack.push(eval(operand1 + token + operand2));
Моя ошибка, сначала написал, чтобы посмотреть, что все остальное работает, и не убрал в итоге. Eval нельзя использовать, потому что может прийти вредоносный код от пользователя, который eval выполнит, это уязвимость. Fixed.

2024-02-11 09:20 UTC, Petr09Mitin commented on tests/solve.js
> +	});
Fixed

2024-02-11 09:21 UTC, Petr09Mitin commented on source/solve.js
> +    const operators = ['+', '-', '*'];
Fixed

2024-02-11 09:21 UTC, Petr09Mitin commented on source/solve.js
> +    for (let i = 0; i < tokens.length; ++i) {
Fixed

2024-02-11 09:22 UTC, Petr09Mitin commented on source/solve.js
> +    }
Fixed, used "reduce"

2024-02-11 09:22 UTC, Petr09Mitin commented on source/solve.js
> +            case ')':
Fixed

2024-02-11 09:26 UTC, Petr09Mitin commented on source/solve.js
> +    let number = '';
const - неизменяемая переменная или объект (в js можно менять переменные-объекты, объявленные как const, но нельзя переприсваивать в них). Let - можно переприсваивать. var - устаревший вариант, использовался до ES5, сейчас считается плохим тоном, изменяемая переменная. Везде, где возможно, лучше использовать const, если надо переменную менять (счетчик, например), то нужно let. Var лучше не использовать. Область видимости переменных - блок кода, из которого к переменной есть доступ. Выше было про arrow functions, у них своего scope нет, они юзают родительский. Есть еще общая как бы область global scope, из нее переменные видны везде.

2024-02-11 09:27 UTC, Petr09Mitin commented on source/solve.js
> +const solve = (expression, x) => {
Fixed

2024-02-11 09:27 UTC, Petr09Mitin commented on source/solve.js
> +                operators.indexOf(stack[stack.length - 1]) >= operators.indexOf(token) //  Приоритет оператора из конца стека больше или равен приоритету текущего оператора
Fixed

2024-02-11 09:27 UTC, Petr09Mitin commented on source/solve.js
> +            }
Fixed

2024-02-11 09:27 UTC, Petr09Mitin commented on source/solve.js
> +            return [];
Fixed

2024-02-11 10:07 UTC, VladislavKirpichov commented on source/solve.js
> +            } else if (Object.keys(OPERATORS_WITH_PRIORITY).includes(token)) {
Тут тоже без keys и includes

2024-02-11 10:07 UTC, VladislavKirpichov commented on source/solve.js
> +// где в качестве операнда будет записан, например, '1)'.
Отлично что пишешь комментарии, есть специальный формат комментариев: JSDoc, давай напишем в этом формате комментарии ко всем функциям

2024-02-11 10:18 UTC, VladislavKirpichov commented on source/solve.js
> +const parseOperandsFromExpression = (expression, x) => {
Еще кстати не все пункты про разницу function declaration и function expression написал, вот тут список: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2024-02-11 10:23 UTC, VladislavKirpichov commented on source/solve.js
> +    let number = '';
Про переменные видны везде не очень понял) В чем разница блочной и лексической областей видимости? Можешь еще рассказать, что такое shadowing и как переменные ищутся в областях видимости?

Расскажи, почему будут разные выводы для этих функций:
```
    const test = () => {
        var i = 0;
        {
            var i = 1;
            {
                var i = 2;
                console.log(i)
            }
            console.log(i)
        }
        console.log(i)
    }

    const test = () => {
        let i = 0;
        {
            let i = 1;
            {
                let i = 2;
                console.log(i)
            }
            console.log(i)
        }
        console.log(i)
    }
```

2024-02-11 10:24 UTC, VladislavKirpichov commented on source/solve.js
> +    let number = '';
Надеюсь не сильно душню) Но разобраться в этих темах надо, ошибки связанные с этим бывает очень сложно дебажить

2024-02-11 10:32 UTC, Petr09Mitin commented on source/solve.js
> +    (typeof expression === 'string' || typeof expression === 'symbol')
Символ - уникальный идентификатор, как выяснилось, ничего общего со строками не имеет и даже в них не конвертится при неявном приведении типов. Он нужен, например, чтобы создавать уникальные ключи для полей объектов.

2024-02-11 10:56 UTC, Petr09Mitin commented on source/solve.js
> +            case 'x':
Использовать можно, но тогда this будет ссылаться на родительский контекст, то есть на контекст на 1 уровень вложенности выше. Контекст - это окружение в виде объекта, в котором выполняется функция и на который ссылается this. Он определяется при вызове функции, его можно переприсвоить или привязать явно с помощью bind (это, например, было нужно в старых версиях реакта на классах, когда из-за пропс дриллинга контекст родительского компонента терялся).

2024-02-11 11:23 UTC, Petr09Mitin commented on source/solve.js
> +            case 'x':
Fixed

2024-02-11 11:23 UTC, Petr09Mitin commented on source/solve.js
> +    let result = expression.split('').reduce((acc, curr) => {
Fixed, опечатка просто

2024-02-11 11:23 UTC, Petr09Mitin commented on source/solve.js
> +    let result = expression.split('').reduce((acc, curr) => {
Fixed

2024-02-11 11:24 UTC, Petr09Mitin commented on source/solve.js
> +        console.log(e.message);
Fixed

2024-02-11 11:24 UTC, Petr09Mitin commented on tests/solve.js
> +	})
Fixed

2024-02-11 11:29 UTC, Petr09Mitin commented on source/solve.js
> +        } else if (Object.keys(OPERATORS_WITH_PRIORITY).includes(token)) { // Если токен - оператор
Fixed

2024-02-11 11:29 UTC, Petr09Mitin commented on source/solve.js
> +    (typeof expression === 'string' || typeof expression === 'symbol')
Fixed

2024-02-11 11:30 UTC, Petr09Mitin commented on source/solve.js
> +    OPERATORS_WITH_PRIORITY[stack[stack.length - 1]] >= OPERATORS_WITH_PRIORITY[token]
Fixed

2024-02-11 11:30 UTC, Petr09Mitin commented on source/solve.js
> +        }
Fixed

2024-02-11 11:30 UTC, Petr09Mitin commented on source/solve.js
> +                throw new Error(`invalid parentheses sequence in input expression ${expression}`);
Fixed

2024-02-11 11:30 UTC, Petr09Mitin commented on source/solve.js
> +            } else if (Object.keys(OPERATORS_WITH_PRIORITY).includes(token)) {
Fixed

2024-02-11 11:30 UTC, Petr09Mitin commented on source/solve.js
> +// где в качестве операнда будет записан, например, '1)'.
Added

2024-02-11 19:49 UTC, VladislavKirpichov commented on source/solve.js
> +const handleStackWhenParsingOperatorCondition = (stack, token) => (
Название не совсем удачное у функции. Обычно функции которые возвращают boolean начинаются с перфикса is/should, давай поменяем тут на что-то типа `shouldParseStack` или что-то похожее на твое усмотрение

2024-02-11 19:49 UTC, VladislavKirpichov commented on source/solve.js
> +            let lastLeftParenthIdx = stack.lastIndexOf(LEFT_PARENTH);
Похоже тут `let` тоже не нужен

2024-02-11 19:49 UTC, VladislavKirpichov commented on source/solve.js
> +            }
`while` и `for` редко пишут в js. Тут ты пытаешься скопировать элементы из `stack` в `queue` до определенного условия, давай для практики поменяем на вызов нескольких методов у массива(комбинация из `reverse`, `filter` и еще каких-то, придумай как можно это сделать). В итоге у тебя получится цепочка вызовов и спред оператор в `queue`.
Возможно тебе будет полезно узнать как работают `&&` и `||` в js, если будешь использовать, напиши в чем их особенность и что, например, вернет `true && 'Hello world!'`
Соглашусь это будет не так оптимально, но зато потренируешься еще в работе с массивами;)

2024-02-11 19:49 UTC, VladislavKirpichov commented on source/solve.js
> +    return queue;
Это можно упростить, придумай как(подсказка, использовать еще один спред оператор)

2024-02-11 19:49 UTC, VladislavKirpichov commented on source/solve.js
> + */
Отлично что написал jsdoc сразу с параметрами и типами!

2024-02-11 19:50 UTC, VladislavKirpichov commented
Не забывай про вопросы которые выше написал, они в комментариях которые я пока не резолвил

2024-02-11 19:55 UTC, VladislavKirpichov commented on source/solve.js
> +            case 'x':
Небольшая ремарка, не из-за props drilling, а просто потому что контекст у любого пропса который мы передаем в компонент не является контекстом класса(можно считать что он слетает), который описывает этот компонент. Props drilling это проблема когда ты прокидываешь пропсы на несколько уровней вложенности компонентов, решается с помощью композиции, контекста или стейт менеджера.
А так да, верно, отлично что реакт знаешь)

2024-02-12 07:19 UTC, Petr09Mitin commented on source/solve.js
> +    let number = '';
Блочная область видимости в JavaScript определяется внутри блоков кода, заключенных в фигурные скобки {}. Переменные, объявленные с помощью let и const, имеют блочную область видимости. Они доступны только внутри блока, в котором были объявлены. Лексическая область видимости определяется во время написания кода. Переменные, объявленные с помощью var, имеют лексическую область видимости. Они доступны внутри функции, в которой были объявлены, включая все вложенные блоки и функции.
Shadowing происходит, когда переменная внутри области видимости имеет такое же имя, как и переменная во внешней области видимости. В этом случае внутренняя переменная "затеняет" внешнюю.
При поиске переменной в областях видимости JavaScript сначала проверяет текущую область видимости. Если переменная не найдена, поиск продолжается во внешней области видимости, и так далее, пока не будет найдена переменная или не будет достигнута глобальная область видимости. Если переменная не найдена в глобальной области видимости, будет сгенерирована ошибка.
Разные выводы происходят, потому что во втором случае имеем 3 переменных с block scope, соответственно выводится 2 1 0. В первом случае var i имеет lexical scope, поэтому вывод 2 2 2.

2024-02-12 07:34 UTC, Petr09Mitin commented on source/solve.js
> +const parseOperandsFromExpression = (expression, x) => {
This использовать можно, но он будет ссылаться на родительский контекст. Контекст - объект на который ссылается this. Там есть несколько случаев, какой именно это объект - в конструкторе это создаваемый объект, в методе объекта это сам объект, в глобальном контексте в браузере это window, можно привязать свой объект с помощью bind.

2024-02-12 08:32 UTC, Petr09Mitin commented on source/solve.js
> +const handleStackWhenParsingOperatorCondition = (stack, token) => (
Fixed

2024-02-12 08:32 UTC, Petr09Mitin commented on source/solve.js
> +            let lastLeftParenthIdx = stack.lastIndexOf(LEFT_PARENTH);
Fixed

2024-02-12 08:32 UTC, Petr09Mitin commented on source/solve.js
> +    return queue;
Fixed

2024-02-12 08:32 UTC, Petr09Mitin commented on source/solve.js
> + */
Спасибо)

2024-02-12 15:00 UTC, VladislavKirpichov commented on source/solve.js
> +            }
Обсудили в телеграме

2024-02-12 15:22 UTC, DPeshkoff requested changes
Привет! Классное решение, еще парочка минорных правок)

Со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-12 15:22 UTC, DPeshkoff commented on index.html
> +	<script src="https://code.jquery.com/qunit/qunit-2.20.0.js"></script>
Это было необязательно, давай вернем так, как было)

2024-02-12 15:22 UTC, DPeshkoff commented on source/solve.js
> +            throw new Error(`invalid type of some argument`);
Кажется, лучше заюзать [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-12 15:22 UTC, DPeshkoff commented on source/solve.js
> +        if (queue.length === 0) {
Тут можно сократить)

2024-02-12 15:32 UTC, Petr09Mitin commented on index.html
> +	<script src="https://code.jquery.com/qunit/qunit-2.20.0.js"></script>
Нет assert.true() в старой версии, поэтому поменял. Могу поменять на assert.equal(solve(...), true), если надо.

2024-02-12 15:37 UTC, DPeshkoff commented on index.html
> +	<script src="https://code.jquery.com/qunit/qunit-2.20.0.js"></script>
Есть такое, [например](https://api.qunitjs.com/assert/ok/)

Можно и на equal)

Умение писать в заданных версиях - тоже полезное умение

2024-02-12 15:44 UTC, Petr09Mitin commented on source/solve.js
> +        if (queue.length === 0) {
Fixed

2024-02-12 15:44 UTC, Petr09Mitin commented on source/solve.js
> +            throw new Error(`invalid type of some argument`);
Fixed

2024-02-12 20:25 UTC, Petr09Mitin commented on index.html
> +	<script src="https://code.jquery.com/qunit/qunit-2.20.0.js"></script>
Fixed

2024-02-13 22:16 UTC, DPeshkoff approved these changes

2024-02-13 22:17 UTC, closed without merging