make hw0
frontend-park-mail-ru/homework_2024_1 pull request #60
Opened 2024-02-25 19:07 UTC by kisssick0

Козлова Алина web-22

2024-02-25 21:01 UTC, CheerfulMushroom commented
Приветствую на курсе по фронтенду)
В ближайшее время проверю твоё решение. В случае вопросов можно писать сюда или мне в [телеграм](https://t.me/CheerfulMushroom)

2024-02-25 21:42 UTC, CheerfulMushroom commented
Поправь название пулл реквеста. Там должны быть твои имя и фамилия, а не "make hw0"

2024-02-25 21:53 UTC, kisssick0 commented
добрый вечер, поменяла

2024-02-25 21:59 UTC, CheerfulMushroom commented
> добрый вечер, поменяла

Не, надо не сообщение в коммите поменять)
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/43929910/af6d9f24-20aa-40b7-a376-e5d027bfb91b)

2024-02-25 22:00 UTC, kisssick0 commented
Значит теперь поменяла)

2024-02-25 22:09 UTC, CheerfulMushroom requested changes
Реализация функции хорошая, рекурсии - это весело. Жаль, что очень много лишних изменений в исходных файлах, сложно сравнивать изменения. Вноси правки и пиши, как готово будет. Успехов)

2024-02-25 22:09 UTC, CheerfulMushroom commented on tests/plainify.js
Аналогично. Не стоит изменять изначальные файлы, сложно проверять изменения.

2024-02-25 22:09 UTC, CheerfulMushroom commented on tests/plainify.js
Кажется, что стоит добавить сюда тесты на объекты с полями более разнообразных типов: bool, symbol, array, null. Вдруг, там произойдёт что-то неожиданное :)

2024-02-25 22:25 UTC, CheerfulMushroom commented
А, ну и форс пуши не надо больше делать, а то они историю перетирают. Мало ли ещё комментарии сломаются

2024-02-27 20:41 UTC, CheerfulMushroom commented on tests/plainify.js
Чего-то я совсем не в ту сторону этим комментарием увёл. Смотри, у тебя изначально в коде была проверка на объект следующая: `typeof obj[key] === 'object' && obj[key] !== null`. И ты ожидаешь, что всё, что пройдёт эту проверку будет объектом, по которому ты через цикл const of пройдёшь по полям и соберёшь новый объект.   
Я намекал, что массив тут эту схему сломает. Например, если бы у тебя в объекте было поле с массивом [1,5,"length"], то он бы прошёл эту проверку и превратился бы в объект `{1: 5, 5: undefined, length: 3}`

2024-02-27 20:47 UTC, CheerfulMushroom commented on tests/plainify.js
Я предлагаю просто доработать эту проверку, чтобы пропускать только настоящие объекты, всё остальное просто записывать как есть в качестве значения

2024-02-28 21:10 UTC, CheerfulMushroom commented on tests/plainify.js
> +        assert.deepEqual(plainify(nested1), plain1);
Всю эту кучу тестов на отдельные. Иначе если упадёт один тест, то все последующие даже проверятся не будут (вроде). Ну и в целом обычно придерживаются правила один тесткейс на один тест

2024-02-28 21:10 UTC, CheerfulMushroom commented on source/plainify.js
> +const plainify = function plainify(obj, parentKey = '', result = {}) {
Исправление засчитываю, но ответ на вопрос нужен

2024-02-28 21:10 UTC, CheerfulMushroom commented on index.html
> +    <meta charset="utf-8">
Актуально

2024-02-28 21:10 UTC, CheerfulMushroom commented on tests/plainify.js
Актуально

2024-02-28 21:46 UTC, kisssick0 commented on source/plainify.js
> +const plainify = function plainify(obj, parentKey = '', result = {}) {
ну здесь не использует (использует ли функция что-то из внешней области видимости с ключевым словом this), поэтому стрелочная

2024-02-28 22:03 UTC, CheerfulMushroom commented on source/plainify.js
> +const plainify = function plainify(obj, parentKey = '', result = {}) {
Нужно ещё изучить этот вопрос. Рекомендую https://learn.javascript.ru/

2024-02-29 14:38 UTC, kisssick0 commented on source/plainify.js
> +const plainify = function plainify(obj, parentKey = '', result = {}) {
У стрелочных упрощенный синтаксис и нет контекста(this), который привязывается к объекту, так что их можно передавать в объекты, а у обычных он есть. Еще их нельзя использовать как конструкторы со словом new.

И вот такой код отработает неправильно
const a = {
    data: 456,
    sayHi: () => this,
}
console.log(a.sayHi());

мы бы хотели получить объект а, а она возвращает глобальный объект (в браузере это будет window)

2024-02-29 17:09 UTC, DPeshkoff requested changes
Привет! Классное решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-29 17:09 UTC, DPeshkoff commented on source/plainify.js
> +'use strict';
А что делает эта строчка?

2024-02-29 17:09 UTC, DPeshkoff commented on tests/plainify.js
> -
Здесь не должно быть изменений

2024-02-29 17:09 UTC, DPeshkoff commented on tests/plainify.js
> +        assert.deepEqual(plainify(nested4), plain4);
Нужны тесты на некорректный ввод

2024-03-01 19:45 UTC, kisssick0 commented on tests/plainify.js
> +        assert.deepEqual(plainify(nested4), plain4);
добавила

2024-03-01 19:45 UTC, kisssick0 commented on tests/plainify.js
> -
убрала

2024-03-01 19:45 UTC, kisssick0 commented on source/plainify.js
> +'use strict';
Это строгий режим для скрипта. Он заменяет исключениями некоторые ошибки, исправляет ошибки, которые мешают оптимизации для более быстрого выполнения, чем с кодом в обычном режиме. Еще запрещает использовать некоторые элементы синтаксиса
Добавила, потому что в тестах он был указан, а как я поняла нельзя смешивать строгий и обычный режимы, могут возникнуть проблемы

2024-03-01 21:40 UTC, DPeshkoff requested changes

2024-03-01 21:40 UTC, DPeshkoff commented on source/plainify.js
> + * @returns {Object} - The result of the transformation..
throws тоже в JSDoc

2024-03-01 21:40 UTC, DPeshkoff commented on tests/plainify.js
> -
Не убрала(

2024-03-01 21:55 UTC, kisssick0 commented on source/plainify.js
> + * @returns {Object} - The result of the transformation..
добавила

2024-03-01 21:56 UTC, kisssick0 commented on tests/plainify.js
> -
теперь убрала

2024-03-03 08:29 UTC, DPeshkoff approved these changes

2024-03-03 08:30 UTC, closed without merging