Кононыхина Ксения
frontend-park-mail-ru/homework_2024_1 pull request #61
Opened 2024-02-25 21:53 UTC by KseniaKono

2024-02-25 22:12 UTC, CheerfulMushroom commented
Приветствую на курсе по фронтенду)
В ближайшее время проверю твоё решение. В случае вопросов можно писать сюда или мне в [телеграм](https://t.me/CheerfulMushroom)

2024-02-25 22:46 UTC, CheerfulMushroom requested changes
Короч, все круто, но нужны небольшие доработки, чтобы этот негранёный алмаз превратить в бриллиант. Как сделаешь, пиши сюда или в телеграм. Успехов)

2024-02-25 22:46 UTC, CheerfulMushroom commented on source/solve.js
> +function solve(expression, x) {
JSDoc хочется)

2024-02-25 22:46 UTC, CheerfulMushroom commented on source/solve.js
> +function solve(expression, x) {
Если нет причины использовать обычную функцию, то стоит использовать стрелочную.
Ну и сразу же сюда вопрос: чем стрелочная функция отличается от обычной?

2024-02-25 22:46 UTC, CheerfulMushroom commented on tests/solve.js
> +		assert.strictEqual(solve('2 + x - 1', 'tik'), 'ErrNotNum');
Добавь сюда тест, где выражение нормальное, а x - пустая строка. Быть может, выйдет неожиданный результат :)

2024-02-25 22:46 UTC, CheerfulMushroom commented on source/solve.js
> +}
Стоит следить за тем, чтобы файлы заканчивались пустой строкой)
Можно погуглить развёрнутые ответы, зачем это нужно, но если кратко, то это может местами привести к неожиданному поведению. Тут, например, я 3 раза вывожу содержимое файла без переноса строки в конце и с переносом
![image](https://github.com/frontend-park-mail-ru/homework_2024_1/assets/43929910/d9f0413c-c817-440d-bbe2-dc0a8ae730fc)

2024-02-25 22:46 UTC, CheerfulMushroom commented on source/solve.js
> +        return 'ErrNotNum';
Смотри, обычно в случае возникновения ошибок есть 2 подхода к тому, как передать информацию о них выше: либо невалидный объект, по которому станет понятно, что что-то пошло не так (например, null) или кинуть exception, который будет отловлен выше. В твоём случае кажется, что стоит использовать exception, так как ты уже проименовала ошибки и ориентируешься на них в тестах

2024-02-25 22:46 UTC, CheerfulMushroom commented on source/solve.js
> +        return eval(expression.replace(/x/g, x));
`eval` - это очень опасный инструмент. Если ты его хочешь использовать, то нужно убедиться, что никто не сможет через него выполнить какой-нибудь JS код. Сейчас можно в `expression` передать `alert('hi!!!') || x + 2`, что приведёт к исполнению чужого кода. Нужны дополнительные проверки на адекватность выражения

2024-02-25 22:46 UTC, CheerfulMushroom commented on source/solve.js
> +        return 'ErrExpression';
О, кстати про кидание exception'ов: тут тогда нужно будет настоящую ошибку вложить в твою ошибку, чтобы не потерять настоящую причину проблемы (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause)

2024-02-27 12:00 UTC, KseniaKono commented on source/solve.js
> +        return 'ErrNotNum';
а как в quint правильно обработать exception, полистала документацию, там особо нет инфы об этом

2024-02-27 17:15 UTC, CheerfulMushroom commented on source/solve.js
> +        return 'ErrNotNum';
Вот такая штука там есть https://api.qunitjs.com/assert/throws/  
А try catch внутри реализации не нужен. Иначе странно выходит, создаём ошибку, чтобы тут же на месте её отловить

2024-02-27 17:26 UTC, CheerfulMushroom commented on source/solve.js
> +        '(', ')', '-', '*', '/', '+', ' ', 'x'])
Очень сильно стоит проставлять `;` в конце строк, иначе это может привести к багам, которые сложно отловить (например, https://stackoverflow.com/questions/1834642/why-should-i-use-a-semicolon-after-every-function-in-javascript)

2024-02-27 17:26 UTC, CheerfulMushroom commented on source/solve.js
> +        if (typeof expression !== 'string'){
Давай проставлять пробелы перед фигурными скобками в if'ах. Ну и в целом добиваемся однообразности стиля кода

2024-02-27 17:26 UTC, CheerfulMushroom commented on source/solve.js
> +function solve(expression, x) {
Раз реализация может кинуть ошибку, то стоит добавить throws в JSDoc (https://jsdoc.app/tags-throws)

2024-02-27 17:45 UTC, CheerfulMushroom requested changes
Уже определённо ближе к идеалу)

2024-02-27 17:45 UTC, CheerfulMushroom commented on source/solve.js
> +            if (!safeSymbols.has(String(symbol))){
Давай эту циклическую проверку заменим на Array.prototype.some (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some)

2024-02-27 17:45 UTC, CheerfulMushroom commented on source/solve.js
> +    const safeSymbols = new Set(['1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
В целом идея верная, но у чисел ещё дробная часть может быть. Думаю, стоит это учесть

2024-02-27 17:45 UTC, CheerfulMushroom commented on source/solve.js
> +        if (typeof x !== 'number') {
И всё-таки зря проверку на NaN убрала. У него, конечно, typeof тоже number, но не думаю, что стоит его принимать. Оно же Not-A-Number :)  

Ну и вообще NaN обычно используется для обозначения ошибки в вычислениях и его не используют целеноправленно как значение для расчётов

2024-02-27 21:38 UTC, CheerfulMushroom requested changes
Финишная прямая

2024-02-27 21:38 UTC, CheerfulMushroom commented on source/solve.js
> +    const safeSymbols = new Set(['1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
Вроде ок, но не могу придумать математическое выражение с запятой сходу. Такие есть?

2024-02-27 21:38 UTC, CheerfulMushroom commented on source/solve.js
> +        if (Array.from(expression).some(symbol => !safeSymbols.has(String(symbol)))){
Вот такой вопрос придумал: в чём идея делать `String(symbol)`?

2024-02-29 17:08 UTC, DPeshkoff requested changes
Привет! Хорошее решение, парочка минорных правок)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-29 17:08 UTC, DPeshkoff commented on source/solve.js
> +function solve(expression, x) {
Гоу стрелочную

2024-02-29 17:08 UTC, DPeshkoff commented on source/solve.js
> +'use strict';
А что означает этот режим?

2024-02-29 17:08 UTC, DPeshkoff commented on source/solve.js
> +        if (typeof expression !== 'string') {
<img width="351" alt="305730633-29f84e5f-609e-4fac-ae74-c114424c4f46" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/dcd7e846-d152-4070-8960-ed2d76817c2a">

тоже строка, давай чинить)

2024-02-29 17:08 UTC, DPeshkoff commented on source/solve.js
> +            throw new Error('ErrNotString');
Лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-02-29 17:08 UTC, DPeshkoff commented on source/solve.js
> +        if (typeof x !== 'number' || isNaN(x)) {
А чем isNaN отличается от Number.isNaN?

2024-02-29 17:08 UTC, DPeshkoff commented on source/solve.js
> +        if (expression.trim() === '') {
Можно [сократить](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

2024-02-29 18:27 UTC, KseniaKono commented on source/solve.js
> +        if (typeof x !== 'number' || isNaN(x)) {
isNaN() сначала преобразует передаваемое значение в число и потом его проверяет.
Number.isNaN() не преобразует передаваемое значение в число, а значит вернет false для любого значения не типа Number.

2024-02-29 18:42 UTC, KseniaKono commented on source/solve.js
> +'use strict';
'use strict' вводит более строгие правила для интерпретации кода. Это помогает избежать ошибок и улучшает безопасность кода.
Например нельзя объявлять переменную без ключевого слова; если свойство объекта отмечено запретом на изменение значения, то если попытаться присвоить новое значение будет ошибка; запрещено использование некоторых слов, которые зарезервированы для будущих версий JS и т.д.

2024-03-01 21:50 UTC, DPeshkoff approved these changes

2024-03-01 21:51 UTC, closed without merging