Zhidkov Anton
frontend-park-mail-ru/homework_2024_1 pull request #8
Opened 2024-02-10 17:22 UTC by FZTOtt

2024-02-10 17:44 UTC, mzingwrld commented
Антон, привет! Меня зовут Ваня. Я буду ревьювером твоего задания

Если вдруг по ходу возникнут вопросы, которые захочешь обсудить лично, ты сможешь написать мне в личку в [телеге](https://t.me/mzingwrld)

2024-02-10 18:27 UTC, mzingwrld commented on source/minmax.js
> +    numbers = numbers.match(/-?\.?\d+\e-?\d+|-?\d*\.?\d+|-?\bInfinity\b/g); //-?\.?\d+\e-?\d+ парсит 1е4 и всё что с этим связано
Такую регуляку будет весьма тяжело поддерживать, если потребуется что-то изменить. Также большие регулярки трудно читать и комментарий не сильно помогает в этом.

Например, такую регулярку легко понять и поддерживать: `^([1-9]\d*)$`


Давай попробуем подойти к решению задачи другими способами? Накину вариант c методом split у строки: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

Если будет нужна помощь - приходи в лс, не стесняйся

2024-02-11 16:04 UTC, mzingwrld commented
Антон, в изменениях твоего PR есть те, которых быть не должно)

Посмотри, пожалуйста, внимательно [тут](https://github.com/frontend-park-mail-ru/homework_2024_1/pull/8/files), убери лишнее)

Если вдруг непонятно, напиши мне в телеге - @mzingwrld

2024-02-11 16:34 UTC, mzingwrld commented on index.html
> -<script src="tests/max.js"></script>
`max.js` не нужно убирать из `index.html`

2024-02-11 16:34 UTC, mzingwrld commented on README.md
> +Утилиты Unix написаны согласно POSIX, поэтому при несоблюдении этого правила могут возникнуть конфликты при их использовании.
Это нужно было написать в ответ на мой комментарий)

2024-02-11 16:34 UTC, mzingwrld commented on source/minmax.js
> +const minmax = numbers => {
Что будет, есть в функцию забудут передать аргумент? А если число? Давай добавим обработку краевых случаев?

2024-02-11 16:34 UTC, mzingwrld commented on source/minmax.js
> +    numbers = numbers.split(' ').filter(num => num!=='');
Давай приведем здесь форматирование в порядок:

```suggestion
    numbers = numbers.split(' ').filter(num => num !== '');
```

2024-02-11 16:34 UTC, mzingwrld commented on source/minmax.js
> +    numbers = numbers.split(' ').filter(num => num!=='');
Не очень хорошо, что везде используется переменная numbers. Она не позволяет читать код и понимать сразу что произошло на каждом шаге, особенно когда над ней проводится подряд несколько операций.

Такой код трудно читать. Рекомендую завести отдельную переменную, с которой ты далее будешь работать.

2024-02-11 16:34 UTC, mzingwrld commented on source/minmax.js
> +	}
Как ты считаешь, 4-6 строки нужны? Что будет результатом `numbers.split(' ').filter(num => num !== '')`, если на вход подана строка (ожидаемое значение)?

2024-02-11 16:34 UTC, mzingwrld commented on source/minmax.js
> +const minmax = numbers => {
Ну и по условиям задачи, что мы ожидаем в качестве аргумента? Ведь там не обязательно только числа)
Стоит подумать над неймингом аргумента и придумать что-то более говорящее (а главное - то, что ты ожидаешь в качестве аргумента)

2024-02-11 16:34 UTC, mzingwrld commented on source/minmax.js
> +    return [min, max];
Есть такая практика clean code. На досуге можешь посмотреть)

Так вот, там, да и не только там, рекомендуют перед return-ом делать перенос строки, чтобы не слипалось с остальным кодом)

2024-02-11 16:34 UTC, mzingwrld commented on source/minmax.js
> +	numbers = numbers.map(Number).filter(num => !isNaN(num));
Вот у тебя по сути только тут должен получиться уже готовый массив с числами)

2024-02-11 17:47 UTC, FZTOtt commented
Добавил тесты на вызов функции без аргумента и передачу в качестве аргумента числа. Исправил minmax, подумал над неймингом, убрал лишнюю проверку, добавил обработку краевых условий.

2024-02-12 15:46 UTC, mzingwrld commented on source/minmax.js
> +
тут перенос строки не нужен

2024-02-12 15:46 UTC, mzingwrld commented on source/minmax.js
> +
после return тоже лишний перенос

2024-02-12 15:46 UTC, mzingwrld commented on source/minmax.js
> +
аналогично и тут - лишний перенос)

2024-02-12 15:46 UTC, mzingwrld commented on index.html
> -<script src="tests/max.js"></script>
@FZTOtt, обрати внимание на это замечание

2024-02-12 15:46 UTC, mzingwrld commented on README.md
> +Жидков Антон Web-21
@FZTOtt,
Файл `readme.md` не нужно изменять.
`screenshot.png` тоже верни, пожалуйста, который был изначально

Также прошу вернуть `max.js` из каталогов `/tests` и `/source`

2024-02-13 23:11 UTC, DPeshkoff requested changes
Привет! Хооршее решение, но кое-что надо поправить)

Если есть вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-13 23:11 UTC, DPeshkoff commented on source/minmax.js
> +const minmax = numericString => {
Предлагаю:

1) Добавить JSDOC

2) Обернуть numericString в скобки (в дальнейшем так будет гораздо проще и нагляднее видеть аргументы)

2024-02-13 23:11 UTC, DPeshkoff commented on source/minmax.js
> +	if (typeof numericString !== typeof ' '){
Я что-то сломал(

<img width="524" alt="Снимок экрана 2024-02-14 в 02 09 02" src="https://github.com/frontend-park-mail-ru/homework_2024_1/assets/31134795/8b5ee845-050c-4658-beee-a63d1871aeaa">

Как ты думаешь, что здесь пошло не так? Как это починить?

2024-02-13 23:11 UTC, DPeshkoff commented on source/minmax.js
> +	const numArray = subStringArray.map(Number).filter(num => !isNaN(num));
А чем isNaN отличается от Number.isNaN?

2024-02-13 23:11 UTC, DPeshkoff commented on source/minmax.js
> +	if (numArray.length === 0) {
Можно [сократить](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

2024-02-13 23:11 UTC, DPeshkoff commented on tests/minmax.js
> +	QUnit.test('в minmax передали число или вызвали без аргумента', function (assert) {
Давай еще допишем тестов - пусть на вход будут new String

Давай подумаем, чем еще можно сломать)

2024-02-14 20:01 UTC, FZTOtt commented on source/minmax.js
> +	if (typeof numericString !== typeof ' '){
Предполагалось, что на вход подаётся исключительно строка. В данном примере подаётся объект, из-за чего данное сравнение типов возвращает true. Первое, что мне пришло в голову - обрабатывать данный случай, то есть изменить проверку на if (typeof numericString !== typeof ' ' && !(numericString instanceof String)). В данном случае если на вход подать объект, то результат логического выражения - false.

2024-02-14 20:08 UTC, FZTOtt commented on source/minmax.js
> +	const numArray = subStringArray.map(Number).filter(num => !isNaN(num));
isNaN приводит значение к Number для проверки, что и так реализовано для дальнейшей обработки функциями Math.min, Math.max. Number.isNaN проверяет является ли значение NaN без приведения, что в данном случае также подойдёт.

2024-02-14 20:11 UTC, FZTOtt commented on source/minmax.js
> +	if (numArray.length === 0) {
Если честно, долго думал что сократить, но так и не понял, относится это к numArray или к if. Исправил на if(!numArray.length)

2024-02-14 20:21 UTC, FZTOtt commented on tests/minmax.js
> +	QUnit.test('в minmax передали число или вызвали без аргумента', function (assert) {
сломать легко, например, "1, 2; 3: 4!". Я бы сходу предложил изменить split, например на split(/[,;:\s]+/), куда можно добавить все интересующие знаки

2024-02-14 21:18 UTC, DPeshkoff commented on source/minmax.js
> +	if (typeof numericString !== typeof ' '){
А как можно получше сделать typeof, если это строка?

2024-02-14 21:19 UTC, DPeshkoff commented on source/minmax.js
> +	const numArray = subStringArray.map(Number).filter(num => !isNaN(num));
А надо ли нам тут еще раз пытаться привести?

2024-02-14 21:19 UTC, DPeshkoff commented on tests/minmax.js
> +	QUnit.test('в minmax передали число или вызвали без аргумента', function (assert) {
Давай так и сделаем)

2024-02-15 15:56 UTC, FZTOtt commented on source/minmax.js
> +	const numArray = subStringArray.map(Number).filter(num => !isNaN(num));
нет, можно использовать Number.isNaN(), поскольку фильтроваться будут уже числовые значения

2024-02-15 16:02 UTC, FZTOtt commented on source/minmax.js
> +	if (typeof numericString !== typeof ' '){
typeof numericString !== 'string'

2024-02-15 22:32 UTC, DPeshkoff requested changes

2024-02-15 22:32 UTC, DPeshkoff commented on source/minmax.js
> +/**
А в каком режиме работает код? Какие вообще есть?

2024-02-17 05:39 UTC, FZTOtt commented on source/minmax.js
> +/**
Код работает в обычном режиме. Есть ещё строгий режим, который можно включить директивой "use strict". Как я понял, по мере развития языка встала проблема с использованием старых версий. Для этого и был введён строгий режим.

2024-02-17 09:13 UTC, DPeshkoff requested changes

2024-02-17 09:13 UTC, DPeshkoff commented on source/minmax.js
> +/**
Давай строгий режим)

2024-02-18 12:28 UTC, DPeshkoff approved these changes

2024-02-18 12:28 UTC, closed without merging