Дранцев Сергей
frontend-park-mail-ru/homework_2024_1 pull request #9
Opened 2024-02-10 19:59 UTC by Bopster410

2024-02-10 21:30 UTC, Glibusss commented
Привет! Меня зовут Глеб и я твой ментор на время проверки ДЗ0. Сейчас я проверю и в случае чего внесу правки.
По всем вопросам ты можешь обратиться ко мне в
TG: @gibusss
VK: @glibu_s

2024-02-10 21:55 UTC, Glibusss requested changes

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +}
В конце лучше оставить пустую строчку. На будущее

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +    for (let i = 0; i < seq.length; i++) {
Здесь рекомендую подумать в сторону перебирающих методов. [Дока](https://learn.javascript.ru/array-iteration)

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +    for (let i = 0; i < seq.length; i++) {
Тут тоже. Перебирающие методы в разы круче

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +function letters(seq, saveFirst) {
Здесь ты использовал function declaration. 
Какие ещё ты знаешь варианты объявления функций?
В чём их разница и в каких ситуациях какие лучше использовать?

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +function letters(seq, saveFirst) {
Ещё один интересный момент - так называемый strict mode([Читаем тут](https://learn.javascript.ru/strict-mode))
Что он нам даёт и почему его стоит использовать?

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +    }
К слову, обрати внимание на [Set](https://learn.javascript.ru/map-set)! Он может тебе неплохо пригодиться

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +    let seen = new Map();
Почему let? [Узнать разницу между вариантами объявления переменных позволит простой jsный...](https://learn.javascript.ru/let-const)

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +    let seen = new Map();
А вот если я на вход передам undefined, то что произойдет? Это нужно всегда предусматривать

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +            seen.set(letter, {first: i, last: i, unique: true});
Здесь у тебя в объекте числа, но в 23 строчке ты используешь == вместо ===.
Подумай, какой оператор и когда лучше использовать. [Подсказка тут](https://learn.javascript.ru/comparison)

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +function letters(seq, saveFirst) {
Стоит также написать JSDoc для функции

2024-02-10 21:55 UTC, Glibusss commented on source/letters.js
> +    let seen = new Map();
Выбирай вариант обработки по желанию

2024-02-10 21:57 UTC, Glibusss commented
Надеюсь, не сильно задушнил.
Также тебе нужно дописать тесты. Помимо того, что есть придумай ещё несколько тесткейсов с разными валидными/невалидными данными

2024-02-10 22:22 UTC, Glibusss requested changes

2024-02-10 22:22 UTC, Glibusss commented on source/letters.js
> +    newSeq = "";
А вот это уже интересный кейс. Это будет работать, но почему? И в каком случае это не заработает?
P.S. Такой код небезопасен, поэтому нужно исправить

2024-02-11 09:02 UTC, Bopster410 commented on source/letters.js
> +function letters(seq, saveFirst) {
Ещё существуют function expression и стрелочная функция.  Они отличаются от function declaration областью видимости, их удобно использовать, например, для написания несложных колбэков. Стрелочная функция предпочтительна в случае очень простых и коротких выражений

2024-02-11 09:08 UTC, Glibusss commented on source/letters.js
> +function letters(seq, saveFirst) {
Стрелочная функция - это также современный способ объявления функций. Его не обязательно используют именно для коротких выражений, но про область видимости ты всё правильно сказал[если имел ввиду this]! 
Нужно писать в соответствии с современными стандартами иии... сделать стрелочную функцию

2024-02-11 09:16 UTC, Bopster410 commented on source/letters.js
> +function letters(seq, saveFirst) {
strict mode изменяет многие аспекты js так, чтобы он стал строже (что следует из названия). Например, не получится создать переменную через выражение " a = 'aaa' "

2024-02-11 09:18 UTC, Glibusss commented on source/letters.js
> +function letters(seq, saveFirst) {
Неплохо. А какие он аспекты изменяет? Перечисли пж несколько штук. (Подсказка кстати даже есть в ревью)

2024-02-11 09:20 UTC, Bopster410 commented on source/letters.js
> +    let seen = new Map();
let, потому что данная переменная нужна только в данном блоке функции

2024-02-11 09:20 UTC, Glibusss commented on source/letters.js
> +    let seen = new Map();
А ты её будешь переприсваивать?

2024-02-11 09:40 UTC, Bopster410 commented on source/letters.js
> +    newSeq = "";
Это работает, потому что используется нестрогий режим

2024-02-11 09:42 UTC, Bopster410 commented on source/letters.js
> +    for (let i = 0; i < seq.length; i++) {
Добавил перебирающий метод

2024-02-11 09:42 UTC, Bopster410 commented on source/letters.js
> +    for (let i = 0; i < seq.length; i++) {
Добавил перебирающий метод

2024-02-11 09:43 UTC, Bopster410 commented on source/letters.js
> +    let seen = new Map();
Нет, буду только менять её с помощью методов. В таком случае стоит использовать const?

2024-02-11 09:45 UTC, Glibusss commented on source/letters.js
> +    newSeq = "";
База

2024-02-11 09:45 UTC, Glibusss commented on source/letters.js
> +    newSeq = "";
Нужно исправить

2024-02-11 09:47 UTC, Glibusss commented on source/letters.js
> +    let seen = new Map();
Именно

2024-02-11 10:04 UTC, Glibusss commented on source/letters.js
> +    seqArr.forEach(function(letter, i) {
Как раз ты упоминал о применении arrow function для callback функций. Очень хороший кейс для применения

2024-02-11 10:05 UTC, Glibusss commented on tests/letters.js
>  });
Пустую строчку в конце файла

2024-02-11 10:06 UTC, Glibusss commented on tests/letters.js
> +	QUnit.test('Если на вход попадает undefined', function (assert) {
Подумай ещё, что я могу отправить на вход. Число? Без проблем! Null? Тоже Array? Запросто!

2024-02-11 10:09 UTC, Glibusss commented on source/letters.js
> +"use strict";
Кстати, принято использовать одиночные кавычки

2024-02-11 17:28 UTC, Glibusss commented on source/letters.js
> +    if (typeof seq != 'string')
Почти! Обработай случай, когда передается объект String

2024-02-11 17:30 UTC, Glibusss commented on source/letters.js
> +}
Пустую строчку

2024-02-11 17:30 UTC, Glibusss commented on source/letters.js
> +function letters(seq, saveFirst) {
Сделай функцию стрелочной

2024-02-11 17:39 UTC, Bopster410 commented on source/letters.js
> +}
Тут есть пустая строчка в конце файла, но её только при редактировании видно

2024-02-11 17:42 UTC, Glibusss commented on source/letters.js
> +}
А, ок

2024-02-11 17:43 UTC, Glibusss commented on source/letters.js
> +    if (typeof seq != 'string')
И не забудь про стрелочную функцию

2024-02-11 17:49 UTC, Glibusss commented
Молодец! Апрув твой

2024-02-12 14:35 UTC, Glibusss approved these changes

2024-02-12 15:26 UTC, DPeshkoff requested changes
Привет! Крутое решение, есть парочка минорных правок)

Если будут вопросы, то со мной можно связаться в [Telegram](t.me/DmPesh)

2024-02-12 15:26 UTC, DPeshkoff commented on source/letters.js
> +'use strict';
А что делает эта строчка? Чем строгий режим отличается от нестрогого?

2024-02-12 15:26 UTC, DPeshkoff commented on source/letters.js
> +        return undefined;
Предлагаю обернуть в {}

Кроме того, я бы возвращал не undefined, а null

2024-02-12 15:26 UTC, DPeshkoff commented on source/letters.js
> +        if (letterObj.unique || (saveFirst && i === letterObj.first) || (saveFirst === false && i === letterObj.last)) {
Проверку saveFirst === false можно упростить)

2024-02-14 19:30 UTC, Bopster410 commented on source/letters.js
> +'use strict';
Эта строчка активирует строгий режим. Он включает в себя множество поправок, например, вызывает ошибки в определенных сценариях, которые до этого бы пропускались (присваивание значения необъявленной переменной, одинаковые поля в классах), изменяет область видимости Function Declaration, объявленной в блоке {...} (видна только внутри этого блока), запрещает восьмеричный префикс '0' и так далее

2024-02-14 21:20 UTC, DPeshkoff approved these changes

2024-02-14 21:20 UTC, closed without merging